IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME = 'tbl_master_user' AND COLUMN_NAME = 'GPSNetworkIntervalMins' AND DATA_TYPE='INT')
	BEGIN
		ALTER TABLE tbl_master_user ADD GPSNetworkIntervalMins INT DEFAULT(0) WITH VALUES
	END
GO

SELECT * FROM FTS_DeviceInformation

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME = 'FTS_DeviceInformation' AND COLUMN_NAME = 'POWER_SAVER_STATUS' AND DATA_TYPE='NVARCHAR')
	BEGIN
		ALTER TABLE FTS_DeviceInformation ADD POWER_SAVER_STATUS NVARCHAR(100) DEFAULT('') WITH VALUES
	END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME = 'FTS_DeviceInformation_Arch' AND COLUMN_NAME = 'POWER_SAVER_STATUS' AND DATA_TYPE='NVARCHAR')
	BEGIN
		ALTER TABLE FTS_DeviceInformation_Arch ADD POWER_SAVER_STATUS NVARCHAR(100) DEFAULT('') WITH VALUES
	END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FSMUSERWISEGPSNETSTATUS') AND TYPE IN (N'U'))
	BEGIN

			CREATE TABLE FSMUSERWISEGPSNETSTATUS
			(
				ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
				USER_ID BIGINT,
				DATE_TIME DATETIME,
				GPS_SERVICE_STATUS NVARCHAR(200),
				NETWORK_STATUS NVARCHAR(200),
				CREATE_DATE DATETIME
			)
	END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FSMUSERWISEGPSNETSTATUS_ARCH') AND TYPE IN (N'U'))
	BEGIN

			CREATE TABLE FSMUSERWISEGPSNETSTATUS_ARCH
			(
				ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
				USER_ID BIGINT,
				DATE_TIME DATETIME,
				GPS_SERVICE_STATUS NVARCHAR(200),
				NETWORK_STATUS NVARCHAR(200),
				CREATE_DATE DATETIME,
				SCHEDULEDATE DATETIME
			)
	END
GO

SELECT * FROM FSMUSERWISEGPSNETSTATUS
SELECT * FROM FSMUSERWISEGPSNETSTATUS_ARCH


SELECT ID,USER_ID,DATE_TIME,GPS_SERVICE_STATUS,NETWORK_STATUS,CREATE_DATE,CONVERT(NVARCHAR(10),DATE_TIME,120) FROM FSMUSERWISEGPSNETSTATUS 
	WHERE CONVERT(NVARCHAR(10),DATE_TIME,120)<=CONVERT(NVARCHAR(10),GETDATE()-7,120)

SELECT CONVERT(NVARCHAR(10),GETDATE()-7,120)


SELECT * FROM FTS_DeviceInformation
SELECT * FROM FTS_DeviceInformation_Arch