IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[API_PRC_TIMESHEET]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [API_PRC_TIMESHEET] AS' 
END
GO

ALTER PROCEDURE [dbo].[API_PRC_TIMESHEET]
(
@ACTION VARCHAR(500)=NULL,
@USER_ID BIGINT=NULL,
@FILE_NAME VARCHAR(100)=NULL,
@TIMESHEET_DATE DATETIME=NULL,
@TIMESHEET_ID VARCHAR(100)=NULL,
@weburl VARCHAR(100)='http://fts.indusnettechnologies.com:8094/CommonFolder/',
@time time =null,
@client_id varchar(20)=null,
@product_id varchar(20)=null,
@project_id varchar(20)=null,
@activity_id varchar(20)=null,
@comments varchar(500)=null
) --WITH ENCRYPTION
AS
/*****************************************************************************************************************************************
Indranil 29-04-2020  Time sheet work procedure created.
*****************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @EMPLOYEE_REPORTTO AS TABLE (EMPCODE VARCHAR(50),REPORTTO_NAME VARCHAR(500))

	INSERT INTO @EMPLOYEE_REPORTTO
	SELECT TBL.EMP_CNTID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+' '+ISNULL(CNT.CNT_LASTNAME,'')  EMP_NAME FROM (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id,emp_reportTo FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
	LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL  
	GROUP BY emp_cntId,desg.deg_designation,desg.deg_id,emp_reportTo
	) TBL 
	LEFT JOIN TBL_MASTER_EMPLOYEE EM WITH(NOLOCK) ON EM.emp_id=TBL.emp_reportTo
	LEFT JOIN TBL_MASTER_CONTACT CNT WITH(NOLOCK) ON CNT.CNT_INTERNALID=EM.emp_contactId

	DECLARE @EMPLOYEECODE VARCHAR(50)=(SELECT TOP 1 user_contactId FROM TBL_MASTER_USER WITH(NOLOCK) WHERE USER_ID=@USER_ID)


	IF(@ACTION ='GETDROPDOWNDATA')
		BEGIN
			SELECT cast(Client_Id as varchar(50)) client_id,client_name FROM FTS_CLIENT_MASTER CLIENT WITH(NOLOCK) 
			INNER JOIN FTS_EMPLOYEE_CLIENTMAP MAP WITH(NOLOCK) ON CLIENT.Client_Id=MAP.EC_CLIENT_ID
			WHERE MAP.EC_EMPLOYEECODE=@EMPLOYEECODE AND CLIENT_ISACTIVE=1

			SELECT cast(Project_Id as varchar(50)) project_id,project_name FROM FTS_PROJECT_MASTER PROJECT WITH(NOLOCK) 
			INNER JOIN FTS_EMPLOYEE_PROJECTMAP MAP WITH(NOLOCK) ON PROJECT.Project_Id=MAP.EP_PROJECT_ID
			WHERE MAP.EP_EMPLOYEECODE=@EMPLOYEECODE AND PROJECT_ISACTIVE=1
			
			SELECT cast(Activity_Id as varchar(50)) activity_id,activity_name FROM FTS_ACTIVITY_MASTER ACTIVITY WITH(NOLOCK) 
			INNER JOIN FTS_EMPLOYEE_ACTIVITYMAP MAP WITH(NOLOCK) ON ACTIVITY.Activity_Id=MAP.EA_ACTIVITY_ID
			WHERE MAP.EA_EMPLOYEECODE=@EMPLOYEECODE AND ACTIVITY_ISACTIVE=1
			
			SELECT cast(SPRODUCTS_ID as varchar(50)) product_id,sProducts_Name product_name FROM MASTER_SPRODUCTS PRODUCT WITH(NOLOCK) 
			INNER JOIN FTS_EMPLOYEE_PRODUCTMAP MAP WITH(NOLOCK) ON PRODUCT.SPRODUCTS_ID=MAP.EP_PRODUCT_ID
			WHERE MAP.EP_EMPLOYEECODE=@EMPLOYEECODE
		END
	ELSE IF(@ACTION ='GETTIMESHEETDATAUSERANDDATEWISE')
		BEGIN
			DECLARE @TOTAL_TIME BIGINT=(SELECT  sum( DATEPART(SECOND, ts.timesheet_time) + 60 * 
						  DATEPART(MINUTE, ts.timesheet_time) + 3600 * 
						  DATEPART(HOUR, ts.timesheet_time ) 
						) 
			FROM FTS_TIMESHEET TS WITH(NOLOCK) 
			LEFT JOIN FTS_CLIENT_MASTER CL WITH(NOLOCK) ON TS.TIMESHEET_CLIENT_ID=CL.Client_Id
			LEFT JOIN FTS_PROJECT_MASTER PRO WITH(NOLOCK) ON TS.TIMESHEET_PROJECT_ID=PRO.Project_Id
			LEFT JOIN FTS_ACTIVITY_MASTER AC WITH(NOLOCK) ON TS.TIMESHEET_ACTIVITY_ID=AC.Activity_Id
			LEFT JOIN MASTER_SPRODUCTS MP WITH(NOLOCK) ON MP.sProducts_ID=TS.TIMESHEET_PRODUCT_ID
			WHERE TIMESHEET_USER_ID=@USER_ID AND TIMESHEET_DATE=@TIMESHEET_DATE
			)

			DECLARE @T_TIMEFORMAT VARCHAR(15)=(SELECT RIGHT('0' + CAST(@TOTAL_TIME / 3600 AS VARCHAR),2) + ':' +
			RIGHT('0' + CAST((@TOTAL_TIME / 60) % 60 AS VARCHAR),2) + ':' +
			RIGHT('0' + CAST(@TOTAL_TIME % 60 AS VARCHAR),2))

			SELECT convert(varchar(50),TS.TIMESHEET_ID_APP) id, convert(varchar(5),ts.timesheet_time,108) time,case when ts.timesheet_client_id=0 then '' else 
			convert(varchar(50),isnull(ts.timesheet_client_id,'')) end client_id,isnull(cl.client_name,'') client_name,
			case when ts.TIMESHEET_PRODUCT_ID =0 then '' else convert(varchar(50),isnull(ts.TIMESHEET_PRODUCT_ID,'')) end product_id,isnull(mp.sproducts_name,'') product_name,
			case when ts.TIMESHEET_PROJECT_ID=0 then '' else convert(varchar(50),isnull(ts.TIMESHEET_PROJECT_ID,'')) end project_id,isnull(pro.Project_Name,'') project_name,
			convert(varchar(10),ts.timesheet_date,120) date,case when ts.TIMESHEET_ACTIVITY_ID=0 then '' else convert(varchar(50),isnull(ts.TIMESHEET_ACTIVITY_ID,'')) end activity_id,isnull(ac.activity_name,'') activity_name,isnull(timesheet_comment,'') comments,
			convert(bit,case when timesheet_isapproved =1 then 0  else 1 end) isUpdateable,CASE WHEN TIMESHEET_ISAPPROVED=1 THEN 'Approved' 
					when TIMESHEET_ISREJECTED=1 then 'Rejected' else 'Pending' end 
					timesheet_status,
			CASE WHEN ISNULL(FILE_NAMES,'')='' THEN '' else @weburl+'/TimeSheetImage/'+FILE_NAMES END image
			FROM FTS_TIMESHEET TS WITH(NOLOCK) 
			LEFT JOIN FTS_CLIENT_MASTER CL WITH(NOLOCK) ON TS.TIMESHEET_CLIENT_ID=CL.Client_Id
			LEFT JOIN FTS_PROJECT_MASTER PRO WITH(NOLOCK) ON TS.TIMESHEET_PROJECT_ID=PRO.Project_Id
			LEFT JOIN FTS_ACTIVITY_MASTER AC WITH(NOLOCK) ON TS.TIMESHEET_ACTIVITY_ID=AC.Activity_Id
			LEFT JOIN MASTER_SPRODUCTS MP WITH(NOLOCK) ON MP.sProducts_ID=TS.TIMESHEET_PRODUCT_ID
			WHERE TIMESHEET_USER_ID=@USER_ID --AND TIMESHEET_DATE=@TIMESHEET_DATE

			SELECT ISNULL(REPORTTO_NAME,'') REPORTTO_NAME,@T_TIMEFORMAT TOTAL_TIME FROM @EMPLOYEE_REPORTTO WHERE EMPCODE=@EMPLOYEECODE
		END
	ELSE IF(@ACTION ='GETTIMESHEETSETTINGS')
		BEGIN
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('activity_text')
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('product_text')
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('project_text')
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('timesheet_past_days' )
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('time_text')
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('comment_text')
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('submit_text')
			union all
			SELECT 'supervisor_name' as [Key],REPORTTO_NAME [Value] FROM @EMPLOYEE_REPORTTO WHERE EMPCODE=@EMPLOYEECODE
			union all
			SELECT [Key],[Value] FROM FTS_APP_CONFIG_SETTINGS where [Key] in ('client_text')
		END
	ELSE IF(@ACTION ='DELETETIMESHEET')
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID_APP=@TIMESHEET_ID AND (TIMESHEET_ISAPPROVED=1 OR TIMESHEET_ISREJECTED=1))
				BEGIN
					SELECT CASE WHEN TIMESHEET_ISAPPROVED=1 THEN 'Approved' 
					when TIMESHEET_ISREJECTED=1 then 'Rejected' else 'Pending' end 
					timesheet_status FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID_APP=@TIMESHEET_ID

					DELETE FROM FTS_TIMESHEET WHERE TIMESHEET_ID_APP=@TIMESHEET_ID
				END
			ELSE
				BEGIN
					SELECT CASE WHEN TIMESHEET_ISAPPROVED=1 THEN 'Approved' 
					when TIMESHEET_ISREJECTED=1 then 'Rejected' else 'Pending' end 
					timesheet_status FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID_APP=@TIMESHEET_ID
				END
		END
	ELSE IF(@ACTION ='ADDTIMESHEET')
		BEGIN
			INSERT INTO FTS_TIMESHEET WITH(TABLOCK) (TIMESHEET_USER_ID,TIMESHEET_CLIENT_ID,TIMESHEET_PRODUCT_ID,TIMESHEET_PROJECT_ID,TIMESHEET_ACTIVITY_ID,
			TIMESHEET_DATE,TIMESHEET_COMMENT,TIMESHEET_TIME,TIMESHEET_CREATEDBY,TIMESHEET_CREATEDON,TIMESHEET_ID_APP,FILE_NAMES)
			VALUES (@USER_ID,CASE WHEN @CLIENT_ID='' THEN 0 ELSE @CLIENT_ID END,CASE WHEN @PRODUCT_ID=''  THEN 0 ELSE @PRODUCT_ID END,CASE WHEN @PROJECT_ID='' THEN 0 ELSE @PROJECT_ID END,
			CASE WHEN @ACTIVITY_ID='' THEN 0  ELSE @ACTIVITY_ID END,@TIMESHEET_DATE,@COMMENTS,@TIME,@USER_ID,GETDATE(),@TIMESHEET_ID,@FILE_NAME )
		END
	ELSE IF(@ACTION ='UPDATETIMESHEET')
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM FTS_TIMESHEET WHERE TIMESHEET_ID_APP=@TIMESHEET_ID AND (TIMESHEET_ISAPPROVED=1 OR TIMESHEET_ISREJECTED=1))
				BEGIN
					UPDATE FTS_TIMESHEET WITH(TABLOCK) SET 
					TIMESHEET_CLIENT_ID=(CASE WHEN @CLIENT_ID='' THEN 0 ELSE @CLIENT_ID END),
					TIMESHEET_PRODUCT_ID=(CASE WHEN @PRODUCT_ID=''  THEN 0 ELSE @PRODUCT_ID END),
					TIMESHEET_PROJECT_ID=(CASE WHEN @PROJECT_ID=''  THEN 0 ELSE @PROJECT_ID END),
					TIMESHEET_ACTIVITY_ID=(CASE WHEN @ACTIVITY_ID='' THEN 0  ELSE @ACTIVITY_ID END),
					TIMESHEET_DATE=@TIMESHEET_DATE,
					TIMESHEET_COMMENT=@COMMENTS,
					TIMESHEET_TIME=@TIME,
					TIMESHEET_MODIFIEDBY=@USER_ID,
					TIMESHEET_MODIFIEDON=GETDATE(),
					FILE_NAMES=@FILE_NAME
					WHERE TIMESHEET_ID_APP=@TIMESHEET_ID

					SELECT CASE WHEN TIMESHEET_ISAPPROVED=1 THEN 'Approved' 
					when TIMESHEET_ISREJECTED=1 then 'Rejected' else 'Pending' end 
					timesheet_status FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID_APP=@TIMESHEET_ID
				END
			ELSE
				BEGIN
					SELECT CASE WHEN TIMESHEET_ISAPPROVED=1 THEN 'Approved' 
					when TIMESHEET_ISREJECTED=1 then 'Rejected' else 'Pending' end 
					timesheet_status FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID_APP=@TIMESHEET_ID
				END
		END
	ELSE IF(@ACTION ='APPROVETIMESHEET')
		BEGIN
			UPDATE FTS_TIMESHEET WITH(TABLOCK) SET 
			TIMESHEET_APPROVEDBY=@USER_ID,
			TIMESHEET_ISAPPROVED=1,
			TIMESHEET_APPROVEDON=GETDATE()
			WHERE TIMESHEET_ID=@TIMESHEET_ID

			SELECT 'Approved Succsessfully.'
			DECLARE @TimeSheetDate_App VARCHAR(10)=(SELECT CONVERT(VARCHAR(10),TIMESHEET_DATE,105) FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID=@TIMESHEET_ID)
			DECLARE @MobileNumber_App VARCHAR(10)=(SELECT user_loginId FROM TBL_MASTER_USER WITH(NOLOCK) WHERE USER_ID=(SELECT TIMESHEET_USER_ID FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID=@TIMESHEET_ID))
			SELECT 'Timesheet approved for the date '+@TimeSheetDate_App+'. Thanks.',@MobileNumber_App MobileNumber
		END

	ELSE IF(@ACTION ='REJECTTIMESHEET')
		BEGIN
			UPDATE FTS_TIMESHEET WITH(TABLOCK) SET 
			TIMESHEET_REJECTEDBY=@USER_ID,
			TIMESHEET_ISREJECTED=1,
			TIMESHEET_REJECTEDON=GETDATE()
			WHERE TIMESHEET_ID=@TIMESHEET_ID
			SELECT 'Rejected Succsessfully.'

			DECLARE @TimeSheetDate_Rej VARCHAR(10)=(SELECT CONVERT(VARCHAR(10),TIMESHEET_DATE,105) FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID=@TIMESHEET_ID)
			DECLARE @MobileNumber_Rej VARCHAR(10)=(SELECT user_loginId FROM TBL_MASTER_USER WITH(NOLOCK) WHERE USER_ID=(SELECT TIMESHEET_USER_ID FROM FTS_TIMESHEET WITH(NOLOCK) WHERE TIMESHEET_ID=@TIMESHEET_ID))
			SELECT 'Timesheet approved for the date '+@TimeSheetDate_Rej+'. Thanks.',@MobileNumber_Rej MobileNumber
		END
	ELSE IF (@ACTION='EMPLOYEEDROPDOWN')
		BEGIN
			SELECT CNT_INTERNALID EmpCode,CNT.CNT_FIRSTNAME+' ' + ISNULL(CNT.CNT_MIDDLENAME,'')+' ' + ISNULL(CNT.CNT_LASTNAME,'') NAME FROM tbl_master_employee EMP WITH(NOLOCK) 
			INNER JOIN TBL_MASTER_USER USR WITH(NOLOCK) ON EMP.emp_contactId=USR.user_contactId and user_inactive='N'
			INNER JOIN TBL_MASTER_CONTACT CNT WITH(NOLOCK) ON CNT.CNT_INTERNALID=USR.user_contactId
			WHERE EXISTS(
			SELECT 1  FROM tbl_master_address WITH(NOLOCK) WHERE add_entity='employee' AND add_addressType='Office' AND ADD_CNTID=emp_contactId)
		END

	SET NOCOUNT OFF
END