--EXEC PRC_FSMTARGETACHIEVEINFODETAILS @ACTION='FETCHTADETAILS',@USER_ID=54795,@TARGET_TYPE_ID=1,@TARGET_LEVEL_ID=1,@TIME_FRAME='M'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FSMTARGETACHIEVEINFODETAILS]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FSMTARGETACHIEVEINFODETAILS] AS' 
END
GO

ALTER PROCEDURE  [dbo].[PRC_FSMTARGETACHIEVEINFODETAILS]
(
@ACTION NVARCHAR(50),
@USER_ID BIGINT=NULL,
@TARGET_TYPE_ID BIGINT=NULL,
@TARGET_LEVEL_ID BIGINT=NULL,
@TIME_FRAME CHAR(1)=NULL,
@START_DATE NVARCHAR(10)=NULL,
@END_DATE NVARCHAR(10)=NULL
) --WITH ENCRYPTION
AS
/************************************************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 11/11/2024
Module	   : Target Vs Achievement Info Details.Refer: Row: 992,993,994,996,997,998 & 999
************************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @M_USERINTERNALID NVARCHAR(100),@M_BRANCHID BIGINT,@M_BRANCHINTERNALID NVARCHAR(100),@M_STARTDATE NVARCHAR(10),@M_ENDDATE NVARCHAR(10),@M_TARGETTYPE_NAME NVARCHAR(100),
	@M_LEVEL_NAME NVARCHAR(200),@M_ASMSLOSLMID BIGINT,@M_ASMSLOSLMINTERNALID NVARCHAR(100),@M_BEATID BIGINT,@M_BEATINTERNALID NVARCHAR(100),@M_OUTLETID BIGINT,@M_OUTLETINTERNALID NVARCHAR(100)

	IF @ACTION='TARGETTYPELIST'
		BEGIN
			SELECT TARGETTYPE_ID AS id,TARGETTYPE_NAME AS [name] FROM FSM_APITARGETTYPELIST WHERE ISACTIVE=1
		END
	IF @ACTION='TARGETLEVELLIST'
		BEGIN
			SELECT ID AS id,LEVEL_NAME AS [name] FROM FSM_TARGETLEVELSETUP_MASTER
		END
	IF @ACTION='TARGETTIMEFRAMELIST'
		BEGIN
			SELECT TARGETTIMEFRAME_ID AS id,TARGETTIMEFRAME_NAME AS [name] FROM FSM_APITARGETTIMEFRAMELIST
		END
	IF @ACTION='FETCHTADETAILS'
		BEGIN
			SET @M_TARGETTYPE_NAME=(SELECT TARGETTYPE_NAME FROM FSM_APITARGETTYPELIST WHERE TARGETTYPE_ID=@TARGET_TYPE_ID)
			SET @M_LEVEL_NAME=(SELECT LEVEL_NAME FROM FSM_TARGETLEVELSETUP_MASTER WHERE ID=@TARGET_LEVEL_ID)
			SET @M_USERINTERNALID=(SELECT user_contactId FROM tbl_master_user WHERE USER_ID=@USER_ID)
			IF @TARGET_LEVEL_ID=1 --Region
				BEGIN
					SET @M_BRANCHID=(SELECT user_branchId FROM tbl_master_user WHERE USER_ID=@USER_ID)
					SET @M_BRANCHINTERNALID=(SELECT branch_internalId FROM tbl_master_branch WHERE branch_id=@M_BRANCHID)
				END
			ELSE IF @TARGET_LEVEL_ID IN(2,3,4) --ASM,SalesOfficer,Salesman
				BEGIN
					SET @M_ASMSLOSLMID=(SELECT CNT_ID FROM tbl_master_CONTACT WHERE cnt_internalId=@M_USERINTERNALID)
					SET @M_ASMSLOSLMINTERNALID=(SELECT CNT_INTERNALID FROM tbl_master_CONTACT WHERE cnt_internalId=@M_USERINTERNALID)
				END
			ELSE IF @TARGET_LEVEL_ID=5 --Beat
				BEGIN
					IF @TARGET_TYPE_ID IN(1,2,3,4) --Outlet Visit,Collection,Order Quantity,Order Value
						BEGIN
							SET @M_BEATID=(SELECT BEAT_ID FROM FSM_GROUPBEAT_USERMAP A
							INNER JOIN (SELECT TARGETLEVELASSIGNID FROM FSM_SALESTARGETASSIGN_DETAILS GROUP BY TARGETLEVELASSIGNID) B ON A.BEAT_ID=B.TARGETLEVELASSIGNID
							WHERE USER_ID=@USER_ID
							GROUP BY BEAT_ID)
						END
					ELSE IF @TARGET_TYPE_ID=5 --WOD
						BEGIN						
							SET @M_BEATID=(SELECT BEAT_ID FROM FSM_GROUPBEAT_USERMAP A
							INNER JOIN (SELECT TARGETLEVELASSIGNID FROM FSM_WODTARGETASSIGN_DETAILS GROUP BY TARGETLEVELASSIGNID) B ON A.BEAT_ID=B.TARGETLEVELASSIGNID
							WHERE USER_ID=@USER_ID
							GROUP BY BEAT_ID)
						END
					SET @M_BEATINTERNALID=(SELECT CODE FROM FSM_GROUPBEAT WHERE ID=@M_BEATID)
				END
			ELSE IF @TARGET_LEVEL_ID=6 --Outlet
				BEGIN
					IF @TARGET_TYPE_ID IN(1,2,3,4) --Outlet Visit,Collection,Order Quantity,Order Value
						BEGIN
							SET @M_OUTLETID=(SELECT SHOP_ID FROM tbl_master_shop A
							INNER JOIN (SELECT TARGETLEVELASSIGNID FROM FSM_SALESTARGETASSIGN_DETAILS GROUP BY TARGETLEVELASSIGNID) B ON A.SHOP_ID=B.TARGETLEVELASSIGNID
							WHERE shop_createuser=@USER_ID)
						END
					ELSE IF @TARGET_TYPE_ID=5 --WOD
						BEGIN
							SET @M_OUTLETID=(SELECT SHOP_ID FROM tbl_master_shop A
							INNER JOIN (SELECT TARGETLEVELASSIGNID FROM FSM_WODTARGETASSIGN_DETAILS GROUP BY TARGETLEVELASSIGNID) B ON A.SHOP_ID=B.TARGETLEVELASSIGNID
							WHERE shop_createuser=@USER_ID)
						END
					SET @M_OUTLETINTERNALID=(SELECT Shop_Code FROM tbl_master_shop WHERE SHOP_ID=@M_OUTLETID)
				END
			IF @TARGET_TYPE_ID IN(1,2,3,4) --Outlet Visit,Collection,Order Quantity,Order Value
				BEGIN
					IF @TIME_FRAME='C'
						BEGIN
							SET @M_STARTDATE=@START_DATE
							SET @M_ENDDATE=@END_DATE
						END
					ELSE IF @TIME_FRAME<>'C'
						BEGIN
							SELECT @M_STARTDATE=CAST(STARTDATE AS DATE),@M_ENDDATE=CAST(ENDDATE AS DATE) FROM FSM_SALESTARGETASSIGN_DETAILS 
							WHERE INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
						END
				END
			ELSE IF @TARGET_TYPE_ID=5 --WOD
				BEGIN
					IF @TIME_FRAME='C'
						BEGIN
							SET @M_STARTDATE=@START_DATE
							SET @M_ENDDATE=@END_DATE
						END
					ELSE IF @TIME_FRAME<>'C'
						BEGIN
							SELECT @M_STARTDATE=CAST(STARTDATE AS DATE),@M_ENDDATE=CAST(ENDDATE AS DATE) FROM FSM_WODTARGETASSIGN_DETAILS 
							WHERE INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
						END
				END
			IF @M_ENDDATE>=CAST(GETDATE() AS DATE)
				BEGIN
					IF @TARGET_TYPE_ID=1 --Outlet Visit
						BEGIN
							SELECT @M_TARGETTYPE_NAME+' : '+@M_LEVEL_NAME AS value_for,SUM([target]) AS [target],SUM(achv) AS achv FROM(
							SELECT SUM(ISNULL(NEWVISIT,0))+SUM(ISNULL(REVISIT,0)) AS [target],0 AS achv FROM FSM_SALESTARGETASSIGN_DETAILS
							WHERE TARGETLEVELASSIGNID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETID END 
							AND INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
							AND TIMEFRAME=CASE WHEN @TIME_FRAME='M' THEN 'Monthly' WHEN @TIME_FRAME='C' THEN 'Custom' ELSE 'Yearly' END 
							AND TARGETLEVELID=@TARGET_LEVEL_ID
							UNION ALL
							SELECT 0 AS [target],COUNT(Shop_Id) AS achv FROM tbl_trans_shopActivitysubmit
							WHERE USER_ID=@USER_ID AND CAST(visited_time AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
							) TAVALUE

							IF @TARGET_LEVEL_ID IN(1) --Region
								BEGIN
									SELECT BR.branch_description AS [name],CONVERT(NVARCHAR,COUNT(Shop_Id)) AS [value],'' AS date_time FROM tbl_trans_shopActivitysubmit SHOPACT
									INNER JOIN tbl_master_user USR ON SHOPACT.User_Id=USR.user_id
									INNER JOIN tbl_master_branch BR ON USR.user_branchId=BR.branch_id
									WHERE SHOPACT.User_Id=@USER_ID AND CAST(SHOPACT.visited_time AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY BR.branch_description
								END
							ELSE IF @TARGET_LEVEL_ID IN(5) --Beat
								BEGIN
									SELECT GB.NAME AS [name],CONVERT(NVARCHAR,COUNT(Shop_Id)) AS [value],'' AS date_time FROM tbl_trans_shopActivitysubmit SHOPACT
									INNER JOIN FSM_GROUPBEAT_USERMAP GBUSR ON SHOPACT.User_Id=GBUSR.user_id
									INNER JOIN FSM_GROUPBEAT GB ON GBUSR.BEAT_ID=GB.ID AND GB.ID=@M_BEATID
									WHERE SHOPACT.User_Id=@USER_ID AND CAST(SHOPACT.visited_time AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY GB.NAME
								END
							ELSE IF @TARGET_LEVEL_ID IN(2,3,4,6) --ASM,SalesOfficer,Salesman,Outlet
								BEGIN
									SELECT MS.Shop_Name AS [name],CONVERT(NVARCHAR,COUNT(SHOPACT.Shop_Id)) AS [value],CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) AS date_time 
									FROM tbl_trans_shopActivitysubmit SHOPACT
									INNER JOIN tbl_Master_shop MS ON SHOPACT.User_Id=MS.shop_createuser AND SHOPACT.Shop_Id=MS.SHOP_CODE
									WHERE SHOPACT.User_Id=@USER_ID AND CAST(SHOPACT.visited_time AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY MS.Shop_Name,CONVERT(NVARCHAR(10),SHOPACT.visited_time,120)
								END
						END
					IF @TARGET_TYPE_ID=2 --Collection
						BEGIN
							SELECT @M_TARGETTYPE_NAME+' : '+@M_LEVEL_NAME AS value_for,SUM([target]) AS [target],SUM(achv) AS achv FROM(
							SELECT SUM(ISNULL([COLLECTION],0)) AS [target],0 AS achv FROM FSM_SALESTARGETASSIGN_DETAILS
							WHERE TARGETLEVELASSIGNID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETID END 
							AND INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
							AND TIMEFRAME=CASE WHEN @TIME_FRAME='M' THEN 'Monthly' WHEN @TIME_FRAME='C' THEN 'Custom' ELSE 'Yearly' END 
							AND TARGETLEVELID=@TARGET_LEVEL_ID
							UNION ALL
							SELECT 0 AS [target],SUM(ISNULL([COLLECTION],0)) AS achv FROM tbl_FTS_Collection
							WHERE USER_ID=@USER_ID AND CAST(collection_date AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
							) TAVALUE

							IF @TARGET_LEVEL_ID IN(1) --Region
								BEGIN
									SELECT BR.branch_description AS [name],CONVERT(NVARCHAR,SUM(ISNULL([COLLECTION],0))) AS [value],'' AS date_time FROM tbl_FTS_Collection COL
									INNER JOIN tbl_master_user USR ON COL.User_Id=USR.user_id
									INNER JOIN tbl_master_branch BR ON USR.user_branchId=BR.branch_id
									WHERE COL.User_Id=@USER_ID AND CAST(COL.collection_date AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY BR.branch_description
								END
							ELSE IF @TARGET_LEVEL_ID IN(5) --Beat
								BEGIN
									SELECT GB.NAME AS [name],CONVERT(NVARCHAR,SUM(ISNULL([COLLECTION],0))) AS [value],'' AS date_time FROM tbl_FTS_Collection COL
									INNER JOIN FSM_GROUPBEAT_USERMAP GBUSR ON COL.User_Id=GBUSR.user_id
									INNER JOIN FSM_GROUPBEAT GB ON GBUSR.BEAT_ID=GB.ID AND GB.ID=@M_BEATID
									WHERE COL.User_Id=@USER_ID AND CAST(COL.collection_date AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY GB.NAME
								END
							ELSE IF @TARGET_LEVEL_ID IN(2,3,4,6) --ASM,SalesOfficer,Salesman,Outlet
								BEGIN
									SELECT MS.Shop_Name AS [name],CONVERT(NVARCHAR,SUM(ISNULL([COLLECTION],0))) AS [value],CAST(COL.collection_date AS DATE) AS date_time FROM tbl_FTS_Collection COL
									INNER JOIN tbl_Master_shop MS ON COL.User_Id=MS.shop_createuser AND COL.Shop_Id=MS.SHOP_CODE
									WHERE COL.User_Id=@USER_ID AND CAST(COL.collection_date AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY MS.Shop_Name,CAST(COL.collection_date AS DATE)
								END
						END
					IF @TARGET_TYPE_ID=3 --Order Quantity
						BEGIN
							SELECT @M_TARGETTYPE_NAME+' : '+@M_LEVEL_NAME AS value_for,SUM([target]) AS [target],SUM(achv) AS achv FROM(
							SELECT SUM(ISNULL(ORDERQTY,0)) AS [target],0 AS achv FROM FSM_SALESTARGETASSIGN_DETAILS
							WHERE TARGETLEVELASSIGNID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETID END 
							AND INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
							AND TIMEFRAME=CASE WHEN @TIME_FRAME='M' THEN 'Monthly' WHEN @TIME_FRAME='C' THEN 'Custom' ELSE 'Yearly' END 
							AND TARGETLEVELID=@TARGET_LEVEL_ID
							UNION ALL
							SELECT 0 AS [target],SUM(ISNULL(Product_Qty,0)) AS achv FROM tbl_trans_fts_Orderupdate ORDH
							INNER JOIN tbl_FTs_OrderdetailsProduct ORDD ON ORDH.OrderId=ORDD.Order_ID AND ORDH.USERID=ORDD.USER_ID
							WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
							) TAVALUE

							IF @TARGET_LEVEL_ID IN(1) --Region
								BEGIN
									SELECT BR.branch_description AS [name],CONVERT(NVARCHAR,SUM(ISNULL(Product_Qty,0))) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_FTs_OrderdetailsProduct ORDD ON ORDH.OrderId=ORDD.Order_ID AND ORDH.USERID=ORDD.USER_ID
									INNER JOIN tbl_master_user USR ON ORDH.USERID=USR.user_id
									INNER JOIN tbl_master_branch BR ON USR.user_branchId=BR.branch_id
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY BR.branch_description
								END
							ELSE IF @TARGET_LEVEL_ID IN(5) --Beat
								BEGIN
									SELECT GB.NAME AS [name],CONVERT(NVARCHAR,SUM(ISNULL(Product_Qty,0))) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_FTs_OrderdetailsProduct ORDD ON ORDH.OrderId=ORDD.Order_ID AND ORDH.USERID=ORDD.USER_ID
									INNER JOIN FSM_GROUPBEAT_USERMAP GBUSR ON ORDH.UserId=GBUSR.user_id
									INNER JOIN FSM_GROUPBEAT GB ON GBUSR.BEAT_ID=GB.ID AND GB.ID=@M_BEATID
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY GB.NAME
								END
							ELSE IF @TARGET_LEVEL_ID IN(2,3,4,6) --ASM,SalesOfficer,Salesman,Outlet
								BEGIN
									SELECT MS.Shop_Name AS [name],CONVERT(NVARCHAR,SUM(ISNULL(Product_Qty,0))) AS [value],CAST(ORDH.Orderdate AS DATE) AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_FTs_OrderdetailsProduct ORDD ON ORDH.OrderId=ORDD.Order_ID AND ORDH.USERID=ORDD.USER_ID
									INNER JOIN tbl_Master_shop MS ON ORDH.UserId=MS.shop_createuser AND ORDH.Shop_CODE=MS.SHOP_CODE
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY MS.Shop_Name,CAST(ORDH.Orderdate AS DATE)
								END
						END
					IF @TARGET_TYPE_ID=4 --Order Value
						BEGIN
							SELECT @M_TARGETTYPE_NAME+' : '+@M_LEVEL_NAME AS value_for,SUM([target]) AS [target],SUM(achv) AS achv FROM(
							SELECT SUM(ISNULL(ORDERAMOUNT,0)) AS [target],0 AS achv FROM FSM_SALESTARGETASSIGN_DETAILS
							WHERE TARGETLEVELASSIGNID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETID END 
							AND INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
							AND TIMEFRAME=CASE WHEN @TIME_FRAME='M' THEN 'Monthly' WHEN @TIME_FRAME='C' THEN 'Custom' ELSE 'Yearly' END 
							AND TARGETLEVELID=@TARGET_LEVEL_ID
							UNION ALL
							SELECT 0 AS [target],SUM(ISNULL(ORDH.Ordervalue,0)) AS achv FROM tbl_trans_fts_Orderupdate ORDH
							WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
							) TAVALUE

							IF @TARGET_LEVEL_ID IN(1) --Region
								BEGIN
									SELECT BR.branch_description AS [name],CONVERT(NVARCHAR,SUM(ISNULL(ORDH.Ordervalue,0))) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_master_user USR ON ORDH.USERID=USR.user_id
									INNER JOIN tbl_master_branch BR ON USR.user_branchId=BR.branch_id
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY BR.branch_description
								END
							ELSE IF @TARGET_LEVEL_ID IN(5) --Beat
								BEGIN
									SELECT GB.NAME AS [name],CONVERT(NVARCHAR,SUM(ISNULL(ORDH.Ordervalue,0))) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN FSM_GROUPBEAT_USERMAP GBUSR ON ORDH.UserId=GBUSR.user_id
									INNER JOIN FSM_GROUPBEAT GB ON GBUSR.BEAT_ID=GB.ID AND GB.ID=@M_BEATID
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY GB.NAME
								END
							ELSE IF @TARGET_LEVEL_ID IN(2,3,4,6) --ASM,SalesOfficer,Salesman,Outlet
								BEGIN
									SELECT MS.Shop_Name AS [name],CONVERT(NVARCHAR,SUM(ISNULL(ORDH.Ordervalue,0))) AS [value],CAST(ORDH.Orderdate AS DATE) AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_Master_shop MS ON ORDH.UserId=MS.shop_createuser AND ORDH.Shop_CODE=MS.SHOP_CODE
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY MS.Shop_Name,CAST(ORDH.Orderdate AS DATE)
								END
						END
					IF @TARGET_TYPE_ID=5 --WOD
						BEGIN
							SELECT @M_TARGETTYPE_NAME+' : '+@M_LEVEL_NAME AS value_for,SUM([target]) AS [target],SUM(achv) AS achv FROM(
							SELECT SUM(ISNULL(WODCOUNT,0)) AS [target],0 AS achv FROM FSM_WODTARGETASSIGN_DETAILS
							WHERE TARGETLEVELASSIGNID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETID END 
							AND INTERNALID=CASE WHEN @TARGET_LEVEL_ID=1 THEN @M_BRANCHINTERNALID WHEN @TARGET_LEVEL_ID IN(2,3,4) THEN @M_ASMSLOSLMINTERNALID 
							WHEN @TARGET_LEVEL_ID=5 THEN @M_BEATINTERNALID WHEN @TARGET_LEVEL_ID=6 THEN @M_OUTLETINTERNALID END
							AND TIMEFRAME=CASE WHEN @TIME_FRAME='M' THEN 'Monthly' WHEN @TIME_FRAME='C' THEN 'Custom' ELSE 'Yearly' END 
							AND TARGETLEVELID=@TARGET_LEVEL_ID
							UNION ALL
							SELECT 0 AS [target],COUNT(DISTINCT Shop_Code) AS achv FROM tbl_trans_fts_Orderupdate ORDH
							WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
							) TAVALUE

							IF @TARGET_LEVEL_ID IN(1) --Region
								BEGIN
									SELECT BR.branch_description AS [name],CONVERT(NVARCHAR,COUNT(DISTINCT Shop_Code)) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_master_user USR ON ORDH.USERID=USR.user_id
									INNER JOIN tbl_master_branch BR ON USR.user_branchId=BR.branch_id
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY BR.branch_description
								END
							ELSE IF @TARGET_LEVEL_ID IN(5) --Beat
								BEGIN
									SELECT GB.NAME AS [name],CONVERT(NVARCHAR,COUNT(DISTINCT Shop_Code)) AS [value],'' AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN FSM_GROUPBEAT_USERMAP GBUSR ON ORDH.UserId=GBUSR.user_id
									INNER JOIN FSM_GROUPBEAT GB ON GBUSR.BEAT_ID=GB.ID AND GB.ID=@M_BEATID
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY GB.NAME
								END
							ELSE IF @TARGET_LEVEL_ID IN(2,3,4,6) --ASM,SalesOfficer,Salesman,Outlet
								BEGIN
									SELECT MS.Shop_Name AS [name],CONVERT(NVARCHAR,COUNT(DISTINCT ORDH.Shop_Code)) AS [value],CAST(ORDH.Orderdate AS DATE) AS date_time FROM tbl_trans_fts_Orderupdate ORDH
									INNER JOIN tbl_Master_shop MS ON ORDH.UserId=MS.shop_createuser AND ORDH.Shop_CODE=MS.SHOP_CODE
									WHERE ORDH.USERID=@USER_ID AND CAST(ORDH.Orderdate AS DATE) BETWEEN @M_STARTDATE AND @M_ENDDATE
									GROUP BY MS.Shop_Name,CAST(ORDH.Orderdate AS DATE)
								END
						END
				END
		END

	SET NOCOUNT OFF
END
GO