IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIUSERWISEDAYSTARTEND]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIUSERWISEDAYSTARTEND] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIUSERWISEDAYSTARTEND]
(
@ACTION NVARCHAR(10),
@USER_ID BIGINT=NULL,
@STARTENDDATE DATETIME=NULL,
@LOCATION_NAME NVARCHAR(1000)=NULL,
@LATITUDE NVARCHAR(MAX)=NULL,
@LONGITUDE NVARCHAR(MAX)=NULL,
@SHOP_TYPE INT=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@ISSTART BIT=NULL,
@ISEND BIT=NULL,
@SALE_VALUE NUMERIC(18,2)=NULL,
@REMARKS NVARCHAR(1000)=NULL,
@VISITDDID NVARCHAR(100)=NULL,
@VISITDDNAME NVARCHAR(500)=NULL,
@VISITDDDATE DATETIME=NULL,
@ISDDVISTEDONCEBYDAY BIT=NULL,
@PathImage NVARCHAR(500)=NULL
) --WITH ENCRYPTION
AS
/***************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 16/08/2021
Purpose : For User wise Day Start/End.
***************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='INSERTDATA'
		BEGIN
			IF NOT EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND ISSTART=@ISSTART)
				BEGIN
					INSERT INTO FSMUSERWISEDAYSTARTEND(USER_ID,STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID,ISSTART,ISEND,SALE_VALUE,REMARKS,VISITDDID,VISITDDNAME,VISITDDDATE,ISDDVISTEDONCEBYDAY)
					SELECT @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,@ISSTART,@ISEND,@SALE_VALUE,@REMARKS,@VISITDDID,@VISITDDNAME,@VISITDDDATE,@ISDDVISTEDONCEBYDAY
				END
			IF NOT EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND ISEND=@ISEND)
				BEGIN
					INSERT INTO FSMUSERWISEDAYSTARTEND(USER_ID,STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID,ISSTART,ISEND,SALE_VALUE,REMARKS,VISITDDID,VISITDDNAME,VISITDDDATE,ISDDVISTEDONCEBYDAY)
					SELECT @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,@ISSTART,@ISEND,@SALE_VALUE,@REMARKS,@VISITDDID,@VISITDDNAME,@VISITDDDATE,@ISDDVISTEDONCEBYDAY
				END

			SELECT CAST(ISSTART AS INT) AS ISSTART FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120)
		END
	IF @ACTION='FETCHDATA'
		BEGIN
			SELECT ISSTART AS DayStartMarked,(SELECT TOP 1 ISEND FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID 
			AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) ORDER BY ID DESC) AS DayEndMarked,
			SHOP_TYPE AS day_start_shop_type,SHOP_ID AS day_start_shop_id,(SELECT TOP 1 ISDDVISTEDONCEBYDAY FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID 
			AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) ORDER BY ID DESC) AS IsDDvistedOnceByDay

			FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120)
		END
	IF @ACTION='SAVEIMAGE'
		BEGIN
			IF EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND @ISSTART=1 AND @ISEND=0)
				BEGIN
					UPDATE FSMUSERWISEDAYSTARTEND SET DAYSTARTENDIMAGE=@PathImage WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=1 AND ISEND=0
					SELECT USER_ID,DAYSTARTENDIMAGE,ISSTART FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=1 AND ISEND=0
				END
			IF EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND @ISSTART=0 AND @ISEND=1)
				BEGIN
					UPDATE FSMUSERWISEDAYSTARTEND SET DAYSTARTENDIMAGE=@PathImage WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=0 AND ISEND=1
					SELECT USER_ID,DAYSTARTENDIMAGE,ISEND FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=0 AND ISEND=1
				END
		END
	
	SET NOCOUNT OFF
END