--EXEC PRC_APIEMPLOYEEAADHARINFORMATION @ACTION='USERAADHARLIST'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIEMPLOYEEAADHARINFORMATION]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIEMPLOYEEAADHARINFORMATION] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIEMPLOYEEAADHARINFORMATION]
(
@ACTION NVARCHAR(20),
@USER_ID BIGINT=NULL,
@USERCONTACTID NVARCHAR(100)=NULL,
@AADHAAR_NO NVARCHAR(50)=NULL,
@AADHAARDATE DATETIME=NULL,
@FEEDBACK NVARCHAR(500)=NULL,
@ADDRESS NVARCHAR(1000)=NULL,
@PathImage NVARCHAR(500)=NULL
) --WITH ENCRYPTION
AS
/***************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 13/09/2021
Purpose : For User wise Aadhar Information.
1.0		v2.0.25		Debashis	06/10/2021		New @ACTION implemented as "USERAADHARLIST"
***************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='INSERTDATA'
		BEGIN
			IF NOT EXISTS(SELECT USER_ID FROM FSMEMPLOYEEAADHARINFORMATION WHERE USER_ID=@USER_ID)
				BEGIN
					INSERT INTO FSMEMPLOYEEAADHARINFORMATION(USER_ID,EMP_INTERNALID,AADHAAR_NO,AADHAARDATE,FEEDBACK,ADDRESS)
					SELECT @USER_ID,@USERCONTACTID,@AADHAAR_NO,@AADHAARDATE,@FEEDBACK,@ADDRESS
				END
			IF EXISTS(SELECT USER_ID FROM FSMEMPLOYEEAADHARINFORMATION WHERE USER_ID=@USER_ID)
				BEGIN
					UPDATE FSMEMPLOYEEAADHARINFORMATION SET AADHAAR_NO=@AADHAAR_NO,AADHAARDATE=@AADHAARDATE,FEEDBACK=@FEEDBACK,ADDRESS=@ADDRESS
					WHERE USER_ID=@USER_ID AND EMP_INTERNALID=@USERCONTACTID
				END
			SELECT USER_ID,AADHAAR_NO FROM FSMEMPLOYEEAADHARINFORMATION WHERE USER_ID=@USER_ID
		END
	IF @ACTION='SAVEIMAGE'
		BEGIN
			IF EXISTS(SELECT USER_ID FROM FSMEMPLOYEEAADHARINFORMATION WHERE USER_ID=@USER_ID)
				BEGIN
					UPDATE FSMEMPLOYEEAADHARINFORMATION SET DOCUMENTIMAGE=@PathImage WHERE USER_ID=@USER_ID
					AND EMP_INTERNALID=@USERCONTACTID AND AADHAAR_NO=@AADHAAR_NO

					SELECT USER_ID,DOCUMENTIMAGE FROM FSMEMPLOYEEAADHARINFORMATION WHERE USER_ID=@USER_ID
					AND EMP_INTERNALID=@USERCONTACTID
				END
		END
	--Rev 1.0
	IF @ACTION='USERAADHARLIST'
		SELECT USER_ID AS user_id,EMP_INTERNALID AS user_login_id,AADHAAR_NO AS RegisteredAadhaarNo FROM FSMEMPLOYEEAADHARINFORMATION
	--End of Rev 1.0

	SET NOCOUNT OFF
END