--EXEC PRC_FTSQUALIFIEDATTENDANCE_REPORT '2022-10-11','2022-11-08','1,118,119,120,121,122,123,124,125','','',378
--EXEC PRC_FTSQUALIFIEDATTENDANCE_REPORT '2022-03-09','2022-03-09','1','EMA0000008,EMA0000016,EMA0000012,EMM0000002,EMA0000020','1,2,3,4,5,6,7,8',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSQUALIFIEDATTENDANCE_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSQUALIFIEDATTENDANCE_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSQUALIFIEDATTENDANCE_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@BRANCHID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@CHANNELID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 05/11/2022
Module	   : Qualified Attendance Report.Refer: 0025416
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @DAYCOUNT INT,@LOOPCOUNT INT,@FIRSTTIME BIT=1
	DECLARE @SqlStrTable NVARCHAR(MAX)
	DECLARE @COLUMN_DATE NVARCHAR(10)=@FROMDATE
	DECLARE @SLHEADID BIGINT,@PARENTID BIGINT

	DECLARE @days AS INT,@FIRSTDATEOFMONTH DATETIME,@CURRENTDATEOFMONTH DATETIME,@EMP_IDs NVARCHAR(MAX)
	SELECT @FIRSTDATEOFMONTH = @FROMDATE
	SELECT @CURRENTDATEOFMONTH = @TODATE

	;WITH CTE AS (SELECT 1 AS DAYID,@FIRSTDATEOFMONTH AS FROMDATE,DATENAME(DW, @FIRSTDATEOFMONTH) AS DAYNAME
	UNION ALL
	SELECT CTE.DAYID + 1 AS DAYID,DATEADD(D, 1 ,CTE.FROMDATE),DATENAME(DW, DATEADD(D, 1 ,CTE.FROMDATE)) AS DAYNAME
	FROM CTE
	WHERE DATEADD(D,1,CTE.FROMDATE) <= @CURRENTDATEOFMONTH
	)
	SELECT FROMDATE AS SUNDAYDATE,DAYNAME INTO #TMPSHOWSUNDAY
	FROM CTE
	WHERE DAYNAME IN ('Sunday')
	OPTION (MAXRECURSION 1000)

	SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1

	SET @days=(SELECT @DAYCOUNT-count(DAYNAME) FROM #TMPSHOWSUNDAY)	

	IF OBJECT_ID('tempdb..#TMPEHEADINGQA') IS NOT NULL
		DROP TABLE #TMPEHEADINGQA
	CREATE TABLE #TMPEHEADINGQA
		(
			HEADID BIGINT,HEADNAME NVARCHAR(800),HEADSHRTNAME NVARCHAR(800),PARRENTID BIGINT
		)
	
	IF OBJECT_ID('tempdb..#EMPLOYEEATTENDANCEQA') IS NOT NULL
	 DROP TABLE #EMPLOYEEATTENDANCEQA
	
	CREATE TABLE #EMPLOYEEATTENDANCEQA (BRANCH_ID BIGINT,BRANCH_DESCRIPTION NVARCHAR(300),USERID BIGINT,EMPCODE NVARCHAR(200),EMPID NVARCHAR(200),EMPNAME NVARCHAR(300),DSTYPE NVARCHAR(300),STATEID BIGINT,
	STATE NVARCHAR(300),DEG_ID BIGINT,DESIGNATION NVARCHAR(300),DATEOFJOINING NVARCHAR(10),CONTACTNO NVARCHAR(100),CH_ID BIGINT,CHANNEL NVARCHAR(100),REPORTTOID NVARCHAR(100),REPORTTOUID NVARCHAR(100),
	REPORTTO NVARCHAR(300),RPTTODESG NVARCHAR(100))
	CREATE NONCLUSTERED INDEX IX1 ON #EMPLOYEEATTENDANCEQA (BRANCH_ID,EMPCODE)

	--FOR REPORT HEADER
	INSERT INTO #TMPEHEADINGQA(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID)
	SELECT 1,'Employee Details [All Unit(s)]','Employee Details [All Unit(s)]',0
	UNION ALL
	SELECT 2,'Branch','BRANCH_DESCRIPTION',1	
	UNION ALL
	SELECT 3,'WD ID','REPORTTOUID',1
	UNION ALL
	SELECT 4,'DS','EMPID',1
	UNION ALL
	SELECT 5,'DS Name','EMPNAME',1
	UNION ALL
	SELECT 6,'DS Type','DSTYPE',1
	UNION ALL
	SELECT 7,'Channel','CHANNEL',1
	SET @SLHEADID=7
	SET @PARENTID=7

	DECLARE @emp_contactId NVARCHAR(100)
	SET @COLUMN_DATE =@FROMDATE

	IF OBJECT_ID('tempdb..#TMPATTENDACEQA') IS NOT NULL
		DROP TABLE #TMPATTENDACEQA
	CREATE TABLE #TMPATTENDACEQA(STARTENDDATE NVARCHAR(10),BRANCH_ID BIGINT,BRANCH_DESCRIPTION NVARCHAR(300),USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),CONTACTNO NVARCHAR(100),
	STATEID BIGINT,STATE NVARCHAR(100),DEG_ID BIGINT,DESIGNATION NVARCHAR(300),DATEOFJOINING NVARCHAR(10),REPORTTOID NVARCHAR(100),REPORTTOUID NVARCHAR(100),REPORTTO NVARCHAR(300),RPTTODESG NVARCHAR(100),
	DSTYPE NVARCHAR(300),CH_ID BIGINT,CHANNEL NVARCHAR(100),PRESENTABSENT INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENDACEQA (BRANCH_ID,EMPCODE)

	IF OBJECT_ID('tempdb..#TMPEMPATTENDACESUMMARYQA') IS NOT NULL
		DROP TABLE #TMPEMPATTENDACESUMMARYQA
	CREATE TABLE #TMPEMPATTENDACESUMMARYQA(BRANCH_ID BIGINT,BRANCH_DESCRIPTION NVARCHAR(300),USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),TOTWORKINGDAYS INT,
	PRESENTABSENT INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPEMPATTENDACESUMMARYQA (BRANCH_ID,EMPCODE)

	SET @LOOPCOUNT=1
	IF @DAYCOUNT>0
		BEGIN
			WHILE @LOOPCOUNT<=@DAYCOUNT
				BEGIN				
					SET @SqlStrTable=''
					SET @SqlStrTable='ALTER TABLE #EMPLOYEEATTENDANCEQA ADD '
					SET @SqlStrTable+='['+RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']' + ' NVARCHAR(50) NULL,'
					SET @SqlStrTable+='[PA_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']'+ ' INT NULL ' 

					EXEC SP_EXECUTESQL @SqlStrTable

					SET @TODATE=@COLUMN_DATE

					INSERT INTO #TMPATTENDACEQA EXEC [PRC_FTSQUALIFIEDATTENDANCE_FETCH] @COLUMN_DATE,@TODATE,@BRANCHID,@EMPID,@CHANNELID,@USERID

					IF (SELECT COUNT(0) FROM #EMPLOYEEATTENDANCEQA A
						INNER JOIN #TMPATTENDACEQA B ON A.BRANCH_ID=B.BRANCH_ID AND A.EMPCODE=B.EMPCODE)>0
						SET @FIRSTTIME=0
					ELSE
						SET @FIRSTTIME=1

					IF @FIRSTTIME=1
						BEGIN
							SET @SqlStrTable=''
							SET @SqlStrTable='INSERT INTO #EMPLOYEEATTENDANCEQA(BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,REPORTTOID,'
							SET @SqlStrTable+='REPORTTOUID,REPORTTO,RPTTODESG,DSTYPE,CH_ID,CHANNEL,'
							SET @SqlStrTable+='[PA_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + '] '
							SET @SqlStrTable+=') '
							SET @SqlStrTable+='SELECT BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,REPORTTOID,REPORTTOUID,REPORTTO,'
							SET @SqlStrTable+='RPTTODESG,DSTYPE,CH_ID,CHANNEL,PRESENTABSENT '
							SET @SqlStrTable+='FROM #TMPATTENDACEQA '

							EXEC SP_EXECUTESQL @SqlStrTable

							SET @FIRSTTIME=0
						END
					ELSE IF @FIRSTTIME=0
						BEGIN
							SET @SqlStrTable=''
							SET @SqlStrTable='UPDATE TEMP SET '
							SET @SqlStrTable+='TEMP.[PA_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']=T.PRESENTABSENT '
							SET @sqlStrTable+='FROM #EMPLOYEEATTENDANCEQA TEMP '
							SET @sqlStrTable+='INNER JOIN #TMPATTENDACEQA T ON TEMP.BRANCH_ID=T.BRANCH_ID AND TEMP.EMPCODE=T.EMPCODE '
						
							EXEC SP_EXECUTESQL @sqlStrTable
						END
						TRUNCATE TABLE #TMPATTENDACEQA

						--FOR REPORT HEADER
						SET @PARENTID=@SLHEADID+1
					
						INSERT INTO #TMPEHEADINGQA(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID) 
						SELECT @SLHEADID+1 AS HEADID,CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105) AS HEADNAME,RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) AS HEADSHRTNAME,0 AS PARRENTID 

						INSERT INTO #TMPEHEADINGQA(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID) 
						SELECT @SLHEADID+2 AS HEADID,'Present/Absent' AS HEADNAME,'PA_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) AS HEADSHRTNAME,@PARENTID AS PARRENTID 

						SET @SLHEADID=@SLHEADID+2

						--FOR REPORT HEADER

						SET @COLUMN_DATE=CONVERT(NVARCHAR(10),(SELECT DATEADD(D, 1, @COLUMN_DATE)),120)
						SET @LOOPCOUNT=@LOOPCOUNT+1
				END
		END		

	INSERT INTO #TMPEHEADINGQA(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID)
	SELECT @SLHEADID+1,'Summary','Summary',0
	UNION ALL
	SELECT @SLHEADID+2,'Total Working Days','TOTWORKINGDAYS',@SLHEADID+1
	UNION ALL
	SELECT @SLHEADID+3,'Total Days Qualified Attendance','TOTDAYSPRESENT',@SLHEADID+1

	ALTER TABLE #EMPLOYEEATTENDANCEQA ADD Summary NVARCHAR(100)
	ALTER TABLE #EMPLOYEEATTENDANCEQA ADD TOTWORKINGDAYS INT DEFAULT(0) WITH VALUES
	ALTER TABLE #EMPLOYEEATTENDANCEQA ADD TOTDAYSPRESENT INT DEFAULT(0) WITH VALUES

	INSERT INTO #TMPEMPATTENDACESUMMARYQA EXEC [PRC_FTSQUALIFIEDATTENDANCESUMMARY_FETCH] @FROMDATE,@TODATE,@BRANCHID,@EMPID,@CHANNELID,@USERID

	UPDATE EMPATT SET EMPATT.TOTWORKINGDAYS=T.TOTWORKINGDAYS FROM #EMPLOYEEATTENDANCEQA AS EMPATT 
	INNER JOIN #TMPEMPATTENDACESUMMARYQA T ON EMPATT.BRANCH_ID=T.BRANCH_ID AND EMPATT.EMPCODE=T.EMPCODE

	UPDATE EMPATT SET EMPATT.TOTDAYSPRESENT=T.TOTDAYSPRESENT FROM #EMPLOYEEATTENDANCEQA AS EMPATT 
	INNER JOIN (SELECT BRANCH_ID,EMPCODE,SUM(PRESENTABSENT) AS TOTDAYSPRESENT FROM #TMPEMPATTENDACESUMMARYQA GROUP BY BRANCH_ID,EMPCODE) T ON EMPATT.BRANCH_ID=T.BRANCH_ID 
	AND EMPATT.EMPCODE=T.EMPCODE

	SELECT * FROM #TMPEHEADINGQA ORDER BY HEADID
	SELECT * FROM #EMPLOYEEATTENDANCEQA

	DROP TABLE #EMPLOYEEATTENDANCEQA
	DROP TABLE #TMPEHEADINGQA
	DROP TABLE #TMPSHOWSUNDAY
	DROP TABLE #TMPEMPATTENDACESUMMARYQA
	DROP TABLE #TMPATTENDACEQA

	SET NOCOUNT OFF
END