--EXEC PRC_FSMUSERWISEDAYSTARTENDAUTOUPDATION

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FSMUSERWISEDAYSTARTENDAUTOUPDATION]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FSMUSERWISEDAYSTARTENDAUTOUPDATION] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FSMUSERWISEDAYSTARTENDAUTOUPDATION]
--WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder On 13/06/2022
Module	   : Scheduler for Auto Update Cutoff Time in FSMUSERWISEDAYSTARTEND table.Refer: 0024934
1.0		v2.0.48		Debashis	02/07/2024		In auto logout schedular, please update IsEnd='0' for auto logout. Rest of the parameters will remain the same.Refer: 0027595
2.0		v2.0.48		Debashis	08/07/2024		The remarks, 'Auto Update Cutoff Time' is generating more than one time against a date for a user in the below mentioned table
												FSMUSERWISEDAYSTARTEND.Now it has been taken care of.Refer: 0027608
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @DAYSTEND_CURSOR CURSOR
	DECLARE @USER_ID BIGINT,@STARTENDDATE NVARCHAR(10),@LOCATION_NAME NVARCHAR(2000),@LATITUDE NVARCHAR(MAX),@LONGITUDE NVARCHAR(MAX),@SHOP_TYPE INT,@SHOP_ID NVARCHAR(200)

	--Rev 2.0 && A new condition CAST(STARTENDDATE AS date)=CAST(GETDATE() AS date) has been added
	SET @DAYSTEND_CURSOR=CURSOR FAST_FORWARD FOR SELECT USER_ID,CAST(STARTENDDATE AS date) AS STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID
	FROM FSMUSERWISEDAYSTARTEND WHERE ISSTART=1 AND CAST(STARTENDDATE AS date)=CAST(GETDATE() AS date) ORDER BY USER_ID,CAST(STARTENDDATE AS date)

	OPEN @DAYSTEND_CURSOR

	FETCH NEXT FROM @DAYSTEND_CURSOR INTO @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID
	WHILE @@FETCH_STATUS=0
		BEGIN
			IF NOT EXISTS(SELECT ISEND FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CAST(STARTENDDATE AS date)=@STARTENDDATE AND ISEND=1)
				BEGIN
					INSERT INTO FSMUSERWISEDAYSTARTEND(USER_ID,STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID,ISSTART,ISEND,SALE_VALUE,REMARKS)
					--Rev 1.0
					--SELECT @USER_ID,@STARTENDDATE+' 21:00:00.000',@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,0,1,0.00,'Auto Update Cutoff Time'
					SELECT @USER_ID,@STARTENDDATE+' 21:00:00.000',@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,0,0,0.00,'Auto Update Cutoff Time'
					--End of Rev 1.0
				END
			FETCH NEXT FROM @DAYSTEND_CURSOR INTO @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID
		END
	CLOSE @DAYSTEND_CURSOR
	DEALLOCATE @DAYSTEND_CURSOR

	SET NOCOUNT OFF
END
GO