IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APICRMOPPORTUNITYDETAIL]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APICRMOPPORTUNITYDETAIL] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APICRMOPPORTUNITYDETAIL]
(
@ACTION NVARCHAR(50),
@USER_ID BIGINT=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@SHOP_NAME NVARCHAR(300)=NULL,
@SHOP_TYPE INT=NULL,
@OPPORTUNITY_ID NVARCHAR(100)=NULL,
@OPPORTUNITY_DESCRIPTION NVARCHAR(300)=NULL,
@OPPORTUNITY_AMOUNT DECIMAL(18,2)=NULL,
@OPPORTUNITY_STATUS_ID BIGINT=NULL,
@OPPORTUNITY_STATUS_NAME NVARCHAR(100)=NULL,
@CREATED_DATE NVARCHAR(10)=NULL,
@CREATED_TIME NVARCHAR(10)=NULL,
@CREATED_DATE_TIME NVARCHAR(20)=NULL,
@EDIT_DATE_TIME NVARCHAR(20)=NULL,
@JsonXML XML=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************
Written By : Debashis Talukder On 31/05/2024
Purpose : For CRM Opportunity Details.Row: 932 to 936
****************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @LASTRECORD BIGINT=0

	IF @ACTION='FETCHOPPORTUNITYSTATUS'
		BEGIN
			SELECT STATUS_ID AS status_id,STATUS_NAME AS status_name FROM FTSCRMOPPORTUNITYSTATUS WHERE IS_ACTIVE=1
		END
	IF @ACTION='INSERTDATA'
		BEGIN
			BEGIN TRAN
				BEGIN TRY
					SET @LASTRECORD=(SELECT TOP 1 ISNULL(ID,0) AS ID FROM FSMCRMOPPORTUNITYHEADER ORDER BY ID DESC)
					IF @LASTRECORD IS NULL
						SET @LASTRECORD=0

					INSERT INTO FSMCRMOPPORTUNITYHEADER(ID,USERID,OPPORTUNITY_ID,OPPORTUNITY_DESCRIPTION,SHOP_ID,SHOP_NAME,SHOP_TYPE,OPPORTUNITY_AMOUNT,OPPORTUNITY_STATUS_ID,OPPORTUNITY_STATUS_NAME,
					CREATED_BY,CREATED_DATE,CREATED_TIME,CREATED_DATE_TIME,CREATED_ON)
					SELECT (@LASTRECORD+1),@USER_ID,@OPPORTUNITY_ID,@OPPORTUNITY_DESCRIPTION,@SHOP_ID,@SHOP_NAME,@SHOP_TYPE,@OPPORTUNITY_AMOUNT,@OPPORTUNITY_STATUS_ID,@OPPORTUNITY_STATUS_NAME,
					@USER_ID,@CREATED_DATE,@CREATED_TIME,(@CREATED_DATE+' '+@CREATED_TIME),GETDATE()
					WHERE EXISTS(SELECT SHOP_CODE FROM tbl_Master_shop WHERE Shop_Code=@SHOP_ID)

					INSERT INTO FSMCRMOPPORTUNITYDETAIL(DETID,USERID,OPPORTUNITY_ID,SHOP_ID,PRODUCT_ID,PRODUCT_NAME)
					SELECT (@LASTRECORD+1),@USER_ID,
					XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)') AS opportunity_id,
					XMLproduct.value('(shop_id/text())[1]','NVARCHAR(100)') AS shop_id,					
					XMLproduct.value('(product_id/text())[1]','BIGINT') AS product_id,
					XMLproduct.value('(product_name/text())[1]','NVARCHAR(300)') AS product_name
					FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct)
					INNER JOIN Master_sProducts MP ON MP.sProducts_ID=XMLproduct.value('(product_id/text())[1]','BIGINT')
					AND EXISTS(SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID)

					SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID
				COMMIT TRAN
			END TRY
			BEGIN CATCH
				ROLLBACK TRAN
				SELECT ERROR_NUMBER() AS ErrorNumber,ERROR_MESSAGE() AS ErrorMessage
			END CATCH
		END
	IF @ACTION='EDITDATA'
		BEGIN
			IF EXISTS(SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID AND USERID=@USER_ID)
				BEGIN
					UPDATE FSMCRMOPPORTUNITYHEADER SET OPPORTUNITY_DESCRIPTION=@OPPORTUNITY_DESCRIPTION,OPPORTUNITY_AMOUNT=@OPPORTUNITY_AMOUNT,
					OPPORTUNITY_STATUS_ID=@OPPORTUNITY_STATUS_ID,OPPORTUNITY_STATUS_NAME=@OPPORTUNITY_STATUS_NAME,MODIFIED_DATE_TIME=@EDIT_DATE_TIME,
					MODIFIED_BY=@USER_ID,MODIFIED_ON=GETDATE()
					WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID AND USERID=@USER_ID

					UPDATE FSMCRMOPPORTUNITYDETAIL SET PRODUCT_ID=XMLproduct.value('(product_id/text())[1]','BIGINT'),
					PRODUCT_NAME=XMLproduct.value('(product_name/text())[1]','NVARCHAR(300)')
					FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct)
					INNER JOIN Master_sProducts MP ON MP.sProducts_ID=XMLproduct.value('(product_id/text())[1]','BIGINT')
					AND EXISTS(SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID AND USERID=@USER_ID)

					SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER WHERE OPPORTUNITY_ID=@OPPORTUNITY_ID
				END
		END
	IF @ACTION='DELETEDATA'
		BEGIN
			IF EXISTS(SELECT OPPORTUNITY_ID FROM FSMCRMOPPORTUNITYHEADER 
			INNER JOIN @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct) ON FSMCRMOPPORTUNITYHEADER.OPPORTUNITY_ID=XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)')
			WHERE USERID=@USER_ID)
				BEGIN
					SELECT 1
					
					DELETE FROM FSMCRMOPPORTUNITYDETAIL 
					WHERE EXISTS(SELECT XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)') FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct) 
					WHERE FSMCRMOPPORTUNITYDETAIL.OPPORTUNITY_ID=XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)'))
					AND USERID=@USER_ID

					DELETE FROM FSMCRMOPPORTUNITYHEADER 
					WHERE EXISTS(SELECT XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)') FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct) 
					WHERE FSMCRMOPPORTUNITYHEADER.OPPORTUNITY_ID=XMLproduct.value('(opportunity_id/text())[1]','NVARCHAR(100)'))
					AND USERID=@USER_ID
				END
		END
	IF @ACTION='FETCHOPPORTUNITYDETAIL'
		BEGIN
			SELECT SHOP_ID AS shop_id,SHOP_NAME AS shop_name,SHOP_TYPE AS shop_type,OPPORTUNITY_ID AS opportunity_id,OPPORTUNITY_DESCRIPTION AS opportunity_description,
			OPPORTUNITY_AMOUNT AS opportunity_amount,OPPORTUNITY_STATUS_ID AS opportunity_status_id,OPPORTUNITY_STATUS_NAME AS opportunity_status_name,CREATED_DATE AS opportunity_created_date,
			CREATED_TIME AS opportunity_created_time,CREATED_DATE_TIME AS opportunity_created_date_time,MODIFIED_DATE_TIME AS opportunity_edited_date_time 
			FROM FSMCRMOPPORTUNITYHEADER WHERE USERID=@USER_ID

			SELECT SHOP_ID AS shop_id,OPPORTUNITY_ID AS opportunity_id,PRODUCT_ID AS product_id,PRODUCT_NAME AS product_name
			FROM FSMCRMOPPORTUNITYDETAIL WHERE USERID=@USER_ID
		END

	SET NOCOUNT OFF
END
GO