IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSAPITASKMANAGEMENTINFO]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSAPITASKMANAGEMENTINFO] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSAPITASKMANAGEMENTINFO]
(
@ACTION NVARCHAR(100)=NULL,
@USER_ID BIGINT=NULL,
@FROM_DATE NVARCHAR(10)=NULL,
@TO_DATE NVARCHAR(10)=NULL,
@TASK_PRIORITY_ID NVARCHAR(MAX)=NULL,
@TASK_PRIORITY_NAME NVARCHAR(MAX)=NULL,
@TASK_ID BIGINT=NULL,
@TASK_DATE DATETIME=NULL,
@TASK_TIME NVARCHAR(10)=NULL,
@TASK_STATUS NVARCHAR(200)=NULL,
@TASK_DETAILS NVARCHAR(100)=NULL,
@OTHER_REMARKS NVARCHAR(500)=NULL,
@TASK_NEXT_DATE DATETIME=NULL,
@TASK_STATUS_ID BIGINT=NULL
) --WITH ENCRYPTION
AS
/**********************************************************************************************************************************************************************
Written By : Debashis Talukder On 16/05/2023
Purpose : For New Task Management MODULE.Row 829 to 832
**********************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX)

	IF @ACTION='TaskPriorityWiseList'
		BEGIN
			IF OBJECT_ID('tempdb..#TASKPRIORITYLIST') IS NOT NULL
				DROP TABLE #TASKPRIORITYLIST
			CREATE TABLE #TASKPRIORITYLIST (TASKPRIORITY_ID BIGINT NULL)
			CREATE NONCLUSTERED INDEX IX ON #TASKPRIORITYLIST (TASKPRIORITY_ID ASC)

			IF @TASK_PRIORITY_ID<>''
				BEGIN
					SET @SqlStrTable=''
					SET @TASK_PRIORITY_ID=REPLACE(@TASK_PRIORITY_ID,'''','')
					SET @sqlStrTable='INSERT INTO #TASKPRIORITYLIST SELECT TASKPRIORITY_ID FROM MASTER_TASKPRIORITY WHERE TASKPRIORITY_ID IN ('+@TASK_PRIORITY_ID+')'
					EXEC SP_EXECUTESQL @SqlStrTable
				END

			SET @Strsql=''
			SET @Strsql='SELECT MT.TASK_ID AS task_id,MT.TASK_NAME AS task_name,MT.TASK_DETAILS AS task_details,CONVERT(NVARCHAR(10),MT.TASK_DUEDATE,105) AS due_date,'
			SET @Strsql+='CONVERT(VARCHAR(8),CAST(MT.TASK_DUEDATE AS TIME),108) AS due_time,CONVERT(NVARCHAR(10),MT.TASK_STARTDATE,105) AS start_date,'
			SET @Strsql+='CONVERT(VARCHAR(8),CAST(MT.TASK_STARTDATE AS TIME),108) AS start_time,MTP.TASKPRIORITY_FROM AS priority_type_name,MT.TASK_STATUS AS status '
			SET @Strsql+='FROM MASTER_TASKMANAGEMENT MT '
			SET @Strsql+='INNER JOIN MASTER_TASKPRIORITY MTP ON MT.TASK_PRIORITY=MTP.TASKPRIORITY_ID '
			SET @Strsql+='WHERE MT.TASK_SALESMANASSIGNID='+LTRIM(RTRIM(STR(@USER_ID)))+ ' '
			SET @Strsql+='AND CONVERT(NVARCHAR(10),MT.TASK_STARTDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROM_DATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TO_DATE+''',120) '
			IF @TASK_PRIORITY_ID<>''
				SET @Strsql+='AND EXISTS (SELECT TASKPRIORITY_ID FROM #TASKPRIORITYLIST AS F WHERE F.TASKPRIORITY_ID=MTP.TASKPRIORITY_ID) '

			--SELECT @Strsql
			EXEC SP_EXECUTESQL @Strsql

			DROP TABLE #TASKPRIORITYLIST
		END
	ELSE IF @ACTION='AddTaskDetailList'
		BEGIN
			IF NOT EXISTS(SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID)
				BEGIN
					INSERT INTO FTSTASKMANAGEMENTDETAIL(TASK_ID,TASK_DATE,TASK_TIME,TASK_STATUS,TASK_DETAILS,OTHER_REMARKS,TASK_NEXT_DATE,ISACTIVE,CREATE_USER,CREATE_DATE)
					SELECT @TASK_ID,@TASK_DATE,@TASK_TIME,@TASK_STATUS,@TASK_DETAILS,@OTHER_REMARKS,@TASK_NEXT_DATE,CAST(1 AS BIT),@USER_ID,GETDATE()

					SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID
				END
			ELSE IF EXISTS(SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID)
				BEGIN
					UPDATE FTSTASKMANAGEMENTDETAIL SET ISACTIVE=0,MODIFIED_USER=@USER_ID,MODIFIED_DATE=GETDATE() 
					WHERE TASK_ID=@TASK_ID

					INSERT INTO FTSTASKMANAGEMENTDETAIL(TASK_ID,TASK_DATE,TASK_TIME,TASK_STATUS,TASK_DETAILS,OTHER_REMARKS,TASK_NEXT_DATE,ISACTIVE,CREATE_USER,CREATE_DATE)
					SELECT @TASK_ID,@TASK_DATE,@TASK_TIME,@TASK_STATUS,@TASK_DETAILS,@OTHER_REMARKS,@TASK_NEXT_DATE,CAST(1 AS BIT),@USER_ID,GETDATE()

					SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID
				END
		END
	ELSE IF @ACTION='EditTaskDetailList'
		BEGIN
			IF EXISTS(SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID AND TASK_STATUS_ID=@TASK_STATUS_ID)
				BEGIN
					UPDATE FTSTASKMANAGEMENTDETAIL SET ISACTIVE=0,MODIFIED_USER=@USER_ID,MODIFIED_DATE=GETDATE() 
					WHERE TASK_ID=@TASK_ID

					UPDATE FTSTASKMANAGEMENTDETAIL SET TASK_DATE=@TASK_DATE,TASK_TIME=@TASK_TIME,TASK_STATUS=@TASK_STATUS,TASK_DETAILS=@TASK_DETAILS,OTHER_REMARKS=@OTHER_REMARKS,
					TASK_NEXT_DATE=@TASK_NEXT_DATE,ISACTIVE=1,MODIFIED_USER=@USER_ID,MODIFIED_DATE=GETDATE() 
					WHERE TASK_ID=@TASK_ID AND TASK_STATUS_ID=@TASK_STATUS_ID

					SELECT TASK_ID FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID AND TASK_STATUS_ID=@TASK_STATUS_ID
				END
		END
	ELSE IF @ACTION='GetTaskDetailList'
		BEGIN
			SELECT TASK_STATUS_ID AS task_status_id,CONVERT(NVARCHAR(10),TASK_DATE,120) AS task_date,TASK_TIME AS task_time,TASK_STATUS AS task_status,TASK_DETAILS AS task_details,
			OTHER_REMARKS AS other_remarks,CONVERT(NVARCHAR(10),TASK_NEXT_DATE,120) AS task_next_date,ISACTIVE AS isactive_status
			FROM FTSTASKMANAGEMENTDETAIL WHERE TASK_ID=@TASK_ID
		END
	SET NOCOUNT OFF
END