--EXEC PRC_LATEVBISITSUMMARY @fromdate='2019-10-01',@todate='2019-10-31',@firstshopvisittime='11:00:00',@lastshopvisittime='18:00:00',@stateid='15,28',@designation='114',@employee='',@inactive=0,@notlogged=0,@duration=60

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_LATEVBISITSUMMARY]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_LATEVBISITSUMMARY] AS' 
END
GO   
ALTER PROCEDURE [PRC_LATEVBISITSUMMARY]  
(
@ACTION VARCHAR(500)  = null,
@fromdate datetime =null,
@todate datetime =null,
@stateid  VARCHAR(max) =null,
@designation VARCHAR(max) =null,
@employee VARCHAR(max) =null,
@firstshopvisittime time =null,
@lastshopvisittime time=null,
@USER_ID BIGINT=0,
@inactive bit =0,
@notlogged bit =0,
@duration varchaR(50) =0
) --WITH ENCRYPTION
AS
/*******************************************************************************************************************************************************************************************
1.0		v2.0.12		Debashis	15/07/2020		Employee Code column required in the Employee Visit analysis Report.Refer: 0022700
********************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	CREATE TABLE #TEMP_STATE(STATEID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_DESIGNATION(DESGID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_EMPLOYEE(EMPID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_CONTACT(CONTACTID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,CON_NAME VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_SHOP(SHOP_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,SHOP_NAME VARCHAR(1000) COLLATE SQL_Latin1_General_CP1_CI_AS,SHOP_ADDRESS VARCHAR(1000),PP_NAME VARCHAR(1000) COLLATE SQL_Latin1_General_CP1_CI_AS,DD_NAME VARCHAR(1000) COLLATE SQL_Latin1_General_CP1_CI_AS,MOBILE VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_ADDRESS(STATE_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,STATE_NAME VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS,EMP_INTERNALID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_ATTENDAANCE(USER_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,ATT_DATE DATE,ATT_STATUS VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE TABLE #TEMP_LOGIN(USER_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGIN_DATE DATE,LOGIN_TIME DATETIME)
	CREATE TABLE #TEMP_LOGOUT(USER_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGOUT_DATE DATE,LOGOUT_TIME DATETIME)
	CREATE TABLE #TEMP_ORDER(USER_ID VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,ORDER_DATE DATE,ORDER_VALUE NUMERIC(18,2))

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'EMPLOYEE_LATE_VISIT_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE EMPLOYEE_LATE_VISIT_REPORT
			(
			SL BIGINT,
			--Rev 1.0
			EMPID NVARCHAR(100),
			--End of Rev 1.0
			EMP_NAME VARCHAR(500),
			STATE_NAME VARCHAR(500),
			DESIGNATION VARCHAR(500),
			SUPERVISOR_NAME VARCHAR(500),
			VISIT_DATE DATETIME,
			ATT_STATUS VARCHAR(500),
			LOGIN_TIME DATETIME,
			total_Count  VARCHAR(500),
			PARTY_NAME_FIRST  VARCHAR(500),
			MOBILE_FIRST  VARCHAR(500),
			SHOP_ADDRESS_FIRST  VARCHAR(500),
			PP_NAME_FIRST  VARCHAR(500),
			DD_NAME_FIRST  VARCHAR(500),
			FIRST_VISIT DATETIME,
			FIRST_REMARKS  VARCHAR(500),
			FIRST_DURATION  VARCHAR(500),
			ONE_HOUR_FIRST_REMARKS  VARCHAR(500),
			PARTY_NAME_LAST  VARCHAR(500),
			MOBILE_LAST  VARCHAR(500),
			SHOP_ADDRESS_LAST  VARCHAR(500),
			PP_NAME_LAST  VARCHAR(500),
			DD_NAME_LAST VARCHAR(500),
			LAST_VISIT DATETIME,
			LAST_REMARKS VARCHAR(500),
			LAST_DURATION  VARCHAR(500),
			ONE_HOUR_LAST_REMARKS VARCHAR(500),
			LOGOUT_TIME DATETIME,
			ORDER_VALUE NUMERIC(18,2),
			USER_ID BIGINT	
			)
		END
	DELETE FROM EMPLOYEE_LATE_VISIT_REPORT WHERE [USER_ID]=@USER_ID

	SELECT * INTO #SHOPSUBMIT FROM tbl_trans_shopActivitysubmit WHERE CAST(visited_date AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)

	INSERT INTO #TEMP_ORDER
	SELECT userID,CAST(Orderdate AS DATE),SUM(Ordervalue) 
	FROM tbl_trans_fts_Orderupdate WHERE CAST(Orderdate AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	GROUP BY userID,CAST(Orderdate AS DATE)

	INSERT INTO #TEMP_SHOP
	SELECT SHOP.Shop_Code,SHOP.Shop_Name,SHOP.Address,PP.Shop_Name,DD.Shop_Name,SHOP.Shop_Owner_Contact FROM TBL_MASTER_SHOP SHOP
	LEFT JOIN TBL_MASTER_SHOP PP ON SHOP.assigned_to_pp_id=PP.Shop_Code
	LEFT JOIN TBL_MASTER_SHOP DD ON SHOP.assigned_to_dd_id=DD.Shop_Code

	INSERT INTO #TEMP_ADDRESS
	SELECT add_state,STATE.state,add_cntId FROM tbl_master_address ADDR
	INNER JOIN TBL_MASTER_STATE STATE ON STATE.ID=ADDR.add_state
	WHERE add_entity='employee' AND add_addressType='Office'

	INSERT INTO #TEMP_ATTENDAANCE
	SELECT DISTINCT USER_ID,
	CAST(Work_datetime AS DATE),
	CASE WHEN Isonleave='TRUE' THEN 'ON LEAVE' ELSE 'AT WORK' END ATT_STATUS 
	FROM tbl_fts_UserAttendanceLoginlogout 

	INSERT INTO #TEMP_LOGOUT
	SELECT User_Id ,CAST(Work_datetime AS DATE) LOGIN_DATE,MAX(Logout_datetime) LAST_LOGOUT FROM tbl_fts_UserAttendanceLoginlogout WHERE 
	CAST(Work_datetime AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	and Login_datetime IS NULL
	GROUP BY User_Id ,CAST(Work_datetime AS DATE)

	--SELECT User_Id ,CAST(SDate AS DATE) LOGIN_DATE,MAX(SDate) LAST_LOGOUT FROM TBL_TRANS_SHOPUSER_ARCH WHERE 
	--location_name LIKE 'Logout at%'  AND CAST(SDate AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	--GROUP BY User_Id ,CAST(SDate AS DATE)
	--UNION 
	--SELECT User_Id ,CAST(SDate AS DATE) LOGIN_DATE,MAX(SDate) LAST_LOGOUT FROM TBL_TRANS_SHOPUSER WHERE 
	--location_name LIKE 'Logout at%'  AND CAST(SDate AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	--GROUP BY User_Id ,CAST(SDate AS DATE)

	INSERT INTO #TEMP_LOGIN
	SELECT User_Id ,CAST(Work_datetime AS DATE) LOGIN_DATE,MAX(Login_datetime) FIRST_LOGIN FROM tbl_fts_UserAttendanceLoginlogout WHERE 
	CAST(Work_datetime AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	and Logout_datetime IS NULL
	GROUP BY User_Id ,CAST(Work_datetime AS DATE)

	--SELECT User_Id ,CAST(SDate AS DATE) LOGIN_DATE,Min(SDate) FIRST_LOGIN FROM TBL_TRANS_SHOPUSER_ARCH 
	--WHERE location_name LIKE 'Login from%'  AND CAST(SDate AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	--GROUP BY User_Id ,CAST(SDate AS DATE)
	--UNION 
	--SELECT User_Id ,CAST(SDate AS DATE) LOGIN_DATE,Min(SDate) FIRST_LOGIN FROM TBL_TRANS_SHOPUSER_ARCH 
	--WHERE location_name LIKE 'Login from%'  AND CAST(SDate AS DATE) BETWEEN CAST(@fromdate AS DATE) AND CAST(@todate AS DATE)
	--GROUP BY User_Id ,CAST(SDate AS DATE)

	IF(ISNULL(@stateid,'')<>'')
		BEGIN  
    
			INSERT INTO #TEMP_STATE 
			SELECT s FROM DBO.GetSplit(',',@stateid)
		END
	ELSE
		BEGIN
			INSERT INTO #TEMP_STATE 
			SELECT ID FROM tbl_master_state
		END

	IF(ISNULL(@designation,'')<>'')
		BEGIN    
			INSERT INTO #TEMP_DESIGNATION
			SELECT s FROM DBO.GetSplit(',',@designation)
		END
	ELSE
		BEGIN
			INSERT INTO #TEMP_DESIGNATION 
			SELECT deg_id FROM tbl_master_designation
		END

	IF(ISNULL(@employee,'')<>'')
		BEGIN
			IF(@inactive=1)    
			INSERT INTO #TEMP_EMPLOYEE
			SELECT s FROM DBO.GetSplit(',',@employee)
			ELSE
			INSERT INTO #TEMP_EMPLOYEE
			SELECT s FROM DBO.GetSplit(',',@employee) WHERE S IN (SELECT user_contactId FROM tbl_master_user WHERE user_inactive='N')
		END
	ELSE
		BEGIN
			IF(@inactive=1)
			INSERT INTO #TEMP_EMPLOYEE 
			SELECT emp_contactId FROM tbl_master_employee
			ELSE
			INSERT INTO #TEMP_EMPLOYEE 
			SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN (SELECT user_contactId FROM tbl_master_user WHERE user_inactive='N')
		END

	DECLARE @STR NVARCHAR(MAX)=''

	--SELECT * FROM (
	SET @STR=@STR+ 'SELECT ROW_NUMBER() OVER (ORDER BY EMP.emp_id),'
	--Rev 1.0 
	--SET @STR=@STR+ 'ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''')  EMP_NAME, '
	SET @STR=@STR+ 'EMP.emp_uniqueCode AS EMPID,'
	SET @STR=@STR+ 'ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMP_NAME,'
	--End of Rev 1.0 
	SET @STR=@STR+ 'TBL_ADD.STATE_NAME STATE_NAME, '
	SET @STR=@STR+ 'DESG.deg_designation DESIGNATION, '
	SET @STR=@STR+ 'ISNULL(CNT_REP.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT_REP.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT_REP.CNT_LASTNAME,'''')  SUPERVISOR_NAME, '
	SET @STR=@STR+ 'TBL_VISITTIME.VISIT_DATE VISIT_DATE, '
	SET @STR=@STR+ 'CASE WHEN ISNULL(ATT.ATT_STATUS,'''')='''' THEN ''NOT LOGGED IN'' ELSE ATT.ATT_STATUS END ATT_STATUS, '
	SET @STR=@STR+ 'LOGINS.LOGIN_TIME  LOGIN_TIME, '
	SET @STR=@STR+ 'TBL_VISITTIME.TOTAL_VISIT total_Count, '
	SET @STR=@STR+ 'FIRST.SHOP_NAME PARTY_NAME_FIRST, '
	SET @STR=@STR+ 'FIRST.SHOP_ADDRESS SHOP_ADDRESS_FIRST, '
	SET @STR=@STR+ 'FIRST.PP_NAME PP_NAME_FIRST, '
	SET @STR=@STR+ 'FIRST.DD_NAME DD_NAME_FIRST, '
	SET @STR=@STR+ 'TBL_VISITTIME.FIRST_VISIT FIRST_VISIT, '
	SET @STR=@STR+ 'CASE WHEN CONVERT(VARCHAR(10),TBL_VISITTIME.FIRST_VISIT,108)>'''+ cONVERT(VARCHAR(10),@firstshopvisittime,108)+''' THEN ''Late'' ELSE '''' END FIRST_REMARKS, '
	SET @STR=@STR+ 'ACT_FIRST.spent_duration FIRST_DURATION, '
	SET @STR=@STR+ 'CASE WHEN ISDATE(ACT_FIRST.spent_duration)=1 THEN '

	IF(@duration=5)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>'+@duration+' THEN ''5 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=15)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15   THEN ''15 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=30)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30   THEN ''30 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=60)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>60   THEN ''1 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=90)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>90   THEN ''1 AND HALF HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=120)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>120  THEN ''2 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=150)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>120 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=150  THEN ''2 HOUR TO 2 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>150  THEN ''2 AND HALF HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END
	ELSE IF(@duration=180)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>120 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=150  THEN ''2 HOUR TO 2 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>150 AND (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))<=180  THEN ''2 AND HALF HOUR TO 3 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_FIRST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_FIRST.spent_duration AS TIME))>180  THEN ''3 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_FIRST_REMARKS, '
		END

	SET @STR=@STR+ 'LAST.SHOP_NAME PARTY_NAME_LAST, '
	SET @STR=@STR+ 'LAST.SHOP_ADDRESS SHOP_ADDRESS_LAST, '
	SET @STR=@STR+ 'LAST.PP_NAME PP_NAME_LAST, '
	SET @STR=@STR+ 'LAST.DD_NAME DD_NAME_LAST, '
	SET @STR=@STR+ 'TBL_VISITTIME.LAST_VISIT LAST_VISIT, '
	SET @STR=@STR+ 'CASE WHEN CONVERT(VARCHAR(10),TBL_VISITTIME.LAST_VISIT,108)<'''+ cONVERT(VARCHAR(10),@lastshopvisittime,108)+''' THEN ''Early Exit'' ELSE '''' END LAST_REMARKS, '
	SET @STR=@STR+ 'ACT_LAST.spent_duration LAST_DURATION, '
	SET @STR=@STR+ 'CASE WHEN ISDATE(ACT_LAST.spent_duration)=1 THEN '

	IF(@duration=5)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>'+@duration+' THEN ''5 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=15)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15   THEN ''15 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=30)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30   THEN ''30 MIN. ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=60)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>60   THEN ''1 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=90)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>90   THEN ''1 AND HALF HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=120)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>120  THEN ''2 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=150)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>120 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=150  THEN ''2 HOUR TO 2 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>150  THEN ''2 AND HALF HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END
	ELSE IF(@duration=180)
		BEGIN
			SET @STR=@STR+ 'CASE WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>0 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=5  THEN ''0 TO 5 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>5 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=15  THEN ''6 TO 15 MIN.''   '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>15 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=30  THEN ''16 TO 30 MIN.''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>30 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=60  THEN ''31 MIN. TO 1 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>60 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=90  THEN ''1 HOUR TO 1 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>90 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=120  THEN ''1 AND HALF HOUR TO 2 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>120 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=150  THEN ''2 HOUR TO 2 AND HALF HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>150 AND (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))<=180  THEN ''2 AND HALF HOUR TO 3 HOUR''  '
			SET @STR=@STR+ 'WHEN (DATEPART(HOUR, CAST(ACT_LAST.spent_duration AS TIME)) *60)+ DATEPART(MINUTE, CAST(ACT_LAST.spent_duration AS TIME))>180  THEN ''3 HOUR ABOVE'' ELSE '''' END  '
			SET @STR=@STR+ 'ELSE '''' END ONE_HOUR_LAST_REMARKS, '
		END

	SET @STR=@STR+ 'LOGOUT.LOGOUT_TIME LOGOUT_TIME, '
	SET @STR=@STR+ 'ORDERS.ORDER_VALUE ORDER_VALUE, '
	SET @STR=@STR+ ''+cast(@USER_ID as varchar(250)) +','
	SET @STR=@STR+ 'FIRST.MOBILE FIRST_MOBILE, '
	SET @STR=@STR+ 'LAST.MOBILE LAST_MOBILE '
	SET @STR=@STR+ 'FROM tbl_master_employee EMP '
	SET @STR=@STR+ 'INNER JOIN tbl_master_contact CNT ON CNT.cnt_internalId=EMP.emp_contactId AND EXISTS (SELECT 1 FROM #TEMP_EMPLOYEE EMP WHERE EMP.EMPID=CNT.cnt_internalId) '
	SET @STR=@STR+ 'INNER JOIN tbl_master_user USR ON CNT.cnt_internalId=USR.user_contactId '
	SET @STR=@STR+ 'INNER JOIN #TEMP_ADDRESS TBL_ADD ON TBL_ADD.EMP_INTERNALID=CNT.cnt_internalId   AND EXISTS (SELECT 1 FROM #TEMP_STATE ST WHERE ST.STATEID=TBL_ADD.STATE_ID)  '
	SET @STR=@STR+ 'INNER JOIN '
	SET @STR=@STR+ '( '
	SET @STR=@STR+ 'SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id,emp_reportTo FROM tbl_trans_employeeCTC AS cnt  '
	SET @STR=@STR+ 'LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL  '
	SET @STR=@STR+ 'GROUP BY emp_cntId,desg.deg_designation,desg.deg_id,emp_reportTo) DESG  '
	SET @STR=@STR+ 'ON DESG.emp_cntId=EMP.emp_contactId AND EXISTS (SELECT 1 FROM #TEMP_DESIGNATION DEG WHERE DEG.DESGID=DESG.deg_id)  '
	SET @STR=@STR+ 'LEFT JOIN tbl_master_employee EMP_REP ON EMP_REP.emp_id=DESG.emp_reportTo '
	SET @STR=@STR+ 'LEFT JOIN tbl_master_contact CNT_REP ON EMP_REP.emp_contactId=CNT_REP.cnt_internalId '
	IF(@notlogged=1)
		SET @STR=@STR+ 'LEFT JOIN  '
	ELSE
		SET @STR=@STR+ 'INNER JOIN  '
	SET @STR=@STR+ '( '
	SET @STR=@STR+ 'select max(visited_time) LAST_VISIT,min(visited_time) FIRST_VISIT,count(0) TOTAL_VISIT,User_Id USER_ID,cast(visited_time as date) VISIT_DATE  '
	SET @STR=@STR+ 'from tbl_trans_shopActivitysubmit WHERE CONVERT(nvarchar(10),visited_date ,120) BETWEEN '''+CONVERT(nvarchar(10),@fromdate,120)+'''  AND '''+CONVERT(nvarchar(10),@todate,120)+ ''' '
	SET @STR=@STR+ 'group by User_Id,cast(visited_time as date) '
	SET @STR=@STR+ ') TBL_VISITTIME ON TBL_VISITTIME.USER_ID=USR.user_id '
	SET @STR=@STR+ 'LEFT JOIN #SHOPSUBMIT ACT_FIRST ON ACT_FIRST.User_Id=USR.user_id AND ACT_FIRST.visited_time=TBL_VISITTIME.FIRST_VISIT '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_SHOP FIRST ON FIRST.SHOP_ID=ACT_FIRST.Shop_Id '
	SET @STR=@STR+ 'LEFT JOIN #SHOPSUBMIT ACT_LAST ON ACT_LAST.User_Id=USR.user_id AND ACT_LAST.visited_time=TBL_VISITTIME.LAST_VISIT '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_SHOP LAST ON LAST.SHOP_ID=ACT_LAST.Shop_Id '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_ATTENDAANCE ATT ON ATT.USER_ID=USR.user_id AND ATT.ATT_DATE=TBL_VISITTIME.VISIT_DATE '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_LOGIN LOGINS ON LOGINS.USER_ID=USR.user_id AND LOGINS.LOGIN_DATE=TBL_VISITTIME.VISIT_DATE '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_LOGOUT LOGOUT ON LOGOUT.USER_ID=USR.user_id AND LOGOUT.LOGOUT_DATE=TBL_VISITTIME.VISIT_DATE '
	SET @STR=@STR+ 'LEFT JOIN #TEMP_ORDER ORDERS ON ORDERS.USER_ID=USR.user_id AND CAST(ORDERS.ORDER_DATE AS DATE)=TBL_VISITTIME.VISIT_DATE '
	--) TBL_FINAL
	--WHERE STATE_ID IN (SELECT TMP.STATEID FROM @TEMP_STATE TMP)

	--Rev 1.0 && EMPID has been implement
	INSERT INTO EMPLOYEE_LATE_VISIT_REPORT(SL,EMPID,EMP_NAME,STATE_NAME,DESIGNATION,SUPERVISOR_NAME,VISIT_DATE,ATT_STATUS,LOGIN_TIME,total_Count,PARTY_NAME_FIRST,SHOP_ADDRESS_FIRST,PP_NAME_FIRST,
	DD_NAME_FIRST,FIRST_VISIT,FIRST_REMARKS,FIRST_DURATION,ONE_HOUR_FIRST_REMARKS,PARTY_NAME_LAST,SHOP_ADDRESS_LAST,PP_NAME_LAST,DD_NAME_LAST,LAST_VISIT,LAST_REMARKS,LAST_DURATION,ONE_HOUR_LAST_REMARKS,
	LOGOUT_TIME,ORDER_VALUE,USER_ID,MOBILE_FIRST,MOBILE_LAST)
	EXEC (@STR)

	DROP TABLE #TEMP_STATE
	DROP TABLE #TEMP_DESIGNATION
	DROP TABLE #TEMP_EMPLOYEE
	DROP TABLE #TEMP_CONTACT
	DROP TABLE #TEMP_SHOP
	DROP TABLE #TEMP_ADDRESS
	DROP TABLE #TEMP_ATTENDAANCE
	DROP TABLE #TEMP_LOGIN
	DROP TABLE #TEMP_LOGOUT
	DROP TABLE #TEMP_ORDER
	DROP TABLE #SHOPSUBMIT

	SET NOCOUNT OFF
END