IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APISALESQUOTATIONADDUPDATEDELFETCH]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APISALESQUOTATIONADDUPDATEDELFETCH] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APISALESQUOTATIONADDUPDATEDELFETCH]
(
@ACTION NVARCHAR(50),
@USER_ID BIGINT=NULL,
@QUOTATION_NUMBER NVARCHAR(100)=NULL,
@QUOTATIONSAVE_DATE DATETIME=NULL,
@QUOTATION_DATE_SELECTION DATETIME=NULL,
@PROJECT_NAME NVARCHAR(300)=NULL,
@TAXES NVARCHAR(300)=NULL,
@FREIGHT NVARCHAR(300)=NULL,
@DELIVERY_TIME NVARCHAR(50)=NULL,
@PAYMENT NVARCHAR(300)=NULL,
@VALIDITY NVARCHAR(300)=NULL,
@BILLING NVARCHAR(300)=NULL,
@PRODUCT_TOLERANCE_OF_THICKNESS NVARCHAR(300)=NULL,
@TOLERANCE_OF_COATING_THICKNESS NVARCHAR(300)=NULL,
@SALESMAN_USER_ID BIGINT=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@QUOTATION_CREATED_LAT NVARCHAR(MAX)=NULL,
@QUOTATION_CREATED_LONG NVARCHAR(MAX)=NULL,
@QUOTATION_CREATED_ADDRESS NVARCHAR(MAX)=NULL,
@JsonXML XML=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************
Written By : Debashis Talukder On 21/02/2022
Purpose : For New Sales Quptation.Row 647 to 652
****************************************************************************************************************/
BEGIN
	SET NOCOUNT ON
	
	DECLARE @HEADERID BIGINT

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF @ACTION='SAVEDATA'
		BEGIN
			IF EXISTS(SELECT QUOTATION_NUMBER FROM FSMAPIQUOTATIONHEAD WHERE QUOTATION_NUMBER=@QUOTATION_NUMBER)
				BEGIN
					SELECT QUOTATION_NUMBER,'Duplicate' AS STRMESSAGE FROM FSMAPIQUOTATIONHEAD WHERE USER_ID=@USER_ID AND QUOTATION_NUMBER=@QUOTATION_NUMBER
				END
			ELSE
				BEGIN
					BEGIN TRAN
						BEGIN TRY
							IF NOT EXISTS(SELECT QUOTATION_NUMBER FROM FSMAPIQUOTATIONHEAD WHERE QUOTATION_NUMBER=@QUOTATION_NUMBER)
								BEGIN
									INSERT INTO FSMAPIQUOTATIONHEAD(USER_ID,QUOTATION_NUMBER,QUOTATIONSAVE_DATE,QUOTATION_DATE_SELECTION,PROJECT_NAME,TAXES,FREIGHT,DELIVERY_TIME,PAYMENT,VALIDITY,BILLING,
									PRODUCT_TOLERANCE_OF_THICKNESS,TOLERANCE_OF_COATING_THICKNESS,SALESMAN_USER_ID,SHOP_ID,QUOTATION_CREATED_LAT,QUOTATION_CREATED_LONG,QUOTATION_CREATED_ADDRESS,CREATED_BY,
									CREATED_DATE)
									SELECT @USER_ID,@QUOTATION_NUMBER,@QUOTATIONSAVE_DATE,@QUOTATION_DATE_SELECTION,@PROJECT_NAME,@TAXES,@FREIGHT,@DELIVERY_TIME,@PAYMENT,@VALIDITY,@BILLING,
									@PRODUCT_TOLERANCE_OF_THICKNESS,@TOLERANCE_OF_COATING_THICKNESS,@SALESMAN_USER_ID,@SHOP_ID,@QUOTATION_CREATED_LAT,@QUOTATION_CREATED_LONG,@QUOTATION_CREATED_ADDRESS,
									@USER_ID,GETDATE()

									SET @HEADERID=SCOPE_IDENTITY();
								END			

							IF(@@ROWCOUNT>0)
								BEGIN
									INSERT INTO FSMAPIQUOTATIONDETAILS(HEADID,USER_ID,QUOTATION_NUMBER,SHOP_ID,PROD_ID,PRODUCT_NAME,COLOR_ID,QTY,RATE_SQFT,RATE_SQMTR,AMOUNT)
									SELECT @HEADERID,@USER_ID,@QUOTATION_NUMBER,@SHOP_ID,
									XMLproduct.value('(product_id/text())[1]','BIGINT') AS product_id,
									MP.sProducts_Name,
									XMLproduct.value('(color_id/text())[1]','NVARCHAR(80)') AS color_id,
									XMLproduct.value('(qty/text())[1]','DECIMAL(18,2)') AS qty,
									XMLproduct.value('(rate_sqft/text())[1]','DECIMAL(18,2)') AS rate_sqft,
									XMLproduct.value('(rate_sqmtr/text())[1]','DECIMAL(18,2)') AS rate_sqmtr,
									XMLproduct.value('(amount/text())[1]','DECIMAL(18,2)') AS amount
									FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct)
									INNER JOIN Master_sProducts MP ON MP.sProducts_ID=XMLproduct.value('(product_id/text())[1]','BIGINT')

									SELECT QUOTATION_NUMBER,'Unique' AS STRMESSAGE FROM FSMAPIQUOTATIONHEAD WHERE USER_ID=@USER_ID AND QUOTATION_NUMBER=@QUOTATION_NUMBER
								END
							COMMIT TRAN
						END TRY
					BEGIN CATCH
						ROLLBACK TRAN
					END CATCH
				END
		END
	ELSE IF @ACTION='SHOPWISEQUOTATIONLIST'
		BEGIN
			SELECT MS.Shop_Code AS shop_id,MS.Shop_Name AS shop_name,MS.Shop_Owner_Contact AS shop_phone_no,QH.QUOTATION_NUMBER AS quotation_number,QH.QUOTATIONSAVE_DATE AS save_date_time 
			FROM tbl_Master_shop MS
			INNER JOIN FSMAPIQUOTATIONHEAD QH ON MS.Shop_Code=QH.SHOP_ID
			WHERE MS.Shop_Code=@SHOP_ID
		END
	ELSE IF @ACTION='SHOWQUOTATIONDETAILS'
		BEGIN
			SELECT QH.QUOTATION_NUMBER AS quotation_number,CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,105)+' '+CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,108) AS save_date_time,
			CONVERT(NVARCHAR(10),QH.QUOTATION_DATE_SELECTION,105) AS quotation_date_selection,QH.PROJECT_NAME AS project_name,QH.TAXES AS taxes,QH.FREIGHT AS Freight,QH.DELIVERY_TIME AS delivery_time,
			QH.PAYMENT AS payment,QH.VALIDITY AS validity,QH.BILLING AS billing,QH.PRODUCT_TOLERANCE_OF_THICKNESS AS product_tolerance_of_thickness,QH.TOLERANCE_OF_COATING_THICKNESS AS tolerance_of_coating_thickness,
			QH.SALESMAN_USER_ID AS salesman_user_id,QH.SHOP_ID AS shop_id,MS.Shop_Name AS shop_name,MS.Shop_Owner_Contact AS shop_phone_no,QH.QUOTATION_CREATED_LAT AS quotation_created_lat,
			QH.QUOTATION_CREATED_LONG AS quotation_created_long,QH.QUOTATION_CREATED_ADDRESS AS quotation_created_address,MS.Address AS shop_addr,MS.Shop_Owner_Email AS shop_email,
			MS.Shop_Owner AS shop_owner_name,SM.salesman_name,SM.salesman_designation,SM.salesman_login_id,SM.salesman_email,SM.salesman_phone_no,QHD.PROD_ID AS product_id,MP.sProducts_Name AS product_name,
			QHD.COLOR_ID AS color_id,MC.Color_Name AS color_name,QHD.RATE_SQFT AS rate_sqft,QHD.RATE_SQMTR AS rate_sqmtr,CAST(QHD.QTY AS int) AS qty,QHD.AMOUNT AS amount
			FROM FSMAPIQUOTATIONHEAD QH
			INNER JOIN FSMAPIQUOTATIONDETAILS QHD ON QH.ID=QHD.HEADID AND QH.QUOTATION_NUMBER=QHD.QUOTATION_NUMBER AND QH.SHOP_ID=QHD.SHOP_ID
			INNER JOIN tbl_Master_shop MS ON QH.SHOP_ID=MS.Shop_Code
			INNER JOIN Master_sProducts MP ON QHD.PROD_ID=MP.sProducts_ID
			LEFT OUTER JOIN Master_Color MC ON QHD.COLOR_ID=MC.Color_ID
			LEFT OUTER JOIN (
			SELECT USR.user_id,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'')<>'' THEN ' ' ELSE '' END)+ISNULL(CNT.CNT_LASTNAME,'') AS salesman_name,
			DESG.deg_designation AS salesman_designation,USR.user_loginId AS salesman_login_id,ME.eml_email AS salesman_email,MP.phf_phoneNumber AS salesman_phone_no
			FROM #TEMPCONTACT CNT
			INNER JOIN TBL_MASTER_USER USR ON CNT.cnt_internalId=USR.user_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt 
			LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL 
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=CNT.cnt_internalId
			LEFT OUTER JOIN TBL_MASTER_EMAIL ME ON CNT.cnt_internalId=ME.eml_internalId AND ME.eml_type='Official'
			LEFT OUTER JOIN TBL_MASTER_PHONEFAX MP ON CNT.cnt_internalId=MP.phf_cntId AND MP.phf_type='Office'
			) SM ON QH.SALESMAN_USER_ID=SM.user_id
			WHERE QH.QUOTATION_NUMBER=@QUOTATION_NUMBER
		END
	ELSE IF @ACTION='UPDATEDATA'
		BEGIN
			IF EXISTS(SELECT QUOTATION_NUMBER FROM FSMAPIQUOTATIONHEAD WHERE USER_ID=@USER_ID AND SHOP_ID=@SHOP_ID AND QUOTATION_NUMBER=@QUOTATION_NUMBER AND SALESMAN_USER_ID=@SALESMAN_USER_ID)
				BEGIN
					UPDATE FSMAPIQUOTATIONHEAD SET USER_ID=@USER_ID,QUOTATION_NUMBER=@QUOTATION_NUMBER,QUOTATIONSAVE_DATE=@QUOTATIONSAVE_DATE,QUOTATION_DATE_SELECTION=@QUOTATION_DATE_SELECTION,
					PROJECT_NAME=@PROJECT_NAME,TAXES=@TAXES,FREIGHT=@FREIGHT,DELIVERY_TIME=@DELIVERY_TIME,PAYMENT=@PAYMENT,VALIDITY=@VALIDITY,BILLING=@BILLING,
					PRODUCT_TOLERANCE_OF_THICKNESS=@PRODUCT_TOLERANCE_OF_THICKNESS,TOLERANCE_OF_COATING_THICKNESS=@TOLERANCE_OF_COATING_THICKNESS,SALESMAN_USER_ID=@SALESMAN_USER_ID,SHOP_ID=@SHOP_ID,
					QUOTATION_CREATED_LAT=@QUOTATION_CREATED_LAT,QUOTATION_CREATED_LONG=@QUOTATION_CREATED_LONG,QUOTATION_CREATED_ADDRESS=@QUOTATION_CREATED_ADDRESS,MODIFIED_BY=@USER_ID,
					MODIFIED_DATE=GETDATE() WHERE USER_ID=@USER_ID AND QUOTATION_NUMBER=@QUOTATION_NUMBER AND SALESMAN_USER_ID=@SALESMAN_USER_ID AND SHOP_ID=@SHOP_ID

					UPDATE QD SET QD.QTY=XMLproduct.value('(qty/text())[1]','DECIMAL(18,2)'),QD.RATE_SQFT=XMLproduct.value('(rate_sqft/text())[1]','DECIMAL(18,2)'),
					QD.RATE_SQMTR=XMLproduct.value('(rate_sqmtr/text())[1]','DECIMAL(18,2)'),QD.AMOUNT=XMLproduct.value('(amount/text())[1]','DECIMAL(18,2)')
					FROM FSMAPIQUOTATIONDETAILS QD
					INNER JOIN @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct)
					ON QD.USER_ID=@USER_ID AND QD.SHOP_ID=@SHOP_ID AND QD.QUOTATION_NUMBER=@QUOTATION_NUMBER AND QD.PROD_ID=XMLproduct.value('(product_id/text())[1]','BIGINT')

					SELECT QUOTATION_NUMBER FROM FSMAPIQUOTATIONHEAD WHERE USER_ID=@USER_ID AND SHOP_ID=@SHOP_ID AND QUOTATION_NUMBER=@QUOTATION_NUMBER AND SALESMAN_USER_ID=@SALESMAN_USER_ID
				END
		END
	ELSE IF @ACTION='DELETEDATA'
		BEGIN
			IF EXISTS(SELECT QUOTATION_NUMBER FROM FSMAPIQUOTATIONHEAD WHERE QUOTATION_NUMBER=@QUOTATION_NUMBER)
				BEGIN
					DELETE FROM FSMAPIQUOTATIONHEAD WHERE QUOTATION_NUMBER=@QUOTATION_NUMBER

					DELETE FROM FSMAPIQUOTATIONDETAILS WHERE QUOTATION_NUMBER=@QUOTATION_NUMBER

					SELECT 'Deleted' AS STRMESSAGE FROM FSMAPIQUOTATIONHEAD
				END
		END

	DROP TABLE #TEMPCONTACT

	SET NOCOUNT OFF
END