--EXEC PRC_FTSTARGETVSACHIEVEMENTSUMMARY_REPORT 'JAN','',1650

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSTARGETVSACHIEVEMENTSUMMARY_REPORT]') AND TYPE in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSTARGETVSACHIEVEMENTSUMMARY_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSTARGETVSACHIEVEMENTSUMMARY_REPORT]
(
@MONTH NVARCHAR(3)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder on 23/01/2019
Module	   : Target Vs Achievement Summary
1.0		v5.0.0		29/01/2019		Debashis		State wise balance has been blocked.
2.0		v6.0.0		01/02/2019		Debashis		Child value has been updated to parrent line.
3.0		v13.0.0		13/02/2019		Debashis		Hierarchy wise filter implementation.
4.0		v1.0.103	14/02/2019		Debashis		Two columns has been introduced as EMPUSRID & RPTTOUSRID.
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@sqlStrTable NVARCHAR(MAX),@MONTHNAME NVARCHAR(3),@MONTHNO INT=0,@FROMDATE NVARCHAR(10),@TODATE NVARCHAR(10),@TGTACHVSUMM_CURSOR CURSOR
	DECLARE @EMPCODE NVARCHAR(50),@EMPNAME NVARCHAR(300),@EMPID NVARCHAR(100),@CONTACTNO NVARCHAR(50),@STID INT,@STATE NVARCHAR(50),@DEG_ID INT,@DESIGNATION NVARCHAR(50),@RPTTOEMPCODE NVARCHAR(50),
	@REPORTTO NVARCHAR(300),@RPTTODESGID INT,@RPTTODESG NVARCHAR(50),@TGT_NC INT,@ACHV_NC INT,@TGT_RV INT,@ACHV_RV INT,@TGT_ORDERVALUE DECIMAL(38,2),@ACHV_ORDERVALUE DECIMAL(38,2),
	@TGT_COLLECTION DECIMAL(38,2),@ACHV_COLLECTION DECIMAL(38,2),@M_FETCHLASTRECORD BIT
	--Rev 1.0
	--DECLARE @M_RPTTOEMPCODE NVARCHAR(50),@M_STID INT,@M_STATE NVARCHAR(50),@M_REPORTTO NVARCHAR(300)
	--DECLARE @S_TGT_NC INT,@S_ACHV_NC INT,@S_TGT_RV INT,@S_ACHV_RV INT,@S_TGT_ORDERVALUE DECIMAL(38,2),@S_ACHV_ORDERVALUE DECIMAL(38,2),@S_TGT_COLLECTION DECIMAL(38,2),@S_ACHV_COLLECTION DECIMAL(38,2)
	DECLARE @M_RPTTOEMPCODE NVARCHAR(50),@M_REPORTTO NVARCHAR(300)
	--End of Rev 1.0
	DECLARE @M_TGT_NC INT,@M_ACHV_NC INT,@M_TGT_RV INT,@M_ACHV_RV INT,@M_TGT_ORDERVALUE DECIMAL(38,2),@M_ACHV_ORDERVALUE DECIMAL(38,2),@M_TGT_COLLECTION DECIMAL(38,2),@M_ACHV_COLLECTION DECIMAL(38,2)
	--Rev 4.0
	DECLARE @EMPUSRID INT,@RPTTOUSRID INT,@M_RPTTOUSRID INT
	--End of Rev 4.0

	SET @MONTHNAME=@MONTH
	SET @MONTHNO=DATEPART(MM,@MONTHNAME+'01 1900')
	SET @FROMDATE=CONVERT(VARCHAR(10),DATEADD(MONTH, CONVERT(INT,@MONTHNO) - 1, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), 0)),120)
	SET @TODATE=CONVERT(VARCHAR(10),DATEADD(DAY, -1, DATEADD(MONTH, CONVERT(INT,@MONTHNO), DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), 0))),120)

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#STATEID_LIST') AND TYPE IN (N'U'))
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #STATEID_LIST SELECT id from tbl_master_state where id in('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#TEMPCONTACT') AND TYPE IN (N'U'))
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#TMPTGTACHVSUMM') AND TYPE IN (N'U'))
		DROP TABLE #TMPTGTACHVSUMM
	--Rev 4.0 &&Two new columns has been introduced as EMPUSRID & RPTTOUSRID
	CREATE TABLE #TMPTGTACHVSUMM(EMPUSRID INT,EMPCODE NVARCHAR(50) NULL,EMPNAME NVARCHAR(300) NULL,EMPID NVARCHAR(100) NULL,CONTACTNO NVARCHAR(50) NULL,STATEID INT,STATE NVARCHAR(50) NULL,DEG_ID INT,DESIGNATION NVARCHAR(50) NULL,
	RPTTOUSRID INT,RPTTOEMPCODE NVARCHAR(50) NULL,REPORTTO NVARCHAR(300) NULL,RPTTODESGID INT,RPTTODESG NVARCHAR(50) NULL,TGT_NC INT,ACHV_NC INT,TGT_RV INT,ACHV_RV INT,TGT_ORDERVALUE DECIMAL(38,2),ACHV_ORDERVALUE DECIMAL(38,2),
	TGT_COLLECTION DECIMAL(38,2),ACHV_COLLECTION DECIMAL(38,2))
	CREATE NONCLUSTERED INDEX IXTMP ON #TMPTGTACHVSUMM (RPTTOEMPCODE)

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTARGETVSACHIEVEMENTSUMMARY_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSTARGETVSACHIEVEMENTSUMMARY_REPORT
			(
			  USERID INT,
			  SEQ INT,
			  --Rev 4.0
			  EMPUSRID INT,
			  --End of Rev 4.0
			  EMPCODE NVARCHAR(50) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  EMPID NVARCHAR(100) NULL,
			  CONTACTNO NVARCHAR(50) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  --Rev 4.0
			  RPTTOUSRID INT,
			  --End of Rev 4.0
			  RPTTOEMPCODE NVARCHAR(50) NULL,
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESGID INT,
			  RPTTODESG NVARCHAR(50) NULL,
			  TGT_NC INT,
			  ACHV_NC INT,
			  TGT_RV INT,
			  ACHV_RV INT,
			  TGT_ORDERVALUE DECIMAL(38,2),
			  ACHV_ORDERVALUE DECIMAL(38,2),
			  TGT_COLLECTION DECIMAL(38,2),
			  ACHV_COLLECTION DECIMAL(38,2)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSTARGETVSACHIEVEMENTSUMMARY_REPORT (SEQ)
		END
	DELETE FROM FTSTARGETVSACHIEVEMENTSUMMARY_REPORT WHERE USERID=@USERID

	SET @Strsql=''
	--Rev 4.0
	--SET @StrSql='SET @TGTACHVSUMM_CURSOR=CURSOR FAST_FORWARD FOR SELECT EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,'
	--SET @Strsql+='DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,SUM(TGT_NC) AS TGT_NC,SUM(ACHV_NC) AS ACHV_NC,SUM(TGT_RV) AS TGT_RV,SUM(ACHV_RV) AS ACHV_RV,'
	SET @StrSql='SET @TGTACHVSUMM_CURSOR=CURSOR FAST_FORWARD FOR SELECT EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,'
	SET @Strsql+='DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,SUM(TGT_NC) AS TGT_NC,SUM(ACHV_NC) AS ACHV_NC,SUM(TGT_RV) AS TGT_RV,SUM(ACHV_RV) AS ACHV_RV,'
	--End of Rev 4.0
	SET @Strsql+='SUM(TGT_ORDERVALUE) AS TGT_ORDERVALUE,SUM(ACHV_ORDERVALUE) AS ACHV_ORDERVALUE,SUM(TGT_COLLECTION) AS TGT_COLLECTION,SUM(ACHV_COLLECTION) AS ACHV_COLLECTION FROM( '
	--Rev 4.0
	--SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,'
	--SET @Strsql+='ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTOEMPCODE,RPTTO.REPORTTO,RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode AS EMPID,'
	SET @Strsql+='SELECT USR.user_id AS EMPUSRID,CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,'
	SET @Strsql+='ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTO.RPTTOUSRID,RPTTO.RPTTOEMPCODE,RPTTO.REPORTTO,RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode AS EMPID,'
	--End of Rev 4.0
	SET @Strsql+='EMPTGTSET.NewCounter AS TGT_NC,EMPTGTSET.Revisit AS TGT_RV,EMPTGTSET.OrderValue AS TGT_ORDERVALUE,EMPTGTSET.Collection AS TGT_COLLECTION,0 AS ACHV_NC,0 AS ACHV_RV,0.00 AS ACHV_ORDERVALUE,'
	SET @Strsql+='0.00 AS ACHV_COLLECTION FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_FTS_EmployeesTargetSetting EMPTGTSET ON EMPTGTSET.EmployeeCode=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE CNT.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	--Rev 4.0
	--SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS RPTTOEMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='LEFT OUTER JOIN (SELECT USR.user_id AS RPTTOUSRID,EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS RPTTOEMPCODE,'
	SET @Strsql+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	--End of Rev 4.0
	SET @Strsql+='DESG.DEG_ID AS RPTTODESGID,DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	--Rev 4.0
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=CNT.cnt_internalId AND USR.user_inactive=''N'' '
	--End of Rev 4.0
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),'''+@TODATE+''',120) BETWEEN CONVERT(NVARCHAR(10),EMPTGTSET.FromDate,120) AND CONVERT(NVARCHAR(10),EMPTGTSET.ToDate,120) '
	SET @Strsql+='AND RPTTO.RPTTOEMPCODE IS NOT NULL '
	SET @Strsql+='UNION ALL '
	--Rev 4.0
	--SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,'
	--SET @Strsql+='ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTOEMPCODE,RPTTO.REPORTTO,RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode AS EMPID,'
	SET @Strsql+='SELECT USR.user_id AS EMPUSRID,CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,'
	SET @Strsql+='ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTO.RPTTOUSRID,RPTTO.RPTTOEMPCODE,RPTTO.REPORTTO,RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode AS EMPID,'
	--End of Rev 4.0
	SET @Strsql+='0 AS TGT_NC,0 AS TGT_RV,0.00 AS TGT_ORDERVALUE,0.00 AS TGT_COLLECTION,'
	SET @Strsql+='ISNULL(NEWSHOPVISITED,0) AS ACHV_NC,ISNULL(REVISITSHOP,0) AS ACHV_RV,SUM(ISNULL(ORDHEAD.Ordervalue,0)) AS ACHV_ORDERVALUE,SUM(ISNULL(COLLEC.collectionvalue,0)) AS ACHV_COLLECTION '
	SET @Strsql+='FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE CNT.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	--Rev 4.0
	--SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS RPTTOEMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='LEFT OUTER JOIN (SELECT USR.user_id AS RPTTOUSRID,EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS RPTTOEMPCODE,'
	SET @Strsql+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	--End of Rev 4.0
	SET @Strsql+='DESG.DEG_ID AS RPTTODESGID,DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	--Rev 4.0
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=CNT.cnt_internalId AND USR.user_inactive=''N'' '
	--End of Rev 4.0
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT User_Id,cnt_internalId,SUM(NEWSHOPVISITED) AS NEWSHOPVISITED,SUM(REVISITSHOP) AS REVISITSHOP FROM('
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOPVISITED,0 AS REVISITSHOP FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),Login_datetime,105) AS Login_datetime FROM tbl_fts_UserAttendanceLoginlogout WHERE Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY User_Id,CONVERT(NVARCHAR(10),Login_datetime,105))ATTEN ON ATTEN.User_Id=SHOPACT.User_Id AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 GROUP BY SHOPACT.User_Id,CNT.cnt_internalId '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOPVISITED,COUNT(SHOPACT.Shop_Id) AS REVISITSHOP FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),Login_datetime,105) AS Login_datetime FROM tbl_fts_UserAttendanceLoginlogout WHERE Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY User_Id,CONVERT(NVARCHAR(10),Login_datetime,105))ATTEN ON ATTEN.User_Id=SHOPACT.User_Id AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 GROUP BY SHOPACT.User_Id,CNT.cnt_internalId '
	SET @Strsql+=') SHOPACT GROUP BY SHOPACT.User_Id,SHOPACT.cnt_internalId) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT ORDH.userID,ORDH.SHOP_CODE,CNT.cnt_internalId,SUM(ISNULL(Ordervalue,0)) AS Ordervalue,CONVERT(NVARCHAR(10),ORDH.Orderdate,105) AS ORDDATE FROM tbl_trans_fts_Orderupdate ORDH '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ORDH.userID '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.Orderdate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY ORDH.userID,ORDH.SHOP_CODE,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORDH.Orderdate,105)) ORDHEAD ON ORDHEAD.cnt_internalId=CNT.cnt_internalId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT COLLEC.user_id,COLLEC.shop_id,CNT.cnt_internalId,SUM(ISNULL(COLLEC.collection,0)) AS collectionvalue,CONVERT(NVARCHAR(10),COLLEC.collection_date,105) AS collection_date FROM tbl_FTS_collection COLLEC '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=COLLEC.user_id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),COLLEC.collection_date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY COLLEC.user_id,COLLEC.shop_id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),COLLEC.collection_date,105)) COLLEC ON COLLEC.cnt_internalId=CNT.cnt_internalId '
	SET @Strsql+='WHERE RPTTO.RPTTOEMPCODE IS NOT NULL '
	--Rev 4.0
	--SET @Strsql+='GROUP BY CNT.cnt_internalId,CNT.CNT_FIRSTNAME,CNT.CNT_MIDDLENAME,CNT.CNT_LASTNAME,ST.ID,ST.state,DESG.DEG_ID,DESG.deg_designation,USR.user_loginId,RPTTO.RPTTOEMPCODE,RPTTO.REPORTTO,'
	--SET @Strsql+='RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode,NEWSHOPVISITED,REVISITSHOP'
	SET @Strsql+='GROUP BY USR.user_id,CNT.cnt_internalId,CNT.CNT_FIRSTNAME,CNT.CNT_MIDDLENAME,CNT.CNT_LASTNAME,ST.ID,ST.state,DESG.DEG_ID,DESG.deg_designation,USR.user_loginId,RPTTO.RPTTOUSRID,RPTTO.RPTTOEMPCODE,'
	SET @Strsql+='RPTTO.REPORTTO,RPTTO.RPTTODESGID,RPTTO.RPTTODESG,EMP.emp_uniqueCode,NEWSHOPVISITED,REVISITSHOP'
	--End of Rev 4.0
	SET @Strsql+=') AS DB '
	IF @STATEID<>''
		SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
	--Rev 4.0
	--SET @Strsql+='GROUP BY EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG '
	SET @Strsql+='GROUP BY EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG '
	--End of Rev 4.0
	SET @Strsql+='ORDER BY RPTTOEMPCODE,STATEID ; OPEN @TGTACHVSUMM_CURSOR '
	--SELECT @Strsql
	--EXEC SP_EXECUTESQL @Strsql
	EXEC sp_executesql @StrSql,N' @TGTACHVSUMM_CURSOR CURSOR OUTPUT', @TGTACHVSUMM_CURSOR OUTPUT
	--SELECT @Strsql

	--Rev 4.0
	--FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
	--@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
	FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPUSRID,@EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOUSRID,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,
	@ACHV_RV,@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
	--End of Rev 4.0
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @M_RPTTOEMPCODE=@RPTTOEMPCODE
			SET @M_REPORTTO=@REPORTTO
			--Rev 4.0
			SET @M_RPTTOUSRID=@RPTTOUSRID
			--End of Rev 4.0
			SET @M_TGT_NC=0
			SET @M_ACHV_NC=0
			SET @M_TGT_RV=0
			SET @M_ACHV_RV=0
			SET @M_TGT_ORDERVALUE=0
			SET @M_ACHV_ORDERVALUE=0
			SET @M_TGT_COLLECTION=0
			SET @M_ACHV_COLLECTION=0
			SET @M_FETCHLASTRECORD=1
			WHILE @M_RPTTOEMPCODE=@RPTTOEMPCODE AND @@FETCH_STATUS = 0
				BEGIN
					--Rev 1.0
					--SET @M_STID=@STID
					--SET @M_STATE=@STATE
					--SET @S_TGT_NC=0
					--SET @S_ACHV_NC=0
					--SET @S_TGT_RV=0
					--SET @S_ACHV_RV=0
					--SET @S_TGT_ORDERVALUE=0
					--SET @S_ACHV_ORDERVALUE=0
					--SET @S_TGT_COLLECTION=0
					--SET @S_ACHV_COLLECTION=0
					--WHILE @M_RPTTOEMPCODE=@RPTTOEMPCODE AND @M_STID=@STID AND @@FETCH_STATUS = 0
					--	BEGIN
							--SET @S_TGT_NC=@S_TGT_NC+@TGT_NC
							--SET @S_ACHV_NC=@S_ACHV_NC+@ACHV_NC
							--SET @S_TGT_RV=@S_TGT_RV+@TGT_RV
							--SET @S_ACHV_RV=@S_ACHV_RV+@ACHV_RV
							--SET @S_TGT_ORDERVALUE=@S_TGT_ORDERVALUE+@TGT_ORDERVALUE
							--SET @S_ACHV_ORDERVALUE=@S_ACHV_ORDERVALUE+@ACHV_ORDERVALUE
							--SET @S_TGT_COLLECTION=@S_TGT_COLLECTION+@TGT_COLLECTION
							--SET @S_ACHV_COLLECTION=@S_ACHV_COLLECTION+@ACHV_COLLECTION
					--End of Rev 1.0
					SET @M_TGT_NC=@M_TGT_NC+@TGT_NC
					SET @M_ACHV_NC=@M_ACHV_NC+@ACHV_NC
					SET @M_TGT_RV=@M_TGT_RV+@TGT_RV
					SET @M_ACHV_RV=@M_ACHV_RV+@ACHV_RV
					SET @M_TGT_ORDERVALUE=@M_TGT_ORDERVALUE+@TGT_ORDERVALUE
					SET @M_ACHV_ORDERVALUE=@M_ACHV_ORDERVALUE+@ACHV_ORDERVALUE
					SET @M_TGT_COLLECTION=@M_TGT_COLLECTION+@TGT_COLLECTION
					SET @M_ACHV_COLLECTION=@M_ACHV_COLLECTION+@ACHV_COLLECTION

					--Rev 4.0
					--INSERT INTO #TMPTGTACHVSUMM(EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,
					--ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)
					--SELECT @EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
					--@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
					INSERT INTO #TMPTGTACHVSUMM(EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,
					TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)
					SELECT @EMPUSRID,@EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOUSRID,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
					@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
					--End of Rev 4.0
					--Rev 1.0
							--FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
							--@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION

							--IF @@FETCH_STATUS=-1 OR (@M_STID<>@STID) OR (@M_RPTTOEMPCODE<>@RPTTOEMPCODE)
							--	BEGIN
							--		INSERT INTO #TMPTGTACHVSUMM(EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,
							--		ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)
							--		SELECT NULL,NULL,NULL,NULL,@M_STID,'Group Total for State '+@M_STATE,NULL,NULL,@M_RPTTOEMPCODE,@M_REPORTTO,NULL,NULL,@S_TGT_NC,@S_ACHV_NC,@S_TGT_RV,@S_ACHV_RV,@S_TGT_ORDERVALUE,
							--		@S_ACHV_ORDERVALUE,@S_TGT_COLLECTION,@S_ACHV_COLLECTION
							--	END
						--END
					--IF (@M_RPTTOEMPCODE<>@RPTTOEMPCODE)
						--BEGIN
							--FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
							--@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
						--END
					--Rev 4.0
					--FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,@ACHV_NC,@TGT_RV,@ACHV_RV,
					--@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
					FETCH NEXT FROM @TGTACHVSUMM_CURSOR INTO @EMPUSRID,@EMPCODE,@EMPNAME,@EMPID,@CONTACTNO,@STID,@STATE,@DEG_ID,@DESIGNATION,@RPTTOUSRID,@RPTTOEMPCODE,@REPORTTO,@RPTTODESGID,@RPTTODESG,@TGT_NC,
					@ACHV_NC,@TGT_RV,@ACHV_RV,@TGT_ORDERVALUE,@ACHV_ORDERVALUE,@TGT_COLLECTION,@ACHV_COLLECTION
					--End of Rev 4.0
					--End of Rev 1.0
					IF @@FETCH_STATUS=-1 OR (@M_RPTTOEMPCODE<>@RPTTOEMPCODE)
						BEGIN
							--Rev 4.0
							--INSERT INTO #TMPTGTACHVSUMM(EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,
							--ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)
							--SELECT NULL,NULL,NULL,NULL,NULL,'Total for Report to '+@M_REPORTTO,NULL,NULL,@M_RPTTOEMPCODE,@M_REPORTTO,NULL,NULL,@M_TGT_NC,@M_ACHV_NC,@M_TGT_RV,@M_ACHV_RV,@M_TGT_ORDERVALUE,
							--@M_ACHV_ORDERVALUE,@M_TGT_COLLECTION,@M_ACHV_COLLECTION
							INSERT INTO #TMPTGTACHVSUMM(EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,
							ACHV_RV,TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)
							SELECT NULL,NULL,NULL,NULL,NULL,NULL,'Total for Report to '+@M_REPORTTO,NULL,NULL,@M_RPTTOUSRID,@M_RPTTOEMPCODE,@M_REPORTTO,NULL,NULL,@M_TGT_NC,@M_ACHV_NC,@M_TGT_RV,@M_ACHV_RV,
							@M_TGT_ORDERVALUE,@M_ACHV_ORDERVALUE,@M_TGT_COLLECTION,@M_ACHV_COLLECTION
							--End of Rev 4.0
						END
				END
		END
		
		CLOSE @TGTACHVSUMM_CURSOR
		DEALLOCATE @TGTACHVSUMM_CURSOR

		--Rev 4.0
		--SELECT @USERID AS USERID,ROW_NUMBER() OVER(ORDER BY RPTTOEMPCODE,STATEID) AS SEQ,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,
		--ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION INTO #TMPTOTTGTACHVSUMM FROM #TMPTGTACHVSUMM ORDER BY RPTTOEMPCODE,STATEID
		SELECT @USERID AS USERID,ROW_NUMBER() OVER(ORDER BY RPTTOEMPCODE,STATEID) AS SEQ,EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,
		RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION INTO #TMPTOTTGTACHVSUMM FROM #TMPTGTACHVSUMM ORDER BY RPTTOEMPCODE,STATEID
		--End of Rev 4.0

		--Rev 2.0
		SELECT REPORTTO,RPTTOEMPCODE,SUM(TGT_NC) AS TGT_NC,SUM(ACHV_NC) AS ACHV_NC,SUM(TGT_RV) AS TGT_RV,SUM(ACHV_RV) AS ACHV_RV,
		SUM(TGT_ORDERVALUE) AS TGT_ORDERVALUE,SUM(ACHV_ORDERVALUE) AS ACHV_ORDERVALUE,SUM(TGT_COLLECTION) AS TGT_COLLECTION,SUM(ACHV_COLLECTION) AS ACHV_COLLECTION INTO #TMPTOTTGTACHVSUMM_RPTTO
		FROM #TMPTOTTGTACHVSUMM WHERE STATE LIKE '%Total for Report to%' GROUP BY REPORTTO,RPTTOEMPCODE
		--End of Rev 2.0

		--Rev 4.0
		--INSERT INTO FTSTARGETVSACHIEVEMENTSUMMARY_REPORT(USERID,SEQ,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,
		--TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)

		----Rev 2.0
		----SELECT @USERID AS USERID,SEQ,CASE WHEN EMPCODE IS NULL THEN LTRIM(RTRIM(STR(SEQ))) ELSE EMPCODE END AS EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOEMPCODE,REPORTTO,RPTTODESGID,
		----RPTTODESG,TGT_NC,ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION FROM #TMPTOTTGTACHVSUMM ORDER BY RPTTOEMPCODE,STATEID

		--SELECT A.USERID,A.SEQ,A.EMPCODE,A.EMPNAME,A.EMPID,A.CONTACTNO,A.STATEID,A.STATE,A.DEG_ID,A.DESIGNATION,A.RPTTOEMPCODE,A.REPORTTO,A.RPTTODESGID,A.RPTTODESG,
		--(A.TGT_NC+ISNULL(B.TGT_NC,0)) AS TGT_NC,(A.ACHV_NC+ISNULL(B.ACHV_NC,0)) AS ACHV_NC,(A.TGT_RV+ISNULL(B.TGT_RV,0)) AS TGT_RV,(A.ACHV_RV+ISNULL(B.ACHV_RV,0)) AS ACHV_RV,
		--(A.TGT_ORDERVALUE+ISNULL(B.TGT_ORDERVALUE,0)) AS TGT_ORDERVALUE,(A.ACHV_ORDERVALUE+ISNULL(B.ACHV_ORDERVALUE,0)) AS ACHV_ORDERVALUE,(A.TGT_COLLECTION+ISNULL(B.TGT_COLLECTION,0)) AS TGT_COLLECTION,
		--(A.ACHV_COLLECTION+ISNULL(B.ACHV_COLLECTION,0)) AS ACHV_COLLECTION FROM #TMPTOTTGTACHVSUMM A
		--LEFT OUTER JOIN #TMPTOTTGTACHVSUMM_RPTTO B ON A.EMPCODE=B.RPTTOEMPCODE WHERE STATE NOT LIKE '%Total for Report to%' ORDER BY A.RPTTOEMPCODE,A.STATEID
		INSERT INTO FTSTARGETVSACHIEVEMENTSUMMARY_REPORT(USERID,SEQ,EMPUSRID,EMPCODE,EMPNAME,EMPID,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,RPTTOUSRID,RPTTOEMPCODE,REPORTTO,RPTTODESGID,RPTTODESG,TGT_NC,
		ACHV_NC,TGT_RV,ACHV_RV,TGT_ORDERVALUE,ACHV_ORDERVALUE,TGT_COLLECTION,ACHV_COLLECTION)

		SELECT A.USERID,A.SEQ,A.EMPUSRID,A.EMPCODE,A.EMPNAME,A.EMPID,A.CONTACTNO,A.STATEID,A.STATE,A.DEG_ID,A.DESIGNATION,A.RPTTOUSRID,A.RPTTOEMPCODE,A.REPORTTO,A.RPTTODESGID,A.RPTTODESG,
		(A.TGT_NC+ISNULL(B.TGT_NC,0)) AS TGT_NC,(A.ACHV_NC+ISNULL(B.ACHV_NC,0)) AS ACHV_NC,(A.TGT_RV+ISNULL(B.TGT_RV,0)) AS TGT_RV,(A.ACHV_RV+ISNULL(B.ACHV_RV,0)) AS ACHV_RV,
		(A.TGT_ORDERVALUE+ISNULL(B.TGT_ORDERVALUE,0)) AS TGT_ORDERVALUE,(A.ACHV_ORDERVALUE+ISNULL(B.ACHV_ORDERVALUE,0)) AS ACHV_ORDERVALUE,(A.TGT_COLLECTION+ISNULL(B.TGT_COLLECTION,0)) AS TGT_COLLECTION,
		(A.ACHV_COLLECTION+ISNULL(B.ACHV_COLLECTION,0)) AS ACHV_COLLECTION FROM #TMPTOTTGTACHVSUMM A
		LEFT OUTER JOIN #TMPTOTTGTACHVSUMM_RPTTO B ON A.EMPCODE=B.RPTTOEMPCODE WHERE STATE NOT LIKE '%Total for Report to%' ORDER BY A.RPTTOEMPCODE,A.STATEID
		--End of Rev 4.0
		--End of Rev 2.0

	DROP TABLE #STATEID_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #TMPTGTACHVSUMM
	DROP TABLE #TMPTOTTGTACHVSUMM
	--Rev 2.0
	DROP TABLE #TMPTOTTGTACHVSUMM_RPTTO
	--End of Rev 2.0
END