--EXEC PRC_FTSORDERSUMMARYMTD_REPORT 'JUL','2023','','','',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSORDERSUMMARYMTD_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSORDERSUMMARYMTD_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSORDERSUMMARYMTD_REPORT]
(
@MONTH NVARCHAR(3)=NULL,
@YEARS NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder on 04/07/2023
Module	   : Employee Performance Month to Date.Refer: 0026429
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	SET LOCK_TIMEOUT -1

	DECLARE @SqlStrTable NVARCHAR(MAX),@COLUMN_DATE NVARCHAR(10),@DAYCOUNT INT,@LOOPCOUNT INT,@FIRSTTIME BIT=1,@MONTHNAME NVARCHAR(3),@MONTHNO INT=0,@FROMDATE NVARCHAR(10),@TODATE NVARCHAR(10)
	DECLARE @SLHEADID BIGINT,@PARENTID BIGINT

	SET @MONTHNAME=@MONTH
	SET @MONTHNO=DATEPART(MM,@MONTHNAME+'01 1900')
	SET @FROMDATE=CONVERT(VARCHAR(10),DATEADD(MONTH, CONVERT(INT,@MONTHNO) - 1, @YEARS),120)
	SET @TODATE=CONVERT(VARCHAR(10),DATEADD(DAY, -1, DATEADD(MONTH, CONVERT(INT,@MONTHNO), @YEARS)),120)
	SET @COLUMN_DATE=@FROMDATE

	SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1

	IF OBJECT_ID('tempdb..#TMPHEADINGOMTD') IS NOT NULL
		DROP TABLE #TMPHEADINGOMTD
	CREATE TABLE #TMPHEADINGOMTD
		(
			HEADID BIGINT,HEADNAME NVARCHAR(800),HEADSHRTNAME NVARCHAR(800),PARRENTID BIGINT
		)
	
	IF OBJECT_ID('tempdb..#EMPORDERMTD') IS NOT NULL
	 DROP TABLE #EMPORDERMTD
	
	CREATE TABLE #EMPORDERMTD (WORKDATE NVARCHAR(10),WORKDATEORDBY NVARCHAR(10),USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),CONTACTNO NVARCHAR(100),
	DEG_ID BIGINT,DESIGNATION NVARCHAR(300),STATEID BIGINT,STATE NVARCHAR(100),REPORTTOID NVARCHAR(100),REPORTTOUID NVARCHAR(100),REPORTTO NVARCHAR(300),RPTTODESG NVARCHAR(100),AVGBILLVALUE DECIMAL(18,2),
	TOTALSHPCNT INT,UNIQUEORDCNT INT,ORDCNT INT,PERCENTOFBILLCUST DECIMAL(18,2),TOTAL_ORDERVALUE DECIMAL(18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #EMPORDERMTD (EMPCODE)

	--FOR REPORT HEADER
	INSERT INTO #TMPHEADINGOMTD(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID)
	SELECT 1,'Employee Details','Employee Details',0
	UNION ALL
	SELECT 2,'Reporting Manager','REPORTTO',1
	UNION ALL
	SELECT 3,'Employee name','EMPNAME',1
	UNION ALL
	SELECT 4,'Employee Code','EMPID',1
	UNION ALL
	SELECT 5,'Avg Billing Value','AVGBILLVALUE',1
	UNION ALL
	SELECT 6,'Customer Base','TOTALSHPCNT',1
	UNION ALL
	SELECT 7,'Unique Billed Customer','UNIQUEORDCNT',1
	UNION ALL
	SELECT 8,'No. of Orders','ORDCNT',1
	UNION ALL
	SELECT 9,'% of Billed Customer','PERCENTOFBILLCUST',1
	UNION ALL
	SELECT 10,'Total Order Value','TOTAL_ORDERVALUE',1
	SET @SLHEADID=10
	SET @PARENTID=10

	DECLARE @emp_contactId NVARCHAR(100)
	SET @COLUMN_DATE =@FROMDATE

	IF OBJECT_ID('tempdb..#TMPORDERMTD') IS NOT NULL
		DROP TABLE #TMPORDERMTD
	CREATE TABLE #TMPORDERMTD(WORKDATE NVARCHAR(10),WORKDATEORDBY NVARCHAR(10),USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),CONTACTNO NVARCHAR(100),
	DEG_ID BIGINT,DESIGNATION NVARCHAR(300),STATEID BIGINT,STATE NVARCHAR(100),REPORTTOID NVARCHAR(100),REPORTTOUID NVARCHAR(100),REPORTTO NVARCHAR(300),RPTTODESG NVARCHAR(100),AVGBILLVALUE DECIMAL(18,2),
	TOTALSHPCNT INT,UNIQUEORDCNT INT,ORDCNT INT,PERCENTOFBILLCUST DECIMAL(18,2),ORDERVALUEPERDAY DECIMAL(18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPORDERMTD (EMPCODE)

	IF OBJECT_ID('tempdb..#TMPORDERMTDDET') IS NOT NULL
		DROP TABLE #TMPORDERMTDDET
	CREATE TABLE #TMPORDERMTDDET(WORKDATE NVARCHAR(10),WORKDATEORDBY NVARCHAR(10),USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),CONTACTNO NVARCHAR(100),
	DEG_ID BIGINT,DESIGNATION NVARCHAR(300),STATEID BIGINT,STATE NVARCHAR(100),REPORTTOID NVARCHAR(100),REPORTTOUID NVARCHAR(100),REPORTTO NVARCHAR(300),RPTTODESG NVARCHAR(100),AVGBILLVALUE DECIMAL(18,2),
	TOTALSHPCNT INT,UNIQUEORDCNT INT,ORDCNT INT,PERCENTOFBILLCUST DECIMAL(18,2),ORDERVALUEPERDAY DECIMAL(18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPORDERMTDDET (EMPCODE)

	IF OBJECT_ID('tempdb..#TMPORDERMTDSUM') IS NOT NULL
		DROP TABLE #TMPORDERMTDSUM
	CREATE TABLE #TMPORDERMTDSUM(USERID BIGINT,EMPCODE NVARCHAR(100),EMPID NVARCHAR(100),EMPNAME NVARCHAR(300),TOTAL_ORDERVALUE DECIMAL(18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPORDERMTDSUM (EMPCODE)

	INSERT INTO #TMPORDERMTDDET EXEC [PRC_FTSORDERSUMMARYMTD_FETCH] @MONTH,@YEARS,@STATEID,@DESIGNID,@EMPID,@USERID

	INSERT INTO #TMPORDERMTDSUM(USERID,EMPCODE,EMPID,EMPNAME,TOTAL_ORDERVALUE)
	SELECT USERID,EMPCODE,EMPID,EMPNAME,SUM(ORDERVALUEPERDAY) AS TOTAL_ORDERVALUE FROM #TMPORDERMTDDET 
	GROUP BY USERID,EMPCODE,EMPID,EMPNAME
	ORDER BY EMPCODE

	SET @LOOPCOUNT=1
	IF @DAYCOUNT>0
		BEGIN
			WHILE @LOOPCOUNT<=@DAYCOUNT
				BEGIN
					SET @SqlStrTable=''
					SET @SqlStrTable='ALTER TABLE #EMPORDERMTD ADD '
					SET @SqlStrTable+='['+RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']' + ' NVARCHAR(50) NULL,'
					SET @SqlStrTable+='[OV_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']'+ ' DECIMAL(18,2) NULL ' 

					EXEC SP_EXECUTESQL @SqlStrTable					

					SET @TODATE=@COLUMN_DATE

					INSERT INTO #TMPORDERMTD(WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,
					AVGBILLVALUE,TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,ORDERVALUEPERDAY)
					SELECT WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,AVGBILLVALUE,
					TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,ORDERVALUEPERDAY FROM #TMPORDERMTDDET WHERE WORKDATEORDBY BETWEEN @COLUMN_DATE AND @TODATE

					IF (SELECT COUNT(0) FROM #EMPORDERMTD A
						INNER JOIN #TMPORDERMTD B ON A.EMPCODE=B.EMPCODE AND B.WORKDATEORDBY BETWEEN @COLUMN_DATE AND @TODATE)>0
						SET @FIRSTTIME=0
					ELSE
						SET @FIRSTTIME=1

					IF @FIRSTTIME=1
						BEGIN
							SET @SqlStrTable=''
							SET @SqlStrTable='INSERT INTO #EMPORDERMTD(WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,'
							SET @SqlStrTable+='REPORTTO,RPTTODESG,AVGBILLVALUE,TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,'
							SET @SqlStrTable+='[OV_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + '] '
							SET @SqlStrTable+=') '
							SET @SqlStrTable+='SELECT WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,'
							SET @SqlStrTable+='AVGBILLVALUE,TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,ORDERVALUEPERDAY '
							SET @SqlStrTable+='FROM #TMPORDERMTD '

							EXEC SP_EXECUTESQL @SqlStrTable

							SET @FIRSTTIME=0
						END
					ELSE IF @FIRSTTIME=0
						BEGIN
							SET @SqlStrTable=''
							SET @SqlStrTable='INSERT INTO #EMPORDERMTD(WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,'
							SET @SqlStrTable+='REPORTTO,RPTTODESG,AVGBILLVALUE,TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,'
							SET @SqlStrTable+='[OV_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + '] '
							SET @SqlStrTable+=') '
							SET @SqlStrTable+='SELECT WORKDATE,WORKDATEORDBY,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,DEG_ID,DESIGNATION,STATEID,STATE,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,'
							SET @SqlStrTable+='AVGBILLVALUE,TOTALSHPCNT,UNIQUEORDCNT,ORDCNT,PERCENTOFBILLCUST,ORDERVALUEPERDAY '
							SET @SqlStrTable+='FROM #TMPORDERMTD WHERE NOT EXISTS(SELECT EMPCODE FROM #EMPORDERMTD A WHERE A.EMPCODE=#TMPORDERMTD.EMPCODE) '
							
							EXEC SP_EXECUTESQL @sqlStrTable

							SET @SqlStrTable=''
							SET @SqlStrTable='UPDATE TEMP SET '
							SET @SqlStrTable+='TEMP.[OV_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) + ']=T.ORDERVALUEPERDAY '
							SET @sqlStrTable+='FROM #EMPORDERMTD TEMP '
							SET @sqlStrTable+='INNER JOIN #TMPORDERMTD T ON TEMP.EMPCODE=T.EMPCODE '
						
							EXEC SP_EXECUTESQL @sqlStrTable
						END
						TRUNCATE TABLE #TMPORDERMTD
						DELETE FROM #TMPORDERMTDDET WHERE WORKDATEORDBY BETWEEN @COLUMN_DATE AND @TODATE

						--FOR REPORT HEADER
						SET @PARENTID=@SLHEADID+1
					
						INSERT INTO #TMPHEADINGOMTD(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID) 
						SELECT @SLHEADID+1 AS HEADID,CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105) AS HEADNAME,RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) AS HEADSHRTNAME,0 AS PARRENTID 

						INSERT INTO #TMPHEADINGOMTD(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID) 
						SELECT @SLHEADID+2 AS HEADID,'Order Value' AS HEADNAME,'OV_' +RTRIM(LTRIM(REPLACE(CONVERT(NVARCHAR(10),CAST(@COLUMN_DATE AS DATE),105),'-','_'))) AS HEADSHRTNAME,@PARENTID AS PARRENTID 

						SET @SLHEADID=@SLHEADID+2

						--FOR REPORT HEADER

						SET @COLUMN_DATE=CONVERT(NVARCHAR(10),(SELECT DATEADD(D, 1, @COLUMN_DATE)),120)
						SET @LOOPCOUNT=@LOOPCOUNT+1
				END
		END		

	UPDATE ORDMTD SET ORDMTD.TOTAL_ORDERVALUE=T.TOTAL_ORDERVALUE,ORDMTD.AVGBILLVALUE=CASE WHEN ORDMTD.UNIQUEORDCNT<>0 THEN (T.TOTAL_ORDERVALUE/ORDMTD.UNIQUEORDCNT) ELSE 0 END 
	FROM #EMPORDERMTD AS ORDMTD 
	INNER JOIN #TMPORDERMTDSUM T ON ORDMTD.EMPCODE=T.EMPCODE

	SELECT * FROM #TMPHEADINGOMTD ORDER BY HEADID
	SELECT * FROM #EMPORDERMTD ORDER BY EMPNAME

	DROP TABLE #EMPORDERMTD
	DROP TABLE #TMPHEADINGOMTD
	DROP TABLE #TMPORDERMTD
	DROP TABLE #TMPORDERMTDDET
	DROP TABLE #TMPORDERMTDSUM

	SET NOCOUNT OFF
END