--EXEC PRC_APIATTENDANCEDETAILS_REPORT

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIATTENDANCEDETAILS_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIATTENDANCEDETAILS_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIATTENDANCEDETAILS_REPORT]
--WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 30/06/2023
Module	   : API Attendance Detail Report.Refer: Row: 853
1.0		v2.0.45		28/03/2024		Debashis	In Application, please consider Saturday and Sunday for qualified attendance.Refer: 0027330
2.0		v2.0.45		28/03/2024		Debashis	Qualified Attendance Report, logic should be updated as the visit count shall be
												(Total Outlet Re-visited + Total Outlet New visit).Refer: 0027327
3.0		v2.0.47		17/06/2024		Debashis	Please consider DS types of 'Stockist DS' and 'Emerging DS' in the Attendance Summary and the Attendance Calendar report of 
												the FSM application.Refer: 0027553
4.0		v2.0.48		05/07/2024		Debashis	If IsEnd= 0 in FSMUSERWISEDAYSTARTEND, table for a user for a particular day then please consider the remarks 
												'Auto Update Cutoff Time' for market duration calculation.Refer: 0027603
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	SET LOCK_TIMEOUT -1

	--Rev 1.0
	--DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX),@FROMDATE NVARCHAR(10),@TODATE NVARCHAR(10),@DAYCOUNT INT,@days AS INT,@FIRSTDATEOFMONTH DATETIME,@CURRENTDATEOFMONTH DATETIME
	DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX),@FROMDATE NVARCHAR(10),@TODATE NVARCHAR(10),@DAYCOUNT INT
	--End of Rev 1.0

	SELECT @FROMDATE=(SELECT CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120))
	SELECT @TODATE=(SELECT CONVERT(NVARCHAR(10),GETDATE(),120))

	--Rev 1.0
	--SELECT @FIRSTDATEOFMONTH = @FROMDATE
	--SELECT @CURRENTDATEOFMONTH = @TODATE

	--;WITH CTE AS (SELECT 1 AS DAYID,@FIRSTDATEOFMONTH AS FROMDATE,DATENAME(DW, @FIRSTDATEOFMONTH) AS DAYNAME
	--UNION ALL
	--SELECT CTE.DAYID + 1 AS DAYID,DATEADD(D, 1 ,CTE.FROMDATE),DATENAME(DW, DATEADD(D, 1 ,CTE.FROMDATE)) AS DAYNAME
	--FROM CTE
	--WHERE DATEADD(D,1,CTE.FROMDATE) <= @CURRENTDATEOFMONTH
	--)
	--SELECT FROMDATE AS SUNDAYDATE,DAYNAME INTO #TMPSHOWSUNDAY
	--FROM CTE
	--WHERE DAYNAME IN ('Sunday')
	--OPTION (MAXRECURSION 1000)

	--SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1

	--SET @days=(SELECT @DAYCOUNT-COUNT(DAYNAME) FROM #TMPSHOWSUNDAY)
	SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1
	--End of Rev 1.0

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WITH (NOLOCK)
	WHERE cnt_contactType IN('EM')

	IF OBJECT_ID('tempdb..#TMPDAYSTARTENDQA') IS NOT NULL
		DROP TABLE #TMPDAYSTARTENDQA
	CREATE TABLE #TMPDAYSTARTENDQA
	(USERID BIGINT,DAYSTTIME NVARCHAR(10),DAYENDTIME NVARCHAR(10),cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,STARTENDDATE NVARCHAR(10),STARTENDDATEORDBY NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPDAYSTARTENDQA(USERID,STARTENDDATE)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPDAYSTARTENDQA(USERID,DAYSTTIME,DAYENDTIME,cnt_internalId,STARTENDDATE,STARTENDDATEORDBY) '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYSTTIME,NULL AS DAYENDTIME,CNT.cnt_internalId,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) AS STARTENDDATEORDBY '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON DAYSTEND.User_Id=USR.user_id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE ISSTART=1 '
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105),CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,NULL AS DAYSTTIME,MAX(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYENDTIME,CNT.cnt_internalId,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) AS STARTENDDATEORDBY '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON DAYSTEND.User_Id=USR.user_id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	--Rev 4.0
	--SET @SqlStr+='WHERE ISEND=1 '
	SET @SqlStr+='WHERE (ISEND=1 OR REMARKS=''Auto Update Cutoff Time'') '
	--End of Rev 4.0
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105),CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF OBJECT_ID('tempdb..#TMPSHOPACTIVITYSUBMITQA') IS NOT NULL
		DROP TABLE #TMPSHOPACTIVITYSUBMITQA
	CREATE TABLE #TMPSHOPACTIVITYSUBMITQA
	(User_Id BIGINT,cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,NEWSHOP_VISITED INT,RE_VISITED INT,VISITED_TIME NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPACTIVITYSUBMITQA(User_Id,cnt_internalId,visited_time)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPSHOPACTIVITYSUBMITQA(User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,VISITED_TIME) '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=1 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'APIATTENDANCEDETAILS_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE APIATTENDANCEDETAILS_REPORT
			(
			STARTENDDATE NVARCHAR(10),
			STARTENDDATEORDBY NVARCHAR(10),
			BRANCH_ID BIGINT,
			BRANCH_DESCRIPTION NVARCHAR(300),
			USERID BIGINT,
			EMPCODE NVARCHAR(100),
			EMPID NVARCHAR(100),
			EMPNAME NVARCHAR(300),
			CONTACTNO NVARCHAR(100),
			STATEID BIGINT,
			STATE NVARCHAR(300),
			DEG_ID BIGINT,
			DESIGNATION NVARCHAR(300),
			DATEOFJOINING NVARCHAR(10),
			REPORTTOID NVARCHAR(100),
			REPORTTOUID NVARCHAR(100),
			REPORTTO NVARCHAR(300),
			RPTTODESG NVARCHAR(100),
			DSTYPE NVARCHAR(100),
			CH_ID BIGINT,
			CHANNEL NVARCHAR(300),
			TOTWORKINGDAYS INT,
			TOTALATTENDANCE INT,
			TOTALQUALIFIEDPRESENT INT
			)
			CREATE NONCLUSTERED INDEX IX1 ON APIATTENDANCEDETAILS_REPORT (USERID)
		END
	TRUNCATE TABLE APIATTENDANCEDETAILS_REPORT

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO APIATTENDANCEDETAILS_REPORT(STARTENDDATE,STARTENDDATEORDBY,BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,CONTACTNO,STATEID,STATE,DEG_ID,DESIGNATION,'
	SET @SqlStr+='DATEOFJOINING,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,DSTYPE,CH_ID,CHANNEL,TOTWORKINGDAYS,TOTALATTENDANCE,TOTALQUALIFIEDPRESENT) '
	SET @SqlStr+='SELECT DAYSTARTEND.STARTENDDATE,DAYSTARTEND.STARTENDDATEORDBY,BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,USR.USER_ID AS USERID,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,'
	SET @SqlStr+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @SqlStr+='USR.user_loginId AS CONTACTNO,ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
	--Rev 1.0
	--SET @SqlStr+='RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,STG.Stage AS DSTYPE,CH.CH_ID,CH.CHANNEL,'+STR(LTRIM(RTRIM(@days)))+' AS TOTWORKINGDAYS,'
	SET @SqlStr+='RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,STG.Stage AS DSTYPE,CH.CH_ID,CH.CHANNEL,'+STR(LTRIM(RTRIM(@DAYCOUNT)))+' AS TOTWORKINGDAYS,'
	--End of Rev 1.0
	SET @SqlStr+='CASE WHEN DAYSTARTEND.DAYSTTIME<>'''' OR DAYSTARTEND.DAYSTTIME IS NOT NULL THEN 1 ELSE 0 END AS TOTALATTENDANCE,'
	--Rev 2.0
	--SET @SqlStr+='CASE WHEN (ISNULL(SHOPACT.RE_VISITED,0))>=20 AND '
	SET @SqlStr+='CASE WHEN (ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0))>=20 AND '
	--End of Rev 2.0
	SET @SqlStr+='(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
	SET @SqlStr+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT))>=240 '
	SET @SqlStr+='THEN 1 ELSE 0 END AS TOTALQUALIFIEDPRESENT '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @SqlStr+='INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @SqlStr+='DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @SqlStr+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '	
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT EC.ch_id,EC.ch_Channel AS CHANNEL,ECM.EP_EMP_CONTACTID FROM Employee_Channel EC WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN Employee_ChannelMap ECM WITH (NOLOCK) ON EC.ch_id=ECM.EP_CH_ID '
	SET @SqlStr+=') CH ON CNT.cnt_internalId=CH.EP_EMP_CONTACTID '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT USERID,MIN(DAYSTTIME) AS DAYSTTIME,MAX(DAYENDTIME) AS DAYENDTIME,cnt_internalId,STARTENDDATE,STARTENDDATEORDBY FROM('
	SET @SqlStr+='SELECT USERID,DAYSTTIME,DAYENDTIME,cnt_internalId,STARTENDDATE,STARTENDDATEORDBY FROM #TMPDAYSTARTENDQA '
	SET @SqlStr+=') DAYSTEND GROUP BY USERID,cnt_internalId,STARTENDDATE,STARTENDDATEORDBY) DAYSTARTEND ON CNT.cnt_internalId=DAYSTARTEND.cnt_internalId AND USR.user_id=DAYSTARTEND.USERID '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT User_Id,cnt_internalId,VISITED_TIME,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,VISITED_TIME FROM #TMPSHOPACTIVITYSUBMITQA '
	SET @SqlStr+=') AA GROUP BY User_Id,cnt_internalId,VISITED_TIME) SHOPACT ON CNT.cnt_internalId=SHOPACT.cnt_internalId AND DAYSTARTEND.STARTENDDATE=SHOPACT.VISITED_TIME '
	SET @SqlStr+='LEFT OUTER JOIN FTS_Stage STG WITH (NOLOCK) ON USR.FaceRegTypeID=STG.StageID '
	--Rev 3.0
	--SET @SqlStr+='WHERE DESG.deg_designation=''DS'' AND USR.FaceRegTypeID IN(1,2) '
	SET @SqlStr+='WHERE DESG.deg_designation=''DS'' AND USR.FaceRegTypeID IN(1,2,36,37) '
	--End of Rev 3.0
	SET @SqlStr+='ORDER BY USR.USER_ID '
	
	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	DROP TABLE #TEMPCONTACT
	DROP TABLE #TMPDAYSTARTENDQA
	DROP TABLE #TMPSHOPACTIVITYSUBMITQA

	SET NOCOUNT OFF
END
GO