--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDCNT'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDVALUE'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','AVGORDVALUE'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDDELV'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDCNTDATE'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDVALDT'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','ORDVALDELV'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','TOP10ITEMSVAL'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','TOP10ITEMSQTY'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','TOP10CUSTVAL'
--EXEC PRC_FTSORDERDBWITHANOTHERTAB_REPORT '2018-04-01','2020-04-30','TOP10STVAL'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSORDERDBWITHANOTHERTAB_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSORDERDBWITHANOTHERTAB_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSORDERDBWITHANOTHERTAB_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@REPORTTYPE NVARCHAR(20)=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder On 30/04/2020
Module	   : FSM ORDER DASHBOARD WITH ANOTHER TAB.Refer: 22266
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX)

	SET @Strsql=''
	IF @REPORTTYPE='ORDCNT'
		BEGIN
			SET @Strsql='SELECT COUNT(0) AS ORDCNT FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
		END
	ELSE IF @REPORTTYPE='ORDVALUE'
		BEGIN
			SET @Strsql='SELECT CASE WHEN CAST(SUM(ISNULL(Ordervalue,0)) AS DECIMAL(18,2)) IS NULL THEN 0.00 ELSE CAST(SUM(ISNULL(Ordervalue,0.00)) AS DECIMAL(18,2)) END AS ORDVALUE '
			SET @Strsql+='FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
		END
	ELSE IF @REPORTTYPE='AVGORDVALUE'
		BEGIN
			SET @Strsql='SELECT CASE WHEN CAST(SUM(ISNULL(Ordervalue,0)) AS DECIMAL(18,2)) IS NULL THEN 0.00 ELSE CAST(SUM(ISNULL(Ordervalue,0.00))/COUNT(0) AS DECIMAL(18,2)) END AS AVGORDVALUE '
			SET @Strsql+='FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
		END
	ELSE IF @REPORTTYPE='ORDDELV'
		BEGIN
			SET @Strsql='SELECT COUNT(0) AS ORDDELV FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND EXISTS(SELECT BILLD.OrderCode FROM tbl_FTS_BillingDetails BILLD WHERE BILLD.OrderCode=ORDHEAD.OrderCode)'
		END
	ELSE IF @REPORTTYPE='ORDCNTDATE'
		BEGIN
			SET @Strsql='SELECT CONVERT(NVARCHAR(5),ORDERDATE,105) AS ORDERDATE,ORDCNT FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY CAST(ORDHEAD.ORDERDATE AS DATE)) AS SEQ,CAST(ORDHEAD.ORDERDATE AS DATE) AS ORDERDATE,COUNT(0) AS ORDCNT FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY CAST(ORDHEAD.ORDERDATE AS DATE)) ORDDT '
		END
	ELSE IF @REPORTTYPE='ORDVALDT'
		BEGIN
			SET @Strsql='SELECT CONVERT(NVARCHAR(5),ORDERDATE,105) AS ORDERDATE,ORDVALUE FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY CAST(ORDHEAD.ORDERDATE AS DATE)) AS SEQ,CAST(ORDHEAD.ORDERDATE AS DATE) AS ORDERDATE,CAST(SUM(ISNULL(ORDHEAD.Ordervalue,0.00)) AS DECIMAL(18,2)) AS ORDVALUE '
			SET @Strsql+='FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY CAST(ORDHEAD.ORDERDATE AS DATE)) ORDVDT '
		END
	ELSE IF @REPORTTYPE='ORDVALDELV'
		BEGIN
			SET @Strsql='SELECT CONVERT(NVARCHAR(5),ORDERDATE,105) AS ORDERDATE,BILLVALUE FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY CAST(ORDHEAD.ORDERDATE AS DATE)) AS SEQ,CAST(ORDHEAD.ORDERDATE AS DATE) AS ORDERDATE,CAST(SUM(ISNULL(BILLHEAD.invoice_amount,0.00)) AS DECIMAL(18,2)) AS BILLVALUE '
			SET @Strsql+='FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='INNER JOIN tbl_FTS_BillingDetails BILLHEAD ON ORDHEAD.OrderCode=BILLHEAD.OrderCode '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY CAST(ORDHEAD.ORDERDATE AS DATE)) ORDBV '
		END
	ELSE IF @REPORTTYPE='TOP10ITEMSVAL'
		BEGIN
			SET @Strsql='SELECT TOP 10 OVD.SEQ,OVD.PRODUCT,OVD.ORDVALUE FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY ORDVALUE DESC) AS SEQ,PRODUCT,ORDVALUE FROM('
			SET @Strsql+='SELECT DET.PRODUCT,CAST(SUM(ISNULL(DET.ORDVALUE,0.00)) AS DECIMAL(18,2)) AS ORDVALUE FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='INNER JOIN (SELECT ORDDET.Order_ID,PROD.sProducts_Name AS PRODUCT,(ORDDET.Product_Qty*ORDDET.Product_Rate) AS ORDVALUE FROM tbl_FTs_OrderdetailsProduct ORDDET '
			SET @Strsql+='INNER JOIN Master_sProducts PROD ON PROD.sProducts_ID=ORDDET.Product_Id '
			SET @Strsql+=') DET ON ORDHEAD.OrderId=DET.Order_ID '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY DET.PRODUCT '
			SET @Strsql+=')OV '
			SET @Strsql+=')OVD '
		END
	ELSE IF @REPORTTYPE='TOP10ITEMSQTY'
		BEGIN
			SET @Strsql='SELECT TOP 10 OVD.SEQ,OVD.PRODUCT,OVD.ORDQTY FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY ORDQTY DESC) AS SEQ,PRODUCT,ORDQTY FROM('
			SET @Strsql+='SELECT DET.PRODUCT,SUM(DET.ORDQTY) AS ORDQTY FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='INNER JOIN (SELECT ORDDET.Order_ID,PROD.sProducts_Name AS PRODUCT,ORDDET.Product_Qty AS ORDQTY FROM tbl_FTs_OrderdetailsProduct ORDDET '
			SET @Strsql+='INNER JOIN Master_sProducts PROD ON PROD.sProducts_ID=ORDDET.Product_Id '
			SET @Strsql+=') DET ON ORDHEAD.OrderId=DET.Order_ID '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY DET.PRODUCT '
			SET @Strsql+=')OV '
			SET @Strsql+=')OVD '
		END
	ELSE IF @REPORTTYPE='TOP10CUSTVAL'
		BEGIN
			SET @Strsql='SELECT TOP 10 CUD.SEQ,CUD.SHOPNAME,CUD.ORDVALUE FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY ORDVALUE DESC) AS SEQ,SHOPNAME,ORDVALUE FROM('
			SET @Strsql+='SELECT SHOP.Shop_Name AS SHOPNAME,CAST(SUM(ISNULL(ORDHEAD.Ordervalue,0.00)) AS DECIMAL(18,2)) AS ORDVALUE FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='INNER JOIN tbl_Master_shop SHOP ON ORDHEAD.Shop_Code=SHOP.Shop_Code '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY SHOP.Shop_Name '
			SET @Strsql+=')CU '
			SET @Strsql+=')CUD '
		END
	ELSE IF @REPORTTYPE='TOP10STVAL'
		BEGIN
			SET @Strsql='SELECT TOP 10 STD.SEQ,STD.STCODE,STD.STATENAME,STD.ORDVALUE FROM('
			SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY ORDVALUE DESC) AS SEQ,STCODE,STATENAME,ORDVALUE FROM('
			SET @Strsql+='SELECT ST.StateUniqueCode AS STCODE,ST.state AS STATENAME,CAST(SUM(ISNULL(ORDHEAD.Ordervalue,0.00)) AS DECIMAL(18,2)) AS ORDVALUE FROM tbl_trans_fts_Orderupdate AS ORDHEAD '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ORDHEAD.userID '
			SET @Strsql+='INNER JOIN tbl_Master_shop SHOP ON SHOP.Shop_CreateUser=USR.user_id '
			SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.ID=SHOP.STATEID '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDHEAD.ORDERDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY ST.StateUniqueCode,ST.state '
			SET @Strsql+=')ST '
			SET @Strsql+=')STD '
		END
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	SET NOCOUNT OFF
END