--EXEC PRC_FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT '2023-07-01','2023-08-04','','','',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@BRANCHID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@CHANNELID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 23/11/2022
Module	   : DS Visit - Hierarchy & Channel Wise.Refer: 0025220
1.0		v2.0.41		Debashis	09/08/2023		A coloumn named as Gender needs to be added in all the ITC reports.Refer: 0026680
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX),@DAYCOUNT INT,@LOGINCNTID NVARCHAR(100)

	SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1

	IF OBJECT_ID('tempdb..#BRANCH_LIST') IS NOT NULL
		DROP TABLE #BRANCH_LIST
	CREATE TABLE #BRANCH_LIST (Branch_Id BIGINT NULL)
	CREATE NONCLUSTERED INDEX Branch_Id ON #BRANCH_LIST (Branch_Id ASC)

	IF @BRANCHID<>''
		BEGIN
			SET @SqlStrTable=''
			SET @BRANCHID=REPLACE(@BRANCHID,'''','')
			SET @sqlStrTable='INSERT INTO #BRANCH_LIST SELECT branch_id FROM tbl_master_branch WHERE branch_id IN ('+@BRANCHID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)

	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @SqlStrTable=''
			SET @SqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF OBJECT_ID('tempdb..#CHANNELHC_LIST') IS NOT NULL
		DROP TABLE #CHANNELHC_LIST
	CREATE TABLE #CHANNELHC_LIST (CH_ID BIGINT)

	IF @CHANNELID <> ''
		BEGIN
			SET @CHANNELID=REPLACE(@CHANNELID,'''','')
			SET @SqlStrTable=''
			SET @SqlStrTable='INSERT INTO #CHANNELHC_LIST SELECT CH_ID FROM Employee_Channel WITH(NOLOCK) WHERE CH_ID IN('+@CHANNELID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF OBJECT_ID('tempdb..#LOGINUSERCHANNELLISTDSVHC') IS NOT NULL
		DROP TABLE #LOGINUSERCHANNELLISTDSVHC
	CREATE TABLE #LOGINUSERCHANNELLISTDSVHC (CH_ID BIGINT)
	SELECT @LOGINCNTID=user_contactId FROM tbl_master_user WHERE user_id=@USERID
	INSERT INTO #LOGINUSERCHANNELLISTDSVHC SELECT EP_CH_ID FROM Employee_ChannelMap WITH(NOLOCK) WHERE EP_EMP_CONTACTID=@LOGINCNTID

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@Userid)		
			CREATE TABLE #EMPHRS
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)

			CREATE TABLE #EMPHR_EDIT
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)
			
			INSERT INTO #EMPHRS
			SELECT DISTINCT EMPCODE,RPTTOEMPCODE FROM(
			SELECT emp_cntId AS EMPCODE,ISNULL(TME.emp_contactId,'') AS RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_employee TME WITH(NOLOCK) ON TME.emp_id=CTC.emp_reportTO WHERE emp_effectiveuntil IS NULL
			UNION ALL
			SELECT emp_cntId AS EMPCODE,ISNULL(TME.emp_contactId,'') AS RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_employee TME WITH(NOLOCK) ON TME.emp_id= CTC.emp_deputy WHERE emp_effectiveuntil IS NULL
			) EMPHRS
		
			;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
			UNION ALL
			SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
			JOIN cte b ON a.RPTTOEMPCODE = b.EMPCODE
			) 
			INSERT INTO #EMPHR_EDIT
			SELECT EMPCODE,RPTTOEMPCODE FROM cte 
		END

	--DS & TL
	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			deg_designation NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			--Rev 1.0
			cnt_sex TINYINT NULL,
			GENDERDESC NVARCHAR(100) NULL
			--End of Rev 1.0
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			--Rev 1.0 && Two new fields added as cnt_sex & GENDERDESC
			INSERT INTO #TEMPCONTACT(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation,cnt_sex,GENDERDESC)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation,cnt_sex,
			CASE WHEN cnt_sex=1 THEN 'Male' WHEN cnt_sex=0 THEN 'Female' END GENDERDESC
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN #EMPHR_EDIT EMPEDIT ON CNT.cnt_internalId=EMPEDIT.EMPCODE 
			INNER JOIN tbl_master_employee EMP WITH(NOLOCK) ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation IN('DS','TL') 
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON EMP.emp_contactId=DESG.emp_cntId
			WHERE cnt_contactType IN('EM')
		END
	ELSE
		BEGIN
			--Rev 1.0 && Two new fields added as cnt_sex & GENDERDESC
			INSERT INTO #TEMPCONTACT(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation,cnt_sex,GENDERDESC)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation,cnt_sex,
			CASE WHEN cnt_sex=1 THEN 'Male' WHEN cnt_sex=0 THEN 'Female' END GENDERDESC 
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN tbl_master_employee EMP WITH(NOLOCK) ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation IN('DS','TL') 
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON EMP.emp_contactId=DESG.emp_cntId
			WHERE cnt_contactType IN('EM')
		END

	--AE
	IF OBJECT_ID('tempdb..#TEMPCONTACTAE') IS NOT NULL
		DROP TABLE #TEMPCONTACTAE
	CREATE TABLE #TEMPCONTACTAE
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			deg_designation NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACTAE(cnt_internalId,cnt_contactType ASC)
	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			INSERT INTO #TEMPCONTACTAE(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation 
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN #EMPHR_EDIT EMPEDIT ON CNT.cnt_internalId=EMPEDIT.EMPCODE 
			INNER JOIN tbl_master_employee EMP WITH(NOLOCK) ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation='AE'
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON DESG.emp_cntId=EMP.emp_contactId
			WHERE cnt_contactType IN('EM')
		END
	ELSE
		BEGIN
			INSERT INTO #TEMPCONTACTAE(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation 
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN tbl_master_employee EMP ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation='AE'
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON DESG.emp_cntId=EMP.emp_contactId
			WHERE cnt_contactType IN('EM')
		END

	--WD
	IF OBJECT_ID('tempdb..#TEMPCONTACTWD') IS NOT NULL
		DROP TABLE #TEMPCONTACTWD
	CREATE TABLE #TEMPCONTACTWD
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			deg_designation NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACTWD(cnt_internalId,cnt_contactType ASC)
	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			INSERT INTO #TEMPCONTACTWD(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation 
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN #EMPHR_EDIT EMPEDIT ON CNT.cnt_internalId=EMPEDIT.EMPCODE 
			INNER JOIN tbl_master_employee EMP WITH(NOLOCK) ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation='WD'
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON DESG.emp_cntId=EMP.emp_contactId
			WHERE cnt_contactType IN('EM')
		END
	ELSE
		BEGIN
			INSERT INTO #TEMPCONTACTWD(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,deg_designation)
			SELECT DISTINCT CNT.cnt_internalId,CNT.cnt_branchid,CNT.cnt_firstName,CNT.cnt_middleName,CNT.cnt_lastName,CNT.cnt_contactType,CNT.cnt_UCC,DESG.deg_designation 
			FROM TBL_MASTER_CONTACT CNT WITH(NOLOCK)
			INNER JOIN tbl_master_employee EMP WITH(NOLOCK) ON CNT.cnt_internalId=EMP.emp_contactId
			INNER JOIN (
			SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) 
			LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation 
			WHERE cnt.emp_effectiveuntil IS NULL AND desg.deg_designation='WD'
			GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
			) DESG ON DESG.emp_cntId=EMP.emp_contactId
			WHERE cnt_contactType IN('EM')
		END

	IF OBJECT_ID('tempdb..#TMPATTENLOGINOUTDSVHC') IS NOT NULL
		DROP TABLE #TMPATTENLOGINOUTDSVHC
	CREATE TABLE #TMPATTENLOGINOUTDSVHC
	(USERID BIGINT,LOGGEDIN NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGEDOUT NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
	Login_datetime NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGINDATE NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINOUTDSVHC(USERID,cnt_internalId,LOGINDATE)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPATTENLOGINOUTDSVHC(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,LOGINDATE) '
	SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) AND Login_datetime IS NOT NULL '
	SET @SqlStr+='AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @SqlStr+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) AND Login_datetime IS NULL '
	SET @SqlStr+='AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	SET @SqlStr+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF OBJECT_ID('tempdb..#TMPSHOPACTIVITYSUBMITDSVHC') IS NOT NULL
		DROP TABLE #TMPSHOPACTIVITYSUBMITDSVHC
	CREATE TABLE #TMPSHOPACTIVITYSUBMITDSVHC
	(User_Id BIGINT,cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,NEWSHOP_VISITED INT,RE_VISITED INT,DISTANCE_TRAVELLED DECIMAL(18,2),SPENT_DURATION NVARCHAR(100),visited_time NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPACTIVITYSUBMITDSVHC(User_Id,cnt_internalId,visited_time)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPSHOPACTIVITYSUBMITDSVHC(User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,DISTANCE_TRAVELLED,SPENT_DURATION,visited_time) '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=1 AND SHOPACT.User_Id<>0 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 AND SHOPACT.User_Id<>0 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF OBJECT_ID('tempdb..#TMPDAYSTARTENDDSVHC') IS NOT NULL
		DROP TABLE #TMPDAYSTARTENDDSVHC
	CREATE TABLE #TMPDAYSTARTENDDSVHC
	(USERID BIGINT,DAYSTTIME NVARCHAR(10),DAYENDTIME NVARCHAR(10),STARTENDDATE NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPDAYSTARTENDDSVHC(USERID,STARTENDDATE)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPDAYSTARTENDDSVHC(USERID,DAYSTTIME,DAYENDTIME,STARTENDDATE) '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYSTTIME,NULL AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	SET @SqlStr+='WHERE ISSTART=1 '
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,NULL AS DAYSTTIME,MAX(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	SET @SqlStr+='WHERE ISEND=1 '
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT') AND TYPE IN (N'U'))
		BEGIN
			--Rev 1.0 && Two new fields added as OUTLETEMPSEX & GENDERDESC
			CREATE TABLE FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT
			(
			  USERID INT,
			  SEQ BIGINT,
			  EMPROWID INT,
			  LOGINDATE	NVARCHAR(10),
			  LOGIN_DATETIME NVARCHAR(10),
			  BRANCH_ID BIGINT,
			  BRANCHDESC NVARCHAR(300),
			  EMPUSERID BIGINT,
			  EMPCODE NVARCHAR(100) NULL,
			  EMPID NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  DATEOFJOINING NVARCHAR(10),
			  CONTACTNO NVARCHAR(50) NULL,
			  REPORTTOIDWD NVARCHAR(300) NULL,
			  REPORTTOUIDWD NVARCHAR(100),
			  REPORTTOWD NVARCHAR(300) NULL,
			  RPTTODESGWD NVARCHAR(50) NULL,
			  REPORTTOIDAE NVARCHAR(300) NULL,
			  REPORTTOUIDAE NVARCHAR(100),
			  REPORTTOAE NVARCHAR(300) NULL,
			  RPTTODESGAE NVARCHAR(50) NULL,
			  OUTLETSMAPPED INT,
			  NEWSHOP_VISITED INT,
			  RE_VISITED INT,
			  TOTAL_VISIT INT,
			  DISTANCE_TRAVELLED DECIMAL(38,2),
			  AVGTIMESPENTINMARKET NVARCHAR(50),
			  DAYSTTIME NVARCHAR(20),
			  DAYENDTIME NVARCHAR(20),
			  AVGSPENTDURATION NVARCHAR(50),
			  DSTYPEID BIGINT,
			  DSTYPE NVARCHAR(600),
			  CIRCLE NVARCHAR(MAX),
			  SECTION NVARCHAR(MAX),
			  CH_ID BIGINT,
			  CHANNEL NVARCHAR(300),
			  OUTLETEMPSEX TINYINT,
			  GENDERDESC NVARCHAR(100)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT (SEQ)
		END
	DELETE FROM FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT WHERE USERID=@USERID

	--Rev 1.0 && Two new fields added as OUTLETEMPSEX & GENDERDESC
	SET @SqlStr=''
	SET @SqlStr='INSERT INTO FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT(USERID,SEQ,EMPROWID,LOGINDATE,LOGIN_DATETIME,BRANCH_ID,BRANCHDESC,EMPUSERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,'
	SET @SqlStr+='DATEOFJOINING,CONTACTNO,REPORTTOIDWD,REPORTTOUIDWD,REPORTTOWD,RPTTODESGWD,REPORTTOIDAE,REPORTTOUIDAE,REPORTTOAE,RPTTODESGAE,OUTLETSMAPPED,NEWSHOP_VISITED,RE_VISITED,TOTAL_VISIT,'
	SET @SqlStr+='DISTANCE_TRAVELLED,AVGTIMESPENTINMARKET,DAYSTTIME,DAYENDTIME,AVGSPENTDURATION,DSTYPEID,DSTYPE,CIRCLE,SECTION,CH_ID,CHANNEL,OUTLETEMPSEX,GENDERDESC) '
	SET @SqlStr+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY EMPCODE,LOGINDATE) AS SEQ,EMPROWID,LOGINDATE,LOGIN_DATETIME,BRANCH_ID,BRANCH_DESCRIPTION,EMPUSERID,EMPCODE,EMPID,'
	SET @SqlStr+='EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOIDWD,REPORTTOUIDWD,REPORTTOWD,RPTTODESGWD,REPORTTOIDAE,REPORTTOUIDAE,REPORTTOAE,RPTTODESGAE,'
	SET @SqlStr+='OUTLETSMAPPED,NEWSHOP_VISITED,RE_VISITED,TOTAL_VISIT,DISTANCE_TRAVELLED,'
	SET @SqlStr+='RIGHT(''0'' + CAST(CAST(AVGDAYSTARTENDDURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(AVGDAYSTARTENDDURATION AS VARCHAR) % 60 AS VARCHAR),2) AS AVGTIMESPENTINMARKET,'
	SET @SqlStr+='DAYSTTIME,DAYENDTIME,'
	SET @SqlStr+='RIGHT(''0'' + CAST(CAST(SPENT_DURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(SPENT_DURATION AS VARCHAR) % 60 AS VARCHAR),2) AS AVGSPENTDURATION,'
	SET @SqlStr+='DSTYPEID,DSTYPE,CIRCLE,SECTION,CH_ID,CHANNEL,OUTLETEMPSEX,GENDERDESC '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT ROW_NUMBER() OVER(PARTITION BY EMPCODE ORDER BY EMPCODE) AS EMPROWID,LOGINDATE,LOGIN_DATETIME,BRANCH_ID,BRANCH_DESCRIPTION,EMPUSERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,'
	SET @SqlStr+='DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOIDWD,REPORTTOUIDWD,REPORTTOWD,RPTTODESGWD,REPORTTOIDAE,REPORTTOUIDAE,REPORTTOAE,RPTTODESGAE,SUM(OUTLETSMAPPED) AS OUTLETSMAPPED,'
	SET @SqlStr+='SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,SUM(TOTAL_VISIT) AS TOTAL_VISIT,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED,'
	SET @SqlStr+='SUM(DAYSTARTENDDURATION) AS DAYSTARTENDDURATION,CAST(ABS(SUM(DAYSTARTENDDURATION)) AS INT) AS AVGDAYSTARTENDDURATION,'
	SET @SqlStr+='CAST(SUM(SPENT_DURATION)/(CASE WHEN (SUM(NEWSHOP_VISITED)+SUM(RE_VISITED))>0 THEN (SUM(NEWSHOP_VISITED)+SUM(RE_VISITED)) ELSE 1 END) AS INT) AS SPENT_DURATION,DAYSTTIME,DAYENDTIME,'
	SET @SqlStr+='DSTYPEID,DSTYPE,CIRCLE,SECTION,CH_ID,CHANNEL,OUTLETEMPSEX,GENDERDESC '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT ATTEN.LOGINDATE,ATTEN.LOGIN_DATETIME,BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,USR.USER_ID AS EMPUSERID,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,'
	SET @SqlStr+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @SqlStr+='ISNULL(ST.ID,0) AS STATEID,ISNULL(ST.state,''State Undefined'') AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
	SET @SqlStr+='USR.user_loginId AS CONTACTNO,ATTEN.LOGGEDIN,ATTEN.LOGEDOUT,RPTTOWD.REPORTTOIDWD,RPTTOWD.REPORTTOUIDWD,RPTTOWD.REPORTTOWD,RPTTOWD.RPTTODESGWD,RPTTOAE.REPORTTOIDAE,RPTTOAE.REPORTTOUIDAE,RPTTOAE.REPORTTOAE,RPTTOAE.RPTTODESGAE,'
	SET @SqlStr+='ISNULL(SHOP.OUTLETSMAPPED,0) AS OUTLETSMAPPED,ISNULL(SHOPACT.NEWSHOP_VISITED,0) AS NEWSHOP_VISITED,ISNULL(SHOPACT.RE_VISITED,0) AS RE_VISITED,ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0) AS TOTAL_VISIT,'
	SET @SqlStr+='ISNULL(DISTANCE_TRAVELLED,0) AS DISTANCE_TRAVELLED,DAYSTARTEND.DAYSTTIME,DAYSTARTEND.DAYENDTIME,'
	SET @SqlStr+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
	SET @SqlStr+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS DAYSTARTENDDURATION,'
	SET @SqlStr+='SHOPACT.SPENT_DURATION,USR.FaceRegTypeID AS DSTYPEID,STG.Stage AS DSTYPE,'
	SET @SqlStr+='ISNULL((SELECT LTRIM(STUFF(((SELECT DISTINCT '', '' + sec_Section FROM '
	SET @SqlStr+='(SELECT ES.sec_Section FROM Employee_Section ES WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN Employee_SectionMap ESM WITH (NOLOCK) ON ES.sec_id=ESM.EP_SEC_ID WHERE ESM.EP_EMP_CONTACTID=CNT.cnt_internalId '
	SET @SqlStr+=') AS SEC FOR XML PATH(''''))),1,2,'' ''))),'''') AS SECTION,'
	SET @SqlStr+='ISNULL((SELECT LTRIM(STUFF(((SELECT DISTINCT '', '' + crl_Circle FROM '
	SET @SqlStr+='(SELECT EC.crl_Circle FROM Employee_Circle EC WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN Employee_CircleMap ECM WITH (NOLOCK) ON EC.crl_id=ECM.EP_CRL_ID WHERE ECM.EP_EMP_CONTACTID=CNT.cnt_internalId '
	SET @SqlStr+=') AS CIR FOR XML PATH(''''))),1,2,'' ''))),'''') AS CIRCLE,CH.CH_ID,CH.CHANNEL,CNT.cnt_sex AS OUTLETEMPSEX,CNT.GENDERDESC '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @SqlStr+='INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state '
	SET @SqlStr+='INNER JOIN FTS_Stage STG WITH (NOLOCK) ON USR.FaceRegTypeID=STG.StageID '
	SET @SqlStr+='INNER JOIN ( '
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	--WD
	SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId AS INTERNALIDWD,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOIDWD,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTOWD,'
	SET @SqlStr+='DESG.deg_designation AS RPTTODESGWD,CNT.cnt_UCC AS REPORTTOUIDWD '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @SqlStr+='INNER JOIN #TEMPCONTACTWD CNT ON EMP.emp_contactId=CNT.cnt_internalId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON EMP.emp_contactId=DESG.emp_cntId '
	SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT EMPCTC.emp_cntId AS INTERNALIDWD,EMPCTC.emp_deputy AS emp_reportTo,CNT.cnt_internalId AS REPORTTOIDWD,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTOWD,'
	SET @SqlStr+='DESG.deg_designation AS RPTTODESGWD,CNT.cnt_UCC AS REPORTTOUIDWD '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_deputy '
	SET @SqlStr+='INNER JOIN #TEMPCONTACTWD CNT ON EMP.emp_contactId=CNT.cnt_internalId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON EMP.emp_contactId=DESG.emp_cntId '
	SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @SqlStr+=') RPTTOWD ON CNT.cnt_internalId=RPTTOWD.INTERNALIDWD '
	--AE
	SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId AS INTERNALIDAE,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOIDAE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTOAE,'
	SET @SqlStr+='DESG.deg_designation AS RPTTODESGAE,CNT.cnt_UCC AS REPORTTOUIDAE '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @SqlStr+='INNER JOIN #TEMPCONTACTAE CNT ON EMP.emp_contactId=CNT.cnt_internalId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON EMP.emp_contactId=DESG.emp_cntId '
	SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT EMPCTC.emp_cntId AS INTERNALIDAE,EMPCTC.emp_deputy AS emp_reportTo,CNT.cnt_internalId AS REPORTTOIDAE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTOAE,'
	SET @SqlStr+='DESG.deg_designation AS RPTTODESGAE,CNT.cnt_UCC AS REPORTTOUIDAE '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_deputy '
	SET @SqlStr+='INNER JOIN #TEMPCONTACTAE CNT ON EMP.emp_contactId=CNT.cnt_internalId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON EMP.emp_contactId=DESG.emp_cntId '
	SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL '	
	SET @SqlStr+=') RPTTOAE ON RPTTOWD.REPORTTOIDWD=RPTTOAE.INTERNALIDAE '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT EC.ch_id,EC.ch_Channel AS CHANNEL,ECM.EP_EMP_CONTACTID FROM Employee_Channel EC WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN Employee_ChannelMap ECM WITH (NOLOCK) ON EC.ch_id=ECM.EP_CH_ID '
	SET @SqlStr+=') CH ON CNT.cnt_internalId=CH.EP_EMP_CONTACTID '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,LOGINDATE FROM( '
	SET @SqlStr+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,LOGINDATE FROM #TMPATTENLOGINOUTDSVHC '
	SET @SqlStr+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,LOGINDATE) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT User_Id,cnt_internalId,VISITED_TIME,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED,'
	SET @SqlStr+='SUM(CAST(SUBSTRING(SPENT_DURATION,1,2) AS INT)*60+CAST(SUBSTRING(SPENT_DURATION,4,2) AS INT)) AS SPENT_DURATION '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,DISTANCE_TRAVELLED,SPENT_DURATION,visited_time FROM #TMPSHOPACTIVITYSUBMITDSVHC '
	SET @SqlStr+=') AA GROUP BY User_Id,cnt_internalId,VISITED_TIME) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT Shop_CreateUser,COUNT(Shop_Code) AS OUTLETSMAPPED FROM tbl_Master_shop WITH (NOLOCK) '
	SET @SqlStr+='GROUP BY Shop_CreateUser) SHOP ON SHOP.Shop_CreateUser=USR.user_id '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT USERID,MIN(DAYSTTIME) AS DAYSTTIME,MAX(DAYENDTIME) AS DAYENDTIME,STARTENDDATE FROM('
	SET @SqlStr+='SELECT USERID,DAYSTTIME,DAYENDTIME,STARTENDDATE FROM #TMPDAYSTARTENDDSVHC '
	SET @SqlStr+=') DAYSTEND GROUP BY USERID,STARTENDDATE) DAYSTARTEND ON DAYSTARTEND.USERID=USR.user_id AND ATTEN.Login_datetime=DAYSTARTEND.STARTENDDATE '
	SET @SqlStr+='WHERE DESG.deg_designation=''DS'' AND USR.FaceRegTypeID IN(1,2) '
	SET @SqlStr+='AND EXISTS (SELECT LC.CH_ID FROM #LOGINUSERCHANNELLISTDSVHC LC WHERE CH.ch_id=LC.CH_ID) '
	IF @BRANCHID<>''
		SET @SqlStr+='AND EXISTS (SELECT Branch_Id FROM #Branch_List AS F WHERE F.Branch_Id=BR.branch_id) '
	IF @EMPID<>''
		SET @SqlStr+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=RPTTOWD.REPORTTOIDWD) '
	IF @CHANNELID<>''
		SET @SqlStr+='AND EXISTS (SELECT ch_id FROM #CHANNELHC_LIST AS CHN WHERE CHN.ch_id=CH.CH_ID) '
	SET @SqlStr+=') DSDET '
	SET @SqlStr+='GROUP BY LOGINDATE,LOGIN_DATETIME,BRANCH_ID,BRANCH_DESCRIPTION,EMPUSERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOIDWD,REPORTTOUIDWD,'
	SET @SqlStr+='REPORTTOWD,RPTTODESGWD,REPORTTOIDAE,REPORTTOUIDAE,REPORTTOAE,RPTTODESGAE,DAYSTTIME,DAYENDTIME,DSTYPEID,DSTYPE,CIRCLE,SECTION,CH_ID,CHANNEL,OUTLETEMPSEX,GENDERDESC '
	SET @SqlStr+=') DSDETAILS '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	DROP TABLE #BRANCH_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #TMPATTENLOGINOUTDSVHC

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
	BEGIN
		DROP TABLE #EMPHR_EDIT
		DROP TABLE #EMPHRS
	END
	DROP TABLE #TMPSHOPACTIVITYSUBMITDSVHC
	DROP TABLE #TMPDAYSTARTENDDSVHC
	DROP TABLE #CHANNELHC_LIST
	DROP TABLE #LOGINUSERCHANNELLISTDSVHC
	DROP TABLE #TEMPCONTACTAE
	DROP TABLE #TEMPCONTACTWD

	SET NOCOUNT OFF
END