--EXEC PRC_FTSLEADREGISTER_REPORT '2021-04-01','2022-01-31','15','14','EMS0000005',378
--EXEC PRC_FTSLEADREGISTER_REPORT '2021-04-01','2022-01-31','','','',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSLEADREGISTER_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSLEADREGISTER_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSLEADREGISTER_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/**********************************************************************************************************************************************************************************************************
Written by : Debashis Talukder On 07/01/2022
Module	   : Lead Register.Refer: 0024541
**********************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@sqlStrTable NVARCHAR(MAX)

	IF OBJECT_ID('tempdb..#STATEID_LIST') IS NOT NULL
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #STATEID_LIST SELECT id from tbl_master_state where id in('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END
	
	IF OBJECT_ID('tempdb..#DESIGNATION_LIST') IS NOT NULL
		DROP TABLE #DESIGNATION_LIST
	CREATE TABLE #DESIGNATION_LIST (deg_id INT)
	CREATE NONCLUSTERED INDEX IX2 ON #DESIGNATION_LIST (deg_id ASC)
	IF @DESIGNID <> ''
		BEGIN
			SET @DESIGNID=REPLACE(@DESIGNID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #DESIGNATION_LIST SELECT deg_id from tbl_master_designation where deg_id in('+@DESIGNID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF OBJECT_ID('tempdb..#TMPQAANAME') IS NOT NULL
		DROP TABLE #TMPQAANAME
	CREATE TABLE #TMPQAANAME(USER_ID BIGINT,SHOP_ID NVARCHAR(200),[Lead Should go and Deliver Products 4-6 Days in week] NVARCHAR(10),[Lead Should go and Collection products 4-6 days in Week] NVARCHAR(10),
	[Monthly investment 75K - 1.25L] NVARCHAR(10),[Should Deliver Products 100-200 outlets] NVARCHAR(10),[Should do cash and carry sales for 25% Retails Outlets] NVARCHAR(10),
	[Should do Credit sales for 50% Retails Outlets] NVARCHAR(10),[Should do Bill to Bill sales for 25% Retails outlets] NVARCHAR(10),[Should have Already be a FMCG Distributors] NVARCHAR(10),
	[Already handled FMCG beverage Products] NVARCHAR(10),[Handling other FMCG Products Parallelly] NVARCHAR(10),[Should have a four-wheeler] NVARCHAR(10),[Should have a Two-Wheeler] NVARCHAR(10),
	[Should have an employed sales Man] NVARCHAR(10),[Should have exposure a Net banking and Google Pay] NVARCHAR(10),[Should have a lived in an area more than 15 years] NVARCHAR(10),
	[Should have a business in an area more than 10 years] NVARCHAR(10),[Should go market and take order from a shop] NVARCHAR(10),[Age between 35 – 55] NVARCHAR(10))

	INSERT INTO #TMPQAANAME(USER_ID,SHOP_ID)
	SELECT DISTINCT QA.USER_ID,QA.SHOP_ID FROM FSMAPIRUBYFOODQA QA
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSLEADREGISTER_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSLEADREGISTER_REPORT
			(
			  USERID INT,
			  SEQ INT,
			  SHOPDATE NVARCHAR(10),
			  SHOPDATEORDBY NVARCHAR(10),
			  USER_ID BIGINT,
			  EMPID NVARCHAR(100) NULL,
			  EMPCODE NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  CONTACTNO NVARCHAR(50) NULL,
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESG NVARCHAR(50) NULL,
			  LEAD_CODE NVARCHAR(100) NULL,
			  LEAD_NAME NVARCHAR(4000) NULL,
			  LEADCONTACTNO NVARCHAR(100) NULL,
			  AGENCY_NAME NVARCHAR(500) NULL,
			  LEAD_ADDRESS NVARCHAR(MAX) NULL,
			  VISITSTATUS NVARCHAR(100) NULL,
			  SELFIE_PIC NVARCHAR(MAX) NULL,
			  VISITNG_CARD1 NVARCHAR(1000) NULL,
			  VISITNG_CARD2 NVARCHAR(1000) NULL,
			  PROSPECT NVARCHAR(600) NULL,
			  APROXMATE_BILLING DECIMAL(18,2) NULL,
			  DELIVER_PRODUCTS_4_6_DAYS NVARCHAR(10),
			  COLLECTION_PRODUCTS_4_6_DAYS NVARCHAR(10),
			  MONTHLY_INVESTMENT_75K_125L NVARCHAR(10),
			  DELIVER_PRODUCTS_100_200_OUTLETS NVARCHAR(10),
			  CASH_CARRY_SALES_FOR_25_RETAILS_OUTLETS NVARCHAR(10),
			  CREDIT_SALES_FOR_50_RETAILS_OUTLETS NVARCHAR(10),
			  BILL_SALES_FOR_25_RETAILS_OUTLETS NVARCHAR(10),
			  ALREADY_FMCG_DISTRIBUTORS NVARCHAR(10),
			  ALREADY_HANDLED_FMCG_BEVERAGE_PRODUCTS NVARCHAR(10),
			  HANDLING_OTHER_FMCG_PRODUCTS_PARALLELLY NVARCHAR(10),
			  FOUR_WHEELER NVARCHAR(10),
			  TWO_WHEELER NVARCHAR(10),
			  EMPLOYED_SALESMAN NVARCHAR(10),
			  NETBANKING_GOOGLEPAY NVARCHAR(10),
			  LIVED_MORETHAN_15YEARS NVARCHAR(10),
			  BUSINESS_MORETHAN_10YEARS NVARCHAR(10),
			  TAKEORDERFROMASHOP NVARCHAR(10),
			  AGE_BETWEEN_35_55 NVARCHAR(10)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSLEADREGISTER_REPORT (SEQ)
		END
	DELETE FROM FTSLEADREGISTER_REPORT WHERE USERID=@USERID

	UPDATE QAHNM SET [Lead Should go and Deliver Products 4-6 Days in week]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Lead Should go and Deliver Products 4-6 Days in week'

	UPDATE QAHNM SET [Lead Should go and Collection products 4-6 days in Week]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Lead Should go and Collection products 4-6 days in Week'

	UPDATE QAHNM SET [Monthly investment 75K - 1.25L]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Monthly investment 75K - 1.25L'

	UPDATE QAHNM SET [Should Deliver Products 100-200 outlets]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should Deliver Products 100-200 outlets'

	UPDATE QAHNM SET [Should do cash and carry sales for 25% Retails Outlets]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should do cash and carry sales for 25% Retails Outlets'

	UPDATE QAHNM SET [Should do Credit sales for 50% Retails Outlets]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should do Credit sales for 50% Retails Outlets'

	UPDATE QAHNM SET [Should do Bill to Bill sales for 25% Retails outlets]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should do Bill to Bill sales for 25% Retails outlets'

	UPDATE QAHNM SET [Should have Already be a FMCG Distributors]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have Already be a FMCG Distributors'

	UPDATE QAHNM SET [Already handled FMCG beverage Products]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Already handled FMCG beverage Products'

	UPDATE QAHNM SET [Handling other FMCG Products Parallelly]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Handling other FMCG Products Parallelly'

	UPDATE QAHNM SET [Should have a four-wheeler]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have a four-wheeler'

	UPDATE QAHNM SET [Should have a Two-Wheeler]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have a Two-Wheeler'

	UPDATE QAHNM SET [Should have an employed sales Man]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have an employed sales Man'

	UPDATE QAHNM SET [Should have exposure a Net banking and Google Pay]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have exposure a Net banking and Google Pay'

	UPDATE QAHNM SET [Should have a lived in an area more than 15 years]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have a lived in an area more than 15 years'

	UPDATE QAHNM SET [Should have a business in an area more than 10 years]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should have a business in an area more than 10 years'

	UPDATE QAHNM SET [Should go market and take order from a shop]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Should go market and take order from a shop'

	UPDATE QAHNM SET [Age between 35 – 55]=(CASE WHEN QA.ANSWER=1 THEN 'Yes' ELSE 'No' END) FROM #TMPQAANAME QAHNM
	INNER JOIN FSMAPIRUBYFOODQA QA ON QAHNM.USER_ID=QA.USER_ID AND QAHNM.SHOP_ID=QA.SHOP_ID
	INNER JOIN FSMAPIRUBYFOODQUESTION QAH ON QA.QUESTION_ID=QAH.QUESID
	WHERE QAH.ISACTIVE=1 AND QAH.QUESDESCRIPTION='Age between 35 – 55'

	SET @Strsql=''
	SET @Strsql='INSERT INTO FTSLEADREGISTER_REPORT(USERID,SEQ,SHOPDATE,SHOPDATEORDBY,USER_ID,EMPID,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REPORTTO,RPTTODESG,LEAD_CODE,LEAD_NAME,LEADCONTACTNO,'
	SET @Strsql+='AGENCY_NAME,LEAD_ADDRESS,VISITSTATUS,SELFIE_PIC,VISITNG_CARD1,VISITNG_CARD2,PROSPECT,APROXMATE_BILLING,DELIVER_PRODUCTS_4_6_DAYS,COLLECTION_PRODUCTS_4_6_DAYS,MONTHLY_INVESTMENT_75K_125L,'
	SET @Strsql+='DELIVER_PRODUCTS_100_200_OUTLETS,CASH_CARRY_SALES_FOR_25_RETAILS_OUTLETS,CREDIT_SALES_FOR_50_RETAILS_OUTLETS,BILL_SALES_FOR_25_RETAILS_OUTLETS,ALREADY_FMCG_DISTRIBUTORS,'
	SET @Strsql+='ALREADY_HANDLED_FMCG_BEVERAGE_PRODUCTS,HANDLING_OTHER_FMCG_PRODUCTS_PARALLELLY,FOUR_WHEELER,TWO_WHEELER,EMPLOYED_SALESMAN,NETBANKING_GOOGLEPAY,LIVED_MORETHAN_15YEARS,'
	SET @Strsql+='BUSINESS_MORETHAN_10YEARS,TAKEORDERFROMASHOP,AGE_BETWEEN_35_55) '
	SET @Strsql+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY SHOPACT.VISITDATEORDBY) AS SEQ,SHOPACT.VISITDATE AS SHOPDATE,SHOPACT.VISITDATEORDBY AS SHOPDATEORDBY,'
	SET @Strsql+='USR.USER_ID,EMP.emp_uniqueCode AS EMPID,CNT.cnt_internalId AS EMPCODE,'
	SET @Strsql+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,'
	SET @Strsql+='DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,MS.SHOP_CODE AS LEAD_CODE,MS.SHOP_NAME AS LEAD_NAME,MS.Shop_Owner_Contact AS LEADCONTACTNO,'
	SET @Strsql+='SHOPACT.AGENCY_NAME,MS.Address AS LEAD_ADDRESS,SHOPACT.VISITSTATUS,MS.Shop_Image AS SELFIE_PIC,LDIMG.DOCUMENTIMAGEPATH1 AS VISITNG_CARD1,LDIMG.DOCUMENTIMAGEPATH2 AS VISITNG_CARD2,STG.Stage AS PROSPECT,'
	SET @Strsql+='SHOPACT.Approximate_1st_Billing_Value AS APROXMATE_BILLING,QAHD.[Lead Should go and Deliver Products 4-6 Days in week],QAHD.[Lead Should go and Collection products 4-6 days in Week],'
	SET @Strsql+='QAHD.[Monthly investment 75K - 1.25L],QAHD.[Should Deliver Products 100-200 outlets],QAHD.[Should do cash and carry sales for 25% Retails Outlets],QAHD.[Should do Credit sales for 50% Retails Outlets],'
	SET @Strsql+='QAHD.[Should do Bill to Bill sales for 25% Retails outlets],QAHD.[Should have Already be a FMCG Distributors],QAHD.[Already handled FMCG beverage Products],QAHD.[Handling other FMCG Products Parallelly],'
	SET @Strsql+='QAHD.[Should have a four-wheeler],QAHD.[Should have a Two-Wheeler],QAHD.[Should have an employed sales Man],QAHD.[Should have exposure a Net banking and Google Pay],'
	SET @Strsql+='QAHD.[Should have a lived in an area more than 15 years],QAHD.[Should have a business in an area more than 10 years],QAHD.[Should go market and take order from a shop],'
	SET @Strsql+='QAHD.[Age between 35 – 55] '
	SET @Strsql+='FROM tbl_Master_shop MS '
	SET @Strsql+='INNER JOIN TBL_MASTER_USER USR ON MS.Shop_CreateUser=USR.user_id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON USR.user_contactId=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN tbl_master_employee EMP ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT USERID,cnt_internalId,LOGGEDINDATE FROM('
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS LOGGEDINDATE '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+=') LOGINLOGOUT) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT User_Id,cnt_internalId,Shop_Id,VISITDATE,VISITDATEORDBY,AGENCY_NAME,PROS_ID,Approximate_1st_Billing_Value,VISITSTATUS FROM('
	SET @Strsql+='SELECT SHOPACT.User_Id,SHOPACT.Shop_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITDATE,CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) AS VISITDATEORDBY,'
	SET @Strsql+='SHOPACT.AGENCY_NAME,SHOPACT.PROS_ID,SHOPACT.Approximate_1st_Billing_Value,CASE WHEN SHOPACT.Is_Newshopadd=1 THEN ''New Visit'' WHEN SHOPACT.Is_Newshopadd=0 THEN ''ReVisit'' END AS VISITSTATUS '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+=') AA) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND SHOPACT.User_Id=ATTEN.USERID AND ATTEN.LOGGEDINDATE=SHOPACT.VISITDATE '
	SET @Strsql+='AND MS.Shop_CreateUser=SHOPACT.User_Id AND MS.Shop_Code=SHOPACT.Shop_Id '
	SET @Strsql+='LEFT OUTER JOIN FSMRUBYLEADIMAGE AS LDIMG ON USR.user_id=LDIMG.USER_ID AND MS.Shop_Code=LDIMG.SHOP_ID '
	SET @Strsql+='LEFT OUTER JOIN FTS_Stage STG ON SHOPACT.Pros_Id=STG.StageID '
	SET @Strsql+='LEFT OUTER JOIN('
	SET @Strsql+='SELECT QAH.USER_ID,QAH.SHOP_ID,QAH.[Lead Should go and Deliver Products 4-6 Days in week],QAH.[Lead Should go and Collection products 4-6 days in Week],'
	SET @Strsql+='QAH.[Monthly investment 75K - 1.25L],QAH.[Should Deliver Products 100-200 outlets],QAH.[Should do cash and carry sales for 25% Retails Outlets],'
	SET @Strsql+='QAH.[Should do Credit sales for 50% Retails Outlets],QAH.[Should do Bill to Bill sales for 25% Retails outlets],QAH.[Should have Already be a FMCG Distributors],'
	SET @Strsql+='QAH.[Already handled FMCG beverage Products],QAH.[Handling other FMCG Products Parallelly],QAH.[Should have a four-wheeler],QAH.[Should have a Two-Wheeler],'
	SET @Strsql+='QAH.[Should have an employed sales Man],QAH.[Should have exposure a Net banking and Google Pay],QAH.[Should have a lived in an area more than 15 years],'
	SET @Strsql+='QAH.[Should have a business in an area more than 10 years],QAH.[Should go market and take order from a shop],QAH.[Age between 35 – 55] FROM #TMPQAANAME QAH '
	SET @Strsql+=') QAHD ON USR.user_id=QAHD.USER_ID AND MS.Shop_Code=QAHD.SHOP_ID '
	SET @Strsql+='WHERE MS.type=16 '
	IF @STATEID<>''
		SET @Strsql+='AND EXISTS (SELECT State_Id from #STATEID_LIST AS STA WHERE STA.State_Id=ST.id) '
	IF @DESIGNID<>''
		SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DESG.DEG_ID) '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #DESIGNATION_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TMPQAANAME

	SET NOCOUNT OFF
END