IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_EMPLOYEELOG]') AND type in (N'P', N'PC')) 
 BEGIN 
 EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_EMPLOYEELOG] AS'  
 END 
 GO 

ALTER PROC [PRC_EMPLOYEELOG]
(
@ACTION VARCHAR(55)=NULL,
@EMPCODE VARCHAR(200)=NULL,
@LOOPNUMBER INT=NULL,
@EMPNAME VARCHAR(200)=NULL,
@USERID VARCHAR (20)=NULL,
@FILENAME VARCHAR(200)=NULL,
@DECRIPTION VARCHAR(200)=NULL,
@STATUS     VARCHAR(200)=NULL
)
AS 
/*****************************************************************************************************************
Written by : Priti Roy ON 20/02/2023
Module	   : Employee  Master Refer: 0025676
*******************************************************************************************************************/

BEGIN TRAN T1        
BEGIN TRY 
 

 IF(@ACTION)='FetchEmployeeLog'
 BEGIN
 COMMIT TRAN T1

 IF ((SELECT COUNT(EMPLOGID) FROM EmployeeImportLog WHERE ISSHOW = 0) > 0)
 BEGIN
   
	SELECT EMPLOGID,EMPLOYEECODE,LOOPNUMBER,EMPNAME,[FILENAME],[DESCRIPTION],[STATUS],CREATEDDATETIME  FROM EmployeeImportLog
	WHERE  ISSHOW = 0;

	UPDATE EmployeeImportLog SET ISSHOW = 1;
 END
 Else
 IF(@ACTION)='INSERTLOG'
 BEGIN
	INSERT INTO EmployeeImportLog(EMPLOYEECODE,LOOPNUMBER,EMPNAME,[STATUS],[FILENAME],[DESCRIPTION],CREATEDBY,CREATEDDATETIME,ISSHOW)
	VALUES(@EMPCODE,@LOOPNUMBER,@EMPNAME,@STATUS,@FILENAME,@DECRIPTION,@USERID,GETDATE(),0)
 END

 ELSE
 BEGIN
    
	SELECT EMPLOGID,EMPLOYEECODE,LOOPNUMBER,EMPNAME,[FILENAME],[DESCRIPTION],[STATUS],CREATEDDATETIME  FROM EmployeeImportLog
	WHERE  ISSHOW = 1
	 ORDER BY CREATEDDATETIME DESC 
	END
	RETURN
 END



COMMIT TRAN T1          
END TRY      
      
BEGIN CATCH      
 ROLLBACK TRAN T1          
		DECLARE @ERRORMESSAGE NVARCHAR(4000) ;
        DECLARE @ERRORSEVERITY INT ;
        DECLARE @ERRORSTATE INT ;
        SELECT  @ERRORMESSAGE = ERROR_MESSAGE() ,
                @ERRORSEVERITY = ERROR_SEVERITY() ,
                @ERRORSTATE = ERROR_STATE() ;
				
				
        RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE) ;    
	RETURN    

END CATCH
	
		
    
GO
