------EXEC PRC_FTSQUOTATIONAPPROVALDETAILS_REPORT @ACTION='LISTING', @FROMDATE='2022-01-01',@TODATE='2022-04-30',@EMPID='',@SHOPID='',@USERID=378
------EXEC PRC_FTSQUOTATIONAPPROVALDETAILS_REPORT @ACTION='LISTING', @FROMDATE='2022-01-01',@TODATE='2022-04-30',@EMPID='',@SHOPID='',@USERID=378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSQUOTATIONAPPROVALDETAILS_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSQUOTATIONAPPROVALDETAILS_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSQUOTATIONAPPROVALDETAILS_REPORT]
(
@ACTION NVARCHAR(500)=NULL,
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@SHOPID NVARCHAR(MAX)=NULL,
@USERID INT=0,
@DOCUMENT_NUMBER nvarchar(200)=null,
@QUOTATION_NUMBER nvarchar(500)=null,
@Remarks nvarchar(500)=null,
@RETURN_VALUE NVARCHAR(50) =NULL OUTPUT
) WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Sanchita Saha ON 31/08/2022
Module	   : Eurobond Customization - Approve/Reject Quotation. Refer: 25177
1.0		Sanchita		V2.0.37		22-11-2022		A hiphen is required in the Suffix of Quotation number creation for Quotation Approval Module. refer: 25465
2.0		Sanchita		V2.0.38		18-01-2022		New table "FSMAPIQUOTATIONMULTICONTACT" to be updated at the time of Approve or Reject. Refer: 
3.0		Debashis		V2.0.38		23-01-2023		Multiple Contact person name to be shown in the Quotation report.Refer: 0025584
4.0		Sanchita		V2.0.38		24-01-2023		For comma seperated Email Id, Contact Person and Contact No, a space added after comma 
													so that wrapping can take place for logn strings. Refer:
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX)

	IF(@ACTION = 'LISTING')
	BEGIN
		IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
			DROP TABLE #EMPLOYEE_LIST
		CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)

		IF @EMPID <> ''
			BEGIN
				SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
				SET @SqlStrTable=''
				SET @SqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
				EXEC SP_EXECUTESQL @SqlStrTable
			END

		IF OBJECT_ID('tempdb..#SHOP_LIST') IS NOT NULL
			DROP TABLE #SHOP_LIST
		CREATE TABLE #SHOP_LIST (Shop_Code NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)

		IF @SHOPID <> ''
			BEGIN
				SET @SHOPID = REPLACE(''''+@SHOPID+'''',',',''',''')
				SET @SqlStrTable=''
				SET @SqlStrTable='INSERT INTO #SHOP_LIST SELECT Shop_Code FROM tbl_Master_shop WHERE Shop_Code IN('+@SHOPID+')'
				EXEC SP_EXECUTESQL @SqlStrTable
			END

		IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
			BEGIN
				DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@Userid)		
				CREATE TABLE #EMPHRS
				(
				EMPCODE VARCHAR(50),
				RPTTOEMPCODE VARCHAR(50)
				)

				CREATE TABLE #EMPHR_EDIT
				(
				EMPCODE VARCHAR(50),
				RPTTOEMPCODE VARCHAR(50)
				)
		
				INSERT INTO #EMPHRS
				SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 
				FROM tbl_trans_employeeCTC CTC LEFT JOIN tbl_master_employee TME on TME.emp_id= CTC.emp_reportTO WHERE emp_effectiveuntil IS NULL
		
				;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
				UNION ALL
				SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
				JOIN cte b ON a.RPTTOEMPCODE = b.EMPCODE
				) 
				INSERT INTO #EMPHR_EDIT
				SELECT EMPCODE,RPTTOEMPCODE FROM cte 
			END

		IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
			DROP TABLE #TEMPCONTACT
		CREATE TABLE #TEMPCONTACT
			(
				cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
				cnt_branchid INT,
				cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
				cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
				cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
				cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
				cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
			)
		CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

		IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
			BEGIN
				INSERT INTO #TEMPCONTACT
				SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT
				INNER JOIN #EMPHR_EDIT ON cnt_internalId=EMPCODE WHERE cnt_contactType IN('EM')
			END
		ELSE
			BEGIN
				INSERT INTO #TEMPCONTACT
				SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')
			END

		IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSQUOTATIONAPPROVALDETAILS_REPORT') AND TYPE IN (N'U'))
			BEGIN
				CREATE TABLE FTSQUOTATIONAPPROVALDETAILS_REPORT
				(
				  USERID INT,
				  SEQ BIGINT,
				  SEQ_DOCUMENT_NUMBER_DUPL BIGINT,
				  BRANCH_ID BIGINT,
				  BRANCHDESC NVARCHAR(300),
				  EMPUSERID BIGINT,
				  EMPCODE NVARCHAR(100) NULL,
				  EMPID NVARCHAR(100) NULL,
				  EMPNAME NVARCHAR(300) NULL,
				  STATEID INT,
				  STATE NVARCHAR(50) NULL,
				  DEG_ID INT,
				  DESIGNATION NVARCHAR(50) NULL,
				  DATEOFJOINING NVARCHAR(10),
				  LOGINID NVARCHAR(50) NULL,
				  REPORTTOID NVARCHAR(300) NULL,
				  REPORTTOUID NVARCHAR(100),
				  REPORTTO NVARCHAR(300) NULL,
				  RPTTODESG NVARCHAR(50) NULL,
				  --QUOTATIONNO NVARCHAR(200) NULL,
				  DOCUMENT_NUMBER NVARCHAR(200) NULL,
				  QUOTATIONDATE NVARCHAR(10) NULL,
				  QUOTATIONDATE_DT datetime NULL,
				  QUOTATIONDATEORDBY NVARCHAR(10) NULL,
				  SHOP_CODE NVARCHAR(100) NULL,
				  CUSTNAME NVARCHAR(3000) NULL,
				  CUSTADDRESS NVARCHAR(MAX) NULL,
				  --Rev 3.0
				  --CUSTEMAIL NVARCHAR(300) NULL,
				  --CONTACTPERSON NVARCHAR(300) NULL,
				  --CONTACTNO NVARCHAR(100) NULL,
				  CUSTEMAIL NVARCHAR(500) NULL,
				  CONTACTPERSON NVARCHAR(500) NULL,
				  CONTACTNO NVARCHAR(500) NULL,
				  --End of Rev 3.0
				  CUSTEMAIL NVARCHAR(300) NULL,
				  CONTACTPERSON NVARCHAR(300) NULL,
				  CONTACTNO NVARCHAR(100) NULL,
				  PROD_ID NVARCHAR(max) NULL,
				  PRODUCT_NAME NVARCHAR(max) NULL,
				  RATE_SQFT NVARCHAR(max) NULL,
				  SALESPERSON NVARCHAR(300) NULL,
				  PROJECT_NAME NVARCHAR(600) NULL,
				  REMARKS NVARCHAR(1000) null,
				  QUOTATION_STATUS nvarchar(100) NULL
				)
				CREATE NONCLUSTERED INDEX IX1 ON FTSQUOTATIONAPPROVALDETAILS_REPORT (SEQ)
			END
		DELETE FROM FTSQUOTATIONAPPROVALDETAILS_REPORT WHERE USERID=@USERID

		SET @SqlStr=''
		SET @SqlStr='INSERT INTO FTSQUOTATIONAPPROVALDETAILS_REPORT(USERID,SEQ,SEQ_DOCUMENT_NUMBER_DUPL,BRANCH_ID,BRANCHDESC,EMPUSERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,LOGINID,REPORTTOID,REPORTTOUID,'
		SET @SqlStr+='REPORTTO,RPTTODESG,DOCUMENT_NUMBER,QUOTATIONDATE,QUOTATIONDATE_DT,QUOTATIONDATEORDBY,SHOP_CODE,CUSTNAME,CUSTADDRESS,CUSTEMAIL,CONTACTPERSON,CONTACTNO,PROD_ID,PRODUCT_NAME,RATE_SQFT,SALESPERSON,'
		SET @SqlStr+='PROJECT_NAME,REMARKS,QUOTATION_STATUS) '
		SET @SqlStr+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120)) AS SEQ, ROW_NUMBER() OVER(PARTITION BY QH.DOCUMENT_NUMBER ORDER BY CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120)) AS SEQ_DOCUMENT_NUMBER_DUPL, '
		SET @SqlStr+='BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,USR.USER_ID AS EMPUSERID,CNT.cnt_internalId AS EMPCODE,'
		SET @SqlStr+='EMP.emp_uniqueCode AS EMPID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
		SET @SqlStr+='ISNULL(ST.ID,0) AS STATEID,ISNULL(ST.state,''State Undefined'') AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
		SET @SqlStr+='USR.user_loginId AS LOGINID,RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,QH.DOCUMENT_NUMBER,CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,105) AS QUOTATIONDATE,QH.QUOTATIONSAVE_DATE as QUOTATIONDATE_DT, '
		--Rev 3.0
		--SET @SqlStr+='CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120) AS QUOTATIONDATEORDBY,MS.SHOP_CODE,MS.Shop_Name AS CUSTNAME,MS.Address AS CUSTADDRESS,MS.Shop_Owner_Email AS CUSTEMAIL,MS.Shop_Owner AS CONTACTPERSON,'
		---- Rev Sanchita
		----SET @SqlStr+='MS.Shop_Owner_Contact AS CONTACTNO,QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME '
		--SET @SqlStr+='MS.Shop_Owner_Contact AS CONTACTNO,QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME,QH.REMARKS,QH.QUOTATION_STATUS '
		-- Rev 4.0 (SELECT '','' changed to SELECT '', '' )
		SET @SqlStr+='CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120) AS QUOTATIONDATEORDBY,MS.SHOP_CODE,MS.Shop_Name AS CUSTNAME,MS.Address AS CUSTADDRESS,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '', '' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_EMAIL)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CUSTEMAIL,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '', '' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_PERSON)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CONTACTPERSON,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '', '' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_NUMBER)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CONTACTNO,'
		SET @SqlStr+='QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME,QH.REMARKS,QH.QUOTATION_STATUS '
		--End of Rev 3.0
		SET @SqlStr+='CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120) AS QUOTATIONDATEORDBY,MS.SHOP_CODE,MS.Shop_Name AS CUSTNAME,MS.Address AS CUSTADDRESS,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_EMAIL)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CUSTEMAIL,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_PERSON)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CONTACTPERSON,'
		SET @SqlStr+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(MQC.QUOTATION_CONTACT_NUMBER)) FROM FSMAPIQUOTATIONMULTICONTACT AS MQC '
		SET @SqlStr+='WHERE MQC.USER_ID=USR.USER_ID AND MQC.USER_ID=QH.USER_ID AND QH.DOCUMENT_NUMBER=MQC.DOCUMENT_NUMBER FOR XML PATH('''')), 1, 1, ''''),'''')) AS CONTACTNO,'
		SET @SqlStr+='QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME,QH.REMARKS,QH.QUOTATION_STATUS '
		--End of Rev 3.0
		SET @SqlStr+='CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120) AS QUOTATIONDATEORDBY,MS.SHOP_CODE,MS.Shop_Name AS CUSTNAME,MS.Address AS CUSTADDRESS,MS.Shop_Owner_Email AS CUSTEMAIL,MS.Shop_Owner AS CONTACTPERSON,'
		-- Rev Sanchita
		--SET @SqlStr+='MS.Shop_Owner_Contact AS CONTACTNO,QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME '
		SET @SqlStr+='MS.Shop_Owner_Contact AS CONTACTNO,QD.PROD_ID,QD.PRODUCT_NAME,QD.RATE_SQFT,MUSR.user_name AS SALESPERSON,QH.PROJECT_NAME,QH.REMARKS,QH.QUOTATION_STATUS '
		-- End of Rev Sanchita
		SET @SqlStr+='FROM tbl_master_employee EMP '
		SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
		SET @SqlStr+='INNER JOIN tbl_master_branch BR ON CNT.cnt_branchid=BR.branch_id '
		SET @SqlStr+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
		SET @SqlStr+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
		SET @SqlStr+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
		SET @SqlStr+='INNER JOIN ( '
		SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
		SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
		SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
		SET @SqlStr+='INNER JOIN FSMAPIQUOTATIONHEAD QH ON USR.user_id=QH.USER_ID '
		SET @SqlStr+='INNER JOIN FSMAPIQUOTATIONDETAILS QD ON QH.DOCUMENT_NUMBER=QD.DOCUMENT_NUMBER '
		SET @SqlStr+='INNER JOIN tbl_Master_shop MS ON QH.SHOP_ID=MS.Shop_Code '
		SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
		SET @SqlStr+='DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP '
		SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
		SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
		SET @SqlStr+='INNER JOIN ('
		SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
		SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
		SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
		SET @SqlStr+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
		SET @SqlStr+='LEFT OUTER JOIN tbl_master_user MUSR ON MUSR.user_id=QH.SALESMAN_USER_ID AND USR.user_inactive=''N'' '
		SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),QH.QUOTATIONSAVE_DATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120)  '
		IF @EMPID<>''
			SET @SqlStr+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
		IF @SHOPID<>''
			SET @SqlStr+='AND EXISTS (SELECT Branch_Id FROM #SHOP_LIST AS SL WHERE SL.Shop_Code=MS.Shop_Code) '
		--SELECT @SqlStr
		EXEC SP_EXECUTESQL @SqlStr

		update R set 
			SEQ=R.SEQ_New ,
			PROD_ID=(ISNULL((SELECT  LTRIM(STUFF(((SELECT DISTINCT ', ' + convert(varchar(10),  PROD_ID) FROM 	
				(SELECT prod_id FROM FTSQUOTATIONAPPROVALDETAILS_REPORT where DOCUMENT_NUMBER=R.DOCUMENT_NUMBER ) AS desnnm FOR XML PATH(''))),1,2,' '))),'') ),
			--PRODUCT_NAME = ( ISNULL((SELECT  LTRIM(STUFF(((SELECT DISTINCT ', ' + PRODUCT_NAME FROM 	
			--(SELECT PRODUCT_NAME FROM FTSQUOTATIONAPPROVALDETAILS_REPORT where DOCUMENT_NUMBER=R.DOCUMENT_NUMBER ) AS desnnm FOR XML PATH(''))),1,2,' '))),'') ),
			PRODUCT_NAME = REPLACE( 
									( ISNULL((SELECT  LTRIM(STUFF(((SELECT DISTINCT ', ' + PRODUCT_NAME FROM 	
										(SELECT (CASE WHEN CHARINDEX('(',PRODUCT_NAME)-1>0 THEN LEFT(PRODUCT_NAME,(CHARINDEX('(',PRODUCT_NAME)-1)) ELSE PRODUCT_NAME END)  PRODUCT_NAME
									FROM FTSQUOTATIONAPPROVALDETAILS_REPORT where DOCUMENT_NUMBER=R.DOCUMENT_NUMBER ) AS desnnm FOR XML PATH(''))),1,2,' '))),'') ) 
							, 'amp;', ''),
			RATE_SQFT = ( ISNULL((SELECT  LTRIM(STUFF(((SELECT DISTINCT ', ' + convert(varchar(10),  RATE_SQFT) FROM 	
			(SELECT RATE_SQFT FROM FTSQUOTATIONAPPROVALDETAILS_REPORT where DOCUMENT_NUMBER=R.DOCUMENT_NUMBER ) AS desnnm FOR XML PATH(''))),1,2,' '))),'') )
		from 
		( select ROW_NUMBER() OVER (ORDER BY QUOTATIONDATE_DT) AS SEQ_New, * from FTSQUOTATIONAPPROVALDETAILS_REPORT where SEQ_DOCUMENT_NUMBER_DUPL=1 ) R

		delete from FTSQUOTATIONAPPROVALDETAILS_REPORT where SEQ_DOCUMENT_NUMBER_DUPL<>1
		
		IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
			BEGIN
				DROP TABLE #EMPHR_EDIT
				DROP TABLE #EMPHRS
			END
		DROP TABLE #EMPLOYEE_LIST
		DROP TABLE #SHOP_LIST
		DROP TABLE #TEMPCONTACT
	END

	IF(@ACTION = 'APPROVE' or @ACTION='REJECT')
	BEGIN
		BEGIN TRY
		BEGIN TRANSACTION	
			
			if @ACTION = 'APPROVE' 
			begin
				-- Rev 1.0
				--set @QUOTATION_NUMBER = 'EP/'+ SUBSTRING(CONVERT(nvarchar(6),getdate(), 112),5,2) +'/'+@QUOTATION_NUMBER+'/'+Right(Year(getDate()),2)+Right(Year(getDate())+ 1,2)
				set @QUOTATION_NUMBER = 'EP/'+ SUBSTRING(CONVERT(nvarchar(6),getdate(), 112),5,2) +'/'+@QUOTATION_NUMBER+'/'+Right(Year(getDate()),2)+'-'+Right(Year(getDate())+ 1,2)
				-- End of Rev 1.0

				update FSMAPIQUOTATIONHEAD set QUOTATION_STATUS='Approved', ApproveRemarks=@Remarks, QUOTATION_NUMBER=@QUOTATION_NUMBER, ApproveRejectUser=@USERID, ApproveRejectDateTime=getdate()
				where DOCUMENT_NUMBER=@DOCUMENT_NUMBER

				update FSMAPIQUOTATIONDETAILS set QUOTATION_NUMBER=@QUOTATION_NUMBER where DOCUMENT_NUMBER=@DOCUMENT_NUMBER

				-- Rev 2.0
				UPDATE FSMAPIQUOTATIONMULTICONTACT SET QUOTATION_NUMBER=@QUOTATION_NUMBER where DOCUMENT_NUMBER=@DOCUMENT_NUMBER
				-- End of Rev 2.0

				COMMIT TRANSACTION
				Set @RETURN_VALUE = @QUOTATION_NUMBER
			end
			else
			begin
				update FSMAPIQUOTATIONHEAD set QUOTATION_STATUS='Rejected', ApproveRemarks=@Remarks, QUOTATION_NUMBER='', ApproveRejectUser=@USERID, ApproveRejectDateTime=getdate()
				where DOCUMENT_NUMBER=@DOCUMENT_NUMBER

				update FSMAPIQUOTATIONDETAILS set QUOTATION_NUMBER=@QUOTATION_NUMBER where DOCUMENT_NUMBER=@DOCUMENT_NUMBER

				-- Rev 2.0
				UPDATE FSMAPIQUOTATIONMULTICONTACT SET QUOTATION_NUMBER='' where DOCUMENT_NUMBER=@DOCUMENT_NUMBER
				-- End of Rev 2.0

				COMMIT TRANSACTION
				Set @RETURN_VALUE = 'Rejected'
			end
		
		END TRY

		BEGIN CATCH

		ROLLBACK TRANSACTION
			
			--Set @RETURNMESSAGE= ERROR_MESSAGE();
			Set @RETURN_VALUE='-10'
	
		END CATCH
		
	end

	IF(@ACTION = 'GETAPPROVALDETAILS')
	BEGIN
		SELECT top 1 F.QUOTATION_STATUS,F.ApproveRemarks,F.QUOTATION_NUMBER, U.user_loginId FROM FSMAPIQUOTATIONHEAD F 
		inner join tbl_master_user U ON F.CREATED_BY=U.user_id
		--left outer join tbl_master_phonefax PH on PH.phf_cntId=U.user_contactid
		where DOCUMENT_NUMBER=@DOCUMENT_NUMBER
	END


	SET NOCOUNT OFF
END
GO