--EXEC PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH '2022-04-01','2022-04-30','','','EMG0000001',1,'Summary','',378
--EXEC PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH '2022-04-01','2022-04-30','','','',1,'Summary','',11706
--EXEC PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH '2022-04-05','2022-04-05','15','','EMS0000071','','Details'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSHORIZONTALEMPLOYEEPERFORMANCESUMDET_FETCH]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@SHOPTYPEID NVARCHAR(MAX)=NULL,
@REPORTTYPE NVARCHAR(20)=NULL,
@VISITTYPE NVARCHAR(50)=NULL,
@USERID INT=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder On 09/05/2022
Module	   : Horizontal Performance Summary & Detail.Refer: 0024858
1.0		v2.0.29		Debashis	11/05/2022		Userwise hierarchy setting required.Refer: 0024880
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@sqlStrTable NVARCHAR(MAX)

	IF OBJECT_ID('tempdb..#STATEID_LIST') IS NOT NULL
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable='INSERT INTO #STATEID_LIST SELECT id FROM tbl_master_state WHERE id IN('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END
	ELSE IF @STATEID=''
		BEGIN
			IF EXISTS (SELECT * FROM FTS_EMPSTATEMAPPING WHERE USER_ID=@USERID AND STATE_ID=0)
				BEGIN
					INSERT INTO #STATEID_LIST(State_Id) 
					SELECT id FROM tbl_master_state 
					ORDER BY state
				END
			ELSE
				BEGIN
					INSERT INTO #STATEID_LIST(State_Id) 
					SELECT STAT.id FROM tbl_master_state STAT 
					INNER JOIN FTS_EMPSTATEMAPPING MAP ON MAP.STATE_ID=STAT.id 
					WHERE USER_ID=@USERID ORDER BY STAT.state
				END
		END
	
	IF OBJECT_ID('tempdb..#DESIGNATION_LIST') IS NOT NULL
		DROP TABLE #DESIGNATION_LIST
	CREATE TABLE #DESIGNATION_LIST (deg_id INT)
	CREATE NONCLUSTERED INDEX IX2 ON #DESIGNATION_LIST (deg_id ASC)
	IF @DESIGNID <> ''
		BEGIN
			SET @DESIGNID=REPLACE(@DESIGNID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable='INSERT INTO #DESIGNATION_LIST SELECT deg_id from tbl_master_designation where deg_id in('+@DESIGNID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @sqlStrTable=''
			SET @sqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId from tbl_master_employee where emp_contactId in('+@EMPID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	--Rev 1.0
	IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DECLARE @empcodes VARCHAR(50)=(SELECT user_contactId FROM Tbl_master_user WHERE user_id=@USERID)		
			CREATE TABLE #EMPHRS
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)

			CREATE TABLE #EMPHR_EDIT
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)
		
			INSERT INTO #EMPHRS
			SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC LEFT JOIN tbl_master_employee TME ON TME.emp_id= CTC.emp_reportTO WHERE emp_effectiveuntil IS NULL
		
			;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
			UNION ALL
			SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
			join cte b ON a.RPTTOEMPCODE = b.EMPCODE
			) 
			INSERT INTO #EMPHR_EDIT
			SELECT EMPCODE,RPTTOEMPCODE FROM cte 
		END
	--End of Rev 1.0

	IF @REPORTTYPE='Summary'
		BEGIN
			IF OBJECT_ID('tempdb..#TMPATTENLOGINLOGOUT') IS NOT NULL
				DROP TABLE #TMPATTENLOGINLOGOUT

			CREATE TABLE #TMPATTENLOGINLOGOUT(ID BIGINT,USER_ID BIGINT,Login_datetime DATETIME,Logout_datetime DATETIME,Work_Desc VARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS,Work_datetime DATETIME,
			Isonleave VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS,WrkActvtyDescription VARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS)
			CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINLOGOUT(ID,USER_ID,Login_datetime,Logout_datetime,Isonleave)

			SET @Strsql=''
			SET @Strsql='INSERT INTO #TMPATTENLOGINLOGOUT(ID,USER_ID,Login_datetime,Logout_datetime,Work_Desc,Work_datetime,Isonleave,WrkActvtyDescription) '
			SET @Strsql+='SELECT UATTEN.Id,UATTEN.User_Id,UATTEN.Login_datetime,UATTEN.Logout_datetime,UATTEN.Work_Desc,UATTEN.Work_datetime,UATTEN.Isonleave,WRKACT.WrkActvtyDescription '
			SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout UATTEN '
			SET @Strsql+='INNER JOIN tbl_master_user MUSR ON MUSR.USER_ID=UATTEN.USER_ID AND MUSR.user_inactive=''N'' '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=MUSR.user_contactId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_attendance_worktype ATTENWRKTYP ON ATTENWRKTYP.UserID=UATTEN.User_Id AND UATTEN.Id=ATTENWRKTYP.attendanceid '
			SET @Strsql+='INNER JOIN tbl_FTS_WorkActivityList WRKACT ON WRKACT.WorkActivityID=ATTENWRKTYP.worktypeID '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '

			--SELECT @Strsql
			EXEC SP_EXECUTESQL @Strsql

			IF OBJECT_ID('tempdb..#TMPATTENLOGINOUT') IS NOT NULL
				DROP TABLE #TMPATTENLOGINOUT

			CREATE TABLE #TMPATTENLOGINOUT(USERID BIGINT,LOGGEDIN NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGEDOUT NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,ACTINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,Login_datetime NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ACTWORKTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ACTGRACEINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ALTINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ALTWORKTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ALTGRACEINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ATTEN_STATUS NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGINDATE NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS)
			CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINOUT(USERID,cnt_internalId,Login_datetime)

			SET @Strsql=''
			SET @Strsql='INSERT INTO #TMPATTENLOGINOUT(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,ACTINTIME,Login_datetime,ACTWORKTIME,ACTGRACEINTIME,ALTINTIME,ALTWORKTIME,ALTGRACEINTIME,ATTEN_STATUS,LOGINDATE) '
			SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTINTIME AS TIME),100)) AS ACTINTIME,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,MAX(EMPWHD.ACTWORKTIME) AS ACTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTGRACEINTIME AS TIME),100)) AS ACTGRACEINTIME,MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTINTIME AS TIME),100)) AS ALTINTIME,MAX(EMPWHD.ALTWORKTIME) AS ALTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTGRACEINTIME AS TIME),100)) AS ALTGRACEINTIME,CASE WHEN Isonleave=''false'' THEN ''At Work'' ELSE ''On Leave'' END AS ATTEN_STATUS,'
			SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE '
			SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMPCTC.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN tbl_EmpWorkingHours EMPWH ON EMPWH.Id=EMPCTC.emp_workinghours '
			SET @Strsql+='INNER JOIN('
			SET @Strsql+='SELECT DISTINCT hourId,BeginTime AS ACTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ACTGRACEINTIME,'
			SET @Strsql+='ALT_BeginTime AS ALTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ALTGRACEINTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ACTWORKTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ALTWORKTIME '
			SET @Strsql+='FROM tbl_EmpWorkingHoursDetails) EMPWHD ON EMPWHD.hourId=EMPWH.Id '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
			SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '
			SET @Strsql+='UNION ALL '
			SET @Strsql+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTINTIME AS TIME),100)) AS ACTINTIME,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,MAX(EMPWHD.ACTWORKTIME) AS ACTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTGRACEINTIME AS TIME),100)) AS ACTGRACEINTIME,MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTINTIME AS TIME),100)) AS ALTINTIME,MAX(EMPWHD.ALTWORKTIME) AS ALTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTGRACEINTIME AS TIME),100)) AS ALTGRACEINTIME,CASE WHEN Isonleave=''false'' THEN ''At Work'' ELSE ''On Leave'' END AS ATTEN_STATUS,'
			SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE '
			SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMPCTC.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN tbl_EmpWorkingHours EMPWH ON EMPWH.Id=EMPCTC.emp_workinghours '
			SET @Strsql+='INNER JOIN('
			SET @Strsql+='SELECT DISTINCT hourId,BeginTime AS ACTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ACTGRACEINTIME,'
			SET @Strsql+='ALT_BeginTime AS ALTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ALTGRACEINTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ACTWORKTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ALTWORKTIME '
			SET @Strsql+='FROM tbl_EmpWorkingHoursDetails) EMPWHD ON EMPWHD.hourId=EMPWH.Id '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
			SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '

			--SELECT @Strsql
			EXEC SP_EXECUTESQL @Strsql

			IF OBJECT_ID('tempdb..#TMPLEAVELOGINOUT') IS NOT NULL
				DROP TABLE #TMPLEAVELOGINOUT

			CREATE TABLE #TMPLEAVELOGINOUT(USERID BIGINT,LOGGEDIN NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGEDOUT NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,ACTINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,Login_datetime NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ACTWORKTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ACTGRACEINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ALTINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ALTWORKTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
			ALTGRACEINTIME NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,ATTEN_STATUS NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,LOGINDATE NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS)
			CREATE NONCLUSTERED INDEX IX1 ON #TMPLEAVELOGINOUT(USERID,cnt_internalId,Login_datetime)

			SET @Strsql=''
			SET @Strsql='INSERT INTO #TMPLEAVELOGINOUT(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,ACTINTIME,Login_datetime,ACTWORKTIME,ACTGRACEINTIME,ALTINTIME,ALTWORKTIME,ALTGRACEINTIME,ATTEN_STATUS,LOGINDATE) '
			SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTINTIME AS TIME),100)) AS ACTINTIME,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,MAX(EMPWHD.ACTWORKTIME) AS ACTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTGRACEINTIME AS TIME),100)) AS ACTGRACEINTIME,MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTINTIME AS TIME),100)) AS ALTINTIME,MAX(EMPWHD.ALTWORKTIME) AS ALTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTGRACEINTIME AS TIME),100)) AS ALTGRACEINTIME,CASE WHEN Isonleave=''false'' THEN ''At Work'' ELSE ''On Leave'' END AS ATTEN_STATUS,'
			SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE '
			SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMPCTC.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN tbl_EmpWorkingHours EMPWH ON EMPWH.Id=EMPCTC.emp_workinghours '
			SET @Strsql+='INNER JOIN('
			SET @Strsql+='SELECT DISTINCT hourId,BeginTime AS ACTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ACTGRACEINTIME,'
			SET @Strsql+='ALT_BeginTime AS ALTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ALTGRACEINTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ACTWORKTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ALTWORKTIME '
			SET @Strsql+='FROM tbl_EmpWorkingHoursDetails) EMPWHD ON EMPWHD.hourId=EMPWH.Id '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''true'' '
			SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '
			SET @Strsql+='UNION ALL '
			SET @Strsql+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTINTIME AS TIME),100)) AS ACTINTIME,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,MAX(EMPWHD.ACTWORKTIME) AS ACTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ACTGRACEINTIME AS TIME),100)) AS ACTGRACEINTIME,MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTINTIME AS TIME),100)) AS ALTINTIME,MAX(EMPWHD.ALTWORKTIME) AS ALTWORKTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(15),CAST(EMPWHD.ALTGRACEINTIME AS TIME),100)) AS ALTGRACEINTIME,CASE WHEN Isonleave=''false'' THEN ''At Work'' ELSE ''On Leave'' END AS ATTEN_STATUS,'
			SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGINDATE '
			SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMPCTC.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN tbl_EmpWorkingHours EMPWH ON EMPWH.Id=EMPCTC.emp_workinghours '
			SET @Strsql+='INNER JOIN('
			SET @Strsql+='SELECT DISTINCT hourId,BeginTime AS ACTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ACTGRACEINTIME,'
			SET @Strsql+='ALT_BeginTime AS ALTINTIME,CASE WHEN (CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace))>0 '
			SET @Strsql+='THEN RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' '
			SET @Strsql+='+RIGHT(''0'' + CAST(CAST((CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ALT_BeginTime),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ALT_BeginTime),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) + (ALT_Grace)) AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''0'' END AS ALTGRACEINTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ACTWORKTIME,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_EndTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_EndTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(ALT_BeginTime,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(ALT_BeginTime,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS ALTWORKTIME '
			SET @Strsql+='FROM tbl_EmpWorkingHoursDetails) EMPWHD ON EMPWHD.hourId=EMPWH.Id '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''true'' '
			SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '

			--SELECT @Strsql
			EXEC SP_EXECUTESQL @Strsql
		END

	SET @Strsql=''
	IF @REPORTTYPE='Summary'
		BEGIN
			SET @Strsql='SELECT ROW_NUMBER() OVER(ORDER BY LOGINDATE DESC) AS SEQ,User_Id AS USERID,LOGIN_DATETIME,LOGINDATE,CONTACTNO,EMPID,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,'
			SET @Strsql+='DATEOFJOINING,OFFICE_ADDRESS,REPORTTO,RPTTODESG,ATTEN_STATUS,WORK_LEAVE_TYPE,REMARKS,ACTINTIME,ACTGRACEINTIME,ALTINTIME,ALTGRACEINTIME,APPLOGGEDIN,FIRSTCALLTIME,LASTCALLTIME,APPLOGEDOUT,'
			SET @Strsql+='ATTENDANCETYPE,ATTENDANCESTATUS,'
			SET @Strsql+='CASE WHEN WORKINGDURATION>0 THEN RIGHT(''0'' + CAST(CAST(WORKINGDURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(WORKINGDURATION AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''00:00'' END AS WORKINGDURATION,'
			SET @Strsql+='CASE WHEN UNDERTIME>0 THEN RIGHT(''0'' + CAST(CAST(UNDERTIME AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(UNDERTIME AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''00:00'' END AS UNDERTIME,'
			SET @Strsql+='CASE WHEN GPS_INACTIVE_DURATION>0 THEN RIGHT(''0'' + CAST(CAST(GPS_INACTIVE_DURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(GPS_INACTIVE_DURATION AS VARCHAR) % 60 AS VARCHAR),2) ELSE ''00:00'' END AS GPS_INACTIVE_DURATION,'
			SET @Strsql+='GPSINACTIVECNT,RIGHT(''0'' + CAST(CAST(IDEAL_TIME AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(IDEAL_TIME AS VARCHAR) % 60 AS VARCHAR),2) AS IDEAL_TIME,'	
			SET @Strsql+='IDEALTIME_CNT,NEWSHOP_VISITED,RE_VISITED,TOTMETTING,SHOPTYPEID,SHOPTYPENAME,SHOPVISITED '
			SET @Strsql+='FROM('
			SET @Strsql+='SELECT USR.User_Id,CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ISNULL(ST.ID,0) AS STATEID,'
			SET @Strsql+='ISNULL(ST.state,''State Undefined'') AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,USR.user_loginId AS CONTACTNO,'
			SET @Strsql+='RPTTO.REPORTTO,RPTTO.RPTTODESG,ATTEN.LOGIN_DATETIME,ATTEN.LOGINDATE,ATTEN.LOGGEDIN AS APPLOGGEDIN,ATTEN.LOGEDOUT AS APPLOGEDOUT,'
			SET @Strsql+='ADDR.add_address1+'' ''+ISNULL(ADDR.add_address2,'''')+'' ''+ISNULL(ADDR.add_address3,'''') AS OFFICE_ADDRESS,EMP.emp_uniqueCode AS EMPID,ATTEN_STATUS,'			
			SET @Strsql+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(UATTEN.WrkActvtyDescription)) FROM #TMPATTENLOGINLOGOUT AS UATTEN '
			SET @Strsql+='WHERE UATTEN.USER_ID=USR.USER_ID AND UATTEN.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),UATTEN.Work_datetime,105) FOR XML PATH('''')), 1, 1, ''''),'''')) AS WORK_LEAVE_TYPE,'
			SET @Strsql+='REPLACE((SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(ISNULL(A.Work_Desc,''''))) FROM #TMPATTENLOGINLOGOUT AS A '
			SET @Strsql+='WHERE A.USER_ID=USR.USER_ID AND A.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),A.Work_datetime,105) FOR XML PATH('''')),1,1,''''),'''')),'','','''') AS REMARKS,'			
			SET @Strsql+='REPLACE(REPLACE(ATTEN.ACTINTIME,''AM'','' AM''),''PM'','' PM'') AS ACTINTIME,'
			SET @Strsql+='REPLACE(REPLACE(ATTEN.ACTGRACEINTIME,''AM'','' AM''),''PM'','' PM'') AS ACTGRACEINTIME,REPLACE(REPLACE(ATTEN.ALTINTIME,''AM'','' AM''),''PM'','' PM'') AS ALTINTIME,'
			SET @Strsql+='REPLACE(REPLACE(ATTEN.ALTGRACEINTIME,''AM'','' AM''),''PM'','' PM'') AS ALTGRACEINTIME,SHOPACT.FIRSTCALLTIME AS FIRSTCALLTIME,SHOPACT.LASTCALLTIME AS LASTCALLTIME,LOCALOUTST.ATTENDANCETYPE,'
			SET @Strsql+='CASE WHEN LOCALOUTST.ATTENDANCETYPE=''Local'' THEN (CASE WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)=CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Ontime'' '
			SET @Strsql+='WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)>CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Before Time'' '
			SET @Strsql+='WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ACTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)<CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Late'' END) '
			SET @Strsql+='WHEN LOCALOUTST.ATTENDANCETYPE=''Outstation'' THEN (CASE WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)=CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Ontime'' '
			SET @Strsql+='WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)>CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Before Time'' '
			SET @Strsql+='WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.ALTGRACEINTIME),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)<CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 60) AS FLOAT) + '
			SET @Strsql+='CAST(DATEPART(MINUTE,ISNULL((ATTEN.LOGGEDIN),''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) THEN ''Late'' END) ELSE NULL END AS ATTENDANCESTATUS,'
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS WORKINGDURATION,'
			SET @Strsql+='CASE WHEN LOCALOUTST.ATTENDANCETYPE=''Local'' THEN '
			SET @Strsql+='(CASE WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)>0 THEN '
			SET @Strsql+='ATTEN.ACTWORKTIME-(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)) ELSE '
			SET @Strsql+='ATTEN.ACTWORKTIME-(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(''23:59:00'',''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(''23:59:00'',''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)) END) '
			SET @Strsql+='WHEN LOCALOUTST.ATTENDANCETYPE=''Outstation'' THEN '
			SET @Strsql+='(CASE WHEN CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)>0 THEN '
			SET @Strsql+='ATTEN.ALTWORKTIME-(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.LASTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)) ELSE '
			SET @Strsql+='ATTEN.ALTWORKTIME-(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(''23:59:00'',''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(''23:59:00'',''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
			SET @Strsql+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SHOPACT.FIRSTCALLTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)) END) END AS UNDERTIME,'
			SET @Strsql+='GPSSM.GPS_Inactive_duration,ISNULL(GPSSM.GPSINACTIVECNT,0) AS GPSINACTIVECNT,IDEALLOACTION.IDEAL_TIME,(IDEALLOACTION.IDEAL_TIME/30) AS IDEALTIME_CNT,'
			SET @Strsql+='ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0) AS TOTMETTING,ISNULL(SHOPACT.NEWSHOP_VISITED,0) AS NEWSHOP_VISITED,ISNULL(SHOPACT.RE_VISITED,0) AS RE_VISITED,'
			SET @Strsql+='SHPTYPE.SHOPTYPEID,SHPTYPE.SHOPTYPENAME,SHPTYPE.SHOPVISITED '
			SET @Strsql+='FROM tbl_master_employee EMP '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
			SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
			IF @STATEID=''
				SET @Strsql+='AND EXISTS (SELECT State_Id FROM #STATEID_LIST AS STAT WHERE STAT.State_Id=ST.id) '
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
			SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
			SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
			SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL ) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,MAX(ACTINTIME) AS ACTINTIME,MAX(ACTGRACEINTIME) AS ACTGRACEINTIME,MAX(ALTINTIME) AS ALTINTIME,'
			SET @Strsql+='MAX(ALTGRACEINTIME) AS ALTGRACEINTIME,MAX(ACTWORKTIME) AS ACTWORKTIME,MAX(ALTWORKTIME) AS ALTWORKTIME,ATTEN_STATUS,LOGINDATE FROM('
			SET @Strsql+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,ACTINTIME,Login_datetime,ACTWORKTIME,ACTGRACEINTIME,ALTINTIME,ALTWORKTIME,ALTGRACEINTIME,ATTEN_STATUS,LOGINDATE FROM #TMPATTENLOGINOUT '
			SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,ATTEN_STATUS,LOGINDATE) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
			SET @Strsql+='LEFT OUTER JOIN ('
			SET @Strsql+='SELECT User_Id,cnt_internalId,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,MIN(CONVERT(VARCHAR(5),CAST(FCALLTIME AS TIME),108)) AS FIRSTCALLTIME,'
			SET @Strsql+='MAX(CONVERT(VARCHAR(5),CAST(LCALLTIME AS TIME),108)) AS LASTCALLTIME,CONVERT(NVARCHAR(10),VISITED_TIME,105) AS VISITED_TIME '
			SET @Strsql+='FROM('
			SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,CAST(SHOPACT.visited_time AS DATE) AS visited_time,'
			SET @Strsql+='MIN(visited_time) AS FCALLTIME,MAX(visited_time) AS LCALLTIME '
			SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 '
			SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CAST(SHOPACT.visited_time AS DATE) '
			SET @Strsql+='UNION ALL '
			SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,CAST(SHOPACT.visited_time AS DATE) AS visited_time,'
			SET @Strsql+='MIN(visited_time) AS FCALLTIME,MAX(visited_time) AS LCALLTIME '
			SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
			SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CAST(SHOPACT.visited_time AS DATE) '
			SET @Strsql+=') AA GROUP BY User_Id,cnt_internalId,CAST(VISITED_TIME AS DATE)) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME '
			--LOCAL/OUTSTATION
			SET @Strsql+='LEFT OUTER JOIN ('
			SET @Strsql+='SELECT User_Id,cnt_internalId,CONVERT(NVARCHAR(10),VISITED_TIME,105) AS VISITED_TIME,ATTENDANCETYPE FROM('
			SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,CASE WHEN IsOutStation=0 THEN ''Local'' ELSE ''Outstation'' END AS ATTENDANCETYPE,CAST(SHOPACT.visited_time AS DATE) AS visited_time '
			SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='WHERE IsFirstVisit=1 '
			SET @Strsql+='AND CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,IsOutStation,CAST(SHOPACT.visited_time AS DATE) '
			SET @Strsql+=') AA GROUP BY User_Id,cnt_internalId,ATTENDANCETYPE,CAST(VISITED_TIME AS DATE) '
			SET @Strsql+=') LOCALOUTST ON LOCALOUTST.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=LOCALOUTST.VISITED_TIME '
			SET @Strsql+='LEFT OUTER JOIN (SELECT GPS.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),GPS.GPsDate,105) AS GPsDate,COUNT(GPS.Gps_OffTime) AS GPSINACTIVECNT,'
			SET @Strsql+='CAST(ISNULL(CAST((SUM(DATEPART(HOUR,ISNULL(GPS.Duration,''00:00:00'')) * 60)) AS FLOAT) +CAST(SUM(DATEPART(MINUTE,ISNULL(GPS.Duration,''00:00:00'')) * 1) AS FLOAT),0) AS VARCHAR(100)) AS GPS_Inactive_duration '
			SET @Strsql+='FROM tbl_FTS_GPSSubmission GPS '
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=GPS.User_Id '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),GPS.GPsDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY GPS.User_Id,CNT.cnt_internalId,GPS.GPsDate) GPSSM ON GPSSM.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=GPSSM.GPsDate '
			SET @Strsql+='LEFT OUTER JOIN ('
			SET @Strsql+='SELECT user_id,SUM(IDEAL_TIME) AS IDEAL_TIME,CONVERT(NVARCHAR(10),start_ideal_date_time,105) AS start_ideal_date_time FROM('
			SET @Strsql+='SELECT user_id,CAST(start_ideal_date_time AS DATE) start_ideal_date_time,'	
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(end_ideal_date_time,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(end_ideal_date_time,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) - '
			SET @Strsql+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(start_ideal_date_time,''00:00:00'')) * 60) AS FLOAT) + CAST(DATEPART(MINUTE,ISNULL(start_ideal_date_time,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS IDEAL_TIME '
			SET @Strsql+='FROM FTS_Ideal_Loaction WHERE CONVERT(NVARCHAR(10),start_ideal_date_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+=') IDLE GROUP BY user_id,start_ideal_date_time) IDEALLOACTION ON IDEALLOACTION.user_id=USR.user_id AND ATTEN.Login_datetime=IDEALLOACTION.start_ideal_date_time '
			SET @Strsql+='INNER JOIN('
			SET @Strsql+='SELECT ST.shop_typeId AS SHOPTYPEID,ST.Name AS SHOPTYPENAME,MU.user_id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) AS VISITDATE,COUNT(SHOPACT.Shop_Id) AS SHOPVISITED '
			SET @Strsql+='FROM tbl_shoptype ST '
			SET @Strsql+='INNER JOIN tbl_Master_shop MS ON ST.TypeId=MS.type '
			SET @Strsql+='INNER JOIN tbl_master_user MU ON MS.Shop_CreateUser=MU.USER_ID AND MU.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON MU.user_contactId=CNT.cnt_internalId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_trans_shopActivitysubmit SHOPACT ON MU.user_id=SHOPACT.User_Id AND MS.Shop_Code=SHOPACT.Shop_Id '
			SET @Strsql+='WHERE ST.IsActive=1 AND SHOPACT.Is_Newshopadd IN(0,1) AND SHOPACT.ISMEETING=0 '
			SET @Strsql+='AND CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND ST.shop_typeId='+LTRIM(RTRIM(STR(@SHOPTYPEID)))+' '
			SET @Strsql+='GROUP BY ST.shop_typeId,ST.Name,MU.user_id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) '
			SET @Strsql+=') SHPTYPE ON SHPTYPE.cnt_internalId=CNT.cnt_internalId AND SHPTYPE.user_id=USR.user_id AND ATTEN.LOGINDATE=SHPTYPE.VISITDATE '
			SET @Strsql+='UNION ALL '
			SET @Strsql+='SELECT USR.User_Id,CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ISNULL(ST.ID,0) AS STATEID,'
			SET @Strsql+='ISNULL(ST.state,''State Undefined'') AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,USR.user_loginId AS CONTACTNO,'
			SET @Strsql+='RPTTO.REPORTTO,RPTTO.RPTTODESG,ATTEN.LOGIN_DATETIME,ATTEN.LOGINDATE,ATTEN.LOGGEDIN AS APPLOGGEDIN,ATTEN.LOGEDOUT AS APPLOGEDOUT,'
			SET @Strsql+='ADDR.add_address1+'' ''+ISNULL(ADDR.add_address2,'''')+'' ''+ISNULL(ADDR.add_address3,'''') AS OFFICE_ADDRESS,EMP.emp_uniqueCode AS EMPID,ATTEN_STATUS,'			
			SET @Strsql+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(UATTEN.WrkActvtyDescription)) FROM #TMPATTENLOGINLOGOUT AS UATTEN '
			SET @Strsql+='WHERE UATTEN.USER_ID=USR.USER_ID AND UATTEN.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),UATTEN.Work_datetime,105) FOR XML PATH('''')), 1, 1, ''''),'''')) AS WORK_LEAVE_TYPE,'			
			SET @Strsql+=''''' AS REMARKS,REPLACE(REPLACE(ATTEN.ACTINTIME,''AM'','' AM''),''PM'','' PM'') AS ACTINTIME,'
			SET @Strsql+='REPLACE(REPLACE(ATTEN.ACTGRACEINTIME,''AM'','' AM''),''PM'','' PM'') AS ACTGRACEINTIME,REPLACE(REPLACE(ATTEN.ALTINTIME,''AM'','' AM''),''PM'','' PM'') AS ALTINTIME,'
			SET @Strsql+='REPLACE(REPLACE(ATTEN.ALTGRACEINTIME,''AM'','' AM''),''PM'','' PM'') AS ALTGRACEINTIME,NULL AS FIRSTCALLTIME,NULL AS LASTCALLTIME,NULL AS ATTENDANCETYPE,''On Leave'' AS ATTENDANCESTATUS,'
			SET @Strsql+='NULL WORKINGDURATION,NULL AS UNDERTIME,NULL AS GPS_INACTIVE_DURATION,0 AS GPSINACTIVECNT,NULL AS IDEAL_TIME,0 AS IDEALTIME_CNT,0 AS TOTMETTING,0 AS NEWSHOP_VISITED,0 AS RE_VISITED,'
			SET @Strsql+='0 AS SHOPTYPEID,'''' AS SHOPTYPENAME,0 AS SHOPVISITED '
			SET @Strsql+='FROM tbl_master_employee EMP '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
			SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
			IF @STATEID=''
				SET @Strsql+='AND EXISTS (SELECT State_Id FROM #STATEID_LIST AS STAT WHERE STAT.State_Id=ST.id) '
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
			SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
			SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
			SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
			SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL ) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
			SET @Strsql+='INNER JOIN ( '
			SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,MAX(ACTINTIME) AS ACTINTIME,MAX(ACTGRACEINTIME) AS ACTGRACEINTIME,MAX(ALTINTIME) AS ALTINTIME,'
			SET @Strsql+='MAX(ALTGRACEINTIME) AS ALTGRACEINTIME,MAX(ACTWORKTIME) AS ACTWORKTIME,MAX(ALTWORKTIME) AS ALTWORKTIME,ATTEN_STATUS,LOGINDATE FROM('
			SET @Strsql+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,ACTINTIME,Login_datetime,ACTWORKTIME,ACTGRACEINTIME,ALTINTIME,ALTWORKTIME,ALTGRACEINTIME,ATTEN_STATUS,LOGINDATE FROM #TMPLEAVELOGINOUT '
			SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,ATTEN_STATUS,LOGINDATE) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
			SET @Strsql+=') AS DB '
			IF @STATEID<>'' AND @DESIGNID='' AND @EMPID=''
				SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID=''
				SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
			ELSE IF @STATEID='' AND @DESIGNID='' AND @EMPID<>''
				SET @Strsql+='WHERE EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
			ELSE IF @STATEID<>'' AND @DESIGNID='' AND @EMPID<>''
				BEGIN
					SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
					SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
				END
			ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID<>''
				BEGIN
					SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
					SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
				END
			ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID=''
				BEGIN
					SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
					SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
				END
			ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID<>''
				BEGIN
					SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
					SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
					SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
				END
		END
	ELSE IF @REPORTTYPE='Details'
		BEGIN
			SET @Strsql='SELECT ROW_NUMBER() OVER(ORDER BY CONVERT(NVARCHAR(10),SHOPACT.visited_time,108) DESC) AS SEQ,MU.USER_ID,CNT.CNT_INTERNALID,MS.Shop_Name AS CUSTNAME,MS.ADDRESS,'
			SET @Strsql+='MS.Shop_Owner_Contact AS MOBILENO,ST.NAME AS SHOPTYPE,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITDATE,CONVERT(NVARCHAR(10),SHOPACT.visited_time,108) AS VISITTIME,'
			SET @Strsql+='SHOPACT.spent_duration AS SPENTDURATION '
			SET @Strsql+='FROM tbl_shoptype ST '
			SET @Strsql+='INNER JOIN tbl_Master_shop MS ON ST.TypeId=MS.type '
			SET @Strsql+='INNER JOIN tbl_master_user MU ON MS.Shop_CreateUser=MU.USER_ID AND MU.user_inactive=''N'' '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON MU.user_contactId=CNT.cnt_internalId '
			--Rev 1.0
			IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
				SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
			--End of Rev 1.0
			SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
			SET @Strsql+='INNER JOIN tbl_master_state STAT ON STAT.id=ADDR.add_state '
			SET @Strsql+='INNER JOIN tbl_trans_shopActivitysubmit SHOPACT ON MU.user_id=SHOPACT.User_Id AND MS.Shop_Code=SHOPACT.Shop_Id '
			SET @Strsql+='WHERE ST.IsActive=1 AND SHOPACT.ISMEETING=0 '
			IF @VISITTYPE='NEWSHOP_VISITED'
				SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 '
			ELSE IF @VISITTYPE='RE_VISITED'
				SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 '
			SET @Strsql+='AND CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='AND EXISTS (SELECT State_Id FROM #STATEID_LIST AS ST WHERE ST.State_Id=STAT.id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
		END
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	DROP TABLE #DESIGNATION_LIST
	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TEMPCONTACT
	IF @REPORTTYPE='Summary'
		BEGIN
			DROP TABLE #TMPATTENLOGINLOGOUT
			DROP TABLE #TMPATTENLOGINOUT
			DROP TABLE #TMPLEAVELOGINOUT
		END
	--Rev 1.0
	IF ((SELECT IsHierarchyforHorizontalPerformanceReport FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DROP TABLE #EMPHR_EDIT
			DROP TABLE #EMPHRS
		END
	--End of Rev 1.0

	SET NOCOUNT OFF
END