--EXEC PRC_FTSLEADERBOARDPOINTSDETAILS_REPORT

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSLEADERBOARDPOINTSDETAILS_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSLEADERBOARDPOINTSDETAILS_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSLEADERBOARDPOINTSDETAILS_REPORT]
--WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 11/04/2024
Module	   : Schedular FOR Leaderboard Points.Row: 905 to 908 & Refer: 0027300
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL			
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT(cnt_internalId,cnt_branchid,cnt_UCC,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType)
	SELECT cnt_internalId,cnt_branchid,cnt_UCC,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType
	FROM TBL_MASTER_CONTACT WITH (NOLOCK)
	WHERE cnt_contactType IN('EM')

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSLEADERBOARDPOINTSDETAILS_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSLEADERBOARDPOINTSDETAILS_REPORT
			(
			  ACTIVITYMODE CHAR(1),
			  USERID INT,
			  BRANCH_ID BIGINT,
			  BRANCHDESC NVARCHAR(300),
			  EMPCODE NVARCHAR(100) NULL,
			  EMPID NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  STATEID INT,
			  STATENAME NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  DATEOFJOINING NVARCHAR(10),
			  CONTACTNO NVARCHAR(50) NULL,
			  REPORTTOID NVARCHAR(300) NULL,
			  REPORTTOUID NVARCHAR(100),
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESG NVARCHAR(50) NULL,
			  HREPORTTOID NVARCHAR(300) NULL,
			  HREPORTTOUID NVARCHAR(100),
			  HREPORTTO NVARCHAR(300) NULL,
			  HRPTTODESG NVARCHAR(50) NULL,
			  ATTENDANCEID INT,
			  ATTENDANCECNT INT,
			  ATTENDANCEPOINTS DECIMAL(18,2),
			  NEWSHOP_VISITEDID INT,
			  NEWSHOP_VISITEDCNT INT,
			  NEWSHOP_VISITEDPOINTS DECIMAL(18,2),
			  RE_VISITEDID INT,
			  RE_VISITEDCNT INT,
			  RE_VISITEDPOINTS DECIMAL(18,2),
			  ORDERID INT,
			  ORDERIDCNT INT,
			  ORDERPOINTS DECIMAL(18,2),
			  ACTIVITIESID INT,
			  ACTIVITIESCNT INT,
			  ACTIVITIESPOINTS DECIMAL(18,2),
			  TOTALSCORES DECIMAL(18,2),
			  POSITION INT,
			  PROFILE_PICTURES_URL NVARCHAR(500)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSLEADERBOARDPOINTSDETAILS_REPORT (POSITION)
		END
	DELETE FROM FTSLEADERBOARDPOINTSDETAILS_REPORT
	
	INSERT INTO FTSLEADERBOARDPOINTSDETAILS_REPORT(ACTIVITYMODE,USERID,BRANCH_ID,BRANCHDESC,EMPCODE,EMPID,EMPNAME,STATEID,STATENAME,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,
	REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,ATTENDANCEID,ATTENDANCECNT,ATTENDANCEPOINTS,NEWSHOP_VISITEDID,NEWSHOP_VISITEDCNT,NEWSHOP_VISITEDPOINTS,RE_VISITEDID,
	RE_VISITEDCNT,RE_VISITEDPOINTS,ORDERID,ORDERIDCNT,ORDERPOINTS,ACTIVITIESID,ACTIVITIESCNT,ACTIVITIESPOINTS,TOTALSCORES,POSITION,PROFILE_PICTURES_URL)
	SELECT 'M' AS ACTIVITYMODE,USERID,BRANCH_ID,BRANCH_DESCRIPTION,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,
	HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,1 AS ATTENDANCEID,SUM(ISNULL(ATTENDANCECNT,0)) AS ATTENDANCECNT,SUM(ISNULL(ATTENDANCEPOINTS,0)) AS ATTENDANCEPOINTS,2 AS NEWSHOP_VISITEDID,
	SUM(ISNULL(NEWSHOP_VISITEDCNT,0)) AS NEWSHOP_VISITEDCNT,SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0)) AS NEWSHOP_VISITEDPOINTS,3 AS RE_VISITEDID,SUM(ISNULL(RE_VISITEDCNT,0)) AS RE_VISITEDCNT,
	SUM(ISNULL(RE_VISITEDPOINTS,0)) AS RE_VISITEDPOINTS,4 AS ORDERID,SUM(ISNULL(ORDERIDCNT,0)) AS ORDERIDCNT,SUM(ISNULL(ORDERIDPOINTS,0)) AS ORDERIDPOINTS,5 AS ACTIVITIESID,
	SUM(ISNULL(ACTIVITIESCNT,0)) AS ACTIVITIESCNT,SUM(ISNULL(ACTIVITIESPOINTS,0)) AS ACTIVITIESPOINTS,SUM(ISNULL(ATTENDANCEPOINTS,0))+SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0))
	+SUM(ISNULL(RE_VISITEDPOINTS,0))+SUM(ISNULL(ORDERIDPOINTS,0))+SUM(ISNULL(ACTIVITIESPOINTS,0)) AS TOTALSCORES,
	DENSE_RANK() OVER (ORDER BY (SUM(ISNULL(ATTENDANCEPOINTS,0))+SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0))+SUM(ISNULL(RE_VISITEDPOINTS,0))+SUM(ISNULL(ORDERIDPOINTS,0))
	+SUM(ISNULL(ACTIVITIESPOINTS,0))) DESC) AS POSITION,PROFILE_PICTURES_URL FROM(
	SELECT USR.USER_ID AS USERID,BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,
	ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'')<>'' THEN ' ' ELSE '' END)+ISNULL(CNT.CNT_LASTNAME,'') AS EMPNAME,
	ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,USR.user_loginId AS CONTACTNO,
	RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTOID,HRPTTO.HREPORTTOUID,HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,--1 AS ATTENDANCEID,
	ATTEN.ATTENDANCECNT,ATTEN.ATTENDANCEPOINTS,SHOPACT.NEWSHOP_VISITEDCNT,SHOPACT.NEWSHOP_VISITEDPOINTS,SHOPACT.RE_VISITEDCNT,SHOPACT.RE_VISITEDPOINTS,ORD.ORDERIDCNT,ORD.ORDERIDPOINTS,
	ACT.ACTIVITIESCNT,ACT.ACTIVITIESPOINTS,PPIC.ProfileImage AS PROFILE_PICTURES_URL
	FROM tbl_master_employee EMP WITH (NOLOCK)
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id 
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive='N'
	INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType='Office'
	INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK)
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id
	) DESG ON DESG.emp_cntId=EMP.emp_contactId 
	LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+' '+ISNULL(CNT.CNT_LASTNAME,'') AS REPORTTO,
	DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) 
	INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) 
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
	) DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL 
	) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId 
	LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+' '+ISNULL(CNT.CNT_LASTNAME,'') AS HREPORTTO,
	DESG.deg_designation AS HRPTTODESG,CNT.cnt_UCC AS HREPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) 
	INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) 
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
	) DESG ON DESG.emp_cntId=EMP.emp_contactId 
	WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON HRPTTO.emp_cntId=RPTTO.REPORTTOID
	INNER JOIN(
	SELECT ATTEN.User_Id AS USERID,CNT.CNT_INTERNALID,COUNT(CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120)) AS ATTENDANCECNT,
	COUNT(CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120))*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=1 AND POINT_SECTION='Attendance' AND IS_ACTIVE=1) AS ATTENDANCEPOINTS,
	CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime
	FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave='false'
	GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105)
	) ATTEN ON CNT.cnt_internalId=ATTEN.cnt_internalId AND USR.user_id=ATTEN.USERID
	LEFT OUTER JOIN(
	SELECT User_Id,cnt_internalId,VISITED_TIME,SUM(NEWSHOP_VISITEDCNT) AS NEWSHOP_VISITEDCNT,SUM(NEWSHOP_VISITEDPOINTS) AS NEWSHOP_VISITEDPOINTS,SUM(RE_VISITEDCNT) AS RE_VISITEDCNT,
	SUM(RE_VISITEDPOINTS) AS RE_VISITEDPOINTS FROM(
	SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITEDCNT,COUNT(SHOPACT.Shop_Id)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS 
	WHERE ID=2 AND POINT_SECTION='New Visit' AND IS_ACTIVE=1) AS NEWSHOP_VISITEDPOINTS,0 AS RE_VISITEDCNT,0 AS RE_VISITEDPOINTS,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME
	FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120)
	AND SHOPACT.Is_Newshopadd=1
	GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time
	UNION ALL 
	SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITEDCNT,0 AS NEWSHOP_VISITEDPOINTS,COUNT(SHOPACT.Shop_Id) AS RE_VISITEDCNT,
	COUNT(SHOPACT.Shop_Id)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=3 AND POINT_SECTION='Revisit' AND IS_ACTIVE=1) AS RE_VISITEDPOINTS,
	CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME
	FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) 
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120)
	AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0
	GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time) AA GROUP BY User_Id,cnt_internalId,VISITED_TIME
	) SHOPACT ON CNT.cnt_internalId=SHOPACT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME
	LEFT OUTER JOIN(
	SELECT USERID,CNT_INTERNALID,SUM(ORDERIDCNT) AS ORDERIDCNT,SUM(ORDERIDPOINTS) AS ORDERIDPOINTS,ORDER_DATE_TIME FROM(
	SELECT ORD.USERID AS USERID,CNT.CNT_INTERNALID,COUNT(ORD.ORDER_CODE) AS ORDERIDCNT,
	COUNT(ORD.ORDER_CODE)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=4 AND POINT_SECTION='Order' AND IS_ACTIVE=1) AS ORDERIDPOINTS,
	CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,105) AS ORDER_DATE_TIME
	FROM FSMITCORDERHEADER ORD WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ORD.USERID AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ORD.USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,105)
	UNION ALL
	SELECT ORD.USERID AS USERID,CNT.CNT_INTERNALID,COUNT(ORD.OrderCode) AS ORDERIDCNT,
	COUNT(ORD.OrderCode)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=4 AND POINT_SECTION='Order' AND IS_ACTIVE=1) AS ORDERIDPOINTS,
	CONVERT(NVARCHAR(10),ORD.Orderdate,105) AS ORDER_DATE_TIME
	FROM tbl_trans_fts_Orderupdate ORD WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ORD.USERID AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ORD.Orderdate,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ORD.USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORD.Orderdate,105)
	) ORDERMAIN GROUP BY USERID,CNT_INTERNALID,ORDER_DATE_TIME
	) ORD ON CNT.cnt_internalId=ORD.cnt_internalId AND ATTEN.Login_datetime=ORD.ORDER_DATE_TIME
	LEFT OUTER JOIN(
	SELECT ACT.Created_by AS USERID,CNT.CNT_INTERNALID,COUNT(ACT.ActivityCode) AS ACTIVITIESCNT,
	COUNT(ACT.ActivityCode)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=5 AND POINT_SECTION='Activities' AND IS_ACTIVE=1) AS ACTIVITIESPOINTS,
	CONVERT(NVARCHAR(10),ACT.Activity_DateTime,105) AS ACTIVITY_DATETIME
	FROM FTS_SalesActivity ACT WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ACT.Created_by AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ACT.Activity_DateTime,120) BETWEEN CONVERT(NVARCHAR(10),DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ACT.Created_by,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ACT.Activity_DateTime,105)
	) ACT ON CNT.cnt_internalId=ACT.cnt_internalId AND ATTEN.Login_datetime=ACT.ACTIVITY_DATETIME
	LEFT OUTER JOIN tbl_salesman_address PPIC ON USR.user_id=PPIC.UserId
	) MTD GROUP BY USERID,BRANCH_ID,BRANCH_DESCRIPTION,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,HREPORTTOID,
	HREPORTTOUID,HREPORTTO,HRPTTODESG,PROFILE_PICTURES_URL

	INSERT INTO FTSLEADERBOARDPOINTSDETAILS_REPORT(ACTIVITYMODE,USERID,BRANCH_ID,BRANCHDESC,EMPCODE,EMPID,EMPNAME,STATEID,STATENAME,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,
	REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,ATTENDANCEID,ATTENDANCECNT,ATTENDANCEPOINTS,NEWSHOP_VISITEDID,NEWSHOP_VISITEDCNT,NEWSHOP_VISITEDPOINTS,RE_VISITEDID,
	RE_VISITEDCNT,RE_VISITEDPOINTS,ORDERID,ORDERIDCNT,ORDERPOINTS,ACTIVITIESID,ACTIVITIESCNT,ACTIVITIESPOINTS,TOTALSCORES,POSITION,PROFILE_PICTURES_URL)
	SELECT 'O' AS ACTIVITYMODE,USERID,BRANCH_ID,BRANCH_DESCRIPTION,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,
	HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,1 AS ATTENDANCEID,SUM(ISNULL(ATTENDANCECNT,0)) AS ATTENDANCECNT,SUM(ISNULL(ATTENDANCEPOINTS,0)) AS ATTENDANCEPOINTS,2 AS NEWSHOP_VISITEDID,
	SUM(ISNULL(NEWSHOP_VISITEDCNT,0)) AS NEWSHOP_VISITEDCNT,SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0)) AS NEWSHOP_VISITEDPOINTS,3 AS RE_VISITEDID,SUM(ISNULL(RE_VISITEDCNT,0)) AS RE_VISITEDCNT,
	SUM(ISNULL(RE_VISITEDPOINTS,0)) AS RE_VISITEDPOINTS,4 AS ORDERID,SUM(ISNULL(ORDERIDCNT,0)) AS ORDERIDCNT,SUM(ISNULL(ORDERIDPOINTS,0)) AS ORDERIDPOINTS,5 AS ACTIVITIESID,
	SUM(ISNULL(ACTIVITIESCNT,0)) AS ACTIVITIESCNT,SUM(ISNULL(ACTIVITIESPOINTS,0)) AS ACTIVITIESPOINTS,SUM(ISNULL(ATTENDANCEPOINTS,0))+SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0))
	+SUM(ISNULL(RE_VISITEDPOINTS,0))+SUM(ISNULL(ORDERIDPOINTS,0))+SUM(ISNULL(ACTIVITIESPOINTS,0)) AS TOTALSCORES,
	DENSE_RANK() OVER (ORDER BY (SUM(ISNULL(ATTENDANCEPOINTS,0))+SUM(ISNULL(NEWSHOP_VISITEDPOINTS,0))+SUM(ISNULL(RE_VISITEDPOINTS,0))+SUM(ISNULL(ORDERIDPOINTS,0))
	+SUM(ISNULL(ACTIVITIESPOINTS,0))) DESC) AS POSITION,PROFILE_PICTURES_URL FROM(
	SELECT USR.USER_ID AS USERID,BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,
	ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'')<>'' THEN ' ' ELSE '' END)+ISNULL(CNT.CNT_LASTNAME,'') AS EMPNAME,
	ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,USR.user_loginId AS CONTACTNO,
	RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTOID,HRPTTO.HREPORTTOUID,HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,--1 AS ATTENDANCEID,
	ATTEN.ATTENDANCECNT,ATTEN.ATTENDANCEPOINTS,SHOPACT.NEWSHOP_VISITEDCNT,SHOPACT.NEWSHOP_VISITEDPOINTS,SHOPACT.RE_VISITEDCNT,SHOPACT.RE_VISITEDPOINTS,ORD.ORDERIDCNT,ORD.ORDERIDPOINTS,
	ACT.ACTIVITIESCNT,ACT.ACTIVITIESPOINTS,PPIC.ProfileImage AS PROFILE_PICTURES_URL
	FROM tbl_master_employee EMP WITH (NOLOCK)
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id 
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive='N'
	INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType='Office'
	INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK)
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id
	) DESG ON DESG.emp_cntId=EMP.emp_contactId 
	LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+' '+ISNULL(CNT.CNT_LASTNAME,'') AS REPORTTO,
	DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) 
	INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) 
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
	) DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL 
	) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId 
	LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+' '+ISNULL(CNT.CNT_LASTNAME,'') AS HREPORTTO,
	DESG.deg_designation AS HRPTTODESG,CNT.cnt_UCC AS HREPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) 
	INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId 
	INNER JOIN (
	SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) 
	LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id 
	) DESG ON DESG.emp_cntId=EMP.emp_contactId 
	WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON HRPTTO.emp_cntId=RPTTO.REPORTTOID
	INNER JOIN(
	SELECT ATTEN.User_Id AS USERID,CNT.CNT_INTERNALID,COUNT(CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120)) AS ATTENDANCECNT,
	COUNT(CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120))*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=1 AND POINT_SECTION='Attendance' AND IS_ACTIVE=1) AS ATTENDANCEPOINTS,
	CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime
	FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave='false'
	GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105)
	) ATTEN ON CNT.cnt_internalId=ATTEN.cnt_internalId AND USR.user_id=ATTEN.USERID
	LEFT OUTER JOIN(
	SELECT User_Id,cnt_internalId,VISITED_TIME,SUM(NEWSHOP_VISITEDCNT) AS NEWSHOP_VISITEDCNT,SUM(NEWSHOP_VISITEDPOINTS) AS NEWSHOP_VISITEDPOINTS,SUM(RE_VISITEDCNT) AS RE_VISITEDCNT,
	SUM(RE_VISITEDPOINTS) AS RE_VISITEDPOINTS FROM(
	SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITEDCNT,COUNT(SHOPACT.Shop_Id)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS 
	WHERE ID=2 AND POINT_SECTION='New Visit' AND IS_ACTIVE=1) AS NEWSHOP_VISITEDPOINTS,0 AS RE_VISITEDCNT,0 AS RE_VISITEDPOINTS,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME
	FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120)
	AND SHOPACT.Is_Newshopadd=1
	GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time
	UNION ALL 
	SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITEDCNT,0 AS NEWSHOP_VISITEDPOINTS,COUNT(SHOPACT.Shop_Id) AS RE_VISITEDCNT,
	COUNT(SHOPACT.Shop_Id)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=3 AND POINT_SECTION='Revisit' AND IS_ACTIVE=1) AS RE_VISITEDPOINTS,
	CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME
	FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) 
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id 
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120)
	AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0
	GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time) AA GROUP BY User_Id,cnt_internalId,VISITED_TIME
	) SHOPACT ON CNT.cnt_internalId=SHOPACT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME
	LEFT OUTER JOIN(
	SELECT USERID,CNT_INTERNALID,SUM(ORDERIDCNT) AS ORDERIDCNT,SUM(ORDERIDPOINTS) AS ORDERIDPOINTS,ORDER_DATE_TIME FROM(
	SELECT ORD.USERID AS USERID,CNT.CNT_INTERNALID,COUNT(ORD.ORDER_CODE) AS ORDERIDCNT,
	COUNT(ORD.ORDER_CODE)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=4 AND POINT_SECTION='Order' AND IS_ACTIVE=1) AS ORDERIDPOINTS,
	CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,105) AS ORDER_DATE_TIME
	FROM FSMITCORDERHEADER ORD WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ORD.USERID AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ORD.USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,105)
	UNION ALL
	SELECT ORD.USERID AS USERID,CNT.CNT_INTERNALID,COUNT(ORD.OrderCode) AS ORDERIDCNT,
	COUNT(ORD.OrderCode)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=4 AND POINT_SECTION='Order' AND IS_ACTIVE=1) AS ORDERIDPOINTS,
	CONVERT(NVARCHAR(10),ORD.Orderdate,105) AS ORDER_DATE_TIME
	FROM tbl_trans_fts_Orderupdate ORD WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ORD.USERID AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ORD.Orderdate,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ORD.USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORD.Orderdate,105)
	) ORDERMAIN GROUP BY USERID,CNT_INTERNALID,ORDER_DATE_TIME
	) ORD ON CNT.cnt_internalId=ORD.cnt_internalId AND ATTEN.Login_datetime=ORD.ORDER_DATE_TIME
	LEFT OUTER JOIN(
	SELECT ACT.Created_by AS USERID,CNT.CNT_INTERNALID,COUNT(ACT.ActivityCode) AS ACTIVITIESCNT,
	COUNT(ACT.ActivityCode)*(SELECT POINT_VALUE FROM MASTER_LEADERBOARDPOINTS WHERE ID=5 AND POINT_SECTION='Activities' AND IS_ACTIVE=1) AS ACTIVITIESPOINTS,
	CONVERT(NVARCHAR(10),ACT.Activity_DateTime,105) AS ACTIVITY_DATETIME
	FROM FTS_SalesActivity ACT WITH (NOLOCK)
	INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ACT.Created_by AND USR.user_inactive='N'
	INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId 
	WHERE CONVERT(NVARCHAR(10),ACT.Activity_DateTime,120) BETWEEN CONVERT(NVARCHAR(10),DateAdd(month,-2,GETDATE()),120) AND CONVERT(NVARCHAR(10),GETDATE(),120) 
	GROUP BY ACT.Created_by,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ACT.Activity_DateTime,105)
	) ACT ON CNT.cnt_internalId=ACT.cnt_internalId AND ATTEN.Login_datetime=ACT.ACTIVITY_DATETIME
	LEFT OUTER JOIN tbl_salesman_address PPIC ON USR.user_id=PPIC.UserId
	) MTD GROUP BY USERID,BRANCH_ID,BRANCH_DESCRIPTION,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,HREPORTTOID,
	HREPORTTOUID,HREPORTTO,HRPTTODESG,PROFILE_PICTURES_URL

	DROP TABLE #TEMPCONTACT

	SET NOCOUNT OFF
END
GO