--EXEC PRC_FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT 'NOV','','','2022',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT]') AND TYPE in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT]
(
@MONTH NVARCHAR(3)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@YEARS NVARCHAR(10)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder on 09/11/2022
Module	   : Territory Sales incharge Wise Performance.Refer: 0025369
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX),@MONTHNAME NVARCHAR(3),@MONTHNO INT=0,@FROMDATE NVARCHAR(10),@TODATE NVARCHAR(10),@FIRSTDATEOFMONTH DATETIME,@CURRENTDATEOFMONTH DATETIME
	DECLARE @IsActivateNewOrderScreenwithSize BIT

	SELECT @IsActivateNewOrderScreenwithSize=IsActivateNewOrderScreenwithSize FROM tbl_master_user WITH(NOLOCK) WHERE USER_ID=@USERID

	SET @MONTHNAME=@MONTH
	SET @MONTHNO=DATEPART(MM,@MONTHNAME+'01 1900')
	SET @FROMDATE=CONVERT(NVARCHAR(10),DATEADD(MONTH, CONVERT(INT,@MONTHNO) - 1, @YEARS),120)
	SET @TODATE=CONVERT(NVARCHAR(10),DATEADD(DAY, -1, DATEADD(MONTH, CONVERT(INT,@MONTHNO), @YEARS)),120)

	SELECT @FIRSTDATEOFMONTH = @FROMDATE
	SELECT @CURRENTDATEOFMONTH = @TODATE

	;WITH mycte AS
	(
		SELECT CAST(@FROMDATE AS DATETIME) DateValue
		UNION ALL
		SELECT DateValue + 1
		FROM mycte   
		WHERE DateValue + 1 <= @TODATE
	)
	SELECT CONVERT(NVARCHAR(10),DateValue,105) AS LOGGEDINDATE INTO #TMPALLDAYINMONTH FROM mycte OPTION (MAXRECURSION 1000)

	;WITH CTE AS (SELECT 1 AS DAYID,@FIRSTDATEOFMONTH AS FROMDATE,DATENAME(DW, @FIRSTDATEOFMONTH) AS DAYNAME
	UNION ALL
	SELECT CTE.DAYID + 1 AS DAYID,DATEADD(D, 1 ,CTE.FROMDATE),DATENAME(DW, DATEADD(D, 1 ,CTE.FROMDATE)) AS DAYNAME
	FROM CTE
	WHERE DATEADD(D,1,CTE.FROMDATE) <= @CURRENTDATEOFMONTH
	)
	SELECT CONVERT(NVARCHAR(10),FROMDATE,105) AS SUNDAYDATE,DAYNAME INTO #TMPSHOWSUNDAY
	FROM CTE
	WHERE DAYNAME IN ('Sunday')
	OPTION (MAXRECURSION 1000)

	DELETE FROM #TMPALLDAYINMONTH WHERE EXISTS(SELECT SUNDAYDATE FROM #TMPSHOWSUNDAY WHERE #TMPALLDAYINMONTH.LOGGEDINDATE=#TMPSHOWSUNDAY.SUNDAYDATE)

	IF OBJECT_ID('tempdb..#STATEID_LIST') IS NOT NULL
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @SqlStrTable=''
			SET @SqlStrTable='INSERT INTO #STATEID_LIST SELECT id from tbl_master_state WITH (NOLOCK) where ID IN('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @SqlStrTable=''
			SET @SqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WITH (NOLOCK) WHERE emp_contactId IN('+@EMPID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@Userid)		
			CREATE TABLE #EMPHRS
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)

			CREATE TABLE #EMPHR_EDIT
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)
			
			INSERT INTO #EMPHRS
			SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC WITH (NOLOCK)
			LEFT JOIN tbl_master_employee TME WITH (NOLOCK) ON TME.emp_id= CTC.emp_reportTO 
			WHERE emp_effectiveuntil IS NULL
		
			;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
			UNION ALL
			SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
			JOIN cte b ON a.RPTTOEMPCODE = b.EMPCODE
			) 
			INSERT INTO #EMPHR_EDIT
			SELECT EMPCODE,RPTTOEMPCODE FROM cte 
		END

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			INSERT INTO #TEMPCONTACT(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC)
			SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WITH (NOLOCK)
			INNER JOIN #EMPHR_EDIT ON cnt_internalId=EMPCODE WHERE cnt_contactType IN('EM')
		END
	ELSE
		BEGIN
			INSERT INTO #TEMPCONTACT(cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC)
			SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WITH (NOLOCK)
			WHERE cnt_contactType IN('EM')
		END

	IF OBJECT_ID('tempdb..#TMPATTENLOGINTSI') IS NOT NULL
		DROP TABLE #TMPATTENLOGINTSI
	CREATE TABLE #TMPATTENLOGINTSI(USERID BIGINT,LOGGEDIN NVARCHAR(10),cnt_internalId NVARCHAR(10),Login_datetime NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINTSI(USERID,cnt_internalId,Login_datetime)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPATTENLOGINTSI(USERID,LOGGEDIN,cnt_internalId,Login_datetime) '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF OBJECT_ID('tempdb..#TMPSHOPSUBMITACTTSI') IS NOT NULL
		DROP TABLE #TMPSHOPSUBMITACTTSI
	CREATE TABLE #TMPSHOPSUBMITACTTSI(USER_ID BIGINT,cnt_internalId NVARCHAR(10),Shop_Id VARCHAR(100),NEWSHOP_VISITED INT,RE_VISITED INT,VISITED_TIME NVARCHAR(20),SPENT_DURATION VARCHAR(100),DISTANCE_TRAVELLED DECIMAL(18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPSUBMITACTTSI(USER_ID,cnt_internalId,Shop_Id)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPSHOPSUBMITACTTSI(USER_ID,cnt_internalId,Shop_Id,NEWSHOP_VISITED,RE_VISITED,VISITED_TIME,SPENT_DURATION,DISTANCE_TRAVELLED) '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME,SPENT_DURATION,'
	SET @Strsql+='SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time,SPENT_DURATION '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_TIME,SPENT_DURATION,'
	SET @Strsql+='SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time,SPENT_DURATION '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF @IsActivateNewOrderScreenwithSize=1
		BEGIN
			IF OBJECT_ID('tempdb..#TMPORDATTRIBUTETSI') IS NOT NULL
				DROP TABLE #TMPORDATTRIBUTETSI
			CREATE TABLE #TMPORDATTRIBUTETSI(USER_ID BIGINT,SHOP_CODE NVARCHAR(200),ORDER_DATE DATETIME,Ordervalue DECIMAL(18,2))
			CREATE NONCLUSTERED INDEX IX1 ON #TMPORDATTRIBUTETSI (USER_ID ASC)

			SET @Strsql=''
			SET @Strsql='INSERT INTO #TMPORDATTRIBUTETSI(USER_ID,SHOP_CODE,ORDER_DATE,Ordervalue) '
			SET @Strsql+='SELECT ORDH.USER_ID,ORDH.SHOP_ID,ORDH.ORDER_DATE,SUM(ISNULL(ORDD.Ordervalue,0)) AS Ordervalue FROM ORDERPRODUCTATTRIBUTE ORDH WITH(NOLOCK) '
			SET @Strsql+='INNER JOIN(SELECT ORDD.ID,ORDD.USER_ID,ORDD.ORDER_ID,(ORDD.QTY*ORDD.RATE) AS Ordervalue FROM ORDERPRODUCTATTRIBUTEDET ORDD WITH(NOLOCK) '
			SET @Strsql+=') ORDD ON ORDH.ID=ORDD.ID AND ORDH.USER_ID=ORDD.USER_ID AND ORDH.ORDER_ID=ORDD.ORDER_ID '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.ORDER_DATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY ORDH.USER_ID,ORDH.ORDER_ID,ORDH.SHOP_ID,ORDH.ORDER_DATE '

			--SELECT @Strsql
			EXEC SP_EXECUTESQL @Strsql
		END

	--New Visit/Re Visit Conversion Rate
	IF OBJECT_ID('tempdb..#TMPSHOPVISITREVISITCONVRATE') IS NOT NULL
		DROP TABLE #TMPSHOPVISITREVISITCONVRATE
	CREATE TABLE #TMPSHOPVISITREVISITCONVRATE(USER_ID BIGINT,cnt_internalId NVARCHAR(10),NEWSHOPVISITCONVRATE INT,NORDSHPCNT INT,REVISITCONVRATE INT,RORDSHPCNT INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPVISITREVISITCONVRATE(USER_ID,cnt_internalId)
	
	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPSHOPVISITREVISITCONVRATE(USER_ID,cnt_internalId,NEWSHOPVISITCONVRATE,NORDSHPCNT,REVISITCONVRATE,RORDSHPCNT) '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOPVISITCONVRATE,COUNT(DISTINCT ORDH.SHOP_CODE) AS NORDSHPCNT,0 AS REVISITCONVRATE,0 AS RORDSHPCNT '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	IF @IsActivateNewOrderScreenwithSize=1
		SET @Strsql+='LEFT OUTER JOIN #TMPORDATTRIBUTETSI ORDH ON SHOPACT.User_Id=ORDH.USER_ID AND SHOPACT.Shop_Id=ORDH.SHOP_CODE '
	ELSE IF @IsActivateNewOrderScreenwithSize=0
		SET @Strsql+='LEFT OUTER JOIN tbl_trans_fts_Orderupdate ORDH ON SHOPACT.User_Id=ORDH.userID AND SHOPACT.Shop_Id=ORDH.Shop_Code '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOPVISITCONVRATE,0 AS NORDSHPCNT,COUNT(SHOPACT.Shop_Id) AS REVISITCONVRATE,COUNT(DISTINCT ORDH.SHOP_CODE) AS RORDSHPCNT '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	IF @IsActivateNewOrderScreenwithSize=1
		SET @Strsql+='LEFT OUTER JOIN #TMPORDATTRIBUTETSI ORDH ON SHOPACT.User_Id=ORDH.USER_ID AND SHOPACT.Shop_Id=ORDH.SHOP_CODE '
	ELSE IF @IsActivateNewOrderScreenwithSize=0
		SET @Strsql+='LEFT OUTER JOIN tbl_trans_fts_Orderupdate ORDH ON SHOPACT.User_Id=ORDH.userID AND SHOPACT.Shop_Id=ORDH.Shop_Code '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	--Number of Days with No Visits
	IF OBJECT_ID('tempdb..#TMPSHOPNOVISIT') IS NOT NULL
		DROP TABLE #TMPSHOPNOVISIT
	CREATE TABLE #TMPSHOPNOVISIT(USER_ID BIGINT,CNTVISITTIME INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPNOVISIT(USER_ID)
	
	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPSHOPNOVISIT(USER_ID,CNTVISITTIME) '
	SET @Strsql+='SELECT User_Id,(SELECT COUNT(0) FROM #TMPALLDAYINMONTH)-COUNT(DISTINCT CONVERT(NVARCHAR(10),visited_time,120)) AS CNTVISITTIME '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND EXISTS(SELECT LOGGEDINDATE FROM #TMPALLDAYINMONTH WHERE CONVERT(NVARCHAR(10),visited_time,105)=LOGGEDINDATE) '
	SET @Strsql+='GROUP BY User_Id '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	--Average Time to First Call
	IF OBJECT_ID('tempdb..#TMPVISITTOCALL') IS NOT NULL
		DROP TABLE #TMPVISITTOCALL
	CREATE TABLE #TMPVISITTOCALL(USERID BIGINT,CNT_INTERNALID NVARCHAR(10),VISITDIFF INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPVISITTOCALL(USERID,CNT_INTERNALID)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPVISITTOCALL(USERID,CNT_INTERNALID,VISITDIFF) '
	SET @Strsql+='SELECT USERID,CNT_INTERNALID,ABS(SUM(VISITDIFF)/SUM(CASE WHEN CNTATTENDANCE<>0 THEN CNTATTENDANCE ELSE 1 END)) AS VISITDIFF FROM('
	SET @Strsql+='SELECT LGINOUT.USERID,ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0) AS LOGGEDIN,'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0) AS LOGEDOUT,'
	SET @Strsql+='LGINOUT.CNTATTENDANCE,LGINOUT.CNT_INTERNALID,LGINOUT.LOGIN_DATETIME,ISNULL(CAST(SUBSTRING(SHOPACT.FIRSTCALLTIME,1,2) AS INT)*60+CAST(SUBSTRING(SHOPACT.FIRSTCALLTIME,4,2) AS INT),0) AS FIRSTCALLTIME,'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(SHOPACT.LASTCALLTIME,1,2) AS INT)*60+CAST(SUBSTRING(SHOPACT.LASTCALLTIME,4,2) AS INT),0) AS LASTCALLTIME,SHOPACT.NEWSHOP_VISITED,'
	SET @Strsql+='SHOPACT.RE_VISITED,ISNULL(SHOPACT.User_Id,LGINOUT.USERID) AS USER_ID,SHOPACT.VISITED_TIME,ISNULL(SHOPACT.CNT_INTERNALID,LGINOUT.CNT_INTERNALID) AS CNTINTERNALID,'
	SET @Strsql+='CASE WHEN SHOPACT.VISITED_TIME IS NOT NULL THEN (ISNULL(CAST(SUBSTRING(SHOPACT.FIRSTCALLTIME,1,2) AS INT)*60+CAST(SUBSTRING(SHOPACT.FIRSTCALLTIME,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0)) '
	SET @Strsql+='WHEN LGINOUT.LOGIN_DATETIME<>'''' AND SHOPACT.VISITED_TIME IS NULL THEN (ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0)) END AS VISITDIFF '
	SET @Strsql+='FROM('
	SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,SUM(CNTATTENDANCE) AS CNTATTENDANCE,cnt_internalId,Login_datetime FROM('
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,COUNT(ATTEN.Login_datetime) AS CNTATTENDANCE,CNT.cnt_internalId,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,COUNT(ATTEN.Login_datetime) AS CNTATTENDANCE,CNT.cnt_internalId,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime) LGINOUT '
	SET @Strsql+='LEFT OUTER JOIN('
	SET @Strsql+='SELECT User_Id,cnt_internalId,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,'
	SET @Strsql+='MIN(CONVERT(VARCHAR(5),CAST(FCALLTIME AS TIME),108)) AS FIRSTCALLTIME,MAX(CONVERT(VARCHAR(5),CAST(LCALLTIME AS TIME),108)) AS LASTCALLTIME,'
	SET @Strsql+='CONVERT(NVARCHAR(10),VISITED_TIME,105) AS VISITED_TIME FROM('
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,CAST(SHOPACT.visited_time AS DATE) AS visited_time,'
	SET @Strsql+='MIN(visited_time) AS FCALLTIME,MAX(visited_time) AS LCALLTIME '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CAST(SHOPACT.visited_time AS DATE) '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,CAST(SHOPACT.visited_time AS DATE) AS visited_time,'
	SET @Strsql+='MIN(visited_time) AS FCALLTIME,MAX(visited_time) AS LCALLTIME '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,CAST(SHOPACT.visited_time AS DATE) '
	SET @Strsql+=') AA GROUP BY User_Id,cnt_internalId,CAST(VISITED_TIME AS DATE) '
	SET @Strsql+=') SHOPACT ON SHOPACT.cnt_internalId=LGINOUT.cnt_internalId AND LGINOUT.Login_datetime=SHOPACT.VISITED_TIME '
	SET @Strsql+=') VISITTOCALL '
	SET @Strsql+='GROUP BY VISITTOCALL.USERID,VISITTOCALL.cnt_internalId '
	SET @Strsql+='ORDER BY VISITTOCALL.USERID '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	--Average Work Duration (HH:MM:SS)
	IF OBJECT_ID('tempdb..#TMPATTENWRKHRS') IS NOT NULL
		DROP TABLE #TMPATTENWRKHRS
	CREATE TABLE #TMPATTENWRKHRS(USERID BIGINT,CNT_INTERNALID NVARCHAR(10),LOGINOUTDIFF INT,CNTATTENDANCE INT,WORKDIFF INT,TOTNOOFFULLDAYS INT,TOTNOOFHALFDAYS INT,LESSTWOHRSWORK INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENWRKHRS(USERID,CNT_INTERNALID)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPATTENWRKHRS(USERID,CNT_INTERNALID,LOGINOUTDIFF,CNTATTENDANCE,WORKDIFF,TOTNOOFFULLDAYS,TOTNOOFHALFDAYS,LESSTWOHRSWORK) '
	SET @Strsql+='SELECT USERID,CNT_INTERNALID,ABS(SUM(LOGINOUTDIFF)/SUM(CASE WHEN CNTATTENDANCE<>0 THEN CNTATTENDANCE ELSE 1 END)) AS LOGINOUTDIFF,SUM(CNTATTENDANCE) AS CNTATTENDANCE,'
	SET @Strsql+='ABS(SUM(LOGINOUTDIFF)) WORKDIFF,SUM(TOTNOOFFULLDAYS) AS TOTNOOFFULLDAYS,SUM(TOTNOOFHALFDAYS) AS TOTNOOFHALFDAYS,SUM(LESSTWOHRSWORK) AS LESSTWOHRSWORK '
	SET @Strsql+='FROM('
	SET @Strsql+='SELECT LGINOUT.USERID,ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0) AS LOGGEDIN,'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0) AS LOGEDOUT,'
	SET @Strsql+='LGINOUT.CNTATTENDANCE,LGINOUT.CNT_INTERNALID,LGINOUT.LOGIN_DATETIME,'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0) AS LOGINOUTDIFF,'
	SET @Strsql+='CASE WHEN ABS(ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0))>465 THEN 1 ELSE 0 END AS TOTNOOFFULLDAYS,'
	SET @Strsql+='CASE WHEN ABS(ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0)) BETWEEN 120 AND 464 THEN 1 ELSE 0 END AS TOTNOOFHALFDAYS,'
	SET @Strsql+='CASE WHEN ABS(ISNULL(CAST(SUBSTRING(LGINOUT.LOGEDOUT,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGEDOUT,4,2) AS INT),0)-'
	SET @Strsql+='ISNULL(CAST(SUBSTRING(LGINOUT.LOGGEDIN,1,2) AS INT)*60+CAST(SUBSTRING(LGINOUT.LOGGEDIN,4,2) AS INT),0))<120 THEN 1 ELSE 0 END AS LESSTWOHRSWORK '
	SET @Strsql+='FROM('
	SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,SUM(CNTATTENDANCE) AS CNTATTENDANCE,cnt_internalId,Login_datetime FROM('
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,COUNT(ATTEN.Login_datetime) AS CNTATTENDANCE,CNT.cnt_internalId,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,COUNT(ATTEN.Login_datetime) AS CNTATTENDANCE,CNT.cnt_internalId,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime '
	SET @Strsql+=') LGINOUT '
	SET @Strsql+=') WORKDURATION '
	SET @Strsql+='GROUP BY WORKDURATION.USERID,WORKDURATION.cnt_internalId '
	SET @Strsql+='ORDER BY WORKDURATION.USERID '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	--Total Number of Absent
	IF OBJECT_ID('tempdb..#TMPABSENT') IS NOT NULL
		DROP TABLE #TMPABSENT
	CREATE TABLE #TMPABSENT(USER_ID BIGINT,CNTNOWORKTIME INT)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPABSENT(USER_ID)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPABSENT(USER_ID,CNTNOWORKTIME) '
	SET @Strsql+='SELECT ATTEN.User_Id,(SELECT COUNT(0) FROM #TMPALLDAYINMONTH)-COUNT(DISTINCT CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120)) AS CNTNOWORKTIME '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH(NOLOCK) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND ATTEN.Login_datetime IS NOT NULL AND ATTEN.Logout_datetime IS NULL AND ATTEN.Isonleave=''false'' '
	SET @Strsql+='AND EXISTS(SELECT LOGGEDINDATE FROM #TMPALLDAYINMONTH WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105)=LOGGEDINDATE) '
	SET @Strsql+='GROUP BY User_Id '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT
			(
			  USERID INT,
			  SEQ INT,
			  EMPCODE NVARCHAR(100),
			  EMPUSERID BIGINT,
			  EMPID NVARCHAR(100),
			  EMPNAME NVARCHAR(300),
			  CITYID INT,
			  EMPCITY NVARCHAR(50),
			  STATEID INT,
			  STATE NVARCHAR(50),
			  BRANCHDESC NVARCHAR(300),
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50),
			  DATEOFJOINING NVARCHAR(10),
			  CONTACTNO NVARCHAR(50),
			  REPORTTO NVARCHAR(300),
			  RPTTODESG NVARCHAR(50),
			  ORDSHPCNT INT,
			  TOTALORDERVALUE DECIMAL(38,2),
			  TARGETORDVALUE DECIMAL(38,2),
			  AVGORDERVALUE DECIMAL(38,2),
			  SHOPCNT INT,
			  AVGREVPERSTORE DECIMAL(38,2),
			  APPROVEEXPAMT DECIMAL(38,2),
			  AVGREVPERVISIT DECIMAL(38,2),
			  TOTAL_VISIT INT,
			  NEWSHOP_VISITED INT,
			  RE_VISITED INT,
			  VISITCONVRATE DECIMAL(38,2),
			  NEWVISITCONVRATE DECIMAL(38,2),
			  REVISITCONVRATE DECIMAL(38,2),
			  TOTALVISITTIME NVARCHAR(10),
			  AVGVISITTIME NVARCHAR(10),
			  NOVISITDAYS INT,
			  AVGTIMETOFSTCALL NVARCHAR(10),
			  AVGWORKDURATION NVARCHAR(10),
			  TOTALKMTRAVELLED DECIMAL(38,2),
			  AVGKMTRAVELLED DECIMAL(38,2),
			  TOTNOOFFULLDAYS INT,
			  TOTNOOFHALFDAYS INT,
			  TOTLEAVEDAYS INT,
			  TOTALABSENT INT
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT (SEQ)
		END
	DELETE FROM FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT WHERE USERID=@USERID	

	SET @Strsql=''
	SET @Strsql='INSERT INTO FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT(USERID,SEQ,EMPCODE,EMPUSERID,EMPID,EMPNAME,CITYID,EMPCITY,STATEID,STATE,BRANCHDESC,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,'
	SET @Strsql+='REPORTTO,RPTTODESG,ORDSHPCNT,TOTALORDERVALUE,TARGETORDVALUE,AVGORDERVALUE,SHOPCNT,AVGREVPERSTORE,APPROVEEXPAMT,AVGREVPERVISIT,TOTAL_VISIT,NEWSHOP_VISITED,RE_VISITED,VISITCONVRATE,'
	SET @Strsql+='NEWVISITCONVRATE,REVISITCONVRATE,TOTALVISITTIME,AVGVISITTIME,NOVISITDAYS,AVGTIMETOFSTCALL,AVGWORKDURATION,TOTALKMTRAVELLED,AVGKMTRAVELLED,TOTNOOFFULLDAYS,TOTNOOFHALFDAYS,TOTLEAVEDAYS,'
	SET @Strsql+='TOTALABSENT) '
	SET @Strsql+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY EMPNAME) AS SEQ,EMPCODE,EMPUSERID,EMPID,EMPNAME,CITYID,EMPCITY,STATEID,STATE,BRANCHDESC,DEG_ID,DESIGNATION,'
	SET @Strsql+='DATEOFJOINING,CONTACTNO,REPORTTO,RPTTODESG,ORDSHPCNT,TOTALORDERVALUE,TARGETORDVALUE,AVGORDERVALUE,SHOPCNT,AVGREVPERSTORE,APPROVEEXPAMT,AVGREVPERVISIT,TOTAL_VISIT,NEWSHOP_VISITED,RE_VISITED,'
	SET @Strsql+='VISITCONVRATE,NEWVISITCONVRATE,REVISITCONVRATE,CAST(CAST((TOTALVISITTIME) AS INT) / 60 AS VARCHAR) + '':''  + RIGHT(''0'' + CAST(CAST((TOTALVISITTIME) AS INT) % 60 AS VARCHAR(2)),2) AS TOTALVISITTIME,'
	SET @Strsql+='CAST(CAST((AVGVISITTIME) AS INT) / 60 AS VARCHAR) + '':''  + RIGHT(''0'' + CAST(CAST((AVGVISITTIME) AS INT) % 60 AS VARCHAR(2)),2) AS AVGVISITTIME,NOVISITDAYS,'
	SET @Strsql+='CAST(CAST((AVGTIMETOFSTCALL) AS INT) / 60 AS VARCHAR) + '':''  + RIGHT(''0'' + CAST(CAST((AVGTIMETOFSTCALL) AS INT) % 60 AS VARCHAR(2)),2) AS AVGTIMETOFSTCALL,'
	SET @Strsql+='CAST(CAST((AVGWORKDURATION) AS INT) / 60 AS VARCHAR) + '':''  + RIGHT(''0'' + CAST(CAST((AVGWORKDURATION) AS INT) % 60 AS VARCHAR(2)),2) AS AVGWORKDURATION,TOTALKMTRAVELLED,AVGKMTRAVELLED,'
	SET @Strsql+='TOTNOOFFULLDAYS,TOTNOOFHALFDAYS,TOTLEAVEDAYS,TOTALABSENT FROM('
	SET @Strsql+='SELECT EMPCODE,EMPUSERID,EMPID,EMPNAME,CITYID,EMPCITY,STATEID,STATE,BRANCHDESC,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTO,RPTTODESG,SUM(ORDSHPCNT) AS ORDSHPCNT,'
	SET @Strsql+='SUM(TOTALORDERVALUE) AS TOTALORDERVALUE,SUM(DISTINCT TARGETORDVALUE) AS TARGETORDVALUE,CASE WHEN SUM(ORDSHPCNT)<> 0 THEN SUM(TOTALORDERVALUE)/SUM(ORDSHPCNT) ELSE 0.00 END AVGORDERVALUE,'
	SET @Strsql+='SUM(DISTINCT SHOPCNT) AS SHOPCNT,CASE WHEN SUM(DISTINCT SHOPCNT)<> 0 THEN SUM(TOTALORDERVALUE)/SUM(DISTINCT SHOPCNT) ELSE 0.00 END AVGREVPERSTORE,'
	SET @Strsql+='CASE WHEN SUM(DISTINCT APPROVEEXPAMT)<> 0 THEN SUM(TOTALORDERVALUE)/SUM(DISTINCT APPROVEEXPAMT) ELSE 0.00 END APPROVEEXPAMT,'
	SET @Strsql+='CASE WHEN SUM(TOTAL_VISIT)<> 0 THEN SUM(TOTALORDERVALUE)/SUM(TOTAL_VISIT) ELSE 0.00 END AVGREVPERVISIT,SUM(TOTAL_VISIT) AS TOTAL_VISIT,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,'
	SET @Strsql+='SUM(RE_VISITED) AS RE_VISITED,CASE WHEN SUM(TOTAL_VISIT)<> 0 THEN (CAST(SUM(ORDSHPCNT) AS DECIMAL(18,2))/CAST(SUM(TOTAL_VISIT) AS DECIMAL(18,2)))*100 ELSE 0.00 END AS VISITCONVRATE,'
	SET @Strsql+='CASE WHEN SUM(NEWSHOPVISITCONVRATE)<> 0 THEN (CAST(SUM(NORDSHPCNT) AS DECIMAL(18,2))/CAST(SUM(NEWSHOPVISITCONVRATE) AS DECIMAL(18,2)))*100 ELSE 0.00 END AS NEWVISITCONVRATE,'
	SET @Strsql+='CASE WHEN SUM(REVISITCONVRATE)<> 0 THEN (CAST(SUM(RORDSHPCNT) AS DECIMAL(18,2))/CAST(SUM(REVISITCONVRATE) AS DECIMAL(18,2)))*100 ELSE 0.00 END AS REVISITCONVRATE,'
	SET @Strsql+='SUM(SPENT_DURATION) AS TOTALVISITTIME,CASE WHEN SUM(TOTAL_VISIT)<> 0 THEN SUM(SPENT_DURATION)/SUM(TOTAL_VISIT) ELSE 0 END AVGVISITTIME,SUM(DISTINCT CNTVISITTIME) AS NOVISITDAYS,'
	SET @Strsql+='SUM(DISTINCT VISITDIFF) AS AVGTIMETOFSTCALL,SUM(DISTINCT LOGINOUTDIFF) AS AVGWORKDURATION,SUM(DISTANCE_TRAVELLED) AS TOTALKMTRAVELLED,SUM(DISTANCE_TRAVELLED)/SUM(DISTINCT CNTATTENDANCE) AS AVGKMTRAVELLED,'
	SET @Strsql+='SUM(DISTINCT TOTNOOFFULLDAYS) AS TOTNOOFFULLDAYS,SUM(DISTINCT TOTNOOFHALFDAYS) AS TOTNOOFHALFDAYS,SUM(DISTINCT CNTSTATUS) AS TOTLEAVEDAYS,SUM(DISTINCT TOTALABSENT) AS TOTALABSENT '
	SET @Strsql+='FROM('
	SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,USR.USER_ID AS EMPUSERID,EMP.emp_uniqueCode AS EMPID,'
	SET @Strsql+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @Strsql+='CITY.city_id AS CITYID,CITY.CITY_NAME AS EMPCITY,ST.ID AS STATEID,ST.STATE,BR.branch_description AS BRANCHDESC,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,'
	SET @Strsql+='CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,USR.user_loginId AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,ISNULL(ORDHEAD.ORDSHPCNT,0) AS ORDSHPCNT,'
	SET @Strsql+='ISNULL(ORDHEAD.Ordervalue,0) AS TOTALORDERVALUE,ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0) AS TOTAL_VISIT,ISNULL(SHOPACT.NEWSHOP_VISITED,0) AS NEWSHOP_VISITED,'
	SET @Strsql+='ISNULL(SHOPACT.RE_VISITED,0) AS RE_VISITED,ISNULL(TARGETORDVALUE,0) AS TARGETORDVALUE,ISNULL(SHOP.SHOPCNT,0) AS SHOPCNT,ISNULL(APPROVEEXP.APPROVEEXPAMT,0) AS APPROVEEXPAMT,'
	SET @Strsql+='ISNULL(SHOPVISITCONVRATE.NORDSHPCNT,0) AS NORDSHPCNT,ISNULL(SHOPVISITCONVRATE.NEWSHOPVISITCONVRATE,0) AS NEWSHOPVISITCONVRATE,ISNULL(SHOPVISITCONVRATE.RORDSHPCNT,0) AS RORDSHPCNT,'
	SET @Strsql+='ISNULL(SHOPVISITCONVRATE.REVISITCONVRATE,0) AS REVISITCONVRATE,ISNULL(SPENT_DURATION,0) AS SPENT_DURATION,ISNULL(SNV.CNTVISITTIME,0) AS CNTVISITTIME,ISNULL(VTC.VISITDIFF,0) AS VISITDIFF,'
	SET @Strsql+='ISNULL(AWD.LOGINOUTDIFF,0) AS LOGINOUTDIFF,ISNULL(AWD.CNTATTENDANCE,0) AS CNTATTENDANCE,ISNULL(DISTANCE_TRAVELLED,0) AS DISTANCE_TRAVELLED,ISNULL(AWD.TOTNOOFFULLDAYS,0) AS TOTNOOFFULLDAYS,'
	SET @Strsql+='ISNULL(AWD.TOTNOOFHALFDAYS,0) AS TOTNOOFHALFDAYS,ISNULL(USRLEAVE.CNTSTATUS,0) AS CNTSTATUS,ISNULL(ABSNT.CNTNOWORKTIME,0)+ISNULL(AWD.LESSTWOHRSWORK,0)+ISNULL(USRRPLEAVE.CNTRPSTATUS,0) AS TOTALABSENT '
	SET @Strsql+='FROM tbl_master_employee EMP WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_branch BR WITH(NOLOCK) ON CNT.cnt_branchid=BR.branch_id '
	SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR WITH(NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN TBL_MASTER_CITY CITY WITH(NOLOCK) ON ADDR.add_city=CITY.city_id '
	SET @Strsql+='INNER JOIN tbl_master_state ST WITH(NOLOCK) ON ADDR.add_state=ST.id '
	SET @Strsql+='INNER JOIN (SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @Strsql+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP WITH(NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH(NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN (SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH(NOLOCK) '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg WITH(NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @Strsql+=') DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN (SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,cnt_internalId,Login_datetime FROM('
	SET @Strsql+='SELECT USERID,LOGGEDIN,cnt_internalId,Login_datetime FROM #TMPATTENLOGINTSI '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime ) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+='LEFT OUTER JOIN (SELECT User_Id,cnt_internalId,Shop_Id,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,VISITED_TIME,'
	SET @Strsql+='SUM(CAST(SUBSTRING(SPENT_DURATION,1,2) AS INT)*60+CAST(SUBSTRING(SPENT_DURATION,4,2) AS INT)) AS SPENT_DURATION,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED FROM('
	SET @Strsql+='SELECT USER_ID,cnt_internalId,Shop_Id,NEWSHOP_VISITED,RE_VISITED,VISITED_TIME,SPENT_DURATION,DISTANCE_TRAVELLED FROM #TMPSHOPSUBMITACTTSI ) AA '
	SET @Strsql+='GROUP BY User_Id,cnt_internalId,Shop_Id,VISITED_TIME,SPENT_DURATION '
	SET @Strsql+=') SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME '
	SET @Strsql+='LEFT OUTER JOIN (SELECT shop.Shop_CreateUser,COUNT(shop.Shop_Code) AS SHOPCNT FROM tbl_Master_shop shop WITH(NOLOCK) '
	SET @Strsql+='GROUP BY shop.Shop_CreateUser '
	SET @Strsql+=') SHOP ON USR.user_id=SHOP.Shop_CreateUser '
	IF @IsActivateNewOrderScreenwithSize=0
		BEGIN
			SET @Strsql+='LEFT OUTER JOIN ('
			SET @Strsql+='SELECT ORDH.userID,ORDH.SHOP_CODE,CNT.cnt_internalId,COUNT(ORDH.SHOP_CODE) AS ORDSHPCNT,SUM(ISNULL(Ordervalue,0)) AS Ordervalue,CONVERT(NVARCHAR(10),ORDH.Orderdate,105) AS ORDDATE '
			SET @Strsql+='FROM tbl_trans_fts_Orderupdate ORDH WITH(NOLOCK) '
			SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ORDH.userID '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.Orderdate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY ORDH.userID,ORDH.SHOP_CODE,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORDH.Orderdate,105) '
			SET @Strsql+=') ORDHEAD ON CNT.cnt_internalId=ORDHEAD.cnt_internalId AND ATTEN.Login_datetime=ORDHEAD.ORDDATE AND SHOPACT.Shop_Id=ORDHEAD.SHOP_CODE '
		END
	ELSE IF @IsActivateNewOrderScreenwithSize=1
		BEGIN
			SET @Strsql+='LEFT OUTER JOIN ('
			SET @Strsql+='SELECT ORDH.USER_ID,ORDH.SHOP_CODE,CNT.cnt_internalId,COUNT(ORDH.SHOP_CODE) AS ORDSHPCNT,SUM(ISNULL(ORDH.Ordervalue,0)) AS Ordervalue,CONVERT(NVARCHAR(10),ORDH.ORDER_DATE,105) AS ORDDATE '
			SET @Strsql+='FROM #TMPORDATTRIBUTETSI ORDH '
			SET @Strsql+='INNER JOIN tbl_master_user USR WITH(NOLOCK) ON USR.user_id=ORDH.USER_ID '
			SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.ORDER_DATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @Strsql+='GROUP BY ORDH.USER_ID,ORDH.SHOP_CODE,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ORDH.ORDER_DATE,105) '
			SET @Strsql+=') ORDHEAD ON CNT.cnt_internalId=ORDHEAD.cnt_internalId AND ATTEN.Login_datetime=ORDHEAD.ORDDATE AND SHOPACT.Shop_Id=ORDHEAD.SHOP_CODE '
		END
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT EmployeeCode,SUM(ISNULL(OrderValue,0)) AS TARGETORDVALUE FROM tbl_FTS_EmployeesTargetSetting WITH(NOLOCK) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),FromDate,120)>=CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),ToDate,120)<=CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY EmployeeCode '
	SET @Strsql+=') TARGETORDER ON CNT.cnt_internalId=TARGETORDER.EmployeeCode '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT UserID,SUM(ISNULL(Amount,0)) AS APPROVEEXPAMT FROM FTS_Reimbursement_Application_Verified WITH(NOLOCK) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),Date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY UserID '
	SET @Strsql+=') APPROVEEXP ON USR.user_id=APPROVEEXP.UserID '
	SET @Strsql+='LEFT OUTER JOIN (SELECT User_Id,cnt_internalId,SUM(NEWSHOPVISITCONVRATE) AS NEWSHOPVISITCONVRATE,SUM(NORDSHPCNT) AS NORDSHPCNT,SUM(REVISITCONVRATE) AS REVISITCONVRATE,'
	SET @Strsql+='SUM(RORDSHPCNT) AS RORDSHPCNT FROM('
	SET @Strsql+='SELECT USER_ID,cnt_internalId,NEWSHOPVISITCONVRATE,NORDSHPCNT,REVISITCONVRATE,RORDSHPCNT FROM #TMPSHOPVISITREVISITCONVRATE ) AA '
	SET @Strsql+='GROUP BY User_Id,cnt_internalId '
	SET @Strsql+=') SHOPVISITCONVRATE ON USR.user_id=SHOPVISITCONVRATE.USER_ID AND CNT.cnt_internalId=SHOPVISITCONVRATE.cnt_internalId '
	SET @Strsql+='LEFT OUTER JOIN #TMPSHOPNOVISIT SNV ON USR.USER_ID=SNV.USER_ID '
	SET @Strsql+='LEFT OUTER JOIN #TMPVISITTOCALL VTC ON USR.USER_ID=VTC.USERID AND CNT.cnt_internalId=VTC.CNT_INTERNALID '
	SET @Strsql+='LEFT OUTER JOIN #TMPATTENWRKHRS AWD ON USR.USER_ID=AWD.USERID AND CNT.cnt_internalId=AWD.CNT_INTERNALID '
	SET @Strsql+='LEFT OUTER JOIN (SELECT USER_ID,COUNT(CURRENT_STATUS) AS CNTSTATUS FROM FTS_USER_LEAVEAPPLICATION WITH(NOLOCK) '
	SET @Strsql+='WHERE CURRENT_STATUS=''APPROVE'' '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),LEAVE_START_DATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY USER_ID '
	SET @Strsql+=') USRLEAVE ON USR.user_id=USRLEAVE.USER_ID '
	SET @Strsql+='LEFT OUTER JOIN #TMPABSENT ABSNT ON USR.USER_ID=ABSNT.USER_ID '
	SET @Strsql+='LEFT OUTER JOIN (SELECT USER_ID,COUNT(CURRENT_STATUS) AS CNTRPSTATUS FROM FTS_USER_LEAVEAPPLICATION WITH(NOLOCK) '
	SET @Strsql+='WHERE CURRENT_STATUS IN(''REJECT'',''PENDING'') '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),LEAVE_START_DATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY USER_ID '
	SET @Strsql+=') USRRPLEAVE ON USR.user_id=USRRPLEAVE.USER_ID '
	SET @Strsql+=') AA '
	SET @Strsql+='GROUP BY EMPCODE,EMPUSERID,EMPID,EMPNAME,CITYID,EMPCITY,STATEID,STATE,BRANCHDESC,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTO,RPTTODESG '
	SET @Strsql+=') TSI '
	IF @STATEID<>'' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=TSI.STATEID) '
	ELSE IF @STATEID='' AND @EMPID<>''
		SET @Strsql+='WHERE EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=TSI.EMPCODE) '
	ELSE IF @STATEID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=TSI.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=TSI.EMPCODE) '
		END

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DROP TABLE #EMPHR_EDIT
			DROP TABLE #EMPHRS
		END
	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #TMPATTENLOGINTSI
	DROP TABLE #TMPSHOPSUBMITACTTSI
	DROP TABLE #TMPABSENT
	DROP TABLE #TMPALLDAYINMONTH
	DROP TABLE #TMPATTENWRKHRS
	DROP TABLE #TMPSHOPNOVISIT
	DROP TABLE #TMPSHOPVISITREVISITCONVRATE
	DROP TABLE #TMPSHOWSUNDAY
	DROP TABLE #TMPVISITTOCALL
	IF @IsActivateNewOrderScreenwithSize=1
		DROP TABLE #TMPORDATTRIBUTETSI
	
	SET NOCOUNT OFF
END