--EXEC PRC_FTSDSPERFORMANCESUMMARY_REPORT '2023-07-01','2024-06-11','','',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSDSPERFORMANCESUMMARY_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSDSPERFORMANCESUMMARY_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSDSPERFORMANCESUMMARY_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@BRANCHID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 23/11/2021
Module	   : Employee DS Performance Summary.Refer: 0024498
1.0		v2.0.27		Debashis	01/03/2022		Enhancement done.Refer: 0024715
2.0		v2.0.27		Debashis	04/03/2022		Query optimized.Refer: 0024733
3.0		v2.0.33		Debashis	09/10/2022		Code optimized.Refer: 0025331
4.0		v2.0.41		Debashis	09/08/2023		A coloumn named as Gender needs to be added in all the ITC reports.Refer: 0026680
5.0		v2.0.43		Debashis	28/12/2023		System is getting logged out while generating DS Summary & DS Performance report in ITC.Refer: 0027103
6.0		v2.0.45		Debashis	12/04/2024		The above mentioned two DS types need to be considered in the below reports.Refer: 0027360
7.0		v2.0.47		Debashis	03/06/2024		A new coloumn shall be added in the below mentioned reports.Refer: 0027402
8.0		v2.0.47		Debashis	11/06/2024		A new coloumn "Total CDM Days" is required. The coloumn shall be placed after "Total Delivery Value" coloumn.Refer: 0027508
9.0		v2.0.48		Debashis	05/07/2024		If IsEnd= 0 in FSMUSERWISEDAYSTARTEND, table for a user for a particular day then please consider the remarks 
												'Auto Update Cutoff Time' for market duration calculation.Refer: 0027603
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX),@DAYCOUNT INT

	SELECT @DAYCOUNT=DATEDIFF(D, @FROMDATE, @TODATE) +1

	IF OBJECT_ID('tempdb..#BRANCH_LIST') IS NOT NULL
		DROP TABLE #BRANCH_LIST
	CREATE TABLE #BRANCH_LIST (Branch_Id BIGINT NULL)
	CREATE NONCLUSTERED INDEX Branch_Id ON #BRANCH_LIST (Branch_Id ASC)

	IF @BRANCHID<>''
		BEGIN
			SET @SqlStrTable=''
			SET @BRANCHID=REPLACE(@BRANCHID,'''','')
			SET @sqlStrTable='INSERT INTO #BRANCH_LIST SELECT branch_id FROM tbl_master_branch WHERE branch_id IN ('+@BRANCHID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)

	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @SqlStrTable=''
			SET @SqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
			EXEC SP_EXECUTESQL @SqlStrTable
		END

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@Userid)		
			CREATE TABLE #EMPHRS
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)

			CREATE TABLE #EMPHR_EDIT
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)
			
			--Rev 3.0 && WITH (NOLOCK) has been added in all tables
			INSERT INTO #EMPHRS
			SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC WITH (NOLOCK)
			LEFT JOIN tbl_master_employee TME WITH (NOLOCK) ON TME.emp_id= CTC.emp_reportTO 
			WHERE emp_effectiveuntil IS NULL
		
			;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
			UNION ALL
			SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
			JOIN cte b ON a.RPTTOEMPCODE = b.EMPCODE
			) 
			INSERT INTO #EMPHR_EDIT
			SELECT EMPCODE,RPTTOEMPCODE FROM cte 
		END

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			--Rev 4.0
			cnt_sex TINYINT NULL,
			GENDERDESC NVARCHAR(100) NULL
			--End of Rev 4.0
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		BEGIN
			--Rev 3.0 && WITH (NOLOCK) has been added in all tables
			INSERT INTO #TEMPCONTACT
			SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,
			--Rev 4.0
			cnt_sex,CASE WHEN cnt_sex=1 THEN 'Male' WHEN cnt_sex=0 THEN 'Female' END GENDERDESC
			--End of Rev 4.0
			FROM TBL_MASTER_CONTACT WITH (NOLOCK)
			INNER JOIN #EMPHR_EDIT ON cnt_internalId=EMPCODE WHERE cnt_contactType IN('EM')
		END
	ELSE
		BEGIN
			--Rev 3.0 && WITH (NOLOCK) has been added in all tables
			INSERT INTO #TEMPCONTACT
			SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC,
			--Rev 4.0
			cnt_sex,CASE WHEN cnt_sex=1 THEN 'Male' WHEN cnt_sex=0 THEN 'Female' END GENDERDESC
			--End of Rev 4.0
			FROM TBL_MASTER_CONTACT WITH (NOLOCK)
			WHERE cnt_contactType IN('EM')
		END

	--Rev 2.0
	IF OBJECT_ID('tempdb..#TMPATTENLOGINOUT') IS NOT NULL
		DROP TABLE #TMPATTENLOGINOUT
	CREATE TABLE #TMPATTENLOGINOUT
	(USERID BIGINT,LOGGEDIN NVARCHAR(10),LOGEDOUT NVARCHAR(10),cnt_internalId NVARCHAR(10),Login_datetime NVARCHAR(10),ATTEN_STATUS NVARCHAR(20))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINOUT(USERID,cnt_internalId,Login_datetime)

	--Rev 3.0 && WITH (NOLOCK) has been added in all tables
	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPATTENLOGINOUT(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,ATTEN_STATUS) '
	SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @SqlStr+='CASE WHEN Isonleave=''false'' THEN ''Present'' ELSE ''Absent'' END AS ATTEN_STATUS '
	SET @SqlStr+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @SqlStr+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @SqlStr+='CASE WHEN Isonleave=''false'' THEN ''Present'' ELSE ''Absent'' END AS ATTEN_STATUS '
	SET @SqlStr+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	SET @SqlStr+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr
	--End of Rev 2.0

	--Rev 3.0
	IF OBJECT_ID('tempdb..#TMPSHOPACTIVITYSUBMITDSP') IS NOT NULL
		DROP TABLE #TMPSHOPACTIVITYSUBMITDSP
	CREATE TABLE #TMPSHOPACTIVITYSUBMITDSP
	(User_Id BIGINT,cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,NEWSHOP_VISITED INT,RE_VISITED INT,DISTANCE_TRAVELLED DECIMAL(18,2),SPENT_DURATION NVARCHAR(100),visited_time NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPACTIVITYSUBMITDSP(User_Id,cnt_internalId,visited_time)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPSHOPACTIVITYSUBMITDSP(User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,DISTANCE_TRAVELLED,SPENT_DURATION,visited_time) '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=1 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	IF OBJECT_ID('tempdb..#TMPDAYSTARTENDDSP') IS NOT NULL
		DROP TABLE #TMPDAYSTARTENDDSP
	--Rev 8.0 && A new column has been added as WORKACTIVITYDESCRIPTION NVARCHAR(500)
	CREATE TABLE #TMPDAYSTARTENDDSP
	(USERID BIGINT,DAYSTTIME NVARCHAR(10),DAYENDTIME NVARCHAR(10),STARTENDDATE NVARCHAR(10),SALE_VALUE DECIMAL(18,2),VISITDDID INT,WORKACTIVITYDESCRIPTION NVARCHAR(500))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPDAYSTARTENDDSP(USERID,STARTENDDATE)

	SET @SqlStr=''
	--Rev 8.0 && A new column has been added as WORKACTIVITYDESCRIPTION
	SET @SqlStr='INSERT INTO #TMPDAYSTARTENDDSP(USERID,DAYSTTIME,DAYENDTIME,STARTENDDATE,SALE_VALUE,VISITDDID,WORKACTIVITYDESCRIPTION) '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYSTTIME,NULL AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,'
	SET @SqlStr+='0.00 AS SALE_VALUE,0 AS VISITDDID,DAYSTEND.WORKACTIVITYDESCRIPTION '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	SET @SqlStr+='WHERE ISSTART=1 '
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE,DAYSTEND.WORKACTIVITYDESCRIPTION '
	SET @SqlStr+='UNION ALL '
	SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,NULL AS DAYSTTIME,MAX(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,'
	SET @SqlStr+='DAYSTEND.SALE_VALUE,COUNT(DAYSTEND.VISITDDID) AS VISITDDID,DAYSTEND.WORKACTIVITYDESCRIPTION '
	SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
	--Rev 9.0
	--SET @SqlStr+='WHERE ISEND=1 '
	SET @SqlStr+='WHERE (ISEND=1 OR REMARKS=''Auto Update Cutoff Time'') '
	--End of Rev 9.0
	SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE,DAYSTEND.SALE_VALUE,DAYSTEND.WORKACTIVITYDESCRIPTION '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr
	--End of Rev 3.0

	--Rev 7.0
	IF OBJECT_ID('tempdb..#TMPORDERDSP') IS NOT NULL
		DROP TABLE #TMPORDERDSP
	CREATE TABLE #TMPORDERDSP
	(USERID BIGINT,ORDER_DATE NVARCHAR(10),ORDER_VALUE DECIMAL (18,2))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPORDERDSP(USERID,ORDER_DATE)

	SET @SqlStr=''
	SET @SqlStr='INSERT INTO #TMPORDERDSP(USERID,ORDER_DATE,ORDER_VALUE) '
	SET @SqlStr+='SELECT ORD.USERID,CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,105) AS ORDER_DATE,SUM(ORD.ORDER_TOTALAMOUNT) AS ORDER_VALUE '
	SET @SqlStr+='FROM FSMITCORDERHEADER ORD WITH (NOLOCK) '
	SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ORD.ORDER_DATE_TIME,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @SqlStr+='GROUP BY ORD.USERID,ORD.ORDER_DATE_TIME '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr
	--End of Rev 7.0

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSPERFORMANCESUMMARY_REPORT') AND TYPE IN (N'U'))
		BEGIN
			--Rev 1.0 && Two new fields added as REPORTTOUID & HREPORTTOUID
			--Rev 4.0 && Two new fields added as OUTLETEMPSEX & GENDERDESC
			--Rev 7.0 && A new cloumn has been added as ORDER_VALUE
			--Rev 8.0 && A new column has been added as TOTALCDMDAYS INT
			CREATE TABLE FTSDSPERFORMANCESUMMARY_REPORT
			(
			  USERID INT,
			  SEQ INT,
			  BRANCH_ID BIGINT,
			  BRANCHDESC NVARCHAR(300),
			  EMPCODE NVARCHAR(100) NULL,
			  EMPID NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  DATEOFJOINING NVARCHAR(10),
			  CONTACTNO NVARCHAR(50) NULL,
			  REPORTTOID NVARCHAR(300) NULL,
			  REPORTTOUID NVARCHAR(100),
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESG NVARCHAR(50) NULL,
			  HREPORTTOID NVARCHAR(300) NULL,
			  HREPORTTOUID NVARCHAR(100),
			  HREPORTTO NVARCHAR(300) NULL,
			  HRPTTODESG NVARCHAR(50) NULL,
			  DATERANGE NVARCHAR(50) NULL,
			  DAYSPRESENT INT,
			  QUALIFYATTENDANCE INT,
			  DAYSPOINTVISITED INT,
			  NEWSHOP_VISITED INT,
			  RE_VISITED INT,
			  TOTAL_VISIT INT,
			  DISTANCE_TRAVELLED DECIMAL(38,2),
			  AVGTIMESPENTINMARKET NVARCHAR(50),
			  AVGSPENTDURATION NVARCHAR(50),
			  SALE_VALUE DECIMAL(18,2),
			  ORDER_VALUE NUMERIC(18,2),
			  OUTLETEMPSEX TINYINT,
			  GENDERDESC NVARCHAR(100),
			  TOTALCDMDAYS INT
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSDSPERFORMANCESUMMARY_REPORT (SEQ)
		END
	DELETE FROM FTSDSPERFORMANCESUMMARY_REPORT WHERE USERID=@USERID

	--Rev 1.0 && Two new fields added as REPORTTOUID & HREPORTTOUID
	--Rev 3.0 && WITH (NOLOCK) has been added in all tables
	--Rev 4.0 && Two new fields added as OUTLETEMPSEX & GENDERDESC
	--Rev 7.0 && A new cloumn has been added as ORDER_VALUE
	--Rev 8.0 && A new column has been added as TOTALCDMDAYS
	SET @SqlStr=''
	SET @SqlStr='INSERT INTO FTSDSPERFORMANCESUMMARY_REPORT(USERID,SEQ,BRANCH_ID,BRANCHDESC,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,'
	SET @SqlStr+='RPTTODESG,HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,DATERANGE,DAYSPRESENT,QUALIFYATTENDANCE,DAYSPOINTVISITED,NEWSHOP_VISITED,RE_VISITED,TOTAL_VISIT,DISTANCE_TRAVELLED,'
	SET @SqlStr+='AVGTIMESPENTINMARKET,AVGSPENTDURATION,SALE_VALUE,ORDER_VALUE,OUTLETEMPSEX,GENDERDESC,TOTALCDMDAYS)'
	SET @SqlStr+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY EMPCODE) AS SEQ,BRANCH_ID,BRANCH_DESCRIPTION,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,'
	SET @SqlStr+='CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,CONVERT(NVARCHAR(10),CAST('''+@FROMDATE+''' AS DATE),105)+'' - ''+CONVERT(NVARCHAR(10),CAST('''+@TODATE+''' AS DATE),105) AS DATERANGE,'
	SET @SqlStr+='DAYSPRESENT,QUALIFYATTENDANCE,DAYSPOINTVISITED,NEWSHOP_VISITED,RE_VISITED,TOTAL_VISIT,DISTANCE_TRAVELLED,'
	SET @SqlStr+='RIGHT(''0'' + CAST(CAST(AVGDAYSTARTENDDURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(AVGDAYSTARTENDDURATION AS VARCHAR) % 60 AS VARCHAR),2) AS AVGTIMESPENTINMARKET,'
	SET @SqlStr+='RIGHT(''0'' + CAST(CAST(SPENT_DURATION AS VARCHAR)/ 60 AS VARCHAR),2)  + '':'' +RIGHT(''0'' + CAST(CAST(SPENT_DURATION AS VARCHAR) % 60 AS VARCHAR),2) AS AVGSPENTDURATION,SALE_VALUE,ORDER_VALUE,'
	SET @SqlStr+='OUTLETEMPSEX,GENDERDESC,TOTALCDMDAYS '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTOUID,'
	SET @SqlStr+='HREPORTTO,HRPTTODESG,COUNT(ATTEN_STATUS) AS DAYSPRESENT,SUM(QUALIFYATTENDANCE) AS QUALIFYATTENDANCE,SUM(SALE_VALUE) AS SALE_VALUE,SUM(ORDER_VALUE) AS ORDER_VALUE,SUM(VISITDDID) AS DAYSPOINTVISITED,'
	SET @SqlStr+='SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,SUM(TOTAL_VISIT) AS TOTAL_VISIT,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED,SUM(DAYSTARTENDDURATION) AS DAYSTARTENDDURATION,'
	SET @SqlStr+='CAST(SUM(DAYSTARTENDDURATION)/'+LTRIM(RTRIM(STR(@DAYCOUNT)))+' AS INT) AS AVGDAYSTARTENDDURATION,'
	--Rev 5.0
	--CAST(SUM(SPENT_DURATION)/(SUM(CASE WHEN DAYSTARTENDDURATION=0 THEN 1 ELSE DAYSTARTENDDURATION END)/'+LTRIM(RTRIM(STR(@DAYCOUNT)))+') AS INT) AS SPENT_DURATION,'
	SET @SqlStr+='CAST(SUM(ISNULL(SPENT_DURATION,1))/((CASE WHEN SUM(CASE WHEN DAYSTARTENDDURATION=0 THEN 1 ELSE DAYSTARTENDDURATION END)=0 THEN 1 ELSE SUM(CASE WHEN DAYSTARTENDDURATION=0 THEN 1 ELSE DAYSTARTENDDURATION END) END)/'+LTRIM(RTRIM(STR(@DAYCOUNT)))+') AS INT) AS SPENT_DURATION,'
	--End of Rev 5.0
	SET @SqlStr+='OUTLETEMPSEX,GENDERDESC,SUM(DISTINCT TOTALCDMDAYS) AS TOTALCDMDAYS '
	SET @SqlStr+='FROM('
	SET @SqlStr+='SELECT BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,USR.USER_ID AS USERID,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,'
	SET @SqlStr+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @SqlStr+='ISNULL(ST.ID,0) AS STATEID,ISNULL(ST.state,''State Undefined'') AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
	SET @SqlStr+='USR.user_loginId AS CONTACTNO,ATTEN.LOGGEDIN,ATTEN.LOGEDOUT,RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTOID,HRPTTO.HREPORTTOUID,HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,'
	SET @SqlStr+='ISNULL(SHOPACT.NEWSHOP_VISITED,0) AS NEWSHOP_VISITED,ISNULL(SHOPACT.RE_VISITED,0) AS RE_VISITED,ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0) AS TOTAL_VISIT,'
	SET @SqlStr+='ISNULL(DISTANCE_TRAVELLED,0) AS DISTANCE_TRAVELLED,DAYSTARTEND.DAYSTTIME,DAYSTARTEND.DAYENDTIME,CASE WHEN ISNULL(LOGGEDIN,'''')<>'''' AND ATTEN_STATUS=''Present'' THEN 1 ELSE 0 END AS ATTEN_STATUS,'
	SET @SqlStr+='CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
	SET @SqlStr+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) AS DAYSTARTENDDURATION,'
	SET @SqlStr+='CASE WHEN (ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0))>=8 AND '
	SET @SqlStr+='(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYENDTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT) '
	SET @SqlStr+='- CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(DAYSTARTEND.DAYSTTIME,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT))>=240 '
	SET @SqlStr+='THEN 1 ELSE 0 END AS QUALIFYATTENDANCE,SPENT_DURATION,DAYSTARTEND.SALE_VALUE,ORD.ORDER_VALUE,DAYSTARTEND.VISITDDID,CNT.cnt_sex AS OUTLETEMPSEX,CNT.GENDERDESC,ISNULL(DAYSTARTEND.TOTALCDMDAYS,0) AS TOTALCDMDAYS '
	SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id '
	SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @SqlStr+='INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @SqlStr+='INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state '
	SET @SqlStr+='INNER JOIN ( '
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	--Rev 1.0
	--SET @SqlStr+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @SqlStr+='DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) '
	--End of Rev 1.0
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @SqlStr+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS HREPORTTO,'
	--Rev 1.0
	--SET @SqlStr+='DESG.deg_designation AS HRPTTODESG FROM tbl_master_employee EMP '
	SET @SqlStr+='DESG.deg_designation AS HRPTTODESG,CNT.cnt_UCC AS HREPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) '
	--End of Rev 1.0
	SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON HRPTTO.emp_cntId=RPTTO.REPORTTOID '
	SET @SqlStr+='INNER JOIN ('
	SET @SqlStr+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,ATTEN_STATUS FROM( '
	--Rev 2.0
	--SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	--SET @SqlStr+='CASE WHEN Isonleave=''false'' THEN ''Present'' ELSE ''Absent'' END AS ATTEN_STATUS '
	--SET @SqlStr+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	--SET @SqlStr+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	--SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	--SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave '
	--SET @SqlStr+='UNION ALL '
	--SET @SqlStr+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	--SET @SqlStr+='CASE WHEN Isonleave=''false'' THEN ''Present'' ELSE ''Absent'' END AS ATTEN_STATUS '
	--SET @SqlStr+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	--SET @SqlStr+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	--SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	--SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	--SET @SqlStr+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave '
	SET @SqlStr+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,ATTEN_STATUS FROM #TMPATTENLOGINOUT '
	--End of Rev 2.0
	SET @SqlStr+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,ATTEN_STATUS) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT User_Id,cnt_internalId,VISITED_TIME,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED,'
	--Rev 2.0
	--SET @SqlStr+='SUM(CAST(CAST(ISNULL(CAST((DATEPART(HOUR,ISNULL(SPENT_DURATION,''00:00:00'')) * 60) AS FLOAT) +CAST(DATEPART(MINUTE,ISNULL(SPENT_DURATION,''00:00:00'')) * 1 AS FLOAT),0) AS VARCHAR(100)) AS FLOAT)) AS SPENT_DURATION '
	SET @SqlStr+='SUM(CAST(SUBSTRING(SPENT_DURATION,1,2) AS INT)*60+CAST(SUBSTRING(SPENT_DURATION,4,2) AS INT)) AS SPENT_DURATION '
	--End of Rev 2.0
	SET @SqlStr+='FROM('
	--Rev 3.0
	--SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	--SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	--SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	--SET @SqlStr+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	--SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	--SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='AND SHOPACT.Is_Newshopadd=1 '
	--SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '
	--SET @SqlStr+='UNION ALL '
	--SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,SHOPACT.SPENT_DURATION,'
	--SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time '
	--SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	--SET @SqlStr+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	--SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	--SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	--SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.visited_time,SHOPACT.SPENT_DURATION '
	SET @SqlStr+='SELECT User_Id,cnt_internalId,NEWSHOP_VISITED,RE_VISITED,DISTANCE_TRAVELLED,SPENT_DURATION,visited_time FROM #TMPSHOPACTIVITYSUBMITDSP '
	--End of Rev 3.0
	SET @SqlStr+=') AA GROUP BY User_Id,cnt_internalId,VISITED_TIME) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME '
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT USERID,MIN(DAYSTTIME) AS DAYSTTIME,MAX(DAYENDTIME) AS DAYENDTIME,STARTENDDATE,SUM(SALE_VALUE) AS SALE_VALUE,SUM(VISITDDID) AS VISITDDID,'
	SET @SqlStr+='SUM(ISNULL(TOTALCDMDAYS,0)) AS TOTALCDMDAYS FROM('
	--Rev 3.0
	--SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYSTTIME,NULL AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,'
	--SET @SqlStr+='0.00 AS SALE_VALUE,0 AS VISITDDID '
	--SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WHERE ISSTART=1 '
	--SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE '
	--SET @SqlStr+='UNION ALL '
	--SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,NULL AS DAYSTTIME,MAX(CONVERT(VARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYENDTIME,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,'
	--SET @SqlStr+='DAYSTEND.SALE_VALUE,COUNT(DAYSTEND.VISITDDID) AS VISITDDID '
	--SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WHERE ISEND=1 '
	--SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	--SET @SqlStr+='GROUP BY DAYSTEND.User_Id,DAYSTEND.STARTENDDATE,DAYSTEND.SALE_VALUE '
	SET @SqlStr+='SELECT USERID,DAYSTTIME,DAYENDTIME,STARTENDDATE,SALE_VALUE,VISITDDID,CASE WHEN WORKACTIVITYDESCRIPTION=''CDM Day'' THEN 1 ELSE 0 END AS TOTALCDMDAYS FROM #TMPDAYSTARTENDDSP '
	--End of Rev 3.0
	SET @SqlStr+=') DAYSTEND GROUP BY USERID,STARTENDDATE) DAYSTARTEND ON DAYSTARTEND.USERID=USR.user_id AND ATTEN.Login_datetime=DAYSTARTEND.STARTENDDATE '
	--Rev 7.0
	SET @SqlStr+='LEFT OUTER JOIN ('
	SET @SqlStr+='SELECT USERID,ORDER_DATE,SUM(ORDER_VALUE) AS ORDER_VALUE FROM('
	SET @SqlStr+='SELECT USERID,ORDER_DATE,ORDER_VALUE FROM #TMPORDERDSP '
	SET @SqlStr+=') ORDDET GROUP BY USERID,ORDER_DATE) ORD ON ORD.USERID=USR.user_id AND ATTEN.Login_datetime=ORD.ORDER_DATE '
	--End of Rev 7.0
	--Rev 1.0
	--SET @SqlStr+='WHERE DESG.deg_designation=''DS'' '
	--Rev 6.0
	--SET @SqlStr+='WHERE DESG.deg_designation IN(''DS'',''TL'') '
	SET @SqlStr+='WHERE DESG.deg_designation=''DS'' AND USR.FaceRegTypeID IN(1,2,36,37) '
	--End of Rev 6.0
	--End of Rev 1.0
	IF @BRANCHID<>''
		SET @SqlStr+='AND EXISTS (SELECT Branch_Id FROM #Branch_List AS F WHERE F.Branch_Id=BR.branch_id) '
	IF @EMPID<>''
		SET @SqlStr+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	--Rev 1.0
	--SET @SqlStr+=') DSSUMM GROUP BY BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTO,'
	--SET @SqlStr+='HRPTTODESG '
	SET @SqlStr+=') DSSUMM GROUP BY BRANCH_ID,BRANCH_DESCRIPTION,USERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,'
	SET @SqlStr+='HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,OUTLETEMPSEX,GENDERDESC '
	--End of Rev 1.0
	SET @SqlStr+=') DSSUMMARY '

	--SELECT @SqlStr
	EXEC SP_EXECUTESQL @SqlStr

	DROP TABLE #BRANCH_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #EMPLOYEE_LIST
	--Rev 2.0
	DROP TABLE #TMPATTENLOGINOUT
	--End of Rev 2.0

	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
	BEGIN
		DROP TABLE #EMPHR_EDIT
		DROP TABLE #EMPHRS
	END
	--Rev 3.0
	DROP TABLE #TMPDAYSTARTENDDSP
	DROP TABLE #TMPSHOPACTIVITYSUBMITDSP
	--End of Rev 3.0
	--Rev 7.0
	DROP TABLE #TMPORDERDSP
	--End of Rev 7.0
	
	SET NOCOUNT OFF
END
GO