--EXEC PRC_FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT '2019-06-12','2019-06-12','15','','EMP0000032','Details',378
--EXEC PRC_FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT '2019-05-01','2019-05-31','','','EM 0000001','Summary',378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@REPORTTYPE NVARCHAR(10),
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder on 12/06/2019
Module	   : Employee Re-visit variance - Details & Summary
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX), @sqlStrTable NVARCHAR(MAX)

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#STATEID_LIST') AND TYPE IN (N'U'))
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #STATEID_LIST SELECT id from tbl_master_state where id in('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END
	
	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#DESIGNATION_LIST') AND TYPE IN (N'U'))
		DROP TABLE #DESIGNATION_LIST
	CREATE TABLE #DESIGNATION_LIST (deg_id INT)
	CREATE NONCLUSTERED INDEX IX2 ON #DESIGNATION_LIST (deg_id ASC)
	IF @DESIGNID <> ''
		BEGIN
			SET @DESIGNID=REPLACE(@DESIGNID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #DESIGNATION_LIST SELECT deg_id from tbl_master_designation where deg_id in('+@DESIGNID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#EMPLOYEE_LIST') AND TYPE IN (N'U'))
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId from tbl_master_employee where emp_contactId in('+@EMPID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#TEMPCONTACT') AND TYPE IN (N'U'))
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#TMPMASTERSHOP') AND TYPE IN (N'U'))
		DROP TABLE #TMPMASTERSHOP
	CREATE TABLE #TMPMASTERSHOP
	(
	Shop_ID INT,
	Shop_Code NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,
	Shop_CreateUser INT,
	Shop_Name NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,
	Address NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS,
	Shop_Owner_Contact NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS,
	Pincode NVARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS,
	SHOPSTAT NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS,
	SHOP_TYPE NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS
	)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPMASTERSHOP(Shop_ID,Shop_CreateUser,Shop_Code ASC)
	INSERT INTO #TMPMASTERSHOP SELECT DISTINCT Shop_ID,Shop_Code,Shop_CreateUser,Shop_Name,Address,Shop_Owner_Contact,Pincode,STAT.state AS SHOPSTAT,
	CASE WHEN TYPE=1 THEN 'Shop' WHEN TYPE=2 THEN 'PP' WHEN TYPE=3 THEN 'New Party' WHEN TYPE=4 THEN 'DD' END AS SHOP_TYPE FROM tbl_Master_shop 
	INNER JOIN tbl_master_state STAT ON STAT.id=tbl_Master_shop.stateId

	IF EXISTS (SELECT * FROM sys.objects WHERE object_id=OBJECT_ID(N'#TMPREVISVARIANCE') AND TYPE IN (N'U'))
		DROP TABLE #TMPREVISVARIANCE
	CREATE TABLE #TMPREVISVARIANCE
	(
	SEQ INT,
	EMPCODE	NVARCHAR(10),
	EMPNAME NVARCHAR(300),
	STATEID INT,
	STATE NVARCHAR(300),
	DEG_ID NUMERIC(18,0),
	DESIGNATION NVARCHAR(300),
	CONTACTNO NVARCHAR(100),
	REPORTTO NVARCHAR(300),
	RPTTODESG NVARCHAR(300),
	SHOP_CODE NVARCHAR(100),
	SHOP_NAME NVARCHAR(100),
	SHOP_OWNER_CONTACT NVARCHAR(100),
	SHOPADDR NVARCHAR(300),
	SHOPSTAT NVARCHAR(300),
	SHOPPIN NVARCHAR(120),
	SHOP_TYPE NVARCHAR(100),
	REVISITTGDATE NVARCHAR(10),
	TARGETRV INT,
	REVISITDATE NVARCHAR(10),
	NEWVISITDATE NVARCHAR(10),
	ACHIEVEMENT INT,
	REMARKS NVARCHAR(100)
	)
	CREATE NONCLUSTERED INDEX IX1 ON #TMPREVISVARIANCE(SEQ ASC)

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT
			(
			USERID INT,
			REPORTTYPE NVARCHAR(10),
			SEQ INT,
			EMPCODE	NVARCHAR(10),
			EMPNAME NVARCHAR(300),
			STATEID INT,
			STATE NVARCHAR(300),
			DEG_ID NUMERIC(18,0),
			DESIGNATION NVARCHAR(300),
			CONTACTNO NVARCHAR(100),
			REPORTTO NVARCHAR(300),
			RPTTODESG NVARCHAR(300),
			SHOP_CODE NVARCHAR(100),
			SHOP_NAME NVARCHAR(100),
			SHOP_OWNER_CONTACT NVARCHAR(100),
			SHOPADDR NVARCHAR(300),
			SHOPSTAT NVARCHAR(300),
			SHOPPIN NVARCHAR(120),
			SHOP_TYPE NVARCHAR(100),
			REVISITTGDATE NVARCHAR(10),
			TARGETRV INT,
			REVISITDATE NVARCHAR(10),
			NEWVISITDATE NVARCHAR(10),
			NEWVISITCNT INT,
			ACHIEVEMENT INT,
			REMARKS NVARCHAR(100)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT (SEQ)
		END
	DELETE FROM FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT WHERE USERID=@USERID AND REPORTTYPE=@REPORTTYPE

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPREVISVARIANCE '
	SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY EMPCODE) AS SEQ,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REPORTTO,RPTTODESG,SHOP_CODE,SHOP_NAME,SHOP_OWNER_CONTACT,SHOPADDR,SHOPSTAT,'
	SET @Strsql+='SHOPPIN,SHOP_TYPE,REVISITTGDATE,TARGETRV,REVISITDATE,NEWVISITDATE,'
	IF @REPORTTYPE='Details'
		SET @Strsql+='CASE WHEN (REVISITDATE IS NOT NULL OR NEWVISITDATE IS NOT NULL) THEN 1 ELSE 0 END AS ACHIEVEMENT,'
	ELSE IF @REPORTTYPE='Summary'
		SET @Strsql+='CASE WHEN (REVISITDATE IS NOT NULL AND NEWVISITDATE IS NULL) THEN 1 ELSE 0 END AS ACHIEVEMENT,'
	SET @Strsql+='CASE WHEN NEWVISITDATE IS NOT NULL THEN ''New Visit'' ELSE NULL END AS REMARKS FROM ('
	SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,'
	SET @Strsql+='DESG.deg_designation AS DESIGNATION,USR.user_loginId AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,SHOP.SHOP_CODE,SHOP.SHOP_NAME,SHOP.SHOP_OWNER_CONTACT,SHOP.Address AS SHOPADDR,'
	SET @Strsql+='SHOP.SHOPSTAT,SHOP.Pincode AS SHOPPIN,SHOP.SHOP_TYPE,SHREV.REVISITTGDATE,CASE WHEN SHREV.REVISITTGDATE IS NOT NULL THEN 1 ELSE 0 END AS TARGETRV,'
	SET @Strsql+='SHOPACT.REVISITDATE,CASE WHEN SHREV.REVISITTGDATE IS NOT NULL THEN NULL ELSE SHOPACT.NEWVISITDATE END AS NEWVISITDATE '
	SET @Strsql+='FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @Strsql+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT USERID,cnt_internalId,Login_datetime FROM('
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),ATTEN.Isonleave '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime '
	SET @Strsql+=') ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT User_Id,cnt_internalId,Shop_Id,VISITED_TIME,REVISITDATE,NEWVISITDATE FROM( '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time,NULL AS REVISITDATE,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS NEWVISITDATE '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=1 GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS visited_time,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS REVISITDATE,NULL AS NEWVISITDATE '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND SHOPACT.Is_Newshopadd=0 GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time '
	SET @Strsql+=') AA GROUP BY User_Id,cnt_internalId,Shop_Id,VISITED_TIME,REVISITDATE,NEWVISITDATE) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_TIME '
	SET @Strsql+='INNER JOIN #TMPMASTERSHOP SHOP ON SHOP.Shop_CreateUser=USR.user_id AND SHOP.Shop_Code=SHOPACT.Shop_Id '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT LOGIN_ID,SHOP_ID,CONVERT(NVARCHAR(10),REVISITDATE,105) AS REVISITTGDATE FROM FTS_SHOP_REVISIT '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),REVISITDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+=') SHREV ON USR.user_loginId=SHREV.LOGIN_ID AND SHOP.Shop_ID=SHREV.SHOP_ID '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT A.EMPLOYEE_CODE AS EMPCODE,A.EMPLOYEE_NAME AS EMPNAME,ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,'
	SET @Strsql+='DESG.deg_designation AS DESIGNATION,A.LOGIN_ID AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,A.SHOP_CODE,A.SHOP_NAME,A.SHOP_CONTACT AS SHOP_OWNER_CONTACT,A.SHOP_ADDRESS AS SHOPADDR,'
	SET @Strsql+='A.SHOP_STATE AS SHOPSTAT,A.SHOPPIN AS SHOPPIN,A.SHOP_TYPE,CONVERT(NVARCHAR(10),A.REVISITDATE,105) AS REVISITTGDATE,1 AS TARGETRV,NULL AS REVISITDATE,NULL AS NEWVISITDATE '
	SET @Strsql+='FROM FTS_SHOP_REVISIT A '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=A.EMPLOYEE_CODE '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=A.EMPLOYEE_CODE AND USR.user_inactive=''N'' '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=A.EMPLOYEE_CODE '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) AS emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
	SET @Strsql+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='WHERE NOT EXISTS(SELECT B.User_Id FROM tbl_trans_shopActivitysubmit B WHERE A.USER_ID=B.User_Id AND A.SHOP_CODE=B.Shop_Id '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),A.REVISITDATE,120)=CONVERT(NVARCHAR(10),B.visited_time,120)) '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),A.REVISITDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+=') AS REVSTVARIANCE '
	IF @STATEID<>'' AND @DESIGNID='' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=REVSTVARIANCE.STATEID) '
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=REVSTVARIANCE.deg_id) '
	ELSE IF @STATEID='' AND @DESIGNID='' AND @EMPID<>''
		SET @Strsql+='WHERE EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=REVSTVARIANCE.EMPCODE) '
	ELSE IF @STATEID<>'' AND @DESIGNID='' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=REVSTVARIANCE.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=REVSTVARIANCE.EMPCODE) '
		END
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=REVSTVARIANCE.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=REVSTVARIANCE.EMPCODE) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID=''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=REVSTVARIANCE.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=REVSTVARIANCE.deg_id) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=REVSTVARIANCE.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=REVSTVARIANCE.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=REVSTVARIANCE.EMPCODE) '
		END
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF @REPORTTYPE='Details'
		BEGIN
			INSERT INTO FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT(USERID,REPORTTYPE,SEQ,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REPORTTO,RPTTODESG,SHOP_CODE,SHOP_NAME,SHOP_OWNER_CONTACT,
			SHOPADDR,SHOPSTAT,SHOPPIN,SHOP_TYPE,REVISITTGDATE,TARGETRV,REVISITDATE,NEWVISITDATE,ACHIEVEMENT,REMARKS)
			SELECT @USERID,@REPORTTYPE,SEQ,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REPORTTO,RPTTODESG,SHOP_CODE,SHOP_NAME,SHOP_OWNER_CONTACT,SHOPADDR,SHOPSTAT,SHOPPIN,SHOP_TYPE,
			REVISITTGDATE,TARGETRV,REVISITDATE,NEWVISITDATE,ACHIEVEMENT,REMARKS FROM #TMPREVISVARIANCE
		END
	ELSE IF @REPORTTYPE='Summary'
		BEGIN
			INSERT INTO FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT(USERID,REPORTTYPE,SEQ,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REVISITTGDATE,TARGETRV,REVISITDATE,NEWVISITCNT,ACHIEVEMENT)
			SELECT @USERID,@REPORTTYPE,ROW_NUMBER() OVER(ORDER BY EMPCODE) AS SEQ,EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REVISITTGDATE,SUM(TARGETRV) AS TARGETRV,REVISITDATE,
			COUNT(CASE WHEN NEWVISITDATE IS NOT NULL AND REVISITDATE IS NULL THEN NEWVISITDATE ELSE NULL END) AS NEWVISITCNT,SUM(ACHIEVEMENT) AS ACHIEVEMENT FROM #TMPREVISVARIANCE
			GROUP BY EMPCODE,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,CONTACTNO,REVISITTGDATE,REVISITDATE
		END

	DROP TABLE #DESIGNATION_LIST
	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #TMPMASTERSHOP
	DROP TABLE #TMPREVISVARIANCE
END