IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIAADHARIMAGEDETECTION]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIAADHARIMAGEDETECTION] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIAADHARIMAGEDETECTION]
(
@ACTION NVARCHAR(20),
@USER_ID BIGINT=NULL,
@PathImage NVARCHAR(500)=NULL,
@RegisterDateTime DATETIME=NULL,
@NAMEONAADHAR NVARCHAR(300)=NULL,
@AADHARDOB DATETIME=NULL,
@AADHAAR_NO NVARCHAR(50)=NULL,
@REG_DOC_TYP NVARCHAR(100)=NULL
) --WITH ENCRYPTION
AS
/***************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 01/12/2021
Purpose : For Aadhar Image Detection API.
1.0		v2.0.27		Debashis	10-02-2022		New feature for DOB & name check only where aadhaar to be avoid.Refer: 0024683
***************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='SAVEAADHARIMAGE'
		BEGIN
			UPDATE tbl_master_user SET AadharImage=@PathImage,isAadharRegistered=1,AadharRegistration_Datetime=@RegisterDateTime WHERE user_id=@USER_ID

			SELECT user_id,AadharImage,isAadharRegistered,CONVERT(NVARCHAR(10),AadharRegistration_Datetime,105)+CONVERT(VARCHAR(5),CAST(Registration_Datetime AS TIME),108) AS AadharRegistration_Datetime 
			FROM tbl_master_user WHERE user_id=@USER_ID
		END
	IF @ACTION='INSERTAADHARINFO'
		BEGIN
			IF NOT EXISTS(SELECT USER_ID FROM FSMUSERAADHARIMAGEDETECTION WHERE USER_ID=@USER_ID OR NAMEONAADHAR=@NAMEONAADHAR OR AADHARDOB=@AADHARDOB OR AADHAAR_NO=@AADHAAR_NO)
				BEGIN
					INSERT INTO FSMUSERAADHARIMAGEDETECTION(USER_ID,NAMEONAADHAR,AADHARDOB,AADHAAR_NO,DOCUMENTIMAGEPATH,REG_DOC_TYPE)
					SELECT @USER_ID,@NAMEONAADHAR,@AADHARDOB,@AADHAAR_NO,(SELECT AadharImage FROM tbl_master_user WHERE user_id=@USER_ID AND isAadharRegistered=1),@REG_DOC_TYP

					SELECT USER_ID,NAMEONAADHAR,AADHAAR_NO,'Unique' AS STRMESSAGE FROM FSMUSERAADHARIMAGEDETECTION WHERE USER_ID=@USER_ID
				END
			IF EXISTS(SELECT USER_ID FROM FSMUSERAADHARIMAGEDETECTION WHERE USER_ID=@USER_ID AND NAMEONAADHAR=@NAMEONAADHAR AND AADHARDOB=@AADHARDOB AND AADHAAR_NO=@AADHAAR_NO)
				BEGIN
					UPDATE FSMUSERAADHARIMAGEDETECTION SET NAMEONAADHAR=@NAMEONAADHAR,AADHARDOB=@AADHARDOB,AADHAAR_NO=@AADHAAR_NO,
					DOCUMENTIMAGEPATH=(SELECT AadharImage FROM tbl_master_user WHERE user_id=@USER_ID AND isAadharRegistered=1),REG_DOC_TYPE=@REG_DOC_TYP
					WHERE USER_ID=@USER_ID

					SELECT USER_ID,NAMEONAADHAR,AADHAAR_NO,'Unique' AS STRMESSAGE FROM FSMUSERAADHARIMAGEDETECTION WHERE USER_ID=@USER_ID
				END
			--Rev 1.0
			--IF EXISTS(SELECT USER_ID FROM FSMUSERAADHARIMAGEDETECTION WHERE NAMEONAADHAR=@NAMEONAADHAR OR AADHARDOB=@AADHARDOB OR AADHAAR_NO=@AADHAAR_NO)
			IF EXISTS(SELECT USER_ID FROM FSMUSERAADHARIMAGEDETECTION WHERE NAMEONAADHAR=@NAMEONAADHAR AND AADHARDOB=@AADHARDOB)
			--End of Rev 1.0
				SELECT USER_ID,NAMEONAADHAR,AADHAAR_NO,'Duplicate' AS STRMESSAGE FROM FSMUSERAADHARIMAGEDETECTION WHERE NAMEONAADHAR=@NAMEONAADHAR OR AADHARDOB=@AADHARDOB OR AADHAAR_NO=@AADHAAR_NO
		END

	SET NOCOUNT OFF
END