IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_DELETEALLRECORDSFROMREPORTTABLES_REPORT]') AND type in (N'P', N'PC')) 
BEGIN 
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_DELETEALLRECORDSFROMREPORTTABLES_REPORT] AS'  
END 
GO 

ALTER PROCEDURE [dbo].[PRC_DELETEALLRECORDSFROMREPORTTABLES_REPORT]
--WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 11/01/2023
Module	   : Delete all records from reports related tables.
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FSMDASHBOARD_TEMPAVGSHOPVISIT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FSMDASHBOARD_TEMPAVGSHOPVISIT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FSMDASHBOARD_TEMPSHOPVISIT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FSMDASHBOARD_TEMPSHOPVISIT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDASHBOARD_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDASHBOARD_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDASHBOARDGRIDDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDASHBOARDGRIDDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDASHBOARDWIDGET_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDASHBOARDWIDGET_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTEAMVISITDASHBOARD_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSTEAMVISITDASHBOARD_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTEAMVISITDASHBOARD_REPORT_HIERARCHY') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSTEAMVISITDASHBOARD_REPORT_HIERARCHY
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSLEAVELIST_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSLEAVELIST_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'EMPLOYEE_LATE_VISIT_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM EMPLOYEE_LATE_VISIT_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'SHOPRATING_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM SHOPRATING_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSPARTYPLAN_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSPARTYPLAN_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSATTENDANCEREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSATTENDANCEREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSSALESORDERANALYSIS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSSALESORDERANALYSIS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEPERFORMANCE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEPERFORMANCE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSATTENDANCEWISEPERFORMANCE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSATTENDANCEWISEPERFORMANCE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSPERFORMANCESUMMARYMONTHWISE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSPERFORMANCESUMMARYMONTHWISE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEREVISITVARIANCESUMMDET_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSATTENDANCEVSPRODUCTIVITYRATIO_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSATTENDANCEVSPRODUCTIVITYRATIO_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_PJPvsActualSummaryReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_PJPvsActualSummaryReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_QUOTATIONREGISTERREPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_QUOTATIONREGISTERREPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_EmployeeAchievementDetailsReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_EmployeeAchievementDetailsReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_TargetVsAcchivementReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_TargetVsAcchivementReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'LATESMS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM LATESMS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_PJPvsActualDetailsReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_PJPvsActualDetailsReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_MeetingDetailsReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_MeetingDetailsReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_ActivityDetailsReport') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_ActivityDetailsReport
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEPERFORMANCEDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEPERFORMANCEDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEPERFORMANCEVISITREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEPERFORMANCEVISITREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEOUTLETMASTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEOUTLETMASTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSSUMMARY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDSSUMMARY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSPERFORMANCESUMMARY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDSPERFORMANCESUMMARY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSVISITDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDSVISITDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSGPSSTATISTICS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSGPSSTATISTICS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSQUOTATIONDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSQUOTATIONDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDSVISITDETAILSHIERARCHYCHANNELWISE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSORDERREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSORDERREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_ORDER_STATUS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_ORDER_STATUS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSINVOICEREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSINVOICEREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSORDERREGISTER_HIERARCHY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSORDERREGISTER_HIERARCHY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSORDERWITHPRODUCTATTRIBUTE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSORDERWITHPRODUCTATTRIBUTE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSLEADREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSLEADREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSRETURNREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSRETURNREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSPAITENTORDERREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSPAITENTORDERREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSCOLLECTIONREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSCOLLECTIONREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSSALESSUMMARY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSSALESSUMMARY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSACTIVITY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSACTIVITY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSLOCATION_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSLOCATION_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSSALESDETAILSDAYWISE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSSALESDETAILSDAYWISE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEACTIVITYSTATUS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEACTIVITYSTATUS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEACTIVITYDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSEMPLOYEEACTIVITYDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSCUSTOMERVISITDETAILS_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSCUSTOMERVISITDETAILS_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDAILYACCOUNTABILITYTRACKER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDAILYACCOUNTABILITYTRACKER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDOCTORACTIVITY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDOCTORACTIVITY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSCHEMISTACTIVITY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSCHEMISTACTIVITY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSCURRENTSTOCK_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSCURRENTSTOCK_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSCOMPETITORSTOCK_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSCOMPETITORSTOCK_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSSTOCKPOSITION_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSSTOCKPOSITION_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSBREAKAGETRACKREGISTER_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSBREAKAGETRACKREGISTER_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSDEALERDISTRIBUTORWISEPERFORMANCE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSDEALERDISTRIBUTORWISEPERFORMANCE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSTERRITORYSALESINCHARGEWISEPERFORMANCE_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSTERRITORYSALESINCHARGEPERFORMANCEANALY_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTSTERRITORYSALESINCHARGEPERFORMANCEANALY_REPORT
		END

	IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTS_EMPLIST_REPORT') AND TYPE IN (N'U'))
        BEGIN
			DELETE FROM FTS_EMPLIST_REPORT
		END

	SET NOCOUNT OFF
END