--EXEC PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT '2020-06-19','2020-06-19','','','EMB0000002',378
--EXEC PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT '2022-12-01','2023-01-31','','','',1,378
--EXEC PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT '2023-01-31','2023-02-01','','','EMK0000044',0,378

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@ISREVISITCONTACTDETAILS INT=NULL,
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder on 31/01/2023
Module	   : Employee Performance Analytics.Refer: 0025620
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX), @sqlStrTable NVARCHAR(MAX)
	DECLARE @isRevisitTeamDetail NVARCHAR(100)
	SELECT @isRevisitTeamDetail=[Value] FROM fts_app_config_settings WHERE [Key]='isRevisitTeamDetail' AND [Description]='Revisit from Team Details in Portal'

	IF OBJECT_ID('tempdb..#STATEID_LIST') IS NOT NULL
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #STATEID_LIST SELECT id from tbl_master_state where id in('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END
	
	IF OBJECT_ID('tempdb..#DESIGNATION_LIST') IS NOT NULL
		DROP TABLE #DESIGNATION_LIST
	CREATE TABLE #DESIGNATION_LIST (deg_id INT)
	CREATE NONCLUSTERED INDEX IX2 ON #DESIGNATION_LIST (deg_id ASC)
	IF @DESIGNID <> ''
		BEGIN
			SET @DESIGNID=REPLACE(@DESIGNID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #DESIGNATION_LIST SELECT deg_id from tbl_master_designation where deg_id in('+@DESIGNID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId from tbl_master_employee where emp_contactId in('+@EMPID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF ((select IsAllDataInPortalwithHeirarchy from tbl_master_user where user_id=@USERID)=1)
		BEGIN
			DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@USERID)		
			CREATE TABLE #EMPHRS
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)

			CREATE TABLE #EMPHR_EDIT
			(
			EMPCODE VARCHAR(50),
			RPTTOEMPCODE VARCHAR(50)
			)
		
			INSERT INTO #EMPHRS
			SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 
			FROM tbl_trans_employeeCTC CTC LEFT JOIN tbl_master_employee TME on TME.emp_id= CTC.emp_reportTO WHERE emp_effectiveuntil IS NULL
		
			;with cte as(SELECT	
			EMPCODE,RPTTOEMPCODE
			FROM #EMPHRS 
			WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
			UNION ALL
			SELECT	
			a.EMPCODE,a.RPTTOEMPCODE
			FROM #EMPHRS a
			join cte b
			ON a.RPTTOEMPCODE = b.EMPCODE
			) 
			INSERT INTO #EMPHR_EDIT
			SELECT EMPCODE,RPTTOEMPCODE FROM cte 

		END

	IF OBJECT_ID('tempdb..#TMPATTENLOGINOUT') IS NOT NULL
		DROP TABLE #TMPATTENLOGINOUT

	CREATE TABLE #TMPATTENLOGINOUT(USERID BIGINT,LOGGEDIN NVARCHAR(10),LOGEDOUT NVARCHAR(10),cnt_internalId NVARCHAR(10),Login_datetime NVARCHAR(10),WORKDATEORDBY NVARCHAR(10),
	ATTEN_STATUS NVARCHAR(20),IsDistributorwiseNearbyShopVisit NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINOUT(USERID,cnt_internalId,Login_datetime)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPATTENLOGINOUT(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS,IsDistributorwiseNearbyShopVisit) '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS WORKDATEORDBY,CASE WHEN Isonleave=''false'' THEN ''At Work'' ELSE ''On Leave'' END AS ATTEN_STATUS,'
	SET @Strsql+='ISNULL(ATTEN.IsDistributorwiseNearbyShopVisit,''No'') AS IsDistributorwiseNearbyShopVisit '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120),ATTEN.Isonleave,ATTEN.IsDistributorwiseNearbyShopVisit '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF OBJECT_ID('tempdb..#TMPATTENLOGOUT') IS NOT NULL
		DROP TABLE #TMPATTENLOGOUT

	CREATE TABLE #TMPATTENLOGOUT(USERID BIGINT,LOGEDOUT NVARCHAR(10),cnt_internalId NVARCHAR(10),Login_datetime NVARCHAR(10),WORKDATEORDBY NVARCHAR(10))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGOUT(USERID,cnt_internalId,Login_datetime)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPATTENLOGOUT(USERID,LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY) '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS WORKDATEORDBY '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''false'' '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	UPDATE A SET A.LOGEDOUT=B.LOGEDOUT
	FROM #TMPATTENLOGINOUT A
	INNER JOIN #TMPATTENLOGOUT B ON A.USERID=B.USERID AND A.cnt_internalId=B.cnt_internalId AND A.Login_datetime=B.Login_datetime AND A.WORKDATEORDBY=B.WORKDATEORDBY

	IF OBJECT_ID('tempdb..#TMPLEAVELOGINOUT') IS NOT NULL
		DROP TABLE #TMPLEAVELOGINOUT

	CREATE TABLE #TMPLEAVELOGINOUT(USERID BIGINT,LOGGEDIN NVARCHAR(10),LOGEDOUT NVARCHAR(10),cnt_internalId NVARCHAR(10),Login_datetime NVARCHAR(10),WORKDATEORDBY NVARCHAR(10),
	ATTEN_STATUS NVARCHAR(20))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPLEAVELOGINOUT(USERID,cnt_internalId,Login_datetime)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPLEAVELOGINOUT(USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS) '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,MIN(CONVERT(VARCHAR(5),CAST(ATTEN.Login_datetime AS TIME),108)) AS LOGGEDIN,NULL AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS WORKDATEORDBY,''On Leave'' AS ATTEN_STATUS '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''true'' '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,NULL AS LOGGEDIN,MAX(CONVERT(VARCHAR(5),CAST(ATTEN.Logout_datetime AS TIME),108)) AS LOGEDOUT,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS Login_datetime,'
	SET @Strsql+='CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS WORKDATEORDBY,''On Leave'' AS ATTEN_STATUS '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NULL AND Logout_datetime IS NOT NULL AND Isonleave=''true'' '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY ATTEN.User_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105),CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF OBJECT_ID('tempdb..#TMPSHOPSUBMITACT') IS NOT NULL
		DROP TABLE #TMPSHOPSUBMITACT

	CREATE TABLE #TMPSHOPSUBMITACT(USER_ID BIGINT,cnt_internalId NVARCHAR(10),Shop_Id VARCHAR(100),NEWSHOP_VISITED INT,RE_VISITED INT,SPENT_DURATION VARCHAR(100),DISTANCE_TRAVELLED DECIMAL(18,2),
	VISITED_DATE NVARCHAR(20),VISITED_TIME NVARCHAR(10),VISITREMARKS NVARCHAR(1000),MULTI_CONTACT_NAME NVARCHAR(300),MULTI_CONTACT_NUMBER NVARCHAR(100))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPSUBMITACT(USER_ID,cnt_internalId,Shop_Id)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPSHOPSUBMITACT(USER_ID,cnt_internalId,Shop_Id,NEWSHOP_VISITED,RE_VISITED,SPENT_DURATION,DISTANCE_TRAVELLED,VISITED_DATE,VISITED_TIME,VISITREMARKS,'
	SET @Strsql+='MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER) '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,COUNT(SHOPACT.Shop_Id) AS NEWSHOP_VISITED,0 AS RE_VISITED,SPENT_DURATION,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,'
	SET @Strsql+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_DATE,MIN(CONVERT(VARCHAR(5),CAST(SHOPACT.visited_time AS TIME),108)) AS VISITED_TIME,SHOPACT.REMARKS AS VISITREMARKS,'
	IF @ISREVISITCONTACTDETAILS=1
		SET @Strsql+='MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER '
	ELSE IF @ISREVISITCONTACTDETAILS=0
		SET @Strsql+=''''' AS MULTI_CONTACT_NAME,'''' AS MULTI_CONTACT_NUMBER '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) AND SHOPACT.Is_Newshopadd=1 '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time,SHOPACT.SPENT_DURATION,SHOPACT.REMARKS '
	IF @ISREVISITCONTACTDETAILS=1
		SET @Strsql+=',SHOPACT.MULTI_CONTACT_NAME,SHOPACT.MULTI_CONTACT_NUMBER '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,Shop_Id,0 AS NEWSHOP_VISITED,COUNT(SHOPACT.Shop_Id) AS RE_VISITED,SPENT_DURATION,SUM(ISNULL(distance_travelled,0)) AS DISTANCE_TRAVELLED,'
	SET @Strsql+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITED_DATE,MIN(CONVERT(VARCHAR(5),CAST(SHOPACT.visited_time AS TIME),108)) AS VISITED_TIME,SHOPACT.REMARKS AS VISITREMARKS,'
	IF @ISREVISITCONTACTDETAILS=1
		SET @Strsql+='MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER '
	ELSE IF @ISREVISITCONTACTDETAILS=0
		SET @Strsql+=''''' AS MULTI_CONTACT_NAME,'''' AS MULTI_CONTACT_NUMBER '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) AND SHOPACT.Is_Newshopadd=0 AND SHOPACT.ISMEETING=0 '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,SHOPACT.visited_time,SHOPACT.SPENT_DURATION,SHOPACT.REMARKS '
	IF @ISREVISITCONTACTDETAILS=1
		SET @Strsql+=',SHOPACT.MULTI_CONTACT_NAME,SHOPACT.MULTI_CONTACT_NUMBER '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql
	
	IF OBJECT_ID('tempdb..#TMPATTENLOGINLOGOUT') IS NOT NULL
		DROP TABLE #TMPATTENLOGINLOGOUT

	CREATE TABLE #TMPATTENLOGINLOGOUT(ID BIGINT,USER_ID BIGINT,Login_datetime DATETIME,Logout_datetime DATETIME,Work_Desc VARCHAR(MAX),Work_datetime DATETIME,Isonleave VARCHAR(50),WrkActvtyDescription VARCHAR(MAX))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPATTENLOGINLOGOUT(ID,USER_ID,Login_datetime,Logout_datetime,Isonleave)

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPATTENLOGINLOGOUT(ID,USER_ID,Login_datetime,Logout_datetime,Work_Desc,Work_datetime,Isonleave,WrkActvtyDescription) '
	SET @Strsql+='SELECT UATTEN.Id,UATTEN.User_Id,UATTEN.Login_datetime,UATTEN.Logout_datetime,UATTEN.Work_Desc,UATTEN.Work_datetime,UATTEN.Isonleave,WRKACT.WrkActvtyDescription '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout UATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user MUSR ON MUSR.USER_ID=UATTEN.USER_ID AND MUSR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_attendance_worktype ATTENWRKTYP ON ATTENWRKTYP.UserID=UATTEN.User_Id AND UATTEN.Id=ATTENWRKTYP.attendanceid '
	SET @Strsql+='INNER JOIN tbl_FTS_WorkActivityList WRKACT ON WRKACT.WorkActivityID=ATTENWRKTYP.worktypeID '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF OBJECT_ID('tempdb..#TMPLOGINOUTLOC') IS NOT NULL		
		DROP TABLE #TMPLOGINOUTLOC

	CREATE TABLE #TMPLOGINOUTLOC(USERID BIGINT,SDATE NVARCHAR(10),LOGINLOATION NVARCHAR(MAX),LOGOUTLOATION NVARCHAR(MAX))
			
	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPLOGINOUTLOC(USERID,SDATE,LOGINLOATION,LOGOUTLOATION) '
	SET @Strsql+='SELECT User_Id,SDate,'''' AS LOGINLOATION,'''' AS LOGOUTLOATION FROM('
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,LoginLogout '
	SET @Strsql+='FROM tbl_trans_shopuser '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),tbl_trans_shopuser.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND LoginLogout IN(0,1) '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,LoginLogout '
	SET @Strsql+='FROM TBL_TRANS_SHOPUSER_ARCH '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),TBL_TRANS_SHOPUSER_ARCH.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND LoginLogout IN(0,1) '
	SET @Strsql+=') AA GROUP BY User_Id,SDate '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	IF OBJECT_ID('tempdb..#TMPLOGINLOC') IS NOT NULL	
		DROP TABLE #TMPLOGINLOC

	CREATE TABLE #TMPLOGINLOC(USERID BIGINT,SDATE NVARCHAR(10),LOGINLOATION NVARCHAR(MAX))

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPLOGINLOC(USERID,SDATE,LOGINLOATION) '
	SET @Strsql+='SELECT User_Id,SDate,LOGINLOATION FROM ('
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,location_name AS LOGINLOATION '
	SET @Strsql+='FROM tbl_trans_shopuser '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),tbl_trans_shopuser.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120)  '
	SET @Strsql+='AND LoginLogout=1 '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,location_name AS LOGINLOATION '
	SET @Strsql+='FROM TBL_TRANS_SHOPUSER_ARCH '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),TBL_TRANS_SHOPUSER_ARCH.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND LoginLogout=1 '
	SET @Strsql+=') BB ORDER BY User_Id '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	UPDATE A SET A.LOGINLOATION=B.LOGINLOATION
	FROM #TMPLOGINOUTLOC A
	INNER JOIN #TMPLOGINLOC B ON A.USERID=B.USERID AND A.SDate=B.SDate

	IF OBJECT_ID('tempdb..#TMPLOGOUTLOC') IS NOT NULL
		DROP TABLE #TMPLOGOUTLOC

	CREATE TABLE #TMPLOGOUTLOC(USERID BIGINT,SDATE NVARCHAR(10),LOGOUTLOATION NVARCHAR(MAX)) 

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPLOGOUTLOC(USERID,SDATE,LOGOUTLOATION) '
	SET @Strsql+='SELECT User_Id,SDate,LOGOUTLOATION FROM ('
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,location_name AS LOGOUTLOATION '
	SET @Strsql+='FROM tbl_trans_shopuser '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),tbl_trans_shopuser.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND LoginLogout=0 '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT User_Id,CONVERT(NVARCHAR(10),SDate,105) AS SDate,location_name AS LOGOUTLOATION '
	SET @Strsql+='FROM TBL_TRANS_SHOPUSER_ARCH '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),TBL_TRANS_SHOPUSER_ARCH.SDate,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND LoginLogout=0 '
	SET @Strsql+=') BB ORDER BY User_Id '

	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	UPDATE A SET A.LOGOUTLOATION=B.LOGOUTLOATION
	FROM #TMPLOGINOUTLOC A
	INNER JOIN #TMPLOGOUTLOC B ON A.USERID=B.USERID AND A.SDate=B.SDate

	IF OBJECT_ID('tempdb..#TMPMAPDDSHOP') IS NOT NULL
		DROP TABLE #TMPMAPDDSHOP

	CREATE TABLE #TMPMAPDDSHOP(SHOP_CODE NVARCHAR(100),SHOP_CREATEUSER INT,SHOP_NAME NVARCHAR(2500),ADDRESS NVARCHAR(MAX),SHOP_OWNER_CONTACT NVARCHAR(100),ASSIGNED_TO_DD_ID NVARCHAR(100),
	TYPE INT,ENTITYCODE NVARCHAR(100),PINCODE NVARCHAR(120))
	CREATE NONCLUSTERED INDEX IX1 ON #TMPMAPDDSHOP(SHOP_CODE,ASSIGNED_TO_DD_ID)
	
	INSERT INTO #TMPMAPDDSHOP(SHOP_CODE,SHOP_CREATEUSER,SHOP_NAME,ADDRESS,SHOP_OWNER_CONTACT,ASSIGNED_TO_DD_ID,TYPE,ENTITYCODE,PINCODE)
	SELECT DISTINCT shop.Shop_Code,shop.Shop_CreateUser,shop.Shop_Name,shop.Address,shop.Shop_Owner_Contact,shop.assigned_to_dd_id,shop.Type,
	shop.EntityCode,shop.Pincode
	FROM tbl_Master_shop shop 
	WHERE shop.TYPE=1 AND SHOP.assigned_to_dd_id<>''

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT
			(
			  USERID INT,
			  SEQ INT,
			  LOGIN_DATE NVARCHAR(10),
			  LOGGEDIN NVARCHAR(100) NULL,
			  LOGEDOUT NVARCHAR(100) NULL,
			  VISITED_TIME NVARCHAR(10),
			  CONTACTNO NVARCHAR(50) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  BRANCHDESC NVARCHAR(300),
			  OFFICE_ADDRESS NVARCHAR(2000),
			  ATTEN_STATUS NVARCHAR(20),
			  LOGINLOATION NVARCHAR(MAX),
			  LOGOUTLOATION NVARCHAR(MAX),
			  MDD_YESNO NVARCHAR(10),
			  WORK_LEAVE_TYPE NVARCHAR(2000) NULL,
			  REMARKS NVARCHAR(2000) NULL,
			  EMPCODE NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  EMPID NVARCHAR(100) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  DATEOFJOINING NVARCHAR(10),
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESG NVARCHAR(50) NULL,
			  HREPORTTO NVARCHAR(300) NULL,
			  HRPTTODESG NVARCHAR(50) NULL,
			  SHOP_TYPE NVARCHAR(50),
			  SHOP_CODE NVARCHAR(100),
			  SHOP_NAME NVARCHAR(300) NULL,
			  OUTLET_TYPE NVARCHAR(500) NULL,
			  ENTITYCODE NVARCHAR(600) NULL,
			  SHOPADDR_CONTACT NVARCHAR(300) NULL,
			  SHOP_DISTRICT NVARCHAR(50) NULL,
			  SHOP_PINCODE NVARCHAR(120) NULL,
			  DD_CODE NVARCHAR(100) NULL,
			  DD_NAME NVARCHAR(300) NULL,
			  DDADDR_CONTACT NVARCHAR(300) NULL,
			  VISITREMARKS NVARCHAR(1000),
			  MANNINGSTATUS NVARCHAR(300) NULL,
			  MULTI_CONTACT_NAME NVARCHAR(300),
			  MULTI_CONTACT_NUMBER NVARCHAR(100),
			  TOTAL_VISIT INT,
			  NEWSHOP_VISITED INT,
			  RE_VISITED INT,
			  SPENT_DURATION NVARCHAR(50),
			  DISTANCE_TRAVELLED DECIMAL(38,2)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT (SEQ)
		END
	DELETE FROM FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT WHERE USERID=@USERID

	SET @Strsql=''
	SET @Strsql='INSERT INTO FTSEMPLOYEEPERFORMANCEANALYTICS_REPORT(USERID,SEQ,LOGIN_DATE,LOGGEDIN,LOGEDOUT,VISITED_TIME,CONTACTNO,STATEID,STATE,BRANCHDESC,OFFICE_ADDRESS,ATTEN_STATUS,'
	SET @Strsql+='LOGINLOATION,LOGOUTLOATION,MDD_YESNO,WORK_LEAVE_TYPE,REMARKS,EMPCODE,EMPNAME,EMPID,DEG_ID,DESIGNATION,DATEOFJOINING,REPORTTO,RPTTODESG,HREPORTTO,HRPTTODESG,SHOP_TYPE,'
	SET @Strsql+='SHOP_CODE,SHOP_NAME,OUTLET_TYPE,ENTITYCODE,SHOPADDR_CONTACT,SHOP_DISTRICT,SHOP_PINCODE,DD_CODE,DD_NAME,DDADDR_CONTACT,VISITREMARKS,MANNINGSTATUS,MULTI_CONTACT_NAME,'
	SET @Strsql+='MULTI_CONTACT_NUMBER,TOTAL_VISIT,NEWSHOP_VISITED,RE_VISITED,SPENT_DURATION,DISTANCE_TRAVELLED) '
	SET @Strsql+='SELECT '+STR(@USERID)+' AS USERID,ROW_NUMBER() OVER(ORDER BY WORKDATEORDBY) AS SEQ,LOGIN_DATETIME,LOGGEDIN,LOGEDOUT,VISITED_TIME,CONTACTNO,STATEID,STATE,BRANCHDESC,'
	SET @Strsql+='OFFICE_ADDRESS,ATTEN_STATUS,LOGINLOATION,LOGOUTLOATION,MDD_YESNO,WORK_LEAVE_TYPE,REMARKS,EMPCODE,EMPNAME,EMPID,DEG_ID,DESIGNATION,DATEOFJOINING,REPORTTO,RPTTODESG,HREPORTTO,'
	SET @Strsql+='HRPTTODESG,SHOP_TYPE,SHOP_CODE,SHOP_NAME,OUTLET_TYPE,ENTITYCODE,SHOPADDR_CONTACT,SHOP_DISTRICT,SHOP_PINCODE,DD_CODE,DD_NAME,DDADDR_CONTACT,VISITREMARKS,MANNINGSTATUS,'
	SET @Strsql+='MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER,TOTAL_VISIT,NEWSHOP_VISITED,RE_VISITED,SPENT_DURATION,DISTANCE_TRAVELLED FROM('
	SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @Strsql+='ISNULL(ST.ID,0) AS STATEID,ST.state AS STATE,BR.branch_description AS BRANCHDESC,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
	SET @Strsql+='USR.user_loginId AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,ATTEN.LOGIN_DATETIME,ATTEN.WORKDATEORDBY,ATTEN.LOGGEDIN AS LOGGEDIN,ATTEN.LOGEDOUT AS LOGEDOUT,SHOPACT.VISITED_TIME,'
	SET @Strsql+='ADDR.add_address1+'' ''+ISNULL(ADDR.add_address2,'''')+'' ''+ISNULL(ADDR.add_address3,'''') AS OFFICE_ADDRESS,EMP.emp_uniqueCode AS EMPID,ATTEN_STATUS,ATTEN.MDD_YESNO,'
	SET @Strsql+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(UATTEN.WrkActvtyDescription)) From #TMPATTENLOGINLOGOUT AS UATTEN '
	SET @Strsql+='WHERE UATTEN.USER_ID=USR.USER_ID AND UATTEN.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),UATTEN.Work_datetime,105) FOR XML PATH('''')), 1, 1, ''''),'''')) AS WORK_LEAVE_TYPE,'
	SET @Strsql+='REPLACE((SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(ISNULL(A.Work_Desc,''''))) From #TMPATTENLOGINLOGOUT AS A '
	SET @Strsql+='WHERE A.USER_ID=USR.USER_ID AND A.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),A.Work_datetime,105) FOR XML PATH('''')),1,1,''''),'''')),'','','''') AS REMARKS,'
	SET @Strsql+='CASE WHEN SHOP.SHOP_TYPE<>'''' THEN SHOP.SHOP_TYPE WHEN SHOPDD.SHOP_TYPE<>'''' THEN ''MDD'' END AS SHOP_TYPE,SHOP.Shop_Code,SHOP.Shop_Name,SHOP.OUTLET_TYPE,SHOP.ENTITYCODE,'
	SET @Strsql+='CASE WHEN ATTEN.MDD_YESNO=''Yes'' THEN SHOP.SHOPSTATUS ELSE SHOPDD.SHOPDDSTATUS END AS MANNINGSTATUS,LOGINOUTLOC.LOGINLOATION,LOGINOUTLOC.LOGOUTLOATION,'
	SET @Strsql+='SHOP.Address+'' ''+SHOP.Shop_Owner_Contact AS SHOPADDR_CONTACT,SHOP.CITY_NAME AS SHOP_DISTRICT,SHOP.Pincode AS SHOP_PINCODE,'	
	SET @Strsql+='CASE WHEN SHOPDD.ENTITYCODE<>'''' THEN SHOPDD.ENTITYCODE ELSE MAPDDSHOP.ENTITYCODE END AS DD_CODE,'
	SET @Strsql+='CASE WHEN SHOPDD.Shop_Name<>'''' THEN SHOPDD.Shop_Name ELSE MAPDDSHOP.Shop_Name END AS DD_NAME,'
	SET @Strsql+='CASE WHEN (SHOPDD.Address+'' ''+SHOPDD.Shop_Owner_Contact)<>'''' THEN SHOPDD.Address+'' ''+SHOPDD.Shop_Owner_Contact ELSE MAPDDSHOP.Address+'' ''+MAPDDSHOP.Shop_Owner_Contact END AS DDADDR_CONTACT,'
	SET @Strsql+='SHOPACT.VISITREMARKS,SHOPACT.MULTI_CONTACT_NAME,SHOPACT.MULTI_CONTACT_NUMBER,ISNULL(SHOPACT.NEWSHOP_VISITED,0)+ISNULL(SHOPACT.RE_VISITED,0) AS TOTAL_VISIT,'
	SET @Strsql+='ISNULL(SHOPACT.NEWSHOP_VISITED,0) AS NEWSHOP_VISITED,ISNULL(SHOPACT.RE_VISITED,0) AS RE_VISITED,SPENT_DURATION,DISTANCE_TRAVELLED '
	SET @Strsql+='FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_branch BR ON CNT.cnt_branchid=BR.branch_id '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
		SET @Strsql+='INNER JOIN #EMPHR_EDIT EMPHR ON EMPHR.EMPCODE=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt WITH (NOLOCK) '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON CNT.cnt_internalId=RPTTO.emp_cntId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS HREPORTTO,'
	SET @Strsql+='DESG.deg_designation AS HRPTTODESG FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @Strsql+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON RPTTO.REPORTTOID=HRPTTO.emp_cntId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS,MDD_YESNO FROM('
	SET @Strsql+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS,IsDistributorwiseNearbyShopVisit AS MDD_YESNO FROM #TMPATTENLOGINOUT '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS,MDD_YESNO '
	SET @Strsql+=') ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+='LEFT OUTER JOIN #TMPLOGINOUTLOC LOGINOUTLOC ON USR.USER_ID=LOGINOUTLOC.USERID AND ATTEN.Login_datetime=LOGINOUTLOC.SDATE '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT User_Id,cnt_internalId,Shop_Id,SUM(NEWSHOP_VISITED) AS NEWSHOP_VISITED,SUM(RE_VISITED) AS RE_VISITED,SPENT_DURATION,SUM(DISTANCE_TRAVELLED) AS DISTANCE_TRAVELLED,'
	SET @Strsql+='VISITED_DATE,VISITED_TIME,VISITREMARKS,MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER FROM('
	SET @Strsql+='SELECT USER_ID,cnt_internalId,Shop_Id,NEWSHOP_VISITED,RE_VISITED,SPENT_DURATION,DISTANCE_TRAVELLED,VISITED_DATE,VISITED_TIME,VISITREMARKS,MULTI_CONTACT_NAME,'
	SET @Strsql+='MULTI_CONTACT_NUMBER FROM #TMPSHOPSUBMITACT '
	SET @Strsql+=') AA GROUP BY User_Id,cnt_internalId,Shop_Id,VISITED_DATE,VISITED_TIME,VISITREMARKS,SPENT_DURATION,MULTI_CONTACT_NAME,MULTI_CONTACT_NUMBER '
	SET @Strsql+=') SHOPACT ON CNT.cnt_internalId=SHOPACT.cnt_internalId AND ATTEN.Login_datetime=SHOPACT.VISITED_DATE '
	SET @Strsql+='LEFT OUTER JOIN ('
	SET @Strsql+='SELECT DISTINCT shop.Shop_Code,shop.Shop_CreateUser,shop.Shop_Name,shop.Address,shop.Shop_Owner_Contact,shop.assigned_to_pp_id,shop.assigned_to_dd_id,shop.Type,'
	SET @Strsql+='shop.EntityCode,SHOPTYPE.Name AS OUTLET_TYPE,shop.Pincode,CITY.CITY_NAME,shop.CLUSTER,PS.PARTYSTATUS AS SHOPSTATUS,SHPTYP.Name AS SHOP_TYPE '
	SET @Strsql+='FROM tbl_Master_shop shop '
	SET @Strsql+='INNER JOIN tbl_shoptype SHPTYP ON shop.TYPE=SHPTYP.shop_typeId '
	SET @Strsql+='LEFT OUTER JOIN tbl_shoptypeDetails SHOPTYPE ON shop.retailer_id=SHOPTYPE.ID '
	SET @Strsql+='LEFT OUTER JOIN TBL_MASTER_CITY CITY ON shop.Shop_City=CITY.city_id '
	SET @Strsql+='LEFT OUTER JOIN FSM_PARTYSTATUS PS ON shop.Party_Status_id=PS.ID '
	SET @Strsql+='WHERE shop.TYPE=1 '
	IF @isRevisitTeamDetail='1'
		SET @Strsql+=') SHOP ON SHOP.Shop_Code=SHOPACT.Shop_Id '
	ELSE IF @isRevisitTeamDetail='0'
		SET @Strsql+=') SHOP ON SHOP.Shop_CreateUser=USR.user_id AND SHOP.Shop_Code=SHOPACT.Shop_Id '
	SET @Strsql+='LEFT OUTER JOIN( '
	SET @Strsql+='SELECT DISTINCT A.Shop_CreateUser,A.assigned_to_dd_id,A.Shop_Code,A.Shop_Name,A.Address,A.Shop_Owner_Contact,A.Type,A.EntityCode,PS.PARTYSTATUS AS SHOPDDSTATUS,'
	SET @Strsql+='SHPTYP.Name AS SHOP_TYPE '
	SET @Strsql+='FROM tbl_Master_shop A '
	SET @Strsql+='INNER JOIN tbl_shoptype SHPTYP ON A.TYPE=SHPTYP.shop_typeId '
	SET @Strsql+='LEFT OUTER JOIN FSM_PARTYSTATUS PS ON A.Party_Status_id=PS.ID '
	SET @Strsql+='WHERE A.TYPE=4 '
	SET @Strsql+=') SHOPDD ON SHOPDD.Shop_Code=SHOPACT.Shop_Id '
	SET @Strsql+='LEFT OUTER JOIN('
	SET @Strsql+='SELECT DISTINCT shop.Shop_Code AS DDSHOP,shop.Shop_CreateUser,shop.Shop_Name,shop.Address,shop.Shop_Owner_Contact,shop.assigned_to_dd_id,shop.Type,'
	SET @Strsql+='shop.EntityCode,shop.Pincode,MAPDD.SHOP_CODE '
	SET @Strsql+='FROM tbl_Master_shop shop '
	SET @Strsql+='INNER JOIN #TMPMAPDDSHOP MAPDD ON SHOP.Shop_Code=MAPDD.assigned_to_dd_id '
	SET @Strsql+='WHERE shop.TYPE=4 AND SHOP.assigned_to_dd_id IS NULL '
	SET @Strsql+=') MAPDDSHOP ON SHOP.Shop_Code=MAPDDSHOP.SHOP_CODE '
	SET @Strsql+='UNION ALL '
	SET @Strsql+='SELECT CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @Strsql+='ISNULL(ST.ID,0) AS STATEID,ST.state AS STATE,'''' AS BRANCHDESC,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
	SET @Strsql+='USR.user_loginId AS CONTACTNO,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,ATTEN.LOGIN_DATETIME,ATTEN.WORKDATEORDBY,ATTEN.LOGGEDIN AS LOGGEDIN,ATTEN.LOGEDOUT AS LOGEDOUT,NULL AS VISITED_TIME,'
	SET @Strsql+='ADDR.add_address1+'' ''+ISNULL(ADDR.add_address2,'''')+'' ''+ISNULL(ADDR.add_address3,'''') AS OFFICE_ADDRESS,EMP.emp_uniqueCode AS EMPID,ATTEN_STATUS,'''' AS MDD_YESNO,'
	SET @Strsql+='(SELECT DISTINCT ISNULL(STUFF((SELECT '','' + LTRIM(RTRIM(UATTEN.WrkActvtyDescription)) From #TMPATTENLOGINLOGOUT AS UATTEN '
	SET @Strsql+='WHERE UATTEN.USER_ID=USR.USER_ID AND UATTEN.USER_ID=ATTEN.USERID AND ATTEN.Login_datetime=CONVERT(NVARCHAR(10),UATTEN.Work_datetime,105) FOR XML PATH('''')), 1, 1, ''''),'''')) AS WORK_LEAVE_TYPE,'
	SET @Strsql+=''''' AS REMARKS,'''' AS SHOP_TYPE,'''' AS Shop_Code,'''' AS Shop_Name,'''' AS OUTLET_TYPE,'''' AS ENTITYCODE,'''' AS MANNINGSTATUS,'''' AS LOGINLOATION,'''' AS LOGOUTLOATION,'
	SET @Strsql+=''''' AS SHOPADDR_CONTACT,'''' AS SHOP_DISTRICT,'''' AS SHOP_PINCODE,'''' AS DD_CODE,'''' AS DD_NAME,'''' AS DDADDR_CONTACT,'''' AS MULTI_CONTACT_NAME,'''' AS MULTI_CONTACT_NUMBER,'
	SET @Strsql+=''''' AS VISITREMARKS,0 AS TOTAL_VISIT,0 AS NEWSHOP_VISITED,0 AS RE_VISITED,NULL AS SPENT_DURATION,0.00 AS DISTANCE_TRAVELLED '
	SET @Strsql+='FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_branch BR ON CNT.cnt_branchid=BR.branch_id '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ( '
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL ) RPTTO ON CNT.cnt_internalId=RPTTO.emp_cntId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS HREPORTTO,'
	SET @Strsql+='DESG.deg_designation AS HRPTTODESG FROM tbl_master_employee EMP WITH (NOLOCK) '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
	SET @Strsql+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON RPTTO.REPORTTOID=HRPTTO.emp_cntId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT USERID,MIN(LOGGEDIN) AS LOGGEDIN,MAX(LOGEDOUT) AS LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS FROM('
	SET @Strsql+='SELECT USERID,LOGGEDIN,LOGEDOUT,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS FROM #TMPLEAVELOGINOUT '
	SET @Strsql+=') LOGINLOGOUT GROUP BY USERID,cnt_internalId,Login_datetime,WORKDATEORDBY,ATTEN_STATUS '
	SET @Strsql+=') ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+=') AS DB '
	IF @STATEID<>'' AND @DESIGNID='' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
	ELSE IF @STATEID='' AND @DESIGNID='' AND @EMPID<>''
		SET @Strsql+='WHERE EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
	ELSE IF @STATEID<>'' AND @DESIGNID='' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID=''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	DROP TABLE #DESIGNATION_LIST
	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TEMPCONTACT
	IF ((SELECT IsAllDataInPortalwithHeirarchy from tbl_master_user where user_id=@USERID)=1)
	BEGIN
		DROP TABLE #EMPHR_EDIT
		DROP TABLE #EMPHRS
	END
	DROP TABLE #TMPATTENLOGINLOGOUT
	DROP TABLE #TMPATTENLOGINOUT
	DROP TABLE #TMPSHOPSUBMITACT
	DROP TABLE #TMPLEAVELOGINOUT
	DROP TABLE #TMPLOGINLOC
	DROP TABLE #TMPLOGINOUTLOC
	DROP TABLE #TMPLOGOUTLOC
	DROP TABLE #TMPATTENLOGOUT
	DROP TABLE #TMPMAPDDSHOP

	SET NOCOUNT OFF
END