IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIAREAROUTEBEATRELATIONINFO]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIAREAROUTEBEATRELATIONINFO] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIAREAROUTEBEATRELATIONINFO]
(
@ACTION NVARCHAR(50),
@USER_ID BIGINT=NULL,
@BEAT_ID BIGINT=NULL
) --WITH ENCRYPTION
AS
/*******************************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 18/01/2023
Purpose : For New Area/Route/Beat informations.Row 794 to 795
*******************************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='AREAROUTEBEATLIST'
		BEGIN
			SELECT BM.USER_ID,BEAT_AREA.ID AS area_id,ISNULL(BEAT_AREA.NAME,'') AS area_name,BEAT_ROUTE.ID AS route_id,ISNULL(BEAT_ROUTE.NAME,'') AS route_name,BM.BEAT_ID AS beat_id,ISNULL(BEAT.Name,'') AS beat_name 
			FROM FSM_GROUPBEAT_USERMAP BM
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT ON BM.BEAT_ID=BEAT.ID AND BEAT.CODE_TYPE='BEAT'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_AREA ON BEAT.AREA_CODE=BEAT_AREA.ID AND BEAT_AREA.CODE_TYPE='AREA'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_ROUTE ON BEAT.ROUTE_CODE=BEAT_ROUTE.ID AND BEAT_ROUTE.CODE_TYPE='ROUTE'
			WHERE BM.USER_ID=@USER_ID AND BM.BEAT_ID=@BEAT_ID
		END
	IF @ACTION='AREAROUTEBEATDETAILSLIST'
		BEGIN
			SELECT BM.USER_ID,BEAT_AREA.ID AS area_id,ISNULL(BEAT_AREA.NAME,'') AS area_name
			FROM FSM_GROUPBEAT_USERMAP BM
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT ON BM.BEAT_ID=BEAT.ID AND BEAT.CODE_TYPE='BEAT'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_AREA ON BEAT.AREA_CODE=BEAT_AREA.ID AND BEAT_AREA.CODE_TYPE='AREA'
			WHERE BM.USER_ID=@USER_ID

			SELECT BM.USER_ID,BEAT_AREA.ID AS area_id,BEAT_ROUTE.ID AS route_id,ISNULL(BEAT_ROUTE.NAME,'') AS route_name
			FROM FSM_GROUPBEAT_USERMAP BM
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT ON BM.BEAT_ID=BEAT.ID AND BEAT.CODE_TYPE='BEAT'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_AREA ON BEAT.AREA_CODE=BEAT_AREA.ID AND BEAT_AREA.CODE_TYPE='AREA'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_ROUTE ON BEAT.ROUTE_CODE=BEAT_ROUTE.ID AND BEAT_ROUTE.CODE_TYPE='ROUTE'
			WHERE BM.USER_ID=@USER_ID

			SELECT BM.USER_ID,BEAT_AREA.ID AS area_id,BEAT_ROUTE.ID AS route_id,BM.BEAT_ID AS beat_id,ISNULL(BEAT.Name,'') AS beat_name 
			FROM FSM_GROUPBEAT_USERMAP BM
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT ON BM.BEAT_ID=BEAT.ID AND BEAT.CODE_TYPE='BEAT'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_AREA ON BEAT.AREA_CODE=BEAT_AREA.ID AND BEAT_AREA.CODE_TYPE='AREA'
			LEFT OUTER JOIN FSM_GROUPBEAT BEAT_ROUTE ON BEAT.ROUTE_CODE=BEAT_ROUTE.ID AND BEAT_ROUTE.CODE_TYPE='ROUTE'
			WHERE BM.USER_ID=@USER_ID
		END

	SET NOCOUNT OFF
END