--EXEC PRC_FTSCLOSINGSTOCK_REPORT '2022-01-12','2022-01-12','','',''

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSCLOSINGSTOCK_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSCLOSINGSTOCK_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSCLOSINGSTOCK_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@STATEID NVARCHAR(MAX)=NULL,
@DESIGNID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL
) --WITH ENCRYPTION
AS
/**********************************************************************************************************************************************************************************************************
Written by : Debashis Talukder On 31/12/2021
Module	   : Closing Stock.Refer: 0024511
**********************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @Strsql NVARCHAR(MAX),@sqlStrTable NVARCHAR(MAX)
	DECLARE @PRODUCT_CURSOR CURSOR,@OPENINGSTK_CURSOR CURSOR,@EMPSHOP_CURSOR CURSOR,@CURSOR_OPENINGSTOCKCALC CURSOR
	DECLARE @PRODID BIGINT,@PRODNAME NVARCHAR(100),@PRODONCE BIT,@M_EMPID NVARCHAR(10),@M_PRODID BIGINT,@PRODNAMEQTY NVARCHAR(MAX)
	DECLARE @EMPCODE NVARCHAR(10),@SHOP_CODE NVARCHAR(100),@PROD_VALUE NVARCHAR(MAX),@M_EMPCODE NVARCHAR(10),@M_SHOP_CODE NVARCHAR(100),@STOCKDATE NVARCHAR(10),@STOCKNO NVARCHAR(60)
	DECLARE @PRODNAME_QTY NVARCHAR(MAX)='',@PRODNAMESUMM_QTY NVARCHAR(MAX)=''
	DECLARE @SLHEADID BIGINT,@M_SLHEADID BIGINT,@M_SLHEADID_NEXT BIGINT,@SLPARRENTID BIGINT,@SLPARRENTID_NEXT BIGINT,@SLPARRENTID_NEXT_CS BIGINT,@HPRODONCE INT

	IF OBJECT_ID('tempdb..#STATEID_LIST') IS NOT NULL
		DROP TABLE #STATEID_LIST
	CREATE TABLE #STATEID_LIST (State_Id INT)
	CREATE NONCLUSTERED INDEX IX1 ON #STATEID_LIST (State_Id ASC)
	IF @STATEID <> ''
		BEGIN
			SET @STATEID=REPLACE(@STATEID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #STATEID_LIST SELECT id from tbl_master_state where id in('+@STATEID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END
	
	IF OBJECT_ID('tempdb..#DESIGNATION_LIST') IS NOT NULL
		DROP TABLE #DESIGNATION_LIST
	CREATE TABLE #DESIGNATION_LIST (deg_id INT)
	CREATE NONCLUSTERED INDEX IX2 ON #DESIGNATION_LIST (deg_id ASC)
	IF @DESIGNID <> ''
		BEGIN
			SET @DESIGNID=REPLACE(@DESIGNID,'''','')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #DESIGNATION_LIST SELECT deg_id from tbl_master_designation where deg_id in('+@DESIGNID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
		DROP TABLE #EMPLOYEE_LIST
	CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)
	IF @EMPID <> ''
		BEGIN
			SET @M_EMPID=@EMPID
			SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
			SET @sqlStrTable=''
			SET @sqlStrTable=' INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
			EXEC SP_EXECUTESQL @sqlStrTable
		END

	IF OBJECT_ID('tempdb..#TMPHEADING') IS NOT NULL
		DROP TABLE #TMPHEADING
	CREATE TABLE #TMPHEADING
		(
			HEADID BIGINT,HEADNAME NVARCHAR(800),HEADSHRTNAME NVARCHAR(800),PARRENTID BIGINT,FIXEDSTYLE BIGINT DEFAULT(0)
		)
	
	IF OBJECT_ID('tempdb..#TEMPPROD') IS NOT NULL
		DROP TABLE #TEMPPROD
	CREATE TABLE #TEMPPROD
		(
			PRODID BIGINT,PRODNAME NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS
		)
	CREATE NONCLUSTERED INDEX IX1 ON #TEMPPROD(PRODID ASC)

	IF OBJECT_ID('tempdb..#TMPOPENINGSTOCK') IS NOT NULL
		DROP TABLE #TMPOPENINGSTOCK
	CREATE TABLE #TMPOPENINGSTOCK
		(
			STOCKDATE NVARCHAR(10),STOCKNO NVARCHAR(60),EMPCODE NVARCHAR(10),SHOP_CODE NVARCHAR(100),PRODID BIGINT,PRODNAME NVARCHAR(100),PRODNAME_QTY NVARCHAR(150),QTY INT,ORDVALUE DECIMAL(18,2)
		)
	CREATE NONCLUSTERED INDEX IXO ON #TMPOPENINGSTOCK(EMPCODE ASC,SHOP_CODE ASC)

	IF OBJECT_ID('tempdb..#TMPOPENINGSTOCK_FINAL') IS NOT NULL
		DROP TABLE #TMPOPENINGSTOCK_FINAL
	CREATE TABLE #TMPOPENINGSTOCK_FINAL
		(
			STOCKDATE NVARCHAR(10),STOCKNO NVARCHAR(60),EMPCODE NVARCHAR(10),SHOP_CODE NVARCHAR(100)
		)
	CREATE NONCLUSTERED INDEX IXOF ON #TMPOPENINGSTOCK_FINAL(EMPCODE ASC,SHOP_CODE ASC)

	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')

	IF OBJECT_ID('tempdb..#TEMPCLSTOCK') IS NOT NULL
		DROP TABLE #TEMPCLSTOCK
	CREATE TABLE #TEMPCLSTOCK
		(
			SEQ BIGINT,
			STOCKDATEORDBY NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			STOCKDATE NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
			STOCKNO NVARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS,
			SHOP_CODE NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			[SHOP NAME] NVARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			CONTACTNO NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			EMPCODE NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			EMPID NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			[SALES MAN NAME] NVARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			STATEID INT,
			STATE NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			DEG_ID NUMERIC(18,0),
			[DESIGNATION] NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			REPORTTO NVARCHAR(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			RPTTODESG NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			[TIME] NVARCHAR(10)
		)

	--FOR REPORT HEADER
	INSERT INTO #TMPHEADING(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID,FIXEDSTYLE)
	SELECT 1,'Date','DATE',0,1
	UNION ALL
	SELECT 2,'Stock Number','STOCK NUMBER',0,0
	UNION ALL
	SELECT 3,'Shop Name','SHOP NAME',0,0
	UNION ALL
	SELECT 4,'Contact Number','CONTACT NUMBER',0,0
	UNION ALL
	SELECT 5,'Salesman','SALES MAN NAME',0,0
	UNION ALL
	SELECT 6,'Time','TIME',0,0
	--FOR REPORT HEADER

	SET @Strsql=''
	SET @StrSql='INSERT INTO #TEMPPROD(PRODID,PRODNAME) '
	SET @StrSql+='SELECT PROD.sProducts_ID AS PRODID,PROD.sProducts_Name AS PRODNAME FROM Master_sProducts PROD '
	SET @StrSql+='WHERE EXISTS(SELECT Product_Id FROM FTS_StockdetailsProduct '
	SET @StrSql+='INNER JOIN FTS_TransStockOpen ON FTS_TransStockOpen.StockId=FTS_StockdetailsProduct.Stock_ID '
	SET @StrSql+='WHERE FTS_StockdetailsProduct.Product_Id=PROD.sProducts_ID '
	SET @Strsql+='AND CONVERT(NVARCHAR(10),FTS_TransStockOpen.Stock_date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @StrSql+=') '
	SET @StrSql+='ORDER BY PROD.sProducts_ID '
	--SELECT @StrSql
	EXEC(@StrSql)
	
	--FOR REPORT HEADER
	SET @M_SLHEADID=1
	SET @M_SLHEADID_NEXT=1
	SET @HPRODONCE=1
	--FOR REPORT HEADER

	SET @Strsql=''
	SET @StrSql='SET @PRODUCT_CURSOR=CURSOR FAST_FORWARD FOR SELECT PRODID,PRODNAME FROM #TEMPPROD '
	SET @StrSql+='ORDER BY PRODID ; OPEN @PRODUCT_CURSOR '
	--SELECT @StrSql
	EXEC sp_executesql @StrSql,N' @PRODUCT_CURSOR CURSOR OUTPUT', @PRODUCT_CURSOR OUTPUT

	FETCH NEXT FROM @PRODUCT_CURSOR INTO @PRODID,@PRODNAME
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @M_PRODID=@PRODID
			SET @PRODONCE=1
			WHILE @M_PRODID=@PRODID AND @@FETCH_STATUS = 0
				BEGIN
					IF @PRODONCE=1
						BEGIN
							SET @sqlStrTable=''
							SET @sqlStrTable = 'ALTER TABLE #TEMPCLSTOCK ADD '
							SET @sqlStrTable += '['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']' + ' INT NULL '
							EXEC SP_EXECUTESQL @sqlStrTable
							
							IF @PRODNAME_QTY=''
								BEGIN
									SET @PRODNAME_QTY='['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'
									SET @PRODNAMESUMM_QTY='SUM('+'['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'+') AS ['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'
								END
							ELSE IF @PRODNAME_QTY<>''
								BEGIN
									SET @PRODNAME_QTY+=',['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'
									SET @PRODNAMESUMM_QTY+=',SUM('+'['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'+') AS ['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']'
								END
							--FOR REPORT HEADER
							SELECT @SLHEADID=6
							IF @HPRODONCE=1
								SET @M_SLHEADID=@M_SLHEADID+@SLHEADID
							ELSE IF @HPRODONCE>1
								SET @M_SLHEADID=@M_SLHEADID+1
							SET @M_SLHEADID_NEXT=@M_SLHEADID
							SET @sqlStrTable=''
							SET @sqlStrTable='INSERT INTO #TMPHEADING(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID) '
							SET @sqlStrTable+='SELECT '+LTRIM(RTRIM(STR(@M_SLHEADID)))+' AS HEADID,'''+@PRODNAME+''' AS HEADNAME,'''+LTRIM(RTRIM(@PRODNAME))+'_QTY'+''' AS HEADSHRTNAME,'+LTRIM(RTRIM(STR(@M_SLHEADID)))+' AS PARRENTID '
							EXEC SP_EXECUTESQL @sqlStrTable
							SELECT @SLPARRENTID_NEXT=HEADID FROM #TMPHEADING WHERE HEADID=@M_SLHEADID
							--FOR REPORT HEADER
							SET @PRODONCE=0
						END
					--FOR REPORT HEADER
					FETCH NEXT FROM @PRODUCT_CURSOR INTO @PRODID,@PRODNAME
					--FOR REPORT HEADER
					SET @HPRODONCE=@HPRODONCE+1
					--FOR REPORT HEADER
				END
		END
	CLOSE @PRODUCT_CURSOR
	DEALLOCATE @PRODUCT_CURSOR

	ALTER TABLE #TEMPCLSTOCK ADD [VALUE] DECIMAL(38,2) DEFAULT(0.00)

	--FOR REPORT HEADER
	SELECT @SLPARRENTID_NEXT=MAX(HEADID) FROM #TMPHEADING
	INSERT INTO #TMPHEADING(HEADID,HEADNAME,HEADSHRTNAME,PARRENTID)
	SELECT (@SLPARRENTID_NEXT+1),'VALUE','VALUE',(@SLPARRENTID_NEXT+1)

	SELECT @SLPARRENTID_NEXT_CS=MAX(HEADID) FROM #TMPHEADING
	SET @M_SLHEADID=1
	SET @M_SLHEADID_NEXT=1
	SET @HPRODONCE=1
	--FOR REPORT HEADER	

	SET @Strsql=''
	SET @Strsql='INSERT INTO #TEMPCLSTOCK(SEQ,STOCKDATEORDBY,STOCKDATE,STOCKNO,SHOP_CODE,[SHOP NAME],CONTACTNO,EMPID,EMPCODE,[SALES MAN NAME],[TIME],STATEID,STATE,DEG_ID,[DESIGNATION],REPORTTO,RPTTODESG) '
	SET @Strsql+='SELECT ROW_NUMBER() OVER(ORDER BY LOGGEDINDATEORDBY) AS SEQ,LOGGEDINDATEORDBY,LOGGEDINDATE,STOCKNO,SHOP_CODE,[SHOP NAME],CONTACTNO,EMPID,EMPCODE,EMPNAME,VISITTIME,STATEID,STATE,DEG_ID,'
	SET @Strsql+='DESIGNATION,REPORTTO,RPTTODESG FROM('
	SET @Strsql+='SELECT DISTINCT ATTEN.LOGGEDINDATEORDBY,ATTEN.LOGGEDINDATE,SHOPACT.VISITTIME,CNT.cnt_internalId AS EMPCODE,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
	SET @Strsql+='ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,SHOP.Shop_Owner_Contact AS CONTACTNO,EMP.emp_uniqueCode AS EMPID,RPTTO.REPORTTO,RPTTO.RPTTODESG,SHOP.SHOP_CODE,'
	SET @Strsql+='SHOP.Shop_Name AS [SHOP NAME],OPSTK.Stock_Code AS STOCKNO '
	SET @Strsql+='FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_address ADDR ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
	SET @Strsql+='INNER JOIN tbl_master_state ST ON ST.id=ADDR.add_state '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
	SET @Strsql+='DESG.deg_designation AS RPTTODESG FROM tbl_master_employee EMP '
	SET @Strsql+='INNER JOIN tbl_trans_employeeCTC EMPCTC ON EMP.emp_id=EMPCTC.emp_reportTo '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC as cnt '
	SET @Strsql+='LEFT OUTER JOIN tbl_master_designation desg ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL '
	SET @Strsql+='GROUP BY emp_cntId,desg.deg_designation,desg.deg_id) DESG ON DESG.emp_cntId=EMP.emp_contactId '
	SET @Strsql+='WHERE EMPCTC.emp_effectiveuntil IS NULL) RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT USERID,cnt_internalId,LOGGEDINDATE,LOGGEDINDATEORDBY FROM('
	SET @Strsql+='SELECT ATTEN.User_Id AS USERID,CNT.cnt_internalId,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,105) AS LOGGEDINDATE,CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) AS LOGGEDINDATEORDBY '
	SET @Strsql+='FROM tbl_fts_UserAttendanceLoginlogout ATTEN '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ATTEN.User_Id AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ATTEN.Work_datetime,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='AND Login_datetime IS NOT NULL AND Logout_datetime IS NULL AND Isonleave=''false'' '
	SET @Strsql+=') LOGINLOGOUT) ATTEN ON ATTEN.cnt_internalId=CNT.cnt_internalId AND ATTEN.USERID=USR.user_id '
	SET @Strsql+='INNER JOIN ('
	SET @Strsql+='SELECT User_Id,cnt_internalId,Shop_Id,VISITDATE,VISITTIME FROM('
	SET @Strsql+='SELECT SHOPACT.User_Id,SHOPACT.Shop_Id,CNT.cnt_internalId,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITDATE,CONVERT(NVARCHAR(8),CAST(SHOPACT.visited_time AS TIME),100) AS VISITTIME '
	SET @Strsql+='FROM tbl_trans_shopActivitysubmit SHOPACT '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=SHOPACT.User_Id '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+=') AA) SHOPACT ON SHOPACT.cnt_internalId=CNT.cnt_internalId AND SHOPACT.User_Id=ATTEN.USERID AND ATTEN.LOGGEDINDATE=SHOPACT.VISITDATE '
	SET @Strsql+='INNER JOIN('
	SET @Strsql+='SELECT MS.Shop_CreateUser,MS.Shop_Code,MS.Shop_Name,MS.assigned_to_pp_id AS SHPPP,MS.Shop_Owner_Contact FROM tbl_Master_shop MS '
	SET @Strsql+=') SHOP ON SHOP.Shop_CreateUser=SHOPACT.User_Id AND SHOP.Shop_Code=SHOPACT.Shop_Id '
	SET @Strsql+='INNER JOIN('
	SET @Strsql+='SELECT Shop_Code,Stock_Code,USERID,CONVERT(NVARCHAR(10),Stock_date,105) AS Stock_date FROM FTS_TransStockOpen '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),Stock_date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+=') OPSTK ON USR.user_id=OPSTK.userID AND SHOPACT.Shop_Id=OPSTK.Shop_Code AND ATTEN.LOGGEDINDATE=OPSTK.Stock_date AND SHOPACT.VISITDATE=OPSTK.Stock_date '
	SET @Strsql+=') DB '
	IF @STATEID<>'' AND @DESIGNID='' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID=''
		SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
	ELSE IF @STATEID='' AND @DESIGNID='' AND @EMPID<>''
		SET @Strsql+='WHERE EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
	ELSE IF @STATEID<>'' AND @DESIGNID='' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	ELSE IF @STATEID='' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID=''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
		END
	ELSE IF @STATEID<>'' AND @DESIGNID<>'' AND @EMPID<>''
		BEGIN
			SET @Strsql+='WHERE EXISTS (SELECT State_Id from #STATEID_LIST AS ST WHERE ST.State_Id=DB.STATEID) '
			SET @Strsql+='AND EXISTS (SELECT deg_id from #DESIGNATION_LIST AS DS WHERE DS.deg_id=DB.deg_id) '
			SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=DB.EMPCODE) '
		END
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	SELECT * INTO #TEMPCLSTOCK_FINAL FROM #TEMPCLSTOCK WHERE 1=2

	SET @StrSql=''
	SET @StrSql='INSERT INTO #TEMPCLSTOCK_FINAL SELECT * FROM('
	SET @StrSql+='SELECT SEQ,STOCKDATEORDBY,STOCKDATE,STOCKNO,SHOP_CODE,[SHOP NAME],CONTACTNO,EMPCODE,EMPID,[SALES MAN NAME],STATEID,STATE,DEG_ID,DESIGNATION,REPORTTO,RPTTODESG,[TIME],'
	SET @StrSql+=''+@PRODNAME_QTY+',[VALUE] FROM #TEMPCLSTOCK '
	SET @StrSql+=') TMP ORDER BY SEQ '
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	--OPENING STOCK CALCULATION
	SET @Strsql=''
	SET @Strsql='INSERT INTO #TMPOPENINGSTOCK(STOCKDATE,STOCKNO,EMPCODE,SHOP_CODE,PRODID,PRODNAME,PRODNAME_QTY,QTY,ORDVALUE) '
	SET @Strsql+='SELECT STOCKDATE,STOCKNO,EMPCODE,SHOP_CODE,PRODID,PRODNAME,PRODNAME_QTY,SUM(ISNULL(QTY,0)) AS QTY,SUM(ISNULL(ORDVALUE,0)) AS ORDVALUE FROM('
	SET @Strsql+='SELECT ORD.STOCKDATE,ORD.STOCKNO,ORD.EMPCODE,ORD.SHOP_CODE,PROD.sProducts_ID AS PRODID,PROD.sProducts_Name AS PRODNAME,PROD.sProducts_Name+''_QTY'' AS PRODNAME_QTY,'
	SET @Strsql+='SUM(ISNULL(ORD.Product_Qty,0)) AS QTY,SUM(ISNULL(ORD.ORDVALUE,0)) AS ORDVALUE '
	SET @Strsql+='FROM Master_sProducts PROD '
	SET @Strsql+='INNER JOIN(SELECT SHOPACT.VISITDATE AS STOCKDATE,ORDH.Stock_Code AS STOCKNO,CNT.cnt_internalId AS EMPCODE,SM.Shop_Code AS SHOP_CODE,ORDD.Product_Id,Product_Qty,ORDVALUE FROM FTS_TransStockOpen ORDH '
	SET @Strsql+='INNER JOIN (SELECT User_Id,Stock_ID,Product_Id,Shop_code,SUM(ISNULL(Product_Qty,0)) AS Product_Qty,SUM(ISNULL(Product_Price,0)) AS ORDVALUE FROM FTS_StockdetailsProduct '
	SET @Strsql+='GROUP BY User_Id,Stock_ID,Product_Id,Shop_code '
	SET @Strsql+=') ORDD ON ORDH.Shop_Code=ORDD.Shop_code AND ORDH.StockId=ORDD.Stock_ID AND ORDH.userID=ORDD.User_Id '
	SET @Strsql+='INNER JOIN tbl_master_user USR ON USR.user_id=ORDH.userID AND USR.user_inactive=''N'' '
	SET @Strsql+='INNER JOIN tbl_master_employee EMP ON USR.user_contactId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @Strsql+='INNER JOIN tbl_Master_shop SM ON SM.Shop_Code=ORDH.Shop_Code AND SM.Shop_CreateUser=ORDH.userID '
	SET @Strsql+='INNER JOIN (SELECT User_Id,Shop_Id,CONVERT(NVARCHAR(10),visited_time,105) AS VISITDATE FROM tbl_trans_shopActivitysubmit '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @Strsql+='GROUP BY User_Id,Shop_Id,CONVERT(NVARCHAR(10),visited_time,105)) SHOPACT ON SHOPACT.Shop_Id=ORDH.Shop_Code AND SHOPACT.Shop_Id=SM.Shop_Code '
	SET @Strsql+='AND SHOPACT.VISITDATE=CONVERT(NVARCHAR(10),ORDH.Stock_date,105) '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.Stock_date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @Strsql+=') ORD ON PROD.sProducts_ID=ORD.Product_Id '
	SET @Strsql+='GROUP BY ORD.STOCKDATE,ORD.STOCKNO,ORD.EMPCODE,ORD.SHOP_CODE,PROD.sProducts_ID,PROD.sProducts_Name '
	SET @Strsql+=') OPS GROUP BY STOCKDATE,STOCKNO,EMPCODE,SHOP_CODE,PRODID,PRODNAME,PRODNAME_QTY ORDER BY OPS.STOCKDATE '
	--SELECT @Strsql
	EXEC SP_EXECUTESQL @Strsql

	SET @Strsql=''
	SET @StrSql='SET @OPENINGSTK_CURSOR=CURSOR FAST_FORWARD FOR SELECT DISTINCT PRODID,PRODNAME_QTY FROM #TMPOPENINGSTOCK '
	SET @StrSql+='GROUP BY PRODID,PRODNAME_QTY ORDER BY PRODID ; OPEN @OPENINGSTK_CURSOR '
	--SELECT @StrSql
	EXEC sp_executesql @StrSql,N' @OPENINGSTK_CURSOR CURSOR OUTPUT', @OPENINGSTK_CURSOR OUTPUT

	FETCH NEXT FROM @OPENINGSTK_CURSOR INTO @PRODID,@PRODNAME
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @M_PRODID=@PRODID
			SET @PRODONCE=1
			WHILE @M_PRODID=@PRODID AND @@FETCH_STATUS = 0
				BEGIN
					SET @sqlStrTable=''
					SET @sqlStrTable = 'ALTER TABLE #TMPOPENINGSTOCK_FINAL ADD '
					SET @sqlStrTable += '['+LTRIM(RTRIM(@PRODNAME)) + ']' + ' INT DEFAULT(0) '
					EXEC SP_EXECUTESQL @sqlStrTable
					FETCH NEXT FROM @OPENINGSTK_CURSOR INTO @PRODID,@PRODNAME
				END
		END
	CLOSE @OPENINGSTK_CURSOR
	DEALLOCATE @OPENINGSTK_CURSOR

	SET @PRODNAMEQTY=''
	SET @Strsql=''
	SET @StrSql='SET @CURSOR_OPENINGSTOCKCALC=CURSOR FAST_FORWARD FOR SELECT DISTINCT PRODID,PRODNAME_QTY FROM #TMPOPENINGSTOCK '
	SET @StrSql+='ORDER BY PRODID ; OPEN @CURSOR_OPENINGSTOCKCALC '
	--SELECT @StrSql
	EXEC sp_executesql @StrSql,N' @CURSOR_OPENINGSTOCKCALC CURSOR OUTPUT', @CURSOR_OPENINGSTOCKCALC OUTPUT

	FETCH NEXT FROM @CURSOR_OPENINGSTOCKCALC INTO @PRODID,@PRODNAME
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @M_PRODID=@PRODID
			SET @PRODONCE=1
			WHILE @M_PRODID=@PRODID AND @@FETCH_STATUS = 0
				BEGIN
					IF @PRODONCE=1
						BEGIN
							IF @PRODNAMEQTY=''
								BEGIN
									SET @PRODNAMEQTY='['+LTRIM(RTRIM(@PRODNAME)) + ']'
								END
							ELSE IF @PRODNAMEQTY<>''
								BEGIN
									SET @PRODNAMEQTY+=',['+LTRIM(RTRIM(@PRODNAME)) + ']'
								END
							SET @PRODONCE=0
						END
					IF @M_PRODID<>@PRODID
						SET @PRODNAMEQTY+=',['+LTRIM(RTRIM(@PRODNAME)) + ']'
					FETCH NEXT FROM @CURSOR_OPENINGSTOCKCALC INTO @PRODID,@PRODNAME
				END
		END
	CLOSE @CURSOR_OPENINGSTOCKCALC
	DEALLOCATE @CURSOR_OPENINGSTOCKCALC

	IF @PRODNAMEQTY<>''
		BEGIN
			SET @StrSql='INSERT INTO #TMPOPENINGSTOCK_FINAL SELECT * FROM('
			SET @StrSql+='SELECT DISTINCT STOCKDATE,STOCKNO,EMPCODE,SHOP_CODE,PRODNAME_QTY,SUM(QTY) AS QTY FROM #TMPOPENINGSTOCK '
			SET @StrSql+='GROUP BY STOCKDATE,STOCKNO,EMPCODE,SHOP_CODE,PRODNAME_QTY '
			SET @StrSql+=') AA PIVOT (SUM(QTY) FOR AA.PRODNAME_QTY IN ('+@PRODNAMEQTY+')) BB '
			EXEC(@StrSql)
		END

	ALTER TABLE #TMPOPENINGSTOCK_FINAL ADD ORDVALUE DECIMAL(18,2) DEFAULT(0.00)

	UPDATE #TMPOPENINGSTOCK_FINAL SET ORDVALUE=(SELECT SUM(ISNULL(ORDVALUE,0)) FROM #TMPOPENINGSTOCK WHERE #TMPOPENINGSTOCK.EMPCODE=#TMPOPENINGSTOCK_FINAL.EMPCODE AND #TMPOPENINGSTOCK.SHOP_CODE=#TMPOPENINGSTOCK_FINAL.SHOP_CODE
	AND #TMPOPENINGSTOCK.STOCKDATE=#TMPOPENINGSTOCK_FINAL.STOCKDATE AND #TMPOPENINGSTOCK.STOCKNO=#TMPOPENINGSTOCK_FINAL.STOCKNO)

	SET @Strsql=''
	SET @StrSql='SET @EMPSHOP_CURSOR=CURSOR FAST_FORWARD FOR SELECT DISTINCT PRI.STOCKDATE,PRI.STOCKNO,PRI.EMPCODE,PRI.Shop_Code,A.PRODID,A.PRODNAME FROM #TEMPPROD A '
	SET @StrSql+='INNER JOIN ('
	SET @StrSql+='SELECT CNT.cnt_internalId AS EMPCODE,A.User_Id,A.Shop_Id AS Shop_Code,ORDH.STOCKNO,ORDH.Product_Id,CONVERT(NVARCHAR(10),visited_time,105) AS STOCKDATE FROM tbl_trans_shopActivitysubmit A '
	SET @StrSql+='INNER JOIN tbl_Master_shop SM ON SM.Shop_Code=A.Shop_Id AND SM.Shop_CreateUser=User_Id '
	SET @StrSql+='INNER JOIN tbl_master_user USR ON USR.user_id=A.User_Id AND USR.user_inactive=''N'' '
	SET @StrSql+='INNER JOIN tbl_master_employee EMP ON USR.user_contactId=EMP.emp_contactId '
	SET @StrSql+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
	SET @StrSql+='INNER JOIN('
	SET @StrSql+='SELECT ORDH.StockId,ORDH.Stock_Code AS STOCKNO,ORDH.userID,ORDH.Shop_Code AS SHOP_CODE,ORDD.Product_Id FROM FTS_TransStockOpen ORDH '
	SET @StrSql+='INNER JOIN ('
	SET @StrSql+='SELECT User_Id,Stock_ID,Product_Id,Shop_code FROM FTS_StockdetailsProduct '
	SET @StrSql+='GROUP BY User_Id,Stock_ID,Product_Id,Shop_code) ORDD ON ORDH.Shop_Code=ORDD.Shop_code AND ORDH.StockId=ORDD.Stock_ID AND ORDH.userID=ORDD.User_Id '
	SET @Strsql+='WHERE CONVERT(NVARCHAR(10),ORDH.Stock_date,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	SET @StrSql+=') ORDH ON ORDH.userID=A.User_Id '
	SET @StrSql+='WHERE CONVERT(NVARCHAR(10),A.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
	IF @EMPID<>''
		SET @Strsql+='AND EXISTS (SELECT emp_contactId from #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '
	SET @StrSql+=') PRI ON A.PRODID=PRI.Product_Id ORDER BY PRI.EMPCODE,A.PRODID ; OPEN @EMPSHOP_CURSOR '
	--SELECT @StrSql
	EXEC sp_executesql @StrSql,N' @EMPSHOP_CURSOR CURSOR OUTPUT', @EMPSHOP_CURSOR OUTPUT

	FETCH NEXT FROM @EMPSHOP_CURSOR INTO @STOCKDATE,@STOCKNO,@EMPCODE,@Shop_Code,@PRODID,@PRODNAME
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @M_EMPCODE=@EMPCODE
			SET @M_SHOP_CODE=@Shop_Code
			WHILE @M_EMPCODE=@EMPCODE AND @M_SHOP_CODE=@SHOP_CODE AND @@FETCH_STATUS=0
				BEGIN
					--OPENING STOCK UPDATE
					IF (EXISTS (SELECT PRODNAME_QTY FROM #TMPOPENINGSTOCK WHERE PRODNAME_QTY=LTRIM(RTRIM(@PRODNAME))+'_QTY' AND EMPCODE=@M_EMPCODE AND SHOP_CODE=@M_SHOP_CODE AND STOCKNO=@STOCKNO))
						BEGIN
							SET @StrSql=''
							SET @StrSql='UPDATE #TEMPCLSTOCK_FINAL SET ['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + ']=A.['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + '],VALUE=A.ORDVALUE FROM(SELECT DISTINCT STOCKDATE,STOCKNO,'
							SET @StrSql+='EMPCODE,SHOP_CODE,ORDVALUE,ISNULL(['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + '],0) AS ['+LTRIM(RTRIM(@PRODNAME))+'_QTY' + '] '
							SET @StrSql+='FROM #TMPOPENINGSTOCK_FINAL) A WHERE #TEMPCLSTOCK_FINAL.STOCKDATE=A.STOCKDATE COLLATE SQL_Latin1_General_CP1_CI_AS '
							SET @StrSql+='AND #TEMPCLSTOCK_FINAL.STOCKNO=A.STOCKNO COLLATE SQL_Latin1_General_CP1_CI_AS '
							SET @StrSql+='AND #TEMPCLSTOCK_FINAL.EMPCODE=A.EMPCODE COLLATE SQL_Latin1_General_CP1_CI_AS AND #TEMPCLSTOCK_FINAL.SHOP_CODE=A.SHOP_CODE COLLATE SQL_Latin1_General_CP1_CI_AS '
							EXEC SP_EXECUTESQL @StrSql
						END

					FETCH NEXT FROM @EMPSHOP_CURSOR INTO @STOCKDATE,@STOCKNO,@EMPCODE,@Shop_Code,@PRODID,@PRODNAME
				END
		END
	CLOSE @EMPSHOP_CURSOR
	DEALLOCATE @EMPSHOP_CURSOR

	SELECT * FROM #TMPHEADING

	SET @StrSql=''
	SET @StrSql='SELECT * FROM('
	--ALL RECORDS
	SET @StrSql+='SELECT SEQ,STOCKDATEORDBY AS [DATEORDBY],STOCKDATE AS [DATE],STOCKNO AS [STOCK NUMBER],SHOP_CODE,[SHOP NAME],CONTACTNO AS [CONTACT NUMBER],EMPCODE,EMPID,[SALES MAN NAME],STATEID,STATE,DEG_ID,DESIGNATION,REPORTTO,RPTTODESG,'
	SET @StrSql+='[TIME],'+@PRODNAME_QTY+',[VALUE] FROM #TEMPCLSTOCK_FINAL '
	SET @StrSql+='UNION ALL '
	--ALL TOTAL
	SET @StrSql+='SELECT 999999999999,''2099-12-01'' AS [DATEORDBY],NULL AS [DATE],NULL AS [STOCK NUMBER],NULL SHOP_CODE,NULL AS [SHOP NAME],NULL AS [CONTACT NUMBER],''ZZZZZZZZZZ'' AS EMPCODE,NULL AS EMPID,'
	SET @StrSql+='''TOTAL STOCK'' AS [SALES MAN NAME],999999999999 AS STATEID,NULL AS STATE,NULL AS DEG_ID,NULL AS DESIGNATION,NULL AS REPORTTO,NULL AS RPTTODESG,NULL AS [TIME],'
	SET @StrSql+=''+@PRODNAMESUMM_QTY+',SUM([VALUE]) AS [VALUE] FROM #TEMPCLSTOCK_FINAL '
	SET @StrSql+=') CLSTK ORDER BY EMPCODE,[DATEORDBY] '
	--SELECT @StrSql
	EXEC SP_EXECUTESQL @StrSql

	DROP TABLE #EMPLOYEE_LIST
	DROP TABLE #TEMPCONTACT
	DROP TABLE #TEMPCLSTOCK
	DROP TABLE #TEMPCLSTOCK_FINAL
	DROP TABLE #TEMPPROD
	DROP TABLE #TMPOPENINGSTOCK
	DROP TABLE #TMPOPENINGSTOCK_FINAL
	DROP TABLE #DESIGNATION_LIST
	DROP TABLE #STATEID_LIST
	DROP TABLE #TMPHEADING

	SET NOCOUNT OFF
END