IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIUSERWISEDAYSTARTEND]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIUSERWISEDAYSTARTEND] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIUSERWISEDAYSTARTEND]
(
@ACTION NVARCHAR(20),
@USER_ID BIGINT=NULL,
@STARTENDDATE DATETIME=NULL,
@LOCATION_NAME NVARCHAR(1000)=NULL,
@LATITUDE NVARCHAR(MAX)=NULL,
@LONGITUDE NVARCHAR(MAX)=NULL,
@SHOP_TYPE INT=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@ISSTART BIT=NULL,
@ISEND BIT=NULL,
@SALE_VALUE NUMERIC(18,2)=NULL,
@REMARKS NVARCHAR(1000)=NULL,
@VISITDDID NVARCHAR(100)=NULL,
@VISITDDNAME NVARCHAR(500)=NULL,
@VISITDDDATE DATETIME=NULL,
@ISDDVISTEDONCEBYDAY BIT=NULL,
@PathImage NVARCHAR(500)=NULL,
--Rev 1.0
@START_DATE NVARCHAR(20)=NULL,
@END_DATE NVARCHAR(20)=NULL
--End of Rev 1.0
) --WITH ENCRYPTION
AS
/***************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 16/08/2021
Purpose : For User wise Day Start/End.
1.0		28-01-2022		Debashis	Day start & end time list.Row 622
***************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	--Rev 1.0
	IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
		DROP TABLE #TEMPCONTACT
	CREATE TABLE #TEMPCONTACT
		(
			cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_branchid INT,
			cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
			cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		)
	CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)
	INSERT INTO #TEMPCONTACT
	SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,ISNULL(cnt_UCC,'') FROM TBL_MASTER_CONTACT WHERE cnt_contactType IN('EM')
	--End of Rev 1.0

	IF @ACTION='INSERTDATA'
		BEGIN
			IF NOT EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND ISSTART=@ISSTART)
				BEGIN
					INSERT INTO FSMUSERWISEDAYSTARTEND(USER_ID,STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID,ISSTART,ISEND,SALE_VALUE,REMARKS,VISITDDID,VISITDDNAME,VISITDDDATE,ISDDVISTEDONCEBYDAY)
					SELECT @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,@ISSTART,@ISEND,@SALE_VALUE,@REMARKS,@VISITDDID,@VISITDDNAME,@VISITDDDATE,@ISDDVISTEDONCEBYDAY
				END
			IF NOT EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND ISEND=@ISEND)
				BEGIN
					INSERT INTO FSMUSERWISEDAYSTARTEND(USER_ID,STARTENDDATE,LOCATION_NAME,LATITUDE,LONGITUDE,SHOP_TYPE,SHOP_ID,ISSTART,ISEND,SALE_VALUE,REMARKS,VISITDDID,VISITDDNAME,VISITDDDATE,ISDDVISTEDONCEBYDAY)
					SELECT @USER_ID,@STARTENDDATE,@LOCATION_NAME,@LATITUDE,@LONGITUDE,@SHOP_TYPE,@SHOP_ID,@ISSTART,@ISEND,@SALE_VALUE,@REMARKS,@VISITDDID,@VISITDDNAME,@VISITDDDATE,@ISDDVISTEDONCEBYDAY
				END

			SELECT CAST(ISSTART AS INT) AS ISSTART FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120)
		END
	IF @ACTION='FETCHDATA'
		BEGIN
			SELECT ISSTART AS DayStartMarked,(SELECT TOP 1 ISEND FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID 
			AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) ORDER BY ID DESC) AS DayEndMarked,
			SHOP_TYPE AS day_start_shop_type,SHOP_ID AS day_start_shop_id,(SELECT TOP 1 ISDDVISTEDONCEBYDAY FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID 
			AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) ORDER BY ID DESC) AS IsDDvistedOnceByDay

			FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120)
		END
	IF @ACTION='SAVEIMAGE'
		BEGIN
			IF EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND @ISSTART=1 AND @ISEND=0)
				BEGIN
					UPDATE FSMUSERWISEDAYSTARTEND SET DAYSTARTENDIMAGE=@PathImage WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=1 AND ISEND=0
					SELECT USER_ID,DAYSTARTENDIMAGE,ISSTART FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=1 AND ISEND=0
				END
			IF EXISTS(SELECT USER_ID FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) AND @ISSTART=0 AND @ISEND=1)
				BEGIN
					UPDATE FSMUSERWISEDAYSTARTEND SET DAYSTARTENDIMAGE=@PathImage WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=0 AND ISEND=1
					SELECT USER_ID,DAYSTARTENDIMAGE,ISEND FROM FSMUSERWISEDAYSTARTEND WHERE USER_ID=@USER_ID AND CONVERT(NVARCHAR(10),STARTENDDATE,120)=CONVERT(NVARCHAR(10),@STARTENDDATE,120) 
					AND ISSTART=0 AND ISEND=1
				END
		END
	--Rev 1.0
	IF @ACTION='DAYSTARTENDLIST'
		BEGIN
			IF(@START_DATE='' AND @END_DATE='')
				BEGIN
					SELECT USR.USER_ID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'')<>'' THEN ' ' ELSE '' END)+ISNULL(CNT.CNT_LASTNAME,'') AS user_name ,
					ATTEN.SDATE,ATTEN.STIME AS dayStart_date_time,ATTEN.EDATE AS ENDDATE,ATTEN.ETIME AS dayEnd_date_time,ATTEN.LOCATION_NAME AS location_name
					FROM tbl_master_user USR
					INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId
					INNER JOIN (
					SELECT USERID,MIN(SDATE) AS SDATE,MIN(STIME) AS STIME,MAX(EDATE) AS EDATE,MAX(ETIME) AS ETIME,LOCATION_NAME FROM(
					SELECT ATTEN.User_Id AS USERID,CAST(CONVERT(NVARCHAR,MIN(STARTENDDATE),102) AS DATETIME) AS SDATE,MIN(STARTENDDATE) AS STIME,NULL AS EDATE,NULL AS ETIME,LOCATION_NAME
					FROM FSMUSERWISEDAYSTARTEND ATTEN 
					WHERE CONVERT(DATE,STARTENDDATE) BETWEEN DATEADD(DAY,-15,CONVERT(DATE,GETDATE())) AND CONVERT(DATE,GETDATE())
					AND ISSTART=1 GROUP BY ATTEN.User_Id,LOCATION_NAME
					UNION ALL 
					SELECT ATTEN.User_Id AS USERID,NULL AS SDATE,NULL AS STIME,CAST(CONVERT(NVARCHAR,MAX(STARTENDDATE),102) AS DATETIME) AS EDATE,MAX(STARTENDDATE) AS ETIME,LOCATION_NAME
					FROM FSMUSERWISEDAYSTARTEND ATTEN 
					WHERE CONVERT(DATE,STARTENDDATE) BETWEEN DATEADD(DAY,-15,CONVERT(DATE,GETDATE())) AND CONVERT(DATE,GETDATE())
					AND ISEND=1 GROUP BY ATTEN.User_Id,LOCATION_NAME
					) LOGINLOGOUT GROUP BY USERID,LOCATION_NAME) ATTEN ON ATTEN.USERID=USR.USER_ID
					WHERE USR.USER_ID=@USER_ID
					ORDER BY ATTEN.SDATE DESC
				END
			ELSE IF(@START_DATE<>'' AND @END_DATE<>'')
				BEGIN
					SELECT USR.USER_ID,ISNULL(CNT.CNT_FIRSTNAME,'')+' '+ISNULL(CNT.CNT_MIDDLENAME,'')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'')<>'' THEN ' ' ELSE '' END)+ISNULL(CNT.CNT_LASTNAME,'') AS user_name ,
					ATTEN.SDATE,ATTEN.STIME AS dayStart_date_time,ATTEN.EDATE AS ENDDATE,ATTEN.ETIME AS dayEnd_date_time,ATTEN.LOCATION_NAME AS location_name
					FROM tbl_master_user USR
					INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId
					INNER JOIN (
					SELECT USERID,MIN(SDATE) AS SDATE,MIN(STIME) AS STIME,MAX(EDATE) AS EDATE,MAX(ETIME) AS ETIME,LOCATION_NAME FROM(
					SELECT ATTEN.User_Id AS USERID,CAST(CONVERT(NVARCHAR,MIN(STARTENDDATE),102) AS DATETIME) AS SDATE,MIN(STARTENDDATE) AS STIME,NULL AS EDATE,NULL AS ETIME,LOCATION_NAME
					FROM FSMUSERWISEDAYSTARTEND ATTEN 
					WHERE CONVERT(DATE,STARTENDDATE) BETWEEN @START_DATE AND @END_DATE
					AND ISSTART=1 GROUP BY ATTEN.User_Id,LOCATION_NAME
					UNION ALL 
					SELECT ATTEN.User_Id AS USERID,NULL AS SDATE,NULL AS STIME,CAST(CONVERT(NVARCHAR,MAX(STARTENDDATE),102) AS DATETIME) AS EDATE,MAX(STARTENDDATE) AS ETIME,LOCATION_NAME
					FROM FSMUSERWISEDAYSTARTEND ATTEN 
					WHERE CONVERT(DATE,STARTENDDATE) BETWEEN @START_DATE AND @END_DATE
					AND ISEND=1 GROUP BY ATTEN.User_Id,LOCATION_NAME
					) LOGINLOGOUT GROUP BY USERID,LOCATION_NAME) ATTEN ON ATTEN.USERID=USR.USER_ID
					WHERE USR.USER_ID=@USER_ID
					ORDER BY ATTEN.SDATE DESC
				END
		END
	--End of Rev 1.0
	
	--Rev 1.0
	DROP TABLE #TEMPCONTACT
	--End of Rev 1.0

	SET NOCOUNT OFF
END