IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FSMAPISURVEYQUESTIONANSWERINFO]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FSMAPISURVEYQUESTIONANSWERINFO] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FSMAPISURVEYQUESTIONANSWERINFO]
(
@ACTION NVARCHAR(100)=NULL,
@USER_ID NVARCHAR(50)=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@SURVEY_ID NVARCHAR(500)=NULL,
@DATE_TIME DATETIME=NULL,
@GROUP_NAME NVARCHAR(500)=NULL,
@QUESTION_FOR_SHOPTYPE_ID BIGINT=NULL,
@QUESTION_ID BIGINT=NULL,
@JsonXML XML=NULL,
@PathImage NVARCHAR(500)=NULL,
@BaseURL NVARCHAR(500)=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************
Written By : Debashis Talukder On 20/07/2022
Purpose : For Survey Question Answer Informations.
****************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='QUESTIONLIST'
		BEGIN
			SELECT CONVERT(NVARCHAR(10),QUESID) AS question_id,QUESDESCRIPTION AS question_desc,QUESTION_TYPE AS question_type,QUESTION_VALUE AS question_value,
			QUESTION_FOR_SHOPTYPE_ID AS question_for_shoptype_id,GROUP_NAME AS group_name FROM FSMAPISURVEYQUESTION 
			WHERE ISACTIVE=1
			ORDER BY QUESID
		END
	IF @ACTION='INSERTDATA'
		BEGIN
			INSERT INTO FSMAPISURVEYQA(USER_ID,SHOP_ID,SURVEY_ID,CREATEBY,CREATEDATE,GROUP_NAME,QUESTION_FOR_SHOPTYPE_ID,QUESTION_ID,ANSWER)
			SELECT @USER_ID,@SHOP_ID,@SURVEY_ID,@USER_ID,@DATE_TIME,@GROUP_NAME,@QUESTION_FOR_SHOPTYPE_ID,
			XMLquesans.value('(question_id/text())[1]','BIGINT') AS question_id,
			XMLquesans.value('(answer/text())[1]','NVARCHAR(500)') AS answer
			FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLquesans)

			SELECT * FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID
		END
	IF @ACTION='IMAGESAVE'
		BEGIN
			IF EXISTS(SELECT USER_ID FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID AND QUESTION_ID=@QUESTION_ID AND SURVEY_ID=@SURVEY_ID)
				BEGIN
					UPDATE FSMAPISURVEYQA SET DOCUMENTIMAGE=@PathImage,MODIFYBY=@USER_ID,MODIFYDATE=GETDATE() WHERE USER_ID=@USER_ID AND QUESTION_ID=@QUESTION_ID AND SURVEY_ID=@SURVEY_ID

					SELECT USER_ID,QUESTION_ID,SURVEY_ID,DOCUMENTIMAGE FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID AND QUESTION_ID=@QUESTION_ID AND SURVEY_ID=@SURVEY_ID
				END
		END
	IF @ACTION='QUESTIONANSWERDETAILLIST'
		BEGIN
			SELECT SURVEY_ID AS survey_id,CREATEDATE AS saved_date_time,QUESTION_FOR_SHOPTYPE_ID AS question_for_shoptype_id,GROUP_NAME AS group_name 
			FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID AND SHOP_ID=@SHOP_ID
			GROUP BY SURVEY_ID,CREATEDATE,QUESTION_FOR_SHOPTYPE_ID,GROUP_NAME

			SELECT QA.QUESID AS question_id,QA.QUESDESCRIPTION AS question_desc,ISNULL(ANS.ANSWER,'') AS answer,ANS.SURVEY_ID AS survey_id,
			CASE WHEN ANS.DOCUMENTIMAGE='' THEN '' ELSE @BaseURL+ISNULL(ANS.DOCUMENTIMAGE,'') END AS image_link
			FROM FSMAPISURVEYQUESTION QA
			INNER JOIN FSMAPISURVEYQA ANS ON QA.QUESID=ANS.QUESTION_ID
			WHERE QA.ISACTIVE=1 AND ANS.USER_ID=@USER_ID AND ANS.SHOP_ID=@SHOP_ID
		END
	IF @ACTION='DELETESURVEY'
		BEGIN
			SELECT * FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID AND SURVEY_ID=@SURVEY_ID

			DELETE FROM FSMAPISURVEYQA WHERE USER_ID=@USER_ID AND SURVEY_ID=@SURVEY_ID
		END

	SET NOCOUNT OFF
END