IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_APIITCORDERWITHPRODUCTDETAIL]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_APIITCORDERWITHPRODUCTDETAIL] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_APIITCORDERWITHPRODUCTDETAIL]
(
@ACTION NVARCHAR(30),
@USER_ID BIGINT=NULL,
@ORDER_CODE NVARCHAR(50)=NULL,
@ORDER_DATE NVARCHAR(10)=NULL,
@ORDER_TIME NVARCHAR(10)=NULL,
@ORDER_DATE_TIME DATETIME=NULL,
@SHOP_ID NVARCHAR(100)=NULL,
@SHOP_NAME NVARCHAR(300)=NULL,
@SHOP_TYPE INT=NULL,
@ISINRANGE INT=NULL,
@ORDER_LAT NVARCHAR(50)=NULL,
@ORDER_LONG NVARCHAR(50)=NULL,
@SHOP_ADDRESS NVARCHAR(300)=NULL,
@SHOP_PINCODE NVARCHAR(100)=NULL,
@ORDER_TOTALAMOUNT DECIMAL(18,2)=NULL,
@ORDER_REMARKS NVARCHAR(500)=NULL,
@JsonXML XML=NULL
) --WITH ENCRYPTION
AS
/****************************************************************************************************************
Written By : Debashis Talukder On 03/04/2024
Purpose : For ITC New Order.Row: 911 to 912
****************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @LASTRECORD BIGINT=0

	IF @ACTION='INSERTDATA'
		BEGIN
			BEGIN TRAN
				BEGIN TRY
					SET @LASTRECORD=(SELECT TOP 1 ISNULL(ID,0) AS ID FROM FSMITCORDERHEADER ORDER BY ID DESC)
					IF @LASTRECORD IS NULL
						SET @LASTRECORD=0

					INSERT INTO FSMITCORDERHEADER(ID,USERID,ORDER_CODE,ORDER_DATE,ORDER_TIME,ORDER_DATE_TIME,SHOP_ID,SHOP_NAME,SHOP_TYPE,ISINRANGE,ORDER_LAT,ORDER_LONG,SHOP_ADDRESS,SHOP_PINCODE,ORDER_TOTALAMOUNT,
					ORDER_REMARKS,CREATED_BY,CREATED_ON)
					SELECT (@LASTRECORD+1),@USER_ID,@ORDER_CODE,@ORDER_DATE,@ORDER_TIME,@ORDER_DATE_TIME,@SHOP_ID,@SHOP_NAME,@SHOP_TYPE,@ISINRANGE,@ORDER_LAT,@ORDER_LONG,@SHOP_ADDRESS,@SHOP_PINCODE,@ORDER_TOTALAMOUNT,
					@ORDER_REMARKS,@USER_ID,GETDATE()

					INSERT INTO FSMITCORDERDETAIL(DETID,USERID,ORDER_CODE,PRODUCT_ID,PRODUCT_NAME,PRODUCT_QTY,PRODUCT_SPECIALRATE)
					SELECT (@LASTRECORD+1),@USER_ID,
					XMLproduct.value('(order_id/text())[1]','NVARCHAR(50)') AS order_id,
					XMLproduct.value('(product_id/text())[1]','BIGINT') AS product_id,
					XMLproduct.value('(product_name/text())[1]','NVARCHAR(300)') AS product_name,
					XMLproduct.value('(submitedQty/text())[1]','DECIMAL(18,2)') AS submitedQty,
					XMLproduct.value('(submitedSpecialRate/text())[1]','DECIMAL(18,2)') AS submitedSpecialRate
					FROM @JsonXML.nodes('/root/data')AS TEMPTABLE(XMLproduct)
					INNER JOIN Master_sProducts MP ON MP.sProducts_ID=XMLproduct.value('(product_id/text())[1]','BIGINT')
					AND EXISTS(SELECT ORDER_CODE FROM FSMITCORDERHEADER WHERE ORDER_CODE=@ORDER_CODE)

					SELECT ORDER_CODE FROM FSMITCORDERHEADER WHERE ORDER_CODE=@ORDER_CODE
				COMMIT TRAN
			END TRY
			BEGIN CATCH
				ROLLBACK TRAN
				SELECT ERROR_NUMBER() AS ErrorNumber,ERROR_MESSAGE() AS ErrorMessage
			END CATCH
		END
	IF @ACTION='FETCHORDPRODDETAIL'
		BEGIN
			SELECT ORDER_CODE AS order_id,ORDER_DATE AS order_date,ORDER_TIME AS order_time,ORDER_DATE_TIME AS order_date_time,SHOP_ID AS shop_id,SHOP_NAME AS shop_name,SHOP_TYPE AS shop_type,ISINRANGE AS isInrange,
			ORDER_LAT AS order_lat,ORDER_LONG AS order_long,SHOP_ADDRESS AS shop_addr,SHOP_PINCODE AS shop_pincode,ORDER_TOTALAMOUNT AS order_total_amt,ORDER_REMARKS AS order_remarks,'true' AS isUploaded
			FROM FSMITCORDERHEADER WHERE USERID=@USER_ID

			SELECT ORDER_CODE AS order_id,PRODUCT_ID AS product_id,PRODUCT_NAME AS product_name,PRODUCT_QTY AS submitedQty,PRODUCT_SPECIALRATE AS submitedSpecialRate FROM FSMITCORDERDETAIL WHERE USERID=@USER_ID
		END

	SET NOCOUNT OFF
END
GO