IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSAPICURRENTSTOCKIMAGEINFO]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSAPICURRENTSTOCKIMAGEINFO] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSAPICURRENTSTOCKIMAGEINFO]
(
@ACTION NVARCHAR(50),
@USER_ID BIGINT=NULL,
@PathImage NVARCHAR(500)=NULL,
@STOCK_CODE varchar(100)=NULL,
@BaseURL NVARCHAR(500)=NULL
) --WITH ENCRYPTION
AS
/***************************************************************************************************************************************************************************************************
Written By : Debashis Talukder On 17/05/2023
Purpose : For Current Stock Image Save API.
***************************************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	IF @ACTION='SAVECURRENTSTOCKIMAGE1'
		BEGIN
			IF NOT EXISTS(SELECT STOCK_CODE FROM FSMCURRENTSTOCKIMAGEMAPINFO WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID)
				BEGIN
					INSERT INTO FSMCURRENTSTOCKIMAGEMAPINFO(USERID,STOCK_CODE,STOCKIMAGEPATH1,CREATE_USER,CREATE_DATE)
					SELECT @USER_ID,@STOCK_CODE,@PathImage,@USER_ID,GETDATE()

					SELECT STOCK_CODE FROM FSMCURRENTSTOCKIMAGEMAPINFO WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID
				END
		END
	ELSE IF @ACTION='SAVECURRENTSTOCKIMAGE2'
		BEGIN
			IF EXISTS(SELECT STOCK_CODE FROM FSMCURRENTSTOCKIMAGEMAPINFO WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID)
				BEGIN
					UPDATE FSMCURRENTSTOCKIMAGEMAPINFO SET STOCKIMAGEPATH2=@PathImage,MODIFIED_USER=@USER_ID,MODIFIED_DATE=GETDATE() 
					WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID

					SELECT STOCK_CODE FROM FSMCURRENTSTOCKIMAGEMAPINFO WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID
				END
		END
	ELSE IF @ACTION='CURRENTSTOCKIMAGELINK'
		BEGIN
			SELECT USERID,STOCK_CODE,@BaseURL+ISNULL(STOCKIMAGEPATH1,'') AS attachment_stock_image1,@BaseURL+ISNULL(STOCKIMAGEPATH2,'') AS attachment_stock_image2 
			FROM FSMCURRENTSTOCKIMAGEMAPINFO WHERE STOCK_CODE=@STOCK_CODE AND USERID=@USER_ID
		END

	SET NOCOUNT OFF
END