--EXEC PRC_FTSOUTLETREVISITDETAILS_REPORT '2023-07-01','2023-07-30','','',378,'1'

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[PRC_FTSOUTLETREVISITDETAILS_REPORT]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [PRC_FTSOUTLETREVISITDETAILS_REPORT] AS' 
END
GO

ALTER PROCEDURE [dbo].[PRC_FTSOUTLETREVISITDETAILS_REPORT]
(
@FROMDATE NVARCHAR(10)=NULL,
@TODATE NVARCHAR(10)=NULL,
@BRANCHID NVARCHAR(MAX)=NULL,
@EMPID NVARCHAR(MAX)=NULL,
@ISPAGELOAD CHAR='0',
@USERID INT
) --WITH ENCRYPTION
AS
/****************************************************************************************************************************************************************************
Written by : Debashis Talukder ON 13/07/2023
Module	   : Outlet Revisit Details.Refer: 0026473
****************************************************************************************************************************************************************************/
BEGIN
	SET NOCOUNT ON

	DECLARE @SqlStr NVARCHAR(MAX),@SqlStrTable NVARCHAR(MAX)

	IF @ISPAGELOAD='1'
		BEGIN
			IF OBJECT_ID('tempdb..#BRANCH_LIST') IS NOT NULL
				DROP TABLE #BRANCH_LIST
			CREATE TABLE #BRANCH_LIST (Branch_Id BIGINT NULL)
			CREATE NONCLUSTERED INDEX Branch_Id ON #BRANCH_LIST (Branch_Id ASC)

			IF @BRANCHID<>''
				BEGIN
					SET @SqlStrTable=''
					SET @BRANCHID=REPLACE(@BRANCHID,'''','')
					SET @sqlStrTable='INSERT INTO #BRANCH_LIST SELECT branch_id FROM tbl_master_branch WHERE branch_id IN ('+@BRANCHID+')'
					EXEC SP_EXECUTESQL @SqlStrTable
				END

			IF OBJECT_ID('tempdb..#EMPLOYEE_LIST') IS NOT NULL
				DROP TABLE #EMPLOYEE_LIST
			CREATE TABLE #EMPLOYEE_LIST (emp_contactId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS)

			IF @EMPID <> ''
				BEGIN
					SET @EMPID = REPLACE(''''+@EMPID+'''',',',''',''')
					SET @SqlStrTable=''
					SET @SqlStrTable='INSERT INTO #EMPLOYEE_LIST SELECT emp_contactId FROM tbl_master_employee WHERE emp_contactId IN('+@EMPID+')'
					EXEC SP_EXECUTESQL @SqlStrTable
				END

			IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
				BEGIN
					DECLARE @empcodes VARCHAR(50)=(select user_contactId from Tbl_master_user where user_id=@Userid)		
					CREATE TABLE #EMPHRS
					(
					EMPCODE VARCHAR(50),
					RPTTOEMPCODE VARCHAR(50)
					)

					CREATE TABLE #EMPHR_EDIT
					(
					EMPCODE VARCHAR(50),
					RPTTOEMPCODE VARCHAR(50)
					)
			
					--Rev 3.0 && WITH (NOLOCK) has been added in all tables
					INSERT INTO #EMPHRS
					SELECT emp_cntId EMPCODE,ISNULL(TME.emp_contactId,'') RPTTOEMPCODE 			
					FROM tbl_trans_employeeCTC CTC WITH (NOLOCK) 
					LEFT JOIN tbl_master_employee TME WITH (NOLOCK) ON TME.emp_id= CTC.emp_reportTO 
					WHERE emp_effectiveuntil IS NULL
		
					;with cte as(SELECT	EMPCODE,RPTTOEMPCODE FROM #EMPHRS WHERE EMPCODE IS NULL OR EMPCODE=@empcodes  
					UNION ALL
					SELECT a.EMPCODE,a.RPTTOEMPCODE FROM #EMPHRS a
					JOIN cte b ON a.RPTTOEMPCODE = b.EMPCODE
					) 
					INSERT INTO #EMPHR_EDIT
					SELECT EMPCODE,RPTTOEMPCODE FROM cte 
				END

			IF OBJECT_ID('tempdb..#TEMPCONTACT') IS NOT NULL
				DROP TABLE #TEMPCONTACT
			CREATE TABLE #TEMPCONTACT
				(
					cnt_internalId NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
					cnt_branchid INT,
					cnt_firstName NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
					cnt_middleName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
					cnt_lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
					cnt_contactType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
					cnt_UCC NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
				)
			CREATE NONCLUSTERED INDEX IX_PARTYID ON #TEMPCONTACT(cnt_internalId,cnt_contactType ASC)

			IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
				BEGIN
					INSERT INTO #TEMPCONTACT
					SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WITH (NOLOCK)
					INNER JOIN #EMPHR_EDIT ON cnt_internalId=EMPCODE WHERE cnt_contactType IN('EM')
				END
			ELSE
				BEGIN
					INSERT INTO #TEMPCONTACT
					SELECT cnt_internalId,cnt_branchid,cnt_firstName,cnt_middleName,cnt_lastName,cnt_contactType,cnt_UCC FROM TBL_MASTER_CONTACT WITH (NOLOCK)
					WHERE cnt_contactType IN('EM')
				END

			IF OBJECT_ID('tempdb..#TMPSHOPACTIVITYSUBMIT') IS NOT NULL
				DROP TABLE #TMPSHOPACTIVITYSUBMIT
			CREATE TABLE #TMPSHOPACTIVITYSUBMIT
			(USER_ID BIGINT,CNT_INTERNALID NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,SHOPCODE NVARCHAR(100),VISITEDDATE NVARCHAR(10),VISITEDDATEORDBY NVARCHAR(10),VISITEDTIME NVARCHAR(10))
			CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPACTIVITYSUBMIT(USER_ID,CNT_INTERNALID)

			SET @SqlStr=''
			SET @SqlStr='INSERT INTO #TMPSHOPACTIVITYSUBMIT(USER_ID,CNT_INTERNALID,SHOPCODE,VISITEDDATE,VISITEDDATEORDBY,VISITEDTIME) '
			SET @SqlStr+='SELECT SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105) AS VISITEDDATE,'
			SET @SqlStr+='CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) AS VISITEDDATEORDBY,CONVERT(NVARCHAR(5),CAST(SHOPACT.visited_time AS TIME),108) AS VISITEDTIME '
			SET @SqlStr+='FROM tbl_trans_shopActivitysubmit SHOPACT WITH (NOLOCK) '
			SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_id=SHOPACT.User_Id '
			SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=USR.user_contactId '
			SET @SqlStr+='WHERE CONVERT(NVARCHAR(10),SHOPACT.visited_time,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @SqlStr+='AND SHOPACT.Is_Newshopadd=0 '
			SET @SqlStr+='GROUP BY SHOPACT.User_Id,CNT.cnt_internalId,SHOPACT.Shop_Id,CONVERT(NVARCHAR(10),SHOPACT.visited_time,105),CONVERT(NVARCHAR(10),SHOPACT.visited_time,120),'
			SET @SqlStr+='CONVERT(NVARCHAR(5),CAST(SHOPACT.visited_time AS TIME),108) '

			--SELECT @SqlStr
			EXEC SP_EXECUTESQL @SqlStr

			IF OBJECT_ID('tempdb..#TMPDAYSTARTEND') IS NOT NULL
				DROP TABLE #TMPDAYSTARTEND
			CREATE TABLE #TMPDAYSTARTEND
			(USERID BIGINT,DAYSTTIME NVARCHAR(10),DAYENDTIME NVARCHAR(10),STARTENDDATE NVARCHAR(10),STARTENDDATEORDBY NVARCHAR(10))
			CREATE NONCLUSTERED INDEX IX1 ON #TMPDAYSTARTEND(USERID,STARTENDDATEORDBY)

			SET @SqlStr=''
			SET @SqlStr='INSERT INTO #TMPDAYSTARTEND(USERID,DAYSTTIME,DAYENDTIME,STARTENDDATE,STARTENDDATEORDBY) '
			SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,MIN(CONVERT(NVARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYSTTIME,NULL AS DAYENDTIME,'
			SET @SqlStr+='CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) AS STARTENDDATEORDBY '
			SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
			SET @SqlStr+='WHERE ISSTART=1 '
			SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @SqlStr+='GROUP BY DAYSTEND.User_Id,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105),CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) '
			SET @SqlStr+='UNION ALL '
			SET @SqlStr+='SELECT DAYSTEND.User_Id AS USERID,NULL AS DAYSTTIME,MAX(CONVERT(NVARCHAR(5),CAST(DAYSTEND.STARTENDDATE AS TIME),108)) AS DAYENDTIME,'
			SET @SqlStr+='CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105) AS STARTENDDATE,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) AS STARTENDDATEORDBY '
			SET @SqlStr+='FROM FSMUSERWISEDAYSTARTEND DAYSTEND WITH (NOLOCK) '
			SET @SqlStr+='WHERE ISEND=1 '
			SET @SqlStr+='AND CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) BETWEEN CONVERT(NVARCHAR(10),'''+@FROMDATE+''',120) AND CONVERT(NVARCHAR(10),'''+@TODATE+''',120) '
			SET @SqlStr+='GROUP BY DAYSTEND.User_Id,CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,105),CONVERT(NVARCHAR(10),DAYSTEND.STARTENDDATE,120) '

			--SELECT @SqlStr
			EXEC SP_EXECUTESQL @SqlStr

			IF OBJECT_ID('tempdb..#TMPSHOPMAST') IS NOT NULL
				DROP TABLE #TMPSHOPMAST
			CREATE TABLE #TMPSHOPMAST(OUTLETID BIGINT,SHPCODE NVARCHAR(100),OUTLETNAME NVARCHAR(4000),LATITUDE NVARCHAR(500),LONGITUDE NVARCHAR(500),SHPCREATEUSER BIGINT)
			CREATE NONCLUSTERED INDEX IX1 ON #TMPSHOPMAST(OUTLETID,SHPCREATEUSER)

			INSERT INTO #TMPSHOPMAST(OUTLETID,SHPCODE,OUTLETNAME,LATITUDE,LONGITUDE,SHPCREATEUSER)
			SELECT Shop_ID,Shop_Code,Shop_Name,Shop_Lat,Shop_Long,Shop_CreateUser FROM tbl_Master_shop WITH (NOLOCK) 
		END

	IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID=OBJECT_ID(N'FTSOUTLETREVISITDETAILS_REPORT') AND TYPE IN (N'U'))
		BEGIN
			CREATE TABLE FTSOUTLETREVISITDETAILS_REPORT
			(
			  USERID INT,
			  SEQ BIGINT,
			  BRANCH_ID BIGINT,
			  BRANCHDESC NVARCHAR(300),
			  EMPUSERID BIGINT,
			  EMPCODE NVARCHAR(100) NULL,
			  EMPID NVARCHAR(100) NULL,
			  EMPNAME NVARCHAR(300) NULL,
			  STATEID INT,
			  STATE NVARCHAR(50) NULL,
			  DEG_ID INT,
			  DESIGNATION NVARCHAR(50) NULL,
			  DATEOFJOINING NVARCHAR(10),
			  CONTACTNO NVARCHAR(50) NULL,
			  STARTENDDATE NVARCHAR(10),
			  REPORTTOID NVARCHAR(300) NULL,
			  REPORTTOUID NVARCHAR(100),
			  REPORTTO NVARCHAR(300) NULL,
			  RPTTODESG NVARCHAR(50) NULL,
			  HREPORTTOID NVARCHAR(300) NULL,
			  HREPORTTOUID NVARCHAR(100),
			  HREPORTTO NVARCHAR(300) NULL,
			  HRPTTODESG NVARCHAR(50) NULL,
			  VISITEDDATE NVARCHAR(10),
			  VISITEDDATEORDBY NVARCHAR(10),
			  VISITEDTIME NVARCHAR(10),
			  OUTLETID BIGINT,
			  OUTLETNAME NVARCHAR(300) NULL,
			  LATITUDE NVARCHAR(500),
			  LONGITUDE NVARCHAR(500),
			  DSTYPEID BIGINT,
			  DSTYPE NVARCHAR(600)
			)
			CREATE NONCLUSTERED INDEX IX1 ON FTSOUTLETREVISITDETAILS_REPORT (SEQ)
		END
	DELETE FROM FTSOUTLETREVISITDETAILS_REPORT WHERE USERID=@USERID

	IF @ISPAGELOAD='1'
		BEGIN
			SET @SqlStr=''
			SET @SqlStr='INSERT INTO FTSOUTLETREVISITDETAILS_REPORT(USERID,SEQ,BRANCH_ID,BRANCHDESC,EMPUSERID,EMPCODE,EMPID,EMPNAME,STATEID,STATE,DEG_ID,DESIGNATION,DATEOFJOINING,CONTACTNO,'
			SET @SqlStr+='STARTENDDATE,REPORTTOID,REPORTTOUID,REPORTTO,RPTTODESG,HREPORTTOID,HREPORTTOUID,HREPORTTO,HRPTTODESG,VISITEDDATE,VISITEDDATEORDBY,VISITEDTIME,OUTLETID,OUTLETNAME,'
			SET @SqlStr+='LATITUDE,LONGITUDE,DSTYPEID,DSTYPE) '
			SET @SqlStr+='SELECT '+LTRIM(RTRIM(STR(@USERID)))+' AS USERID,ROW_NUMBER() OVER(ORDER BY CNT.cnt_internalId,SHOPACT.VISITEDDATEORDBY) AS SEQ,BR.BRANCH_ID,BR.BRANCH_DESCRIPTION,'
			SET @SqlStr+='USR.USER_ID AS EMPUSERID,CNT.cnt_internalId AS EMPCODE,EMP.emp_uniqueCode AS EMPID,'
			SET @SqlStr+='ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+(CASE WHEN ISNULL(CNT.CNT_MIDDLENAME,'''')<>'''' THEN '' '' ELSE '''' END)+ISNULL(CNT.CNT_LASTNAME,'''') AS EMPNAME,'
			SET @SqlStr+='ST.ID AS STATEID,ST.state AS STATE,DESG.DEG_ID,DESG.deg_designation AS DESIGNATION,CONVERT(NVARCHAR(10),EMP.emp_dateofJoining,105) AS DATEOFJOINING,'
			SET @SqlStr+='USR.user_loginId AS CONTACTNO,DAYSTARTEND.STARTENDDATE,RPTTO.REPORTTOID,RPTTO.REPORTTOUID,RPTTO.REPORTTO,RPTTO.RPTTODESG,HRPTTO.HREPORTTOID,HRPTTO.HREPORTTOUID,'
			SET @SqlStr+='HRPTTO.HREPORTTO,HRPTTO.HRPTTODESG,SHOPACT.VISITEDDATE,SHOPACT.VISITEDDATEORDBY,SHOPACT.VISITEDTIME,SHOP.OUTLETID,SHOP.OUTLETNAME,SHOP.LATITUDE,SHOP.LONGITUDE,'
			SET @SqlStr+='USR.FaceRegTypeID AS DSTYPEID,STG.Stage AS DSTYPE '
			SET @SqlStr+='FROM tbl_master_employee EMP WITH (NOLOCK) '
			SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			SET @SqlStr+='INNER JOIN tbl_master_branch BR WITH (NOLOCK) ON CNT.cnt_branchid=BR.branch_id '
			SET @SqlStr+='INNER JOIN tbl_master_user USR WITH (NOLOCK) ON USR.user_contactId=EMP.emp_contactId AND USR.user_inactive=''N'' '
			SET @SqlStr+='INNER JOIN tbl_master_address ADDR WITH (NOLOCK) ON ADDR.add_cntId=CNT.cnt_internalid AND ADDR.add_addressType=''Office'' '
			SET @SqlStr+='INNER JOIN tbl_master_state ST WITH (NOLOCK) ON ST.id=ADDR.add_state '
			SET @SqlStr+='INNER JOIN FTS_Stage STG WITH (NOLOCK) ON USR.FaceRegTypeID=STG.StageID '
			SET @SqlStr+='INNER JOIN ( '
			SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
			SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
			SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS REPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS REPORTTO,'
			SET @SqlStr+='DESG.deg_designation AS RPTTODESG,CNT.cnt_UCC AS REPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) '
			SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
			SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			SET @SqlStr+='INNER JOIN ('
			SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
			SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
			SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId WHERE EMPCTC.emp_effectiveuntil IS NULL '
			SET @SqlStr+=') RPTTO ON RPTTO.emp_cntId=CNT.cnt_internalId '
			SET @SqlStr+='LEFT OUTER JOIN (SELECT EMPCTC.emp_cntId,EMPCTC.emp_reportTo,CNT.cnt_internalId AS HREPORTTOID,ISNULL(CNT.CNT_FIRSTNAME,'''')+'' ''+ISNULL(CNT.CNT_MIDDLENAME,'''')+'' ''+ISNULL(CNT.CNT_LASTNAME,'''') AS HREPORTTO,'
			SET @SqlStr+='DESG.deg_designation AS HRPTTODESG,CNT.cnt_UCC AS HREPORTTOUID FROM tbl_master_employee EMP WITH (NOLOCK) '
			SET @SqlStr+='INNER JOIN tbl_trans_employeeCTC EMPCTC WITH (NOLOCK) ON EMP.emp_id=EMPCTC.emp_reportTo '
			SET @SqlStr+='INNER JOIN #TEMPCONTACT CNT ON CNT.cnt_internalId=EMP.emp_contactId '
			SET @SqlStr+='INNER JOIN ('
			SET @SqlStr+='SELECT cnt.emp_cntId,desg.deg_designation,MAX(emp_id) as emp_id,desg.deg_id FROM tbl_trans_employeeCTC AS cnt WITH (NOLOCK) '
			SET @SqlStr+='LEFT OUTER JOIN tbl_master_designation desg WITH (NOLOCK) ON desg.deg_id=cnt.emp_Designation WHERE cnt.emp_effectiveuntil IS NULL GROUP BY emp_cntId,desg.deg_designation,desg.deg_id '
			SET @SqlStr+=') DESG ON DESG.emp_cntId=EMP.emp_contactId '
			SET @SqlStr+='WHERE EMPCTC.emp_effectiveuntil IS NULL) HRPTTO ON HRPTTO.emp_cntId=RPTTO.REPORTTOID '
			SET @SqlStr+='INNER JOIN ('
			SET @SqlStr+='SELECT USERID,STARTENDDATE,STARTENDDATEORDBY FROM #TMPDAYSTARTEND '
			SET @SqlStr+='GROUP BY USERID,STARTENDDATE,STARTENDDATEORDBY '
			SET @SqlStr+=') DAYSTARTEND ON USR.user_id=DAYSTARTEND.USERID '
			SET @SqlStr+='LEFT OUTER JOIN ('
			SET @SqlStr+='SELECT USER_ID,CNT_INTERNALID,SHOPCODE,VISITEDDATE,VISITEDDATEORDBY,VISITEDTIME '
			SET @SqlStr+='FROM #TMPSHOPACTIVITYSUBMIT '
			SET @SqlStr+='GROUP BY USER_ID,CNT_INTERNALID,SHOPCODE,VISITEDDATE,VISITEDDATEORDBY,VISITEDTIME '
			SET @SqlStr+=') SHOPACT ON CNT.cnt_internalId=SHOPACT.cnt_internalId AND DAYSTARTEND.STARTENDDATEORDBY=SHOPACT.VISITEDDATEORDBY '
			SET @SqlStr+='LEFT OUTER JOIN ('
			SET @SqlStr+='SELECT OUTLETID,SHPCODE,OUTLETNAME,LATITUDE,LONGITUDE,SHPCREATEUSER FROM #TMPSHOPMAST WITH (NOLOCK) '
			SET @SqlStr+=') SHOP ON USR.user_id=SHOP.SHPCREATEUSER AND SHOPACT.SHOPCODE=SHOP.SHPCODE '
			SET @SqlStr+='WHERE DESG.deg_designation=''DS'' AND USR.FaceRegTypeID IN(1,2) '
			IF @BRANCHID<>''
				SET @SqlStr+='AND EXISTS (SELECT Branch_Id FROM #Branch_List AS F WHERE F.Branch_Id=BR.branch_id) '
			IF @EMPID<>''
				SET @SqlStr+='AND EXISTS (SELECT emp_contactId FROM #EMPLOYEE_LIST AS EMP WHERE EMP.emp_contactId=CNT.cnt_internalId) '

			--SELECT @SqlStr
			EXEC SP_EXECUTESQL @SqlStr

			DROP TABLE #BRANCH_LIST
			DROP TABLE #TEMPCONTACT
			DROP TABLE #EMPLOYEE_LIST

			IF ((SELECT IsAllDataInPortalwithHeirarchy FROM tbl_master_user WHERE user_id=@USERID)=1)
			BEGIN
				DROP TABLE #EMPHR_EDIT
				DROP TABLE #EMPHRS
			END
			DROP TABLE #TMPSHOPACTIVITYSUBMIT
			DROP TABLE #TMPDAYSTARTEND
			DROP TABLE #TMPSHOPMAST
		END

	SET NOCOUNT OFF
END